/// Arabic language strings for the DMine application
const Map<String, String> stringsAr = {
  'appTitle': 'DMine',
  'settings': 'الإعدادات',
  'gameSettings': 'إعدادات اللعبة',
  'showTimer': 'عرض المؤقت',
  'showTimerDesc': 'عرض مؤقت اللعبة على واجهة اللعبة',
  'showActionCounter': 'عرض عداد الإجراءات',
  'showActionCounterDesc': 'عرض إحصائيات عدد الإجراءات على واجهة اللعبة',
  'autoAdjustBoardWidth': 'ضبط عرض اللوحة تلقائيًا',
  'autoAdjustBoardWidthDesc': 'ضبط عرض اللوحة تلقائيًا بناءً على حجم الشاشة',
  'resetToDefaults': 'إعادة التعيين إلى الإعدادات الافتراضية',
  'resetToDefaultsDesc': 'استعادة جميع الإعدادات إلى القيم الافتراضية',
  'aboutDMine': 'حول DMine',
  'version': 'الإصدار',
  'close': 'إغلاق',
  'manualBoardWidth': 'عرض اللوحة اليدوي',
  'currentWidth': 'الحالي',
  'range': 'النطاق',
  'widthSliderHint': 'تلميح: يمكنك معاينة تغييرات عرض اللوحة أثناء سحب المنزلق',
  'gameRecords': 'سجلات اللعبة',
  'selectMapToViewRecords': 'يرجى اختيار خريطة لعرض السجلات',
  'totalRecords': 'الإجمالي',
  'gameRecordsTitle': 'قائمة سجلات اللعبة',
  'pleaseSelectMapFirst': 'يرجى اختيار خريطة أولاً',
  'noGameRecords': 'لا توجد سجلات لعبة',
  'miningMethodFlag': 'علم',
  'miningMethodBlind': 'أعمى',
  'statusPlaying': '▶️ قيد اللعب...',
  'statusWin': '🎉 فوز',
  'statusLose': '💥 خسارة',
  'actionsCount': 'الإجراءات',
  'miningMethod': 'الطريقة',
  'duration': 'المدة',
  'seconds': 'ث',
  'startTime': 'وقت البدء',
  'endTime': 'وقت الانتهاء',
  'pauseTime': 'وقت الإيقاف المؤقت',
  'unlock': 'فتح',
  'lock': 'قفل',
  'delete': 'حذف',
  'languageSetting': 'إعداد اللغة',
  'currentLanguage': 'الحالي',
  'systemLanguage': 'لغة النظام',
  'chinese': 'الصينية',
  'english': 'الإنجليزية',
  'language': 'اللغة',
  // Home page
  'newbie': 'مبتدئ',
  'newBattle': 'جبهة جديدة',
  'continueChallenge': 'متابعة',
  'error': 'خطأ',
  'initializationFailed': 'فشل التهيئة',
  // Game page
  'congratulations': 'تهانينا!',
  'gameOver': 'انتهت اللعبة',
  'timeUsed': 'الوقت',
  'actionCount': 'الإجراءات',
  'mineCount': 'الألغام',
  'nextLevel': 'التالي: المستوى {level}',
  'newbieNextLevel': 'التالي: المستوى المبتدئ {level}',
  'nextLevelMines': 'الألغام',
  'mineIncrease': 'زيادة',
  'newbieFinish': 'تم إكمال المستوى المبتدئ',
  'ok': 'موافق',
  'continueNextLevel': 'المستوى التالي',
  'restart': 'إعادة البدء',
  'level': 'المستوى {level}',
  'newbieLevel': 'المستوى المبتدئ {level}',
  'operationFailed': 'فشلت العملية',
  // Game status texts
  'returnHome': 'العودة إلى الصفحة الرئيسية',
  'revealMode': 'وضع الكشف',
  'flagMode': 'وضع العلم',
  'newMap': 'خريطة جديدة (نفس الألغام)',
  'resetMap': 'إعادة تحميل الخريطة (نفس الخريطة، إعادة تعيين حالة اللعبة)',
  'zoomOut': 'تصغير',
  'zoomIn': 'تكبير',
  'resetZoom': 'إعادة تعيين التكبير',
  'previousStep': 'الخطوة السابقة',
  'pause': 'إيقاف مؤقت',
  'play': 'تشغيل',
  'nextStep': 'الخطوة التالية',
  'clickToStart': 'انقر على أي خلية لبدء اللعبة',
  'playing': 'قيد اللعب...',
  'gameWin': 'تهانينا!',
  'gameLose': 'انتهت اللعبة، دُست على لغم',
  'gamePaused': 'اللعبة متوقفة مؤقتًا',
  'ready': 'جاهز للبدء',
  'clickStartShort': 'انقر للبدء',
  'playingShort': 'قيد اللعب',
  'winShort': 'فوز!',
  'loseShort': 'خسارة',
  'pausedShort': 'متوقف مؤقتًا',
  // Counter strings
  'currentLevel': 'المستوى الحالي',
  'remainingMines': 'الألغام المتبقية',
  'gameTime': 'مدة اللعبة (ثواني)',
  'operationCount': 'الإجراءات',
  'previousLevel': 'المستوى السابق',
  'nextLevelShort': 'المستوى التالي',
  // Battlefront strings
  'completed': 'مكتمل',
  'inProgress': 'قيد التنفيذ',
  'continueGame': 'متابعة اللعبة',
  'replay': 'إعادة اللعب',
  'creater': 'القائد',
  'created': 'وقت الهجوم',
  'updated': 'تم التحديث',
  // Battlefront UI strings
  'noBattlefronts': 'لا توجد جبهات',
  'battlefrontCount': '{count} جبهة(جبهات)',
  'levelPrefix': 'م{level}',
  'newbieLevelPrefix': 'مبتدئ م{level}',
  'minesCount': '{count} لغم(ألغام)',
  'notStarted': 'لم يبدأ',
  'victory': 'فوز',
  'defeat': 'هزيمة',
  'gameDurationParam': 'المدة: {seconds}ث',
  'actionsCountParam': 'الإجراءات: {count}',
  'actionsCountParamShort': '{count}',
  'miningMethodParam': 'الطريقة: {method}',
  'startTimeParam': 'وقت البدء: {time}',
  'endTimeParam': 'وقت الانتهاء: {time}',
  'returnButton': 'رجوع',
  'battlefrontDetails': 'تفاصيل الجبهة',
  'clickToEditName': 'انقر لتحرير الاسم',
  'clickToAddDescription': 'انقر لإضافة وصف...',
  'noDescription': 'لا يوجد وصف',
  // Dialog strings
  'confirm': 'تأكيد',
  'cancel': 'إلغاء',
  'yes': 'نعم',
  'no': 'لا',
  'save': 'حفظ',
  'edit': 'تحرير',
  'levelFormat': 'المستوى {level}',
  'newbieLevelFormat': 'المستوى المبتدئ {level}',
  'totalLevel': 'المستوى {level}/{totalLevel}',
  'totalLevelTooltip':
      'المستوى الحالي: {level} / إجمالي المستويات: {totalLevel}',
  // Level record strings
  'levelCount': '{count} مستويات',
  'noLevelRecords': 'لا توجد سجلات للمستويات',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'حذف الجبهة',
  'deleteBattlefrontContent':
      'هل أنت متأكد أنك تريد حذف الجبهة "{name}"؟ لا يمكن التراجع عن هذا الإجراء.',
  'battlefrontLockedCannotDelete': 'الجبهة مقفلة ولا يمكن حذفها',
  'unknownNavigationLevel': 'مستوى تنقل غير معروف',
  'noBattlefrontSelected': 'لم يتم اختيار جبهة',
  'noBattlefrontToContinue': 'لم يتم العثور على جبهة للمتابعة',
  'synced': 'متزامن',
  'notSynced': 'غير متزامن',
  'newbieBattlefrontName': 'جبهة مبتدئ {number}',
  'battlefrontName': 'جبهة {number}',
  'nickname': 'اللقب',
  'nicknameSetting': 'إعداد اللقب',
  'nicknameDesc': 'قم بتعيين لقبك',
  'enterNickname': 'أدخل اللقب',
  'nicknameSaved': 'تم حفظ اللقب',
  'nicknameUpdated': 'تم تحديث اللقب بنجاح',
  'nicknameRequired': 'اللقب مطلوب',
  'nicknameTooLong': 'لا يمكن أن يتجاوز اللقب 30 حرفًا',
  // Level top strings
  'levelTopCount': 'الترتيب الأعلى ({count})',
  'levelTopCountShort': 'الأعلى ({count})',
  'retry': 'إعادة المحاولة',
  'noLevelTopData': 'لا توجد بيانات',
  'remoteBattlefront': 'جبهة بعيدة',
  'participated': 'مشارك',
  'notParticipated': 'غير مشارك',
  'loadMore': 'تحميل المزيد',

  'joinBattle': 'الانضمام إلى المعركة',
  'joinBattleTooltip': 'الانضمام إلى المعركة "{name}"',
  'joinBattleConfirm': 'هل أنت متأكد أنك تريد الانضمام إلى المعركة "{name}"؟',
  'joinBattleSuccess': 'تم الانضمام بنجاح إلى المعركة "{name}"',
  'joinBattleErrorSelf':
      'لا يمكن الانضمام إلى المعركة "{name}" التي أنشأتها بنفسك',

  'replayBattlefront': 'إعادة لعب الجبهة',
  'replayBattlefrontTooltip': 'إعادة لعب الجبهة "{name}"',
  'getReplayBattlefrontConfirm': 'هل أنت متأكد أنك تريد إعادة لعب "{name}"؟',
  'getReplayBattlefrontFailed': 'فشلت إعادة لعب "{name}": {error}',

  'download': 'تنزيل',
  'downloadBattlefront': 'تنزيل الجبهة',
  'downloadBattlefrontTooltip': 'تنزيل الجبهة "{name}"',
  'getDownloadBattlefrontConfirm': 'هل أنت متأكد أنك تريد تنزيل "{name}"؟',
  'getDownloadBattlefrontSuccess': 'تم تنزيل "{name}" بنجاح',
  'downloadMyOwnBattlefrontError': 'يمكن تنزيل جبهاتك فقط',
  'getDownloadBattlefrontFailed': 'فشل تنزيل "{name}": {error}',

  'continueGameShort': 'متابعة',
  'replayShort': 'إعادة اللعب',
  'highestLevel': 'المستوى {level}',
  'deviceNickname': 'الجهاز',
  'createdTime': 'وقت الإنشاء',
  'remoteBattlefrontDetail': 'تفاصيل الجبهة',
  'levelList': 'قائمة المستويات',
  'fastClearTimeParam': 'إزالة سريعة: {time}',
  // Remote battlefront detail strings
  'selectLocalBattlefrontHint': 'يرجى اختيار جبهة محلية لعرض التفاصيل',
  'loadingRemoteDetail': 'جارٍ تحميل تفاصيل الجبهة البعيدة...',
  'noRemoteBattlefrontSelected': 'لم يتم اختيار جبهة بعيدة',
  'failedToLoadRemoteDetail': 'فشل تحميل تفاصيل الجبهة البعيدة',
  'fastestRecord': 'الأسرع',
  'safestRecord': 'الأكثر أمانًا',
  'fastestRecordDesc': 'الأسرع (أقصر وقت)',
  'safestRecordDesc': 'الأكثر أمانًا (أقل إجراءات)',
  'creator': 'المنشئ',
  'player': 'اللاعب',
  // Branch map strings
  'getBranchMapCount': '{count} فرع',
  'collapse': 'طي',
  'expand': 'توسيع',
  // Quit battlefront
  'quitBattlefront': 'مغادرة الجبهة',
  'quitBattlefrontTooltip': 'مغادرة الجبهة البعيدة',
  'quitBattlefrontTitle': 'مغادرة الجبهة',
  'quitBattlefrontContent':
      'هل أنت متأكد أنك تريد مغادرة الجبهة "{name}"؟ سيتم حذف تقدمك المحلي.',

  // Download page
  'downloadClient': 'تنزيل العميل',
  'browser': 'المتصفح',
  'browserDesc': 'اللعب مباشرة في المتصفح، لا حاجة للتنزيل',
  'windowsDesc': 'لـ Windows 10 والإصدارات الأحدث',
  'macosDesc': 'لـ macOS 10.15 والإصدارات الأحدث',
  'android': 'Android',
  'androidDesc': 'لـ Android 8.0 والإصدارات الأحدث',
  'iosDesc': 'لـ iOS 14.0 والإصدارات الأحدث',
  'linkAddress': 'عنوان الرابط',
  'downloadLink': 'رابط التنزيل',
  'qrCode': 'رمز QR',
  'scanToDownload': 'امسح بالهاتف للتنزيل',
  'copy': 'نسخ',
  'copiedToClipboard': 'تم النسخ إلى الحافظة',
  'openLink': 'فتح الرابط',
  'cannotOpenLink': 'لا يمكن فتح الرابط',
  // Game introduction
  'gameIntroduction':
      '1. يبدأ "المبتدئ" بـ 15 لغماً، ويمكن أن يصل إلى 99 لغماً.\n2. يبدأ "الجبهة الجديدة" بـ 81 لغماً، ويزداد عدد الألغام في كل مستوى، دون حد أعلى.\n3. في وضع الاتصال، يتم مشاركة الجبهات المكتملة تلقائيًا إلى السحابة للآخرين للتعلم منها.',
};
