// German（德语）
/// Deutsche Zeichenketten für die DMine-Anwendung
const Map<String, String> stringsDe = {
  'appLabel': 'Top Minesweeper',
  'appTitle': 'DMine - Top Minesweeper',
  'settings': 'Einstellungen',
  'gameSettings': 'Spieleinstellungen',
  'showTimer': 'Timer anzeigen',
  'showTimerDesc': 'Zeige den Spiel-Timer in der Oberfläche',
  'showActionCounter': 'Aktionszähler anzeigen',
  'showActionCounterDesc':
      'Zeige die Anzahl der Aktionen in der Spieloberfläche',
  'autoAdjustBoardWidth': 'Breite des Spielfeldes automatisch anpassen',
  'autoAdjustBoardWidthDesc':
      'Passe die Breite des Spielfeldes automatisch an die Bildschirmgröße an',
  'resetToDefaults': 'Auf Standardwerte zurücksetzen',
  'resetToDefaultsDesc':
      'Setze alle Einstellungen auf die Standardwerte zurück',
  'aboutDMine': 'Über DMine',
  'version': 'Version',
  'close': 'Schließen',
  'manualBoardWidth': 'Breite des Spielfeldes manuell einstellen',
  'currentWidth': 'Aktuell',
  'range': 'Bereich',
  'widthSliderHint':
      'Tipp: Du kannst Änderungen der Feldbreite in Echtzeit sehen, während du den Schieberegler ziehst',
  'gameRecords': 'Spielaufzeichnungen',
  'selectMapToViewRecords':
      'Wähle eine Karte aus, um Aufzeichnungen anzuzeigen',
  'totalRecords': 'Gesamt',
  'gameRecordsTitle': 'Liste der Spielaufzeichnungen',
  'pleaseSelectMapFirst': 'Wähle zuerst eine Karte aus',
  'noGameRecords': 'Keine Spielaufzeichnungen vorhanden',
  'miningMethodFlag': 'Flagge setzen',
  'miningMethodBlind': 'Blindsuchen',
  'statusPlaying': '▶️ Läuft...',
  'statusWin': '🎉 Sieg',
  'statusLose': '💥 Niederlage',
  'actionsCount': 'Anzahl der Aktionen',
  'miningMethod': 'Minensuchmethode',
  'duration': 'Dauer',
  'seconds': 'Sekunden',
  'startTime': 'Startzeit',
  'endTime': 'Endzeit',
  'pauseTime': 'Pausenzeit',
  'unlock': 'Entsperren',
  'lock': 'Sperren',
  'delete': 'Löschen',
  'languageSetting': 'Spracheinstellung',
  'currentLanguage': 'Aktuell',
  'systemLanguage': 'Systemsprache',
  'chinese': 'Chinesisch',
  'english': 'Englisch',
  'language': 'Sprache',
  // Home page
  'newbie': 'Neuling',
  'newBattle': 'Neue Front',
  'continueChallenge': 'Herausforderung fortsetzen',
  'error': 'Fehler',
  'initializationFailed': 'Initialisierung fehlgeschlagen',
  // Game page
  'congratulations': 'Glückwunsch, du hast das Level geschafft!',
  'gameOver': 'Spiel vorbei',
  'timeUsed': 'Benötigte Zeit',
  'actionCount': 'Anzahl der Aktionen',
  'mineCount': 'Anzahl der Minen',
  'nextLevel': 'Nächstes Level: Level {level}',
  'newbieNextLevel': 'Nächstes Level: Neuling {level}',
  'nextLevelMines': 'Anzahl der Minen',
  'mineIncrease': 'Erhöhung',
  'newbieFinish': 'Neulings-Einführung abgeschlossen',
  'ok': 'OK',
  'continueNextLevel': 'Weiter zum nächsten Level',
  'restart': 'Neustarten',
  'level': 'Level {level}',
  'newbieLevel': 'Neulingslevel {level}',
  'operationFailed': 'Vorgang fehlgeschlagen',
  // Game status texts
  'returnHome': 'Zurück zur Startseite',
  'revealMode': 'Aufdeckmodus',
  'flagMode': 'Flaggenmodus',
  'newMap': 'Neue Karte (gleiche Minenanzahl, neue Karte generieren)',
  'resetMap': 'Karte neu laden (gleiche Karte, Status zurücksetzen)',
  'zoomOut': 'Verkleinern',
  'zoomIn': 'Vergrößern',
  'resetZoom': 'Zoom zurücksetzen',
  'previousStep': 'Vorheriger Schritt',
  'pause': 'Pausieren',
  'play': 'Spielen',
  'nextStep': 'Nächster Schritt',
  'clickToStart': 'Klicke auf ein beliebiges Feld, um das Spiel zu starten',
  'playing': 'Spielt...',
  'gameWin': 'Glückwunsch, du hast das Level geschafft!',
  'gameLose': 'Spiel vorbei, du hast eine Mine getroffen',
  'gamePaused': 'Spiel pausiert',
  'ready': 'Bereit',
  'clickStartShort': 'Klicken zum Starten',
  'playingShort': 'Läuft',
  'winShort': 'Geschafft!',
  'loseShort': 'Mine getroffen',
  'pausedShort': 'Pausiert',
  // Counter strings
  'currentLevel': 'Aktuelles Level',
  'remainingMines': 'Verbleibende Minen',
  'gameTime': 'Spielzeit (Sekunden)',
  'operationCount': 'Anzahl der Vorgänge',
  'previousLevel': 'Vorheriges Level',
  'nextLevelShort': 'Nächstes Level',
  // Battlefront strings
  'completed': 'Abgeschlossen',
  'inProgress': 'Laufend',
  'continueGame': 'Spiel fortsetzen',
  'replay': 'Wiederholen',
  'creater': 'Kommandant',
  'created': 'Schlachtbeginn',
  'updated': 'Aktualisiert',
  // Dialog strings
  'confirm': 'Bestätigen',
  'cancel': 'Abbrechen',
  'yes': 'Ja',
  'no': 'Nein',
  'save': 'Speichern',
  'edit': 'Bearbeiten',
  'levelFormat': 'Level {level}',
  'newbieLevelFormat': 'Neulingslevel {level}',
  'totalLevel': '{level}/{totalLevel} Level',
  'totalLevelTooltip': 'Aktuell: Level {level} / Gesamt {totalLevel} Level',
  // Battlefront UI strings
  'noBattlefronts': 'Keine Fronten',
  'battlefrontCount': '{count} Fronten',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'NEU{level}',
  'minesCount': '{count} Minen',
  'notStarted': 'Nicht gestartet',
  'victory': 'Sieg',
  'defeat': 'Niederlage',
  'gameDurationParam': 'Dauer: {seconds} Sekunden',
  'actionsCountParam': 'Aktionen: {count} Mal',
  'actionsCountParamShort': '{count} Mal',
  'miningMethodParam': 'Methode: {method}',
  'startTimeParam': 'Startzeit: {time}',
  'endTimeParam': 'Endzeit: {time}',
  'returnButton': 'Zurück',
  'battlefrontDetails': 'Frontdetails',
  'clickToEditName': 'Klicken, um den Namen zu ändern',
  'clickToAddDescription': 'Klicken, um eine Beschreibung hinzuzufügen...',
  'noDescription': 'Keine Beschreibung',
  // Level record strings
  'levelCount': '{count} Level',
  'noLevelRecords': 'Wähle eine Front aus',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Front löschen',
  'deleteBattlefrontContent':
      'Bist du sicher, dass du die Front "{name}" löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.',
  'battlefrontLockedCannotDelete':
      'Front ist gesperrt, kann nicht gelöscht werden',
  'unknownNavigationLevel': 'Unbekanntes Navigationslevel',
  'noBattlefrontSelected': 'Keine Front ausgewählt',
  'noBattlefrontToContinue': 'Keine Front zum Fortfahren gefunden',
  'synced': 'Synchronisiert',
  'notSynced': 'Nicht synchronisiert',
  'newbieBattlefrontName': 'Neulingsfront {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Spitzname',
  'nicknameSetting': 'Spitznameeinstellung',
  'nicknameDesc': 'Lege deinen Spitznamen fest',
  'enterNickname': 'Spitznamen eingeben',
  'nicknameSaved': 'Spitzname gespeichert',
  'nicknameUpdated': 'Spitzname aktualisiert',
  'nicknameRequired': 'Spitzname ist erforderlich',
  'nicknameTooLong': 'Spitzname darf nicht länger als 30 Zeichen sein',
  // Level top strings
  'levelTopCount': 'Bestenliste ({count})',
  'levelTopCountShort': 'Bestenliste ({count})',
  'retry': 'Erneut versuchen',
  'noLevelTopData': 'Keine Daten vorhanden',
  'remoteBattlefront': 'Ferndienstfront',
  'participated': 'Teilgenommen',
  'notParticipated': 'Nicht teilgenommen',
  'loadMore': 'Mehr laden',

  'joinBattle': 'Kampf beitreten',
  'joinBattleTooltip': 'Kampf "{name}" beitreten',
  'joinBattleConfirm':
      'Bist du sicher, dass du dem Kampf "{name}" beitreten möchtest?',
  'joinBattleSuccess': 'Du hast dem Kampf "{name}" erfolgreich beigetreten',
  'joinBattleErrorSelf': 'Du kannst nicht deiner eigenen Front beitreten',

  'replayBattlefront': 'Front wiederholen',
  'replayBattlefrontTooltip': 'Front "{name}" wiederholen',
  'getReplayBattlefrontConfirm':
      'Bist du sicher, dass du "{name}" wiederholen möchtest?',
  'getReplayBattlefrontFailed':
      'Wiederholen von "{name}" fehlgeschlagen: {error}',

  'download': 'Herunterladen',
  'downloadBattlefront': 'Front herunterladen',
  'downloadBattlefrontTooltip': 'Front "{name}" herunterladen',
  'getDownloadBattlefrontConfirm':
      'Bist du sicher, dass du "{name}" herunterladen möchtest?',
  'getDownloadBattlefrontSuccess': 'Front "{name}" erfolgreich heruntergeladen',
  'downloadMyOwnBattlefrontError':
      'Du kannst nur deine eigenen Fronten herunterladen',
  'getDownloadBattlefrontFailed':
      'Herunterladen von "{name}" fehlgeschlagen: {error}',

  'continueGameShort': 'Kampf fortsetzen',
  'replayShort': 'Wiederholen',
  'highestLevel': 'Level {level}',
  'deviceNickname': 'Gerät',
  'createdTime': 'Erstellungszeit',
  'remoteBattlefrontDetail': 'Details zur Ferndienstfront',
  'levelList': 'Level-Liste',
  'fastClearTimeParam': 'Abschlusszeit: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Wähle eine lokale Front aus, um Details anzuzeigen',
  'loadingRemoteDetail': 'Lade Details zur Ferndienstfront...',
  'noRemoteBattlefrontSelected': 'Keine Ferndienstfront ausgewählt',
  'failedToLoadRemoteDetail': 'Laden der Ferndienstdetails fehlgeschlagen',
  'fastestRecord': 'Schnellster Abschluss',
  'safestRecord': 'Sicherster Abschluss',
  'fastestRecordDesc': 'Schnellster Abschluss (am wenigsten Zeit)',
  'safestRecordDesc': 'Sicherster Abschluss (am wenigsten Aktionen)',
  'creator': 'Ersteller',
  'player': 'Spieler',
  // 分支地图字符串
  'getBranchMapCount': '{count} Kopien',
  'collapse': 'Zuklappen',
  'expand': 'Aufklappen',
  // 退出战线
  'quitBattlefront': 'Front verlassen',
  'quitBattlefrontTooltip': 'Ferndienstfront verlassen',
  'quitBattlefrontTitle': 'Front verlassen',
  'quitBattlefrontContent':
      'Bist du sicher, dass du die Front "{name}" verlassen möchtest? Dein lokaler Fortschritt wird gelöscht.',

  // 下载页面
  'downloadClient': 'Client herunterladen',
  'browser': 'Browser',
  'browserDesc': 'Spiele direkt im Browser, ohne Herunterladen',
  'windowsDesc': 'Für Windows 10 und höher',
  'macosDesc': 'Für macOS 10.15 und höher',
  'android': 'Android',
  'androidDesc': 'Für Android 8.0 und höher',
  'iosDesc': 'Für iOS 14.0 und höher',
  'linkAddress': 'Link-Adresse',
  'downloadLink': 'Download-Link',
  'qrCode': 'QR-Code',
  'scanToDownload': 'Mit dem Telefon scannen, um herunterzuladen',
  'copy': 'Kopieren',
  'copiedToClipboard': 'In die Zwischenablage kopiert',
  'openLink': 'Link öffnen',
  'cannotOpenLink': 'Link kann nicht geöffnet werden',
  // 游戏介绍
  'gameIntroduction':
      '1. „Neuling“ beginnt mit 15 Minen und kann bis zu 99 Minen erreichen;\n2. „Neue Front“ beginnt mit 81 Minen, jedes Level fügt Minen hinzu, ohne Obergrenze.\n3. Bei Internetverbindung werden „abgeschlossene“ Fronten automatisch in der Cloud geteilt, damit andere lernen können.',
};
