// Indonesian（印尼语）
/// String Bahasa Indonesia untuk aplikasi DMine
const Map<String, String> stringsId = {
  'appLabel': 'Minesweeper Terbaik',
  'appTitle': 'DMine - Minesweeper Terbaik',
  'settings': 'Pengaturan',
  'gameSettings': 'Pengaturan Permainan',
  'showTimer': 'Tampilkan timer',
  'showTimerDesc': 'Tampilkan timer permainan di antarmuka',
  'showActionCounter': 'Tampilkan penghitung aksi',
  'showActionCounterDesc': 'Tampilkan jumlah aksi di antarmuka permainan',
  'autoAdjustBoardWidth': 'Sesuaikan lebar papan secara otomatis',
  'autoAdjustBoardWidthDesc':
      'Sesuaikan lebar papan sesuai ukuran layar secara otomatis',
  'resetToDefaults': 'Atur ulang ke default',
  'resetToDefaultsDesc': 'Kembalikan semua pengaturan ke nilai awal',
  'aboutDMine': 'Tentang DMine',
  'version': 'Versi',
  'close': 'Tutup',
  'manualBoardWidth': 'Atur lebar papan secara manual',
  'currentWidth': 'Saat ini',
  'range': 'Rentang',
  'widthSliderHint':
      'Tips: Anda bisa melihat perubahan lebar papan secara real-time saat menggeser slider',
  'gameRecords': 'Rekor permainan',
  'selectMapToViewRecords': 'Pilih peta untuk melihat rekor',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Daftar rekor permainan',
  'pleaseSelectMapFirst': 'Silakan pilih peta terlebih dahulu',
  'noGameRecords': 'Tidak ada rekor permainan',
  'miningMethodFlag': 'Pasang bendera',
  'miningMethodBlind': 'Pencarian buta',
  'statusPlaying': '▶️ Sedang bermain...',
  'statusWin': '🎉 Menang',
  'statusLose': '💥 Kalah',
  'actionsCount': 'Jumlah aksi',
  'miningMethod': 'Metode pencarian ranjau',
  'duration': 'Durasi',
  'seconds': 'detik',
  'startTime': 'Waktu mulai',
  'endTime': 'Waktu selesai',
  'pauseTime': 'Waktu jeda',
  'unlock': 'Buka kunci',
  'lock': 'Kunci',
  'delete': 'Hapus',
  'languageSetting': 'Pengaturan bahasa',
  'currentLanguage': 'Saat ini',
  'systemLanguage': 'Bahasa sistem',
  'chinese': 'Mandarin',
  'english': 'Inggris',
  'language': 'Bahasa',
  // Home page
  'newbie': 'Pemula',
  'gameIntro': 'Pengenalan Game',
  'newBattle': 'Front baru',
  'continueChallenge': 'Lanjutkan tantangan',
  'error': 'Error',
  'initializationFailed': 'Inisialisasi gagal',
  // Game page
  'congratulations': 'Selamat, Anda menyelesaikan level!',
  'gameOver': 'Permainan selesai',
  'timeUsed': 'Waktu yang dipakai',
  'actionCount': 'Jumlah aksi',
  'mineCount': 'Jumlah ranjau',
  'nextLevel': 'Level selanjutnya: Level {level}',
  'newbieNextLevel': 'Level selanjutnya: Pemula {level}',
  'nextLevelMines': 'Jumlah ranjau',
  'mineIncrease': 'Peningkatan',
  'newbieFinish': 'Tutorial pemula selesai',
  'ok': 'OK',
  'continueNextLevel': 'Lanjut ke level berikutnya',
  'restart': 'Mulai ulang',
  'level': 'Level {level}',
  'newbieLevel': 'Level pemula {level}',
  'operationFailed': 'Operasi gagal',
  // Game status texts
  'returnHome': 'Kembali ke beranda',
  'revealMode': 'Mode buka',
  'flagMode': 'Mode bendera',
  'newMap': 'Peta baru (jumlah ranjau sama, buat peta baru)',
  'resetMap': 'Muat ulang peta (peta sama, atur ulang status)',
  'zoomOut': 'Perkecil',
  'zoomIn': 'Perbesar',
  'resetZoom': 'Atur ulang zoom',
  'previousStep': 'Langkah sebelumnya',
  'pause': 'Jeda',
  'play': 'Main',
  'nextStep': 'Langkah selanjutnya',
  'clickToStart': 'Klik kotak apa saja untuk memulai permainan',
  'playing': 'Sedang bermain...',
  'gameWin': 'Selamat, Anda menyelesaikan level!',
  'gameLose': 'Permainan selesai, Anda terkena ranjau',
  'gamePaused': 'Permainan dijeda',
  'ready': 'Siap',
  'clickStartShort': 'Klik untuk mulai',
  'playingShort': 'Sedang berjalan',
  'winShort': 'Selesai!',
  'loseShort': 'Terkena ranjau',
  'pausedShort': 'Dijeda',
  // Counter strings
  'currentLevel': 'Level saat ini',
  'remainingMines': 'Ranjau tersisa',
  'gameTime': 'Waktu bermain (detik)',
  'operationCount': 'Jumlah operasi',
  'previousLevel': 'Level sebelumnya',
  'nextLevelShort': 'Level selanjutnya',
  // Battlefront strings
  'completed': 'Selesai',
  'inProgress': 'Sedang berlangsung',
  'continueGame': 'Lanjutkan permainan',
  'replay': 'Main ulang',
  'creater': 'Komandan',
  'created': 'Waktu mulai pertempuran',
  'updated': 'Diperbarui',
  // Dialog strings
  'confirm': 'Konfirmasi',
  'cancel': 'Batal',
  'yes': 'Ya',
  'no': 'Tidak',
  'save': 'Simpan',
  'edit': 'Edit',
  'levelFormat': 'Level {level}',
  'newbieLevelFormat': 'Level pemula {level}',
  'totalLevel': '{level}/{totalLevel} level',
  'totalLevelTooltip': 'Saat ini: Level {level} / Total {totalLevel} level',
  // Battlefront UI strings
  'noBattlefronts': 'Tidak ada front',
  'battlefrontCount': '{count} front',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'PM{level}',
  'minesCount': '{count} ranjau',
  'notStarted': 'Belum dimulai',
  'victory': 'Menang',
  'defeat': 'Kalah',
  'gameDurationParam': 'Durasi: {seconds} detik',
  'actionsCountParam': 'Aksi: {count} kali',
  'actionsCountParamShort': '{count} kali',
  'miningMethodParam': 'Metode: {method}',
  'startTimeParam': 'Waktu mulai: {time}',
  'endTimeParam': 'Waktu selesai: {time}',
  'returnButton': 'Kembali',
  'battlefrontDetails': 'Detail front',
  'clickToEditName': 'Klik untuk ubah nama',
  'clickToAddDescription': 'Klik untuk tambah deskripsi...',
  'noDescription': 'Tidak ada deskripsi',
  // Level record strings
  'levelCount': '{count} level',
  'noLevelRecords': 'Pilih front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Hapus front',
  'deleteBattlefrontContent':
      'Apakah Anda yakin ingin menghapus front "{name}"? Tindakan ini tidak dapat dibatalkan.',
  'battlefrontLockedCannotDelete': 'Front terkunci, tidak dapat dihapus',
  'unknownNavigationLevel': 'Level navigasi tidak diketahui',
  'noBattlefrontSelected': 'Tidak ada front yang dipilih',
  'noBattlefrontToContinue': 'Tidak ada front untuk dilanjutkan',
  'synced': 'Tersinkronisasi',
  'notSynced': 'Belum tersinkronisasi',
  'newbieBattlefrontName': 'Front pemula {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Nama panggilan',
  'nicknameSetting': 'Pengaturan nama panggilan',
  'nicknameDesc': 'Atur nama panggilan Anda',
  'enterNickname': 'Masukkan nama panggilan',
  'nicknameSaved': 'Nama panggilan tersimpan',
  'nicknameUpdated': 'Nama panggilan diperbarui',
  'nicknameRequired': 'Nama panggilan diperlukan',
  'nicknameTooLong': 'Nama panggilan tidak boleh lebih dari 30 karakter',
  // Level top strings
  'levelTopCount': 'Peringkat ({count})',
  'levelTopCountShort': 'Peringkat ({count})',
  'retry': 'Coba lagi',
  'noLevelTopData': 'Tidak ada data',
  'remoteBattlefront': 'Front jarak jauh',
  'participated': 'Sudah ikut',
  'notParticipated': 'Belum ikut',
  'loadMore': 'Muat lebih banyak',

  'joinBattle': 'Bergabung ke pertempuran',
  'joinBattleTooltip': 'Bergabung ke pertempuran "{name}"',
  'joinBattleConfirm':
      'Apakah Anda yakin ingin bergabung ke pertempuran "{name}"?',
  'joinBattleSuccess': 'Anda berhasil bergabung ke pertempuran "{name}"',
  'joinBattleErrorSelf': 'Anda tidak bisa bergabung ke front Anda sendiri',

  'replayBattlefront': 'Main ulang front',
  'replayBattlefrontTooltip': 'Main ulang front "{name}"',
  'getReplayBattlefrontConfirm': 'Apakah Anda yakin ingin main ulang "{name}"?',
  'getReplayBattlefrontFailed': 'Gagal main ulang "{name}": {error}',

  'download': 'Unduh',
  'downloadBattlefront': 'Unduh front',
  'downloadBattlefrontTooltip': 'Unduh front "{name}"',
  'getDownloadBattlefrontConfirm':
      'Apakah Anda yakin ingin mengunduh "{name}"?',
  'getDownloadBattlefrontSuccess': 'Front "{name}" berhasil diunduh',
  'downloadMyOwnBattlefrontError':
      'Anda hanya bisa mengunduh front Anda sendiri',
  'getDownloadBattlefrontFailed': 'Gagal mengunduh "{name}": {error}',

  'continueGameShort': 'Lanjutkan pertempuran',
  'replayShort': 'Main ulang',
  'highestLevel': 'Level {level}',
  'deviceNickname': 'Perangkat',
  'createdTime': 'Waktu dibuat',
  'remoteBattlefrontDetail': 'Detail front jarak jauh',
  'levelList': 'Daftar level',
  'fastClearTimeParam': 'Waktu selesai: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Pilih front lokal untuk melihat detail',
  'loadingRemoteDetail': 'Memuat detail front jarak jauh...',
  'noRemoteBattlefrontSelected': 'Tidak ada front jarak jauh yang dipilih',
  'failedToLoadRemoteDetail': 'Gagal memuat detail jarak jauh',
  'fastestRecord': 'Penyelesaian tercepat',
  'safestRecord': 'Penyelesaian teraman',
  'fastestRecordDesc': 'Penyelesaian tercepat (waktu lebih sedikit)',
  'safestRecordDesc': 'Penyelesaian teraman (aksi lebih sedikit)',
  'creator': 'Pembuat',
  'player': 'Pemain',
  // 分支地图字符串
  'getBranchMapCount': '{count} salinan',
  'collapse': 'Lipat',
  'expand': 'Buka',
  // 退出战线
  'quitBattlefront': 'Keluar dari front',
  'quitBattlefrontTooltip': 'Keluar dari front jarak jauh',
  'quitBattlefrontTitle': 'Keluar dari front',
  'quitBattlefrontContent':
      'Apakah Anda yakin ingin keluar dari front "{name}"? Progres lokal Anda akan dihapus.',
  // 游戏介绍
  'gameIntroduction':
      '1. "Pemula" dimulai dengan 15 ranjau dan bisa mencapai hingga 99 ranjau.\n2. "Front baru" dimulai dengan 81 ranjau, setiap level menambah ranjau tanpa batas atas.\n3. Dengan koneksi internet, front "selesai" dibagikan otomatis ke cloud untuk dipelajari orang lain.',
};
