// Finnish（芬兰语）
/// Suomet merkkijonot DMine-sovellukseen
const Map<String, String> stringsFi = {
  'appTitle': 'DMine - Huippu Miinaharava',
  'settings': 'Asetukset',
  'gameSettings': 'Peliasetukset',
  'showTimer': 'Näytä ajastin',
  'showTimerDesc': 'Näytä pelin ajastin käyttöliittymässä',
  'showActionCounter': 'Näytä toimenpiteiden laskuri',
  'showActionCounterDesc': 'Näytä toimenpiteiden määrä pelin käyttöliittymässä',
  'autoAdjustBoardWidth': 'Säädä lautaleveyttä automaattisesti',
  'autoAdjustBoardWidthDesc':
      'Säädä lautaleveyttä automaattisesti näytron koon mukaan',
  'resetToDefaults': 'Palauta oletusasetukset',
  'resetToDefaultsDesc': 'Palauta kaikki asetukset oletusarvoihin',
  'aboutDMine': 'Tietoa DMine',
  'version': 'Versio',
  'close': 'Sulje',
  'manualBoardWidth': 'Määritä lautaleveys manuaalisesti',
  'currentWidth': 'Nykyinen',
  'range': 'Alue',
  'widthSliderHint':
      'Vihje: Voit esikatsella lautaleveyden muutoksia reaaliajassa liukuhihnaa liikuttamalla',
  'gameRecords': 'Pelitiedot',
  'selectMapToViewRecords': 'Valitse kartta nähdäksesi tiedot',
  'totalRecords': 'Yhteensä',
  'gameRecordsTitle': 'Pelitietojen luettelo',
  'pleaseSelectMapFirst': 'Valitse ensin kartta',
  'noGameRecords': 'Ei pelitietoja',
  'miningMethodFlag': 'Aseta lippu',
  'miningMethodBlind': 'Sokea etsintä',
  'statusPlaying': '▶️ Pelataan...',
  'statusWin': '🎉 Voitto',
  'statusLose': '💥 Häviö',
  'actionsCount': 'Toimenpiteiden määrä',
  'miningMethod': 'Miinojen etsimistapa',
  'duration': 'Kesto',
  'seconds': 'sekuntia',
  'startTime': 'Alkamisaika',
  'endTime': 'Päättymisaika',
  'pauseTime': 'Pysäytysaika',
  'unlock': 'Vapauta',
  'lock': 'Lukitse',
  'delete': 'Poista',
  'languageSetting': 'Kieliasetus',
  'currentLanguage': 'Nykyinen',
  'systemLanguage': 'Järjestelmäkieli',
  'chinese': 'Kiina',
  'english': 'Englanti',
  'language': 'Kieli',
  // Home page
  'newbie': 'Uusien opetus',
  'newBattle': 'Uusi rintama',
  'continueChallenge': 'Jatka haastetta',
  'error': 'Virhe',
  'initializationFailed': 'Alustus epäonnistui',
  // Game page
  'congratulations': 'Onnittelut, läpäisit tason!',
  'gameOver': 'Peli päättyi',
  'timeUsed': 'Kulunut aika',
  'actionCount': 'Toimenpiteiden määrä',
  'mineCount': 'Miinojen määrä',
  'nextLevel': 'Seuraava taso: Taso {level}',
  'newbieNextLevel': 'Seuraava taso: Uusien {level}',
  'nextLevelMines': 'Miinojen määrä',
  'mineIncrease': 'Lisääntyminen',
  'newbieFinish': 'Uusien opetus valmis',
  'ok': 'OK',
  'continueNextLevel': 'Jatka seuraavaan tasoon',
  'restart': 'Käynnistä uudelleen',
  'level': 'Taso {level}',
  'newbieLevel': 'Uusien taso {level}',
  'operationFailed': 'Toimenpite epäonnistui',
  // Game status texts
  'returnHome': 'Palaa alkuun',
  'revealMode': 'Paljastustila',
  'flagMode': 'Lipputila',
  'newMap': 'Uusi kartta (miinojen määrä pysyy samana, luo uusi kartta)',
  'resetMap': 'Lataa kartta uudelleen (sama kartta, palauta tila)',
  'zoomOut': 'Loitonna',
  'zoomIn': 'Lähennä',
  'resetZoom': 'Palauta alkuzoom',
  'previousStep': 'Edellinen askel',
  'pause': 'Pysäytä',
  'play': 'Pelaa',
  'nextStep': 'Seuraava askel',
  'clickToStart': 'Klikkaa mikä tahansa ruutu aloittaaksesi pelin',
  'playing': 'Pelataan...',
  'gameWin': 'Onnittelut, läpäisit tason!',
  'gameLose': 'Peli päättyi, osuit miinaan',
  'gamePaused': 'Peli pysäytetty',
  'ready': 'Valmis',
  'clickStartShort': 'Klikkaa aloittaaksesi',
  'playingShort': 'Pelataan',
  'winShort': 'Läpäisty!',
  'loseShort': 'Osui miinaan',
  'pausedShort': 'Pysäytetty',
  // Counter strings
  'currentLevel': 'Nykyinen taso',
  'remainingMines': 'Jäljellä olevat miinat',
  'gameTime': 'Peliaika (sekuntia)',
  'operationCount': 'Toimenpiteiden määrä',
  'previousLevel': 'Edellinen taso',
  'nextLevelShort': 'Seuraava taso',
  // Battlefront strings
  'completed': 'Valmistettu',
  'inProgress': 'Käynnissä',
  'continueGame': 'Jatka peliä',
  'replay': 'Toista',
  'creater': 'Lähetti',
  'created': 'Taistelun alkamisaika',
  'updated': 'Päivitetty',
  // Dialog strings
  'confirm': 'Vahvista',
  'cancel': 'Peruuta',
  'yes': 'Kyllä',
  'no': 'Ei',
  'save': 'Tallenna',
  'edit': 'Muokkaa',
  'levelFormat': 'Taso {level}',
  'newbieLevelFormat': 'Uusien taso {level}',
  'totalLevel': '{level}/{totalLevel} tasoa',
  'totalLevelTooltip': 'Nykyinen: Taso {level} / Yhteensä {totalLevel} tasoa',
  // Battlefront UI strings
  'noBattlefronts': 'Ei rintamia',
  'battlefrontCount': '{count} rintamaa',
  'levelPrefix': 'TAS{level}',
  'newbieLevelPrefix': 'UUS{level}',
  'minesCount': '{count} miinaa',
  'notStarted': 'Ei aloitettu',
  'victory': 'Voitto',
  'defeat': 'Häviö',
  'gameDurationParam': 'Kesto: {seconds} sekuntia',
  'actionsCountParam': 'Toimenpiteet: {count} kertaa',
  'actionsCountParamShort': '{count} kertaa',
  'miningMethodParam': 'Tapa: {method}',
  'startTimeParam': 'Alkamisaika: {time}',
  'endTimeParam': 'Päättymisaika: {time}',
  'returnButton': 'Takaisin',
  'battlefrontDetails': 'Rintaman tiedot',
  'clickToEditName': 'Klikkaa vaihtaaaksesi nimeä',
  'clickToAddDescription': 'Klikkaa lisätäksesi kuvauksen...',
  'noDescription': 'Ei kuvausta',
  // Level record strings
  'levelCount': '{count} tasoa',
  'noLevelRecords': 'Valitse rintama',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Poista rintama',
  'deleteBattlefrontContent':
      'Haluatko varmasti poistaa rintaman "{name}"? Tämä toimenpite ei ole peruuttamaton.',
  'battlefrontLockedCannotDelete': 'Rintama on lukittu, ei voida poistaa',
  'unknownNavigationLevel': 'Tuntematon navigointitaso',
  'noBattlefrontSelected': 'Ei valittua rintamaa',
  'noBattlefrontToContinue': 'Ei jatettavaa rintamaa',
  'synced': 'Synkronoitu',
  'notSynced': 'Ei synkronoitu',
  'newbieBattlefrontName': 'Uusien rintama {number}',
  'battlefrontName': 'Rintama {number}',
  'nickname': 'Lempinimi',
  'nicknameSetting': 'Lempinimen asetus',
  'nicknameDesc': 'Aseta lempinimesi',
  'enterNickname': 'Syötä lempinimi',
  'nicknameSaved': 'Lempinimi tallennettu',
  'nicknameUpdated': 'Lempinimi päivitetty',
  'nicknameRequired': 'Lempinimi on pakollinen',
  'nicknameTooLong': 'Lempinimi ei voi olla yli 30 merkkiä',
  // Level top strings
  'levelTopCount': 'Parhaat tulokset ({count})',
  'levelTopCountShort': 'Parhaat ({count})',
  'retry': 'Yritä uudelleen',
  'noLevelTopData': 'Ei tietoja',
  'remoteBattlefront': 'Etärintama',
  'participated': 'Osallistunut',
  'notParticipated': 'Ei osallistunut',
  'loadMore': 'Lataa lisää',

  'joinBattle': 'Liity taisteluun',
  'joinBattleTooltip': 'Liity taisteluun "{name}"',
  'joinBattleConfirm': 'Haluatko varmasti liittyä taisteluun "{name}"?',
  'joinBattleSuccess': 'Liityit onnistuneesti taisteluun "{name}"',
  'joinBattleErrorSelf': 'Et voi liittyä oman luomaasi rintamaan',

  'replayBattlefront': 'Toista rintama',
  'replayBattlefrontTooltip': 'Toista rintama "{name}"',
  'getReplayBattlefrontConfirm': 'Haluatko varmasti toistaa "{name}"?',
  'getReplayBattlefrontFailed': 'Toistaminen "{name}" epäonnistui: {error}',

  'download': 'Lataa',
  'downloadBattlefront': 'Lataa rintama',
  'downloadBattlefrontTooltip': 'Lataa rintama "{name}"',
  'getDownloadBattlefrontConfirm': 'Haluatko varmasti ladata "{name}"?',
  'getDownloadBattlefrontSuccess': 'Rintama "{name}" ladattu onnistuneesti',
  'downloadMyOwnBattlefrontError': 'Voit ladata vain omia rintamojasi',
  'getDownloadBattlefrontFailed': 'Lataus "{name}" epäonnistui: {error}',

  'continueGameShort': 'Jatka taistelua',
  'replayShort': 'Toista',
  'highestLevel': 'Taso {level}',
  'deviceNickname': 'Laite',
  'createdTime': 'Luontiaika',
  'remoteBattlefrontDetail': 'Etärintaman tiedot',
  'levelList': 'Tasoluettelo',
  'fastClearTimeParam': 'Läpäisy aika: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Valitse paikallinen rintama nähdäksesi tiedot',
  'loadingRemoteDetail': 'Ladataan etärintaman tietoja...',
  'noRemoteBattlefrontSelected': 'Ei valittua etärintamaa',
  'failedToLoadRemoteDetail': 'Etärintaman tietojen lataus epäonnistui',
  'fastestRecord': 'Nopein läpäisy',
  'safestRecord': 'Varmisin läpäisy',
  'fastestRecordDesc': 'Nopein läpäisy (vähiten aikaa)',
  'safestRecordDesc': 'Varmisin läpäisy (vähiten toimenpiteitä)',
  'creator': 'Tekijä',
  'player': 'Pelaaja',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopiota',
  'collapse': 'Supista',
  'expand': 'Laajenna',
  // 退出战线
  'quitBattlefront': 'Poistu rintamasta',
  'quitBattlefrontTooltip': 'Poistu etärintamasta',
  'quitBattlefrontTitle': 'Poistu rintamasta',
  'quitBattlefrontContent':
      'Haluatko varmasti poistua rintamasta "{name}"? Paikallinen edistymisesi poistetaan.',

  // 下载页面
  'downloadClient': 'Lataa asiakasohjelma',
  'browser': 'Selain',
  'browserDesc': 'Pelaa suoraan selaimessa ilman latausta',
  'windowsDesc': 'Soveltuu Windows 10:een ja uudempiin',
  'macosDesc': 'Soveltuu macOS 10.15:een ja uudempiin',
  'android': 'Android',
  'androidDesc': 'Soveltuu Android 8.0:een ja uudempiin',
  'iosDesc': 'Soveltuu iOS 14.0:een ja uudempiin',
  'linkAddress': 'Linkin osoite',
  'downloadLink': 'Latauslinkki',
  'qrCode': 'QR-koodi',
  'scanToDownload': 'Skannaa puhelimella ladataksesi',
  'copy': 'Kopioi',
  'copiedToClipboard': 'Kopioitu leikepöydälle',
  'openLink': 'Avaa linkki',
  'cannotOpenLink': 'Linkkiä ei voida avata',
  // 游戏介绍
  'gameIntroduction':
      '1. "Uusien opetus" alkaa 15 miinasta, voi nousta jopa 99 miinaan;\n2. "Uusi rintama" alkaa 81 miinasta, joka taso lisää miinoja ilman ylärajaa.\n3. Internet-yhteydessä "läpäistyet" rintamat jaetaan automaattisesti pilvessä muiden oppimiseksi.',
};
