/// Afrikaans（南非荷兰语）
/// Afrikaans language strings for the DMine application
const Map<String, String> stringsAf = {
  'appLabel': 'Top Mynveër',
  'appTitle': 'DMine - Top Mynveër',
  'settings': 'Instellings',
  'gameSettings': 'Instellings',
  'showTimer': 'Wys Tydhouer',
  'showTimerDesc': 'Vertoon speltydhouer op spelkoppelvlak',
  'showActionCounter': 'Wys Aksieteller',
  'showActionCounterDesc': 'Vertoon aksietellingstatistieke op spelkoppelvlak',
  "showUnrevealedCounter": "Wys onontdekte sel-teller",
  "showUnrevealedCounterDesc":
      "Wys die aantal onontdekte selle op die speelvlak",
  "showMineCounter": "Wys myn-teller",
  "showMineCounterDesc": "Wys die oorblywende aantal myne op die speelvlak",
  'autoAdjustBoardWidth': 'Outomaties Pas Bordwydte Aan',
  'autoAdjustBoardWidthDesc':
      'Pas bordwydte outomaties aan volgens skermgrootte',
  'resetToDefaults': 'Herstel na Verstekinstellings',
  'resetToDefaultsDesc': 'Herstel alle instellings na verstekwaardes',
  'aboutDMine': 'Oor DMine',
  'version': 'Weergawe',
  'close': 'Sluit',
  'manualBoardWidth': 'Handmatige Bordwydte',
  'currentWidth': 'Huidig',
  'range': 'Omvang',
  'widthSliderHint':
      'Wenk: Jy kan bordwydteveranderings voorbeskou terwyl jy die skuif trek',
  'gameRecords': 'Spelrekords',
  'selectMapToViewRecords': 'Kies asseblief \'n kaart om rekords te sien',
  'totalRecords': 'Totaal',
  'gameRecordsTitle': 'Spelrekordslys',
  'pleaseSelectMapFirst': 'Kies asseblief eers \'n kaart',
  'noGameRecords': 'Geen spelrekords',
  'miningMethodFlag': 'Vlag',
  'miningMethodBlind': 'Blind',
  'statusPlaying': '▶️ Besig...',
  'statusWin': '🎉 Oorwinning',
  'statusLose': '💥 Mislukking',
  'actionsCount': 'Aksies',
  'miningMethod': 'Metode',
  'duration': 'Tydduur',
  'seconds': 's',
  'startTime': 'Begintyd',
  'endTime': 'Eindtyd',
  'pauseTime': 'Pouse Tyd',
  'unlock': 'Ontsluit',
  'lock': 'Sluit',
  'delete': 'Verwyder',
  'languageSetting': 'Taalinstelling',
  'currentLanguage': 'Huidig',
  'systemLanguage': 'Stelseltaal',
  'chinese': 'Chinees',
  'english': 'Engels',
  'language': 'Taal',
  // Home page
  'newbie': 'Beginner',
  'gameIntro': 'Spelbeskrywing',
  'newBattle': 'Nuwe Front',
  'continueChallenge': 'Gaan voort',
  'error': 'Fout',
  'initializationFailed': 'Inisialisering het misluk',
  // Game page
  'congratulations': 'Geluk!',
  'gameOver': 'Spel Verby',
  'timeUsed': 'Tyd',
  'actionCount': 'Aksies',
  'mineCount': 'Myns',
  'nextLevel': 'Volgende: Vlak {level}',
  'newbieNextLevel': 'Volgende: Beginner Vlak {level}',
  'nextLevelMines': 'Myns',
  'mineIncrease': 'Vermeerder',
  'newbieFinish': 'Beginner voltooi',
  'ok': 'OK',
  'continueNextLevel': 'Volgende Vlak',
  'restart': 'Begin oor',
  'level': 'Vlak {level}',
  'newbieLevel': 'Beginner Vlak {level}',
  'operationFailed': 'Operasie het misluk',
  // Game status texts
  'returnHome': 'Terug na Tuis',
  'revealMode': 'Openbaar Modus',
  'flagMode': 'Vlag Modus',
  'newMap': 'Nuwe Kaart (dieselfde myns)',
  'resetMap': 'Herlaai Kaart (dieselfde kaart, herstel spelstatus)',
  'zoomOut': 'Zoom Uit',
  'zoomIn': 'Zoom In',
  'resetZoom': 'Herstel Zoom',
  'previousStep': 'Vorige Stap',
  'pause': 'Pouse',
  'play': 'Speel',
  'nextStep': 'Volgende Stap',
  'clickToStart': 'Klik enige sel om spel te begin',
  'playing': 'Besig...',
  'gameWin': 'Geluk!',
  'gameLose': 'Spel Verby, op \'n myn gestap',
  'gamePaused': 'Spel Gepouseer',
  'ready': 'Gereed om te Begin',
  'clickStartShort': 'Klik Begin',
  'playingShort': 'Besig',
  'winShort': 'Wen!',
  'loseShort': 'Mislukking',
  'pausedShort': 'Gepouseer',
  // Counter strings
  'currentLevel': 'Huidige Vlak',
  "remainingMines": "Oorblywende myne",
  "unrevealedCells": "Onontdekte selle",
  'gameTime': 'Speltyd (sekondes)',
  'operationCount': 'Aksies',
  'previousLevel': 'Vorige Vlak',
  'nextLevelShort': 'Volgende Vlak',
  // Battlefront strings
  'completed': 'Voltooi',
  'inProgress': 'In Uitvoering',
  'continueGame': 'Gaan voort met Spel',
  'replay': 'Herhaal',
  'creater': 'Bevelvoerder',
  'created': 'Aanval Tyd',
  'updated': 'Opgedateer',
  // Battlefront UI strings
  'noBattlefronts': 'Geen fronte',
  'battlefrontCount': '{count} front(e)',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'Beginner LV{level}',
  'minesCount': '{count} myns',
  'notStarted': 'Nie begin nie',
  'victory': 'Oorwinning',
  'defeat': 'Nederlaag',
  'gameDurationParam': 'Tydduur: {seconds}s',
  'actionsCountParam': 'Aksies: {count}',
  'actionsCountParamShort': '{count}',
  'miningMethodParam': 'Metode: {method}',
  'startTimeParam': 'Begintyd: {time}',
  'endTimeParam': 'Eindtyd: {time}',
  'returnButton': 'Terug',
  'battlefrontDetails': 'Front Besonderhede',
  'clickToEditName': 'Klik om naam te wysig',
  'clickToAddDescription': 'Klik om beskrywing by te voeg...',
  'noDescription': 'Geen beskrywing',
  // Dialog strings
  'confirm': 'Bevestig',
  'cancel': 'Kanselleer',
  'yes': 'Ja',
  'no': 'Nee',
  'save': 'Stoor',
  'edit': 'Wysig',
  'levelFormat': 'Vlak {level}',
  'newbieLevelFormat': 'Beginner Vlak {level}',
  'totalLevel': 'Vlak {level}/{totalLevel}',
  'totalLevelTooltip': 'Huidig: Vlak {level} / Totaal Vlakke: {totalLevel}',
  // Level record strings
  'levelCount': '{count} vlakke',
  'noLevelRecords': 'Geen vlakrekords',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Verwyder Front',
  'deleteBattlefrontContent':
      'Is jy seker jy wil front "{name}" verwyder? Hierdie aksie kan nie ongedaan gemaak word nie.',
  'battlefrontLockedCannotDelete':
      'Front is gesluit en kan nie verwyder word nie',
  'unknownNavigationLevel': 'Onbekende navigasievlak',
  'noBattlefrontSelected': 'Geen front gekies',
  'noBattlefrontToContinue': 'Geen front gevind om voort te gaan',
  'synced': 'Gesinkroniseer',
  'notSynced': 'Nie gesinkroniseer',
  'newbieBattlefrontName': 'Beginner Front {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Bynaam',
  'nicknameSetting': 'Bynaam Instelling',
  'nicknameDesc': 'Stel jou bynaam',
  'enterNickname': 'Voer bynaam in',
  'nicknameSaved': 'Bynaam gestoor',
  'nicknameUpdated': 'Bynaam suksesvol opgedateer',
  'nicknameRequired': 'Bynaam is verpligtend',
  'nicknameTooLong': 'Bynaam kan nie meer as 30 karakters wees nie',
  // Level top strings
  'levelTopCount': 'Top Ranglys ({count})',
  'levelTopCountShort': 'Top ({count})',
  'retry': 'Probeer weer',
  'noLevelTopData': 'Geen data',
  'remoteBattlefront': 'Afstandsfront',
  'participated': 'Deelgeneem',
  'notParticipated': 'Nie Deelgeneem',
  'loadMore': 'Laai meer',

  'joinBattle': 'Sluit aan by Stryd',
  'joinBattleTooltip': 'Sluit aan by stryd "{name}"',
  'joinBattleConfirm': 'Is jy seker jy wil by stryd "{name}" aansluit?',
  'joinBattleSuccess': 'Suksesvol by stryd "{name}" aangesluit',
  'joinBattleErrorSelf':
      'Kan nie by stryd "{name}" aansluit wat deur jouself geskep is nie',

  'replayBattlefront': 'Herhaal Front',
  'replayBattlefrontTooltip': 'Herhaal front "{name}"',
  'getReplayBattlefrontConfirm': 'Is jy seker jy wil "{name}" herhaal?',
  'getReplayBattlefrontFailed': 'Herhaal "{name}" het misluk: {error}',

  'download': 'Laai af',
  'downloadBattlefront': 'Laai Front af',
  'downloadBattlefrontTooltip': 'Laai front "{name}" af',
  'getDownloadBattlefrontConfirm': 'Is jy seker jy wil "{name}" aflaai?',
  'getDownloadBattlefrontSuccess': 'Suksesvol "{name}" afgelaai',
  'downloadMyOwnBattlefrontError': 'Kan slegs jou eie fronte aflaai',
  'getDownloadBattlefrontFailed': 'Aflaai "{name}" het misluk: {error}',

  'continueGameShort': 'Gaan voort',
  'replayShort': 'Herhaal',
  'highestLevel': 'Vlak {level}',
  'deviceNickname': 'Toestel',
  'createdTime': 'Geskepte Tyd',
  'remoteBattlefrontDetail': 'Front Besonderhede',
  'levelList': 'Vlak Lys',
  'fastClearTimeParam': 'Vinnige skoonmaak: {time}',
  // Remote battlefront detail strings
  'selectLocalBattlefrontHint':
      'Kies asseblief \'n plaaslike front om besonderhede te sien',
  'loadingRemoteDetail': 'Laai afstandsfront besonderhede...',
  'noRemoteBattlefrontSelected': 'Geen afstandsfront gekies',
  'failedToLoadRemoteDetail': 'Laai afstandsfront besonderhede het misluk',
  'fastestRecord': 'Vinnigste',
  'safestRecord': 'Veiligste',
  'fastestRecordDesc': 'Vinnigste (kortste tyd)',
  'safestRecordDesc': 'Veiligste (minste aksies)',
  'creator': 'Skepper',
  'player': 'Speler',
  // Branch map strings
  'getBranchMapCount': '{count} tak',
  'collapse': 'Vou saam',
  'expand': 'Vou uit',
  // Quit battlefront
  'quitBattlefront': 'Verlaat Front',
  'quitBattlefrontTooltip': 'Verlaat afstandsfront',
  'quitBattlefrontTitle': 'Verlaat Front',
  'quitBattlefrontContent':
      'Is jy seker jy wil front "{name}" verlaat? Jou plaaslike vordering sal verwyder word.',
  // Game introduction
  'gameIntroduction':
      '1. "Beginner" begin met 15 myns, kan tot 99 myns gaan.\n2. "Nuwe Front" begin met 81 myns, elke vlak verhoog myntelling, geen boonste limiet.\n3. In aanlynmodus word voltooide fronte outomaties na die wolk gedeel vir ander om te leer.',
};
