// Icelandic（冰岛语）
/// Íslenskir textar fyrir DMine forritið
const Map<String, String> stringsIs = {
  'appLabel': 'Æðsti sprengjuleitari',
  'appTitle': 'DMine - Æðsti sprengjuleitari',
  'settings': 'Stillingar',
  'gameSettings': 'Leikjastillingar',
  'showTimer': 'Sýna tímamælir',
  'showTimerDesc': 'Sýna tímamæl leiksins á skjánum',
  'showActionCounter': 'Sýna aðgerðatalara',
  'showActionCounterDesc': 'Sýna fjölda aðgerða á leikskjánanum',
  'autoAdjustBoardWidth': 'Sjálfvirkt aðlagja breidd leikborðs',
  'autoAdjustBoardWidthDesc':
      'Aðlagja breidd leikborðs sjálfvirkt að skjárastærð',
  'resetToDefaults': 'Endurheimta sjálfgefin stilling',
  'resetToDefaultsDesc': 'Endurheimta allar stillingar í sjálfgefin gildi',
  'aboutDMine': 'Um DMine',
  'version': 'Útgáfa',
  'close': 'Loka',
  'manualBoardWidth': 'Handvirkt stilla breidd leikborðs',
  'currentWidth': 'Núverandi',
  'range': 'Svið',
  'widthSliderHint':
      'Ábending: Þú getur séð breytingar á breidd leikborðs í rauntíma með því að draga skytturnar',
  'gameRecords': 'Leikskrár',
  'selectMapToViewRecords': 'Veldu kort til að skoða skrár',
  'totalRecords': 'Samtals',
  'gameRecordsTitle': 'Listi yfir leikskrár',
  'pleaseSelectMapFirst': 'Veldu fyrst kort',
  'noGameRecords': 'Engar leikskrár',
  'miningMethodFlag': 'Setja fána',
  'miningMethodBlind': 'Blind leit',
  'statusPlaying': '▶️ Í leik...',
  'statusWin': '🎉 Sigurur',
  'statusLose': '💥 Tap',
  'actionsCount': 'Fjöldi aðgerða',
  'miningMethod': 'Aðferð sprengjuleitar',
  'duration': 'Tímalengd',
  'seconds': 'sekúndur',
  'startTime': 'Upphafstími',
  'endTime': 'Lokatími',
  'pauseTime': 'Pásutími',
  'unlock': 'Aflæsa',
  'lock': 'Læsa',
  'delete': 'Eyða',
  'languageSetting': 'Tungumálastilling',
  'currentLanguage': 'Núverandi',
  'systemLanguage': 'Kerfistungumál',
  'chinese': 'Kænska',
  'english': 'Enska',
  'language': 'Tungumál',
  // Home page
  'newbie': 'Nýbyrji',
  'gameIntro': 'Leikjalýsing',
  'newBattle': 'Nýtt herframlið',
  'continueChallenge': 'Halda áfram áskorun',
  'error': 'Villa',
  'initializationFailed': 'Upphafssetja mistókst',
  // Game page
  'congratulations': 'Til hamingju, þú kláraðir stigið!',
  'gameOver': 'Leik lokið',
  'timeUsed': 'Notuður tími',
  'actionCount': 'Fjöldi aðgerða',
  'mineCount': 'Fjöldi sprengja',
  'nextLevel': 'Næsta stigi: Stigi {level}',
  'newbieNextLevel': 'Næsta stigi: Nýbyrji {level}',
  'nextLevelMines': 'Fjöldi sprengja',
  'mineIncrease': 'Aukin fjöldi',
  'newbieFinish': 'Kynning fyrir nýbýrjanda lokið',
  'ok': 'OK',
  'continueNextLevel': 'Fara á næsta stigi',
  'restart': 'Endurræsa',
  'level': 'Stigi {level}',
  'newbieLevel': 'Nýbyrja stigi {level}',
  'operationFailed': 'Aðgerð mistókst',
  // Game status texts
  'returnHome': 'Aftur til heimasíðu',
  'revealMode': 'Afhjúpunarmiði',
  'flagMode': 'Fánamiði',
  'newMap': 'Nýtt kort (sami fjöldi sprengja, búa til nýtt kort)',
  'resetMap': 'Hlaða korti aftur (sama kort, endurheimta stöðu)',
  'zoomOut': 'Auka skáli',
  'zoomIn': 'Minnka skáli',
  'resetZoom': 'Endurheimta aðdrátt',
  'previousStep': 'Fyrra skref',
  'pause': 'Pása',
  'play': 'Spila',
  'nextStep': 'Næsta skref',
  'clickToStart': 'Smelltu á hvaða reit sem er til að hefja leik',
  'playing': 'Spilar...',
  'gameWin': 'Til hamingju, þú kláraðir stigið!',
  'gameLose': 'Leik lokið, þú rakst á sprengju',
  'gamePaused': 'Leikur er pásaður',
  'ready': 'Tilbúinn',
  'clickStartShort': 'Smelltu til að hefja',
  'playingShort': 'Í gangi',
  'winShort': 'Lokið!',
  'loseShort': 'Rakst á sprengju',
  'pausedShort': 'Pásaður',
  // Counter strings
  'currentLevel': 'Núverandi stigi',
  'remainingMines': 'Eftirstöðar sprengjur',
  'gameTime': 'Leiktími (sekúndur)',
  'operationCount': 'Fjöldi aðgerða',
  'previousLevel': 'Fyrra stigi',
  'nextLevelShort': 'Næsta stigi',
  // Battlefront strings
  'completed': 'Lokið',
  'inProgress': 'Í gangi',
  'continueGame': 'Halda áfram leik',
  'replay': 'Spila aftur',
  'creater': 'Yfirmaður',
  'created': 'Tími herferðar',
  'updated': 'Uppfært',
  // Dialog strings
  'confirm': 'Staðfesta',
  'cancel': 'Hætta við',
  'yes': 'Já',
  'no': 'Nei',
  'save': 'Vista',
  'edit': 'Breyta',
  'levelFormat': 'Stigi {level}',
  'newbieLevelFormat': 'Nýbyrja stigi {level}',
  'totalLevel': '{level}/{totalLevel} stigi',
  'totalLevelTooltip': 'Núverandi: Stigi {level} / Samtals {totalLevel} stigi',
  // Battlefront UI strings
  'noBattlefronts': 'Engin herframlið',
  'battlefrontCount': '{count} herframlið',
  'levelPrefix': 'ST{level}',
  'newbieLevelPrefix': 'NB{level}',
  'minesCount': '{count} sprengjur',
  'notStarted': 'Ekki hafið',
  'victory': 'Sigurur',
  'defeat': 'Tap',
  'gameDurationParam': 'Tímalengd: {seconds} sekúndur',
  'actionsCountParam': 'Aðgerðir: {count} sinnum',
  'actionsCountParamShort': '{count} sinnum',
  'miningMethodParam': 'Aðferð: {method}',
  'startTimeParam': 'Upphafstími: {time}',
  'endTimeParam': 'Lokatími: {time}',
  'returnButton': 'Til baka',
  'battlefrontDetails': 'Nánar um herframlið',
  'clickToEditName': 'Smelltu til að breyta nafni',
  'clickToAddDescription': 'Smelltu til að bæta við lýsingu...',
  'noDescription': 'Engin lýsing',
  // Level record strings
  'levelCount': '{count} stigi',
  'noLevelRecords': 'Veldu herframlið',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Eyða herframliði',
  'deleteBattlefrontContent':
      'Ertu viss um að þú viljir eyða herframliðinu "{name}"? Þessi aðgerð er óafturkölluð.',
  'battlefrontLockedCannotDelete':
      'Herframliðið er læst, ekki hægt að eyða því',
  'unknownNavigationLevel': 'Óþekkt stigi',
  'noBattlefrontSelected': 'Ekkert herframlið valið',
  'noBattlefrontToContinue': 'Ekkert herframlið til að halda áfram',
  'synced': 'Samstillt',
  'notSynced': 'Ekki samstillt',
  'newbieBattlefrontName': 'Nýbyrja herframlið {number}',
  'battlefrontName': 'Herframlið {number}',
  'nickname': 'Kallnafn',
  'nicknameSetting': 'Stilling kallnafns',
  'nicknameDesc': 'Stilltu kallnafn þitt',
  'enterNickname': 'Sláðu inn kallnafn',
  'nicknameSaved': 'Kallnafn vistað',
  'nicknameUpdated': 'Kallnafn uppfært',
  'nicknameRequired': 'Kallnafn er nauðsynlegt',
  'nicknameTooLong': 'Kallnafn má ekki vera lengra en 30 stafir',
  // Level top strings
  'levelTopCount': 'Stigatafla ({count})',
  'levelTopCountShort': 'Stigatafla ({count})',
  'retry': 'Reyna aftur',
  'noLevelTopData': 'Engin gögn',
  'remoteBattlefront': 'Fjarherframlið',
  'participated': 'Tók þátt',
  'notParticipated': 'Tók ekki þátt',
  'loadMore': 'Hlaða meira',

  'joinBattle': 'Taka þátt í herferð',
  'joinBattleTooltip': 'Taka þátt í herferðinni "{name}"',
  'joinBattleConfirm':
      'Ertu viss um að þú viljir taka þátt í herferðinni "{name}"?',
  'joinBattleSuccess': 'Þú tókst að taka þátt í herferðinni "{name}"',
  'joinBattleErrorSelf': 'Þú getur ekki tekið þátt í þínu eigin herframliði',

  'replayBattlefront': 'Spila herframlið aftur',
  'replayBattlefrontTooltip': 'Spila herframliðið "{name}" aftur',
  'getReplayBattlefrontConfirm':
      'Ertu viss um að þú viljir spila "{name}" aftur?',
  'getReplayBattlefrontFailed': 'Mistókst að spila "{name}" aftur: {error}',

  'download': 'Niðurhala',
  'downloadBattlefront': 'Niðurhala herframliði',
  'downloadBattlefrontTooltip': 'Niðurhala herframliðinu "{name}"',
  'getDownloadBattlefrontConfirm':
      'Ertu viss um að þú viljir niðurhala "{name}"?',
  'getDownloadBattlefrontSuccess': 'Herframliðið "{name}" var niðurhalað',
  'downloadMyOwnBattlefrontError':
      'Þú getur aðeins niðurhalað þínu eigin herframliði',
  'getDownloadBattlefrontFailed': 'Mistókst að niðurhala "{name}": {error}',

  'continueGameShort': 'Halda áfram herferð',
  'replayShort': 'Spila aftur',
  'highestLevel': 'Stigi {level}',
  'deviceNickname': 'Tæki',
  'createdTime': 'Búið til þann',
  'remoteBattlefrontDetail': 'Nánar um fjarherframlið',
  'levelList': 'Listi yfir stigi',
  'fastClearTimeParam': 'Klárunartími: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Veldu staðvært herframlið til að sjá nánar',
  'loadingRemoteDetail': 'Hlaða nánar um fjarherframlið...',
  'noRemoteBattlefrontSelected': 'Ekkert fjarherframlið valið',
  'failedToLoadRemoteDetail': 'Mistókst að hlaða fjargögnum',
  'fastestRecord': 'Hástelva klárun',
  'safestRecord': 'Öruggasta klárun',
  'fastestRecordDesc': 'Hástelva klárun (minni tími)',
  'safestRecordDesc': 'Öruggasta klárun (færari aðgerðir)',
  'creator': 'Höfundur',
  'player': 'Leikmaður',
  // 分支地图字符串
  'getBranchMapCount': '{count} afrit',
  'collapse': 'Fella saman',
  'expand': 'Auka út',
  // 退出战线
  'quitBattlefront': 'Hætta í herframliði',
  'quitBattlefrontTooltip': 'Hætta í fjarherframliði',
  'quitBattlefrontTitle': 'Hætta í herframliði',
  'quitBattlefrontContent':
      'Ertu viss um að þú viljir hætta í herframliðinu "{name}"? Staðvær framvanga verður eytt.',
  // 游戏介绍
  'gameIntroduction':
      '1. „Nýbyrji“ byrjar með 15 sprengjum og getur náð allt að 99 sprengjum.\n2. „Nýtt herframlið“ byrjar með 81 sprengjum, hvert stigi bætir við sprengjum án efri mörk.\n3. Með nettenging deila „kláruðu“ herframlið sjálfvirkt í skýinu fyrir aðra að læra af.',
};
