// Mongolian（蒙古语）
/// DMine аппликэйшны Монгол хэлний үгс
const Map<String, String> stringsMn = {
  'appLabel': 'Уламжлалт Уурхагын Тоглоом',
  'appTitle': 'DMine - Уламжлалт Уурхагын Тоглоом',
  'settings': 'Тохиргоо',
  'gameSettings': 'Тоглоомын Тохиргоо',
  'showTimer': 'Цаг таймер харуулах',
  'showTimerDesc': 'Тоглоомын цаг таймерыг интерфэйсэд харуулах',
  'showActionCounter': 'Үйлдлийн тоог харуулах',
  'showActionCounterDesc': 'Тоглоом дээрх үйлдлийн тоог харуулах',
  'autoAdjustBoardWidth': 'Самбарын өргөнийг автоматаар тохируулах',
  'showUnrevealedCounter': 'Нээлтгүй нүдний тоолуурыг харуулах',
  'showUnrevealedCounterDesc': 'Тоглоомын интерфейс дээр нээлтгүй нүдний тоог харуулах',
  'showMineCounter': 'Минний тоолуурыг харуулах',
  'showMineCounterDesc': 'Тоглоомын интерфейс дээр үлдсэн минний тоог харуулах',
  'autoAdjustBoardWidthDesc':
      'Самбарын өргөнийг дэлгэцийн хэмжээнд автоматаар тохируулах',
  'resetToDefaults': 'Анхдагч тохиргоо руу буцаах',
  'resetToDefaultsDesc': 'Бүх тохиргоог анхдагч утгад сэргээх',
  'aboutDMine': 'DMine тухай',
  'version': 'Хувилбар',
  'close': 'Хаах',
  'manualBoardWidth': 'Самбарын өргөнийг гар утаснаар тохируулах',
  'currentWidth': 'Одоогийн',
  'range': 'Хүрээ',
  'widthSliderHint':
      'Зөвлөмж: Слайдерыг шилжүүлж самбарын өргөнийг өнгөрөх цагт харах',
  'gameRecords': 'Тоглоомын Бүртгэл',
  'selectMapToViewRecords': 'Бүртгэлийг харахын тулд газрын зураг сонгоно уу',
  'totalRecords': 'Нийт',
  'gameRecordsTitle': 'Тоглоомын Бүртгэлийн Жагсаалт',
  'pleaseSelectMapFirst': 'Эхлээд газрын зураг сонгоно уу',
  'noGameRecords': 'Тоглоомын бүртгэл байхгүй',
  'miningMethodFlag': 'Туг хэмжлэх',
  'miningMethodBlind': 'Хаанаас ч цохилт',
  'statusPlaying': '▶️ Тоглож байна...',
  'statusWin': '🎉 Ялсан!',
  'statusLose': '💥 Хожсон!',
  'actionsCount': 'Үйлдлийн Тоо',
  'miningMethod': 'Уурхайг олох арга',
  'duration': 'Үргэлжлэх хугацаа',
  'seconds': 'секунд',
  'startTime': 'Эхлэх Цаг',
  'endTime': 'Дуусах Цаг',
  'pauseTime': 'Паузын Цаг',
  'unlock': 'Нээх',
  'lock': 'Хаах',
  'delete': 'Устгах',
  'languageSetting': 'Хэлний Тохиргоо',
  'currentLanguage': 'Одоогийн Хэл',
  'systemLanguage': 'Системийн Хэл',
  'chinese': 'Хятад',
  'english': 'Англи',
  'language': 'Хэл',
  // Home page
  'newbie': 'Шинэ Тоглогч',
  'gameIntro': 'Тоглоомын танилцуулга',
  'newBattle': 'Шинэ Фронт',
  'continueChallenge': 'Дарлалтыг үргэлжлүүлэх',
  'error': 'Алдаа',
  'initializationFailed': 'Анхны ажиллуулалт амжилтгүй',
  // Game page
  'congratulations': 'Баяр хүргэе! Та түвшин дуусгав!',
  'gameOver': 'Тоглоом Дуусав',
  'timeUsed': 'Зарцуулсан Цаг',
  'actionCount': 'Үйлдлийн Тоо',
  'mineCount': 'Уурхайны Тоо',
  'nextLevel': 'Дараах Түвшин: Түвшин {level}',
  'newbieNextLevel': 'Дараах Түвшин: Шинэ Тоглогч {level}',
  'nextLevelMines': 'Уурхайны Тоо',
  'mineIncrease': 'Нэмэгдэл',
  'newbieFinish': 'Шинэ тоглогчийн сургалт дуусав',
  'ok': 'OK',
  'continueNextLevel': 'Дараах түвшинрүү очих',
  'restart': 'Дахин эхлүүлэх',
  'level': 'Түвшин {level}',
  'newbieLevel': 'Шинэ Тоглогчийн Түвшин {level}',
  'operationFailed': 'Үйлдэл амжилтгүй',
  // Game status texts
  'returnHome': 'Нүүр хуудас руу буцах',
  'revealMode': 'Нээх Режим',
  'flagMode': 'Туг Режим',
  'newMap': 'Шинэ газар зураг (уурхайны тоо ижил)',
  'resetMap': 'Газар зураг сэргээх',
  'zoomOut': 'Багаарлах',
  'zoomIn': 'Ихэсгэх',
  'resetZoom': 'Зум сэргээх',
  'previousStep': 'Өмнөх Алхам',
  'pause': 'Пауза',
  'play': 'Тоглох',
  'nextStep': 'Дараах Алхам',
  'clickToStart': 'Тоглоомыг эхлүүлэхэд ямар нэгэн хосолт цохилт хий',
  'playing': 'Тоглож байна...',
  'gameWin': 'Баяр хүргэе! Та түвшин дуусгав!',
  'gameLose': 'Тоглоом дуусав, уурхайд цохив',
  'gamePaused': 'Тоглоом паузлав',
  'ready': 'Бэлэн',
  'clickStartShort': 'Цохилт хийж эхлэх',
  'playingShort': 'Тоглож байна',
  'winShort': 'Ялсан!',
  'loseShort': 'Уурхайд цохив',
  'pausedShort': 'Паузлав',
  // Counter strings
  'currentLevel': 'Одоогийн Түвшин',
  'remainingMines': 'Үлдсэн Уурхай',
  'unrevealedCells': 'Нээлтгүй нүднүүд',
  'gameTime': 'Тоглоомын Цаг (секунд)',
  'operationCount': 'Үйлдлийн Тоо',
  'previousLevel': 'Өмнөх Түвшин',
  'nextLevelShort': 'Дараах Түвшин',
  // Battlefront strings
  'completed': 'Дууссан',
  'inProgress': 'Яваж байна',
  'continueGame': 'Тоглоомыг үргэлжлүүлэх',
  'replay': 'Дахин тоглох',
  'creater': 'Үүсгэгч',
  'created': 'Үүсгэсэн',
  'updated': 'Шинэчлэгдсэн',
  // Dialog strings
  'confirm': 'Баталгаажуулах',
  'cancel': 'Цуцлах',
  'yes': 'Тийм',
  'no': 'Үгүй',
  'save': 'Хадгалах',
  'edit': 'Засварлах',
  'levelFormat': 'Түвшин {level}',
  'newbieLevelFormat': 'Шинэ Тоглогчийн Түвшин {level}',
  'totalLevel': '{level}/{totalLevel} түвшин',
  'totalLevelTooltip': 'Одоо: Түвшин {level} / Нийт {totalLevel} түвшин',
  // Battlefront UI strings
  'noBattlefronts': 'Фронт байхгүй',
  'battlefrontCount': '{count} фронт',
  'levelPrefix': 'ТҮВ{level}',
  'newbiePrefix': 'ШТ{level}',
  'minesCount': '{count} уурхай',
  'notStarted': 'Эхлээгүй',
  'victory': 'Ялалт',
  'defeat': 'Хожил',
  'gameDurationParam': 'Хугацаа: {seconds} секунд',
  'actionsCountParam': 'Үйлдэл: {count} удаа',
  'actionsCountParamShort': '{count} удаа',
  'miningMethodParam': 'Арга: {method}',
  'startTimeParam': 'Эхлэл: {time}',
  'endTimeParam': 'Дуусах: {time}',
  'returnButton': 'Буцах',
  'battlefrontDetails': 'Фронтын Дэлгэрэнгүй',
  'clickToEditName': 'Нэрээ засварлахын тулд цохилт хий',
  'clickToAddDescription': 'Тодорхойлолт нэмэхэд цохилт хий...',
  'noDescription': 'Тодорхойлолт байхгүй',
  // Level record strings
  'levelCount': '{count} түвшин',
  'noLevelRecords': 'Фронт сонгоно уу',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Фронт устгах',
  'deleteBattlefrontContent':
      'Та "{name}" фронтыг устгахыг хүсэж байна уу? Энэ үйлдлийг буцаах боломжгүй.',
  'battlefrontLockedCannotDelete': 'Фронт хаалттай, устгах боломжгүй',
  'unknownNavigationLevel': 'Үл мэдэгдэх навигацийн түвшин',
  'noBattlefrontSelected': 'Фронт сонгогдоогүй',
  'noBattlefrontToContinue': 'Үргэлжлүүлэх фронт байхгүй',
  'synced': 'Синхронлогдсон',
  'notSynced': 'Синхронлогдогүй',
  'newbieBattlefrontName': 'Шинэ Тоглогчийн Фронт {number}',
  'battlefrontName': 'Фронт {number}',
  'nickname': 'Хошуу Нэр',
  'nicknameSetting': 'Хошуу Нэрийн Тохиргоо',
  'nicknameDesc': 'Хошуу нэрээ тохируулна уу',
  'enterNickname': 'Хошуу нэрээ оруулна уу',
  'nicknameSaved': 'Хошуу нэр хадгалагдлаа',
  'nicknameUpdated': 'Хошуу нэр шинэчлэгдлээ',
  'nicknameRequired': 'Хошуу нэр шаардлагатай',
  'nicknameTooLong': 'Хошуу нэр 30 тэмдэгтээс урт байж болохгүй',
  // Level top strings
  'levelTopCount': 'Ранк ({count})',
  'levelTopCountShort': 'Ранк ({count})',
  'retry': 'Дахин оролдох',
  'noLevelTopData': 'Мэдээлэл байхгүй',
  'remoteBattlefront': 'Алсын Фронт',
  'participated': 'Оролцсон',
  'notParticipated': 'Оролцогүй',
  'loadMore': 'Илүү ачаалах',

  'joinBattle': 'Дайн оролцох',
  'joinBattleTooltip': '"{name}" дайнд оролцох',
  'joinBattleConfirm': 'Та "{name}" дайнд оролцохыг хүсэж байна уу?',
  'joinBattleSuccess': 'Та "{name}" дайнд амжилттай оролцлоо',
  'joinBattleErrorSelf': 'Өөрийн фронтод оролцох боломжгүй',

  'replayBattlefront': 'Фронтыг дахин тоглох',
  'replayBattlefrontTooltip': '"{name}" фронтыг дахин тоглох',
  'getReplayBattlefrontConfirm':
      'Та "{name}"-ыг дахин тоглохыг хүсэж байна уу?',
  'getReplayBattlefrontFailed': '"{name}" дахин тоглох амжилтгүй: {error}',

  'download': 'Татаж авах',
  'downloadBattlefront': 'Фронт татаж авах',
  'downloadBattlefrontTooltip': '"{name}" фронтыг татаж авах',
  'getDownloadBattlefrontConfirm':
      'Та "{name}"-ыг татаж авахыг хүсэж байна уу?',
  'getDownloadBattlefrontSuccess': '"{name}" фронт амжилттай татагдлаа',
  'downloadMyOwnBattlefrontError': 'Зөвхөн өөрийн фронтыг татаж авах боломжтой',
  'getDownloadBattlefrontFailed': '"{name}" татаж авах амжилтгүй: {error}',

  'continueGameShort': 'Дайныг үргэлжлүүлэх',
  'replayShort': 'Дахин',
  'highestLevel': 'Түвшин {level}',
  'deviceNickname': 'Төхөөрөмж',
  'createdTime': 'Үүсгэсэн Цаг',
  'remoteBattlefrontDetail': 'Алсын Фронтын Дэлгэрэнгүй',
  'levelList': 'Түвшний Жагсаалт',
  'fastClearTimeParam': 'Хурдан дуусгах цаг: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Дэлгэрэнгүйг харахын тулд орон нутгийн фронт сонгоно уу',
  'loadingRemoteDetail': 'Алсын фронтын мэдээлэл ачаалж байна...',
  'noRemoteBattlefrontSelected': 'Алсын фронт сонгогдоогүй',
  'failedToLoadRemoteDetail': 'Алсын мэдээлэл ачаалах амжилтгүй',
  'fastestRecord': 'Хурдан Дуусгах',
  'safestRecord': 'Аюулгүй Дуусгах',
  'fastestRecordDesc': 'Хамгийн хурдан дуусгах (бага цаг)',
  'safestRecordDesc': 'Хамгийн аюулгүй дуусгах (бага үйлдэл)',
  'creator': 'Үүсгэгч',
  'player': 'Тоглогч',
  // 分支地图字符串
  'getBranchMapCount': '{count} хуулбар',
  'collapse': 'Хаах',
  'expand': 'Нээх',
  // 退出战线
  'quitBattlefront': 'Фронтөөс гарах',
  'quitBattlefrontTooltip': 'Алсын фронтөөс гарах',
  'quitBattlefrontTitle': 'Фронтөөс Гарах',
  'quitBattlefrontContent':
      'Та "{name}" фронтөөс гарахыг хүсэж байна уу? Орон нутгийн прогрес устгардаг.',
  // 游戏介绍
  'gameIntroduction':
      '1. «Шинэ Тоглогч» 15 уурхайгаар эхэлж 99 уурхай хүртэл чадна.\n2. «Шинэ Фронт» 81 уурхайгаар эхэлж түвшин бүрт уурхай нэмэгдэн хязгааргүй.\n3. Интернет холболтой бол «дууссан» фронтууд автоматаар түгэнд хадгалагддаг.',
};
