// Galician（加利西亚语）
/// Cadeas en galego para a aplicación DMine
const Map<String, String> stringsGl = {
  'appLabel': 'Buscaminas Premium',
  'appTitle': 'DMine - Buscaminas Premium',
  'settings': 'Configuración',
  'gameSettings': 'Configuración do xogo',
  'showTimer': 'Amosar temporizador',
  'showTimerDesc': 'Amosar o temporizador do xogo na interface',
  'showActionCounter': 'Amosar contador de accións',
  'showActionCounterDesc': 'Amosar o número de accións na interface do xogo',
  'autoAdjustBoardWidth': 'Axustar automaticamente a largura do taboleiro',
  'showUnrevealedCounter': 'Amosar o contador de celas sen revelar',
  'showUnrevealedCounterDesc': 'Amosar o número de celas sen revelar na interface do xogo',
  'showMineCounter': 'Amosar o contador de minas',
  'showMineCounterDesc': 'Amosar as minas restantes na interface do xogo',
  'autoAdjustBoardWidthDesc':
      'Axustar automaticamente a largura do taboleiro segundo o tamaño da pantalla',
  'resetToDefaults': 'Restablecer valores predeterminados',
  'resetToDefaultsDesc':
      'Restablecer todas as configuracións aos valores por defecto',
  'aboutDMine': 'Sobre DMine',
  'version': 'Versión',
  'close': 'Pechar',
  'manualBoardWidth': 'Establecer manualmente a largura do taboleiro',
  'currentWidth': 'Actual',
  'range': 'Gama',
  'widthSliderHint':
      'Consello: Podes previsualizar os cambios de largura en tempo real arrastrando o control deslizante',
  'gameRecords': 'Rexistros de xogo',
  'selectMapToViewRecords': 'Selecciona un mapa para ver os rexistros',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Lista de rexistros de xogo',
  'pleaseSelectMapFirst': 'Selecciona un mapa primeiro',
  'noGameRecords': 'Sen rexistros de xogo',
  'miningMethodFlag': 'Poner bandeira',
  'miningMethodBlind': 'Exploración a cegas',
  'statusPlaying': '▶️ En xogo...',
  'statusWin': '🎉 Vitoria',
  'statusLose': '💥 Derrota',
  'actionsCount': 'Número de accións',
  'miningMethod': 'Método de busca de minas',
  'duration': 'Duración',
  'seconds': 'segundos',
  'startTime': 'Hora de inicio',
  'endTime': 'Hora de fin',
  'pauseTime': 'Tempo de pausa',
  'unlock': 'Desbloquear',
  'lock': 'Bloquear',
  'delete': 'Eliminar',
  'languageSetting': 'Configuración de idioma',
  'currentLanguage': 'Actual',
  'systemLanguage': 'Idioma do sistema',
  'chinese': 'Chinés',
  'english': 'Inglés',
  'language': 'Idioma',
  // Home page
  'newbie': 'Iniciación para novos',
  'gameIntro': 'Introdución ao xogo',
  'newBattle': 'Nova batalla',
  'continueChallenge': 'Continuar o desafío',
  'error': 'Erro',
  'initializationFailed': 'Fallou a inicialización',
  // Game page
  'congratulations': 'Parabéns, superaches o nivel!',
  'gameOver': 'Xogo rematado',
  'timeUsed': 'Tempo empregado',
  'actionCount': 'Número de accións',
  'mineCount': 'Número de minas',
  'nextLevel': 'Seguinte nivel: Nivel {level}',
  'newbieNextLevel': 'Seguinte nivel: Iniciación {level}',
  'nextLevelMines': 'Número de minas',
  'mineIncrease': 'Aumento',
  'newbieFinish': 'Iniciación completada',
  'ok': 'Aceptar',
  'continueNextLevel': 'Continuar ao seguinte nivel',
  'restart': 'Reiniciar',
  'level': 'Nivel {level}',
  'newbieLevel': 'Nivel de iniciación {level}',
  'operationFailed': 'Operación fallida',
  // Game status texts
  'returnHome': 'Volver ao inicio',
  'revealMode': 'Modo de revelación',
  'flagMode': 'Modo bandeiras',
  'newMap': 'Novo mapa (mesmo número de minas, xera un novo mapa)',
  'resetMap': 'Recargar mapa (mesmo mapa, restablece o estado)',
  'zoomOut': 'Reducir',
  'zoomIn': 'Aumentar',
  'resetZoom': 'Restablecer zoom',
  'previousStep': 'Paso anterior',
  'pause': 'Pausa',
  'play': 'Xogar',
  'nextStep': 'Seguinte paso',
  'clickToStart': 'Fai clic en calquera cela para comezar o xogo',
  'playing': 'Xogando...',
  'gameWin': 'Parabéns, superaches o nivel!',
  'gameLose': 'Xogo rematado, picaches unha mina',
  'gamePaused': 'Xogo en pausa',
  'ready': 'Listo',
  'clickStartShort': 'Fai clic para comezar',
  'playingShort': 'En xogo',
  'winShort': 'Superado!',
  'loseShort': 'Picaches unha mina',
  'pausedShort': 'En pausa',
  // Counter strings
  'currentLevel': 'Nivel actual',
  'remainingMines': 'Minas restantes',
  'unrevealedCells': 'Celas sen revelar',
  'gameTime': 'Tempo de xogo (segundos)',
  'operationCount': 'Número de operacións',
  'previousLevel': 'Nivel anterior',
  'nextLevelShort': 'Seguinte nivel',
  // Battlefront strings
  'completed': 'Completado',
  'inProgress': 'En curso',
  'continueGame': 'Continuar o xogo',
  'replay': 'Repetir',
  'creater': 'Comandante',
  'created': 'Hora de inicio da batalla',
  'updated': 'Actualizado',
  // Dialog strings
  'confirm': 'Confirmar',
  'cancel': 'Cancelar',
  'yes': 'Si',
  'no': 'Non',
  'save': 'Gardar',
  'edit': 'Editar',
  'levelFormat': 'Nivel {level}',
  'newbieLevelFormat': 'Nivel de iniciación {level}',
  'totalLevel': '{level}/{totalLevel} niveis',
  'totalLevelTooltip': 'Actual: Nivel {level} / Total {totalLevel} niveis',
  // Battlefront UI strings
  'noBattlefronts': 'Sen batallas',
  'battlefrontCount': '{count} batallas',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'INI{level}',
  'minesCount': '{count} minas',
  'notStarted': 'Non comezado',
  'victory': 'Vitoria',
  'defeat': 'Derrota',
  'gameDurationParam': 'Duración: {seconds} segundos',
  'actionsCountParam': 'Accións: {count} veces',
  'actionsCountParamShort': '{count} veces',
  'miningMethodParam': 'Método: {method}',
  'startTimeParam': 'Hora de inicio: {time}',
  'endTimeParam': 'Hora de fin: {time}',
  'returnButton': 'Volver',
  'battlefrontDetails': 'Detalles da batalla',
  'clickToEditName': 'Fai clic para cambiar o nome',
  'clickToAddDescription': 'Fai clic para engadir unha descrición...',
  'noDescription': 'Sen descrición',
  // Level record strings
  'levelCount': '{count} niveis',
  'noLevelRecords': 'Selecciona unha batalla',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Eliminar batalla',
  'deleteBattlefrontContent':
      'Seguro que queres eliminar a batalla "{name}"? Esta acción non se pode desfacer.',
  'battlefrontLockedCannotDelete':
      'A batalla está bloqueada, non se pode eliminar',
  'unknownNavigationLevel': 'Nivel de navegación descoñecido',
  'noBattlefrontSelected': 'Ningunha batalla seleccionada',
  'noBattlefrontToContinue': 'Non hai batallas para continuar',
  'synced': 'Sincronizado',
  'notSynced': 'Non sincronizado',
  'newbieBattlefrontName': 'Batalla de iniciación {number}',
  'battlefrontName': 'Batalla {number}',
  'nickname': 'Alcume',
  'nicknameSetting': 'Configuración de alcume',
  'nicknameDesc': 'Establece o teu alcume',
  'enterNickname': 'Introduce o alcume',
  'nicknameSaved': 'Alcume gardado',
  'nicknameUpdated': 'Alcume actualizado',
  'nicknameRequired': 'O alcume é obrigatorio',
  'nicknameTooLong': 'O alcume non pode ter máis de 30 caracteres',
  // Level top strings
  'levelTopCount': 'Rankin {count})',
  'levelTopCountShort': 'Rankin ({count})',
  'retry': 'Tentar de novo',
  'noLevelTopData': 'Sen datos',
  'remoteBattlefront': 'Batalla remota',
  'participated': 'Participado',
  'notParticipated': 'Non participado',
  'loadMore': 'Cargar máis',

  'joinBattle': 'Unirse á batalla',
  'joinBattleTooltip': 'Unirse á batalla "{name}"',
  'joinBattleConfirm': 'Seguro que queres unirte á batalla "{name}"?',
  'joinBattleSuccess': 'Uniche correctamente á batalla "{name}"',
  'joinBattleErrorSelf': 'Non podes unirte á túa propia batalla',

  'replayBattlefront': 'Repetir a batalla',
  'replayBattlefrontTooltip': 'Repetir a batalla "{name}"',
  'getReplayBattlefrontConfirm': 'Seguro que queres repetir "{name}"?',
  'getReplayBattlefrontFailed': 'Non se puido repetir "{name}": {error}',

  'download': 'Descargar',
  'downloadBattlefront': 'Descargar batalla',
  'downloadBattlefrontTooltip': 'Descargar a batalla "{name}"',
  'getDownloadBattlefrontConfirm': 'Seguro que queres descargar "{name}"?',
  'getDownloadBattlefrontSuccess': 'Batalla "{name}" descargada correctamente',
  'downloadMyOwnBattlefrontError':
      'Solo podes descargar as túas propias batallas',
  'getDownloadBattlefrontFailed': 'Non se puido descargar "{name}": {error}',

  'continueGameShort': 'Continuar a batalla',
  'replayShort': 'Repetir',
  'highestLevel': 'Nivel {level}',
  'deviceNickname': 'Dispositivo',
  'createdTime': 'Hora de creación',
  'remoteBattlefrontDetail': 'Detalles da batalla remota',
  'levelList': 'Lista de niveis',
  'fastClearTimeParam': 'Tempo de superación: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Selecciona unha batalla local para ver os detalles',
  'loadingRemoteDetail': 'Cargando detalles da batalla remota...',
  'noRemoteBattlefrontSelected': 'Ningunha batalla remota seleccionada',
  'failedToLoadRemoteDetail': 'Non se puideron cargar os detalles remotos',
  'fastestRecord': 'Superación máis rápida',
  'safestRecord': 'Superación máis segura',
  'fastestRecordDesc': 'Superación máis rápida (menos tempo)',
  'safestRecordDesc': 'Superación máis segura (menos accións)',
  'creator': 'Creador',
  'player': 'Xogador',
  // 分支地图字符串
  'getBranchMapCount': '{count} copias',
  'collapse': 'Contraer',
  'expand': 'Expandir',
  // 退出战线
  'quitBattlefront': 'Abandonar a batalla',
  'quitBattlefrontTooltip': 'Abandonar a batalla remota',
  'quitBattlefrontTitle': 'Abandonar batalla',
  'quitBattlefrontContent':
      'Seguro que queres abandonar a batalla "{name}"? O teu progreso local eliminarse.',
  // 游戏介绍
  'gameIntroduction':
      '1. "Iniciación" comeza con 15 minas, pode chegar ata 99 minas;\n2. "Nova batalla" comeza con 81 minas, cada nivel engade minas, sen límite superior.\n3. Conexión a internet, as batallas "superadas" compártense automaticamente na nube para que outros poidan aprender.',
};
