// Georgian（格鲁吉亚语）
/// ქართული ენის სტრიქონები DMine აპლიკაციისთვის
const Map<String, String> stringsKa = {
  'appLabel': 'საუკეთესო მინაპოვი',
  'appTitle': 'DMine - საუკეთესო მინაპოვი',
  'settings': 'პარამეტრები',
  'gameSettings': 'თამაშის პარამეტრები',
  'showTimer': 'ტაიმერის ჩვენება',
  'showTimerDesc': 'თამაშის ტაიმერის ჩვენება ინტერფეისში',
  'showActionCounter': 'მოქმედებების მთვლელის ჩვენება',
  'showActionCounterDesc':
      'მოქმედებების რაოდენობის ჩვენება თამაშის ინტერფეისში',
  'autoAdjustBoardWidth': 'დაფის სიგანის ავტომატური მორგება',
  'autoAdjustBoardWidthDesc':
      'დაფის სიგანის ავტომატური მორგება ეკრანის ზომის მიხედვით',
  'resetToDefaults': 'საწყისი პარამეტრების აღდგენა',
  'resetToDefaultsDesc': 'ყველა პარამეტრის აღდგენა საწყის მნიშვნელობებზე',
  'aboutDMine': 'DMine-ს შესახებ',
  'version': 'ვერსია',
  'close': 'დახურვა',
  'manualBoardWidth': 'დაფის სიგანის ხელით დაყენება',
  'currentWidth': 'მიმდინარე',
  'range': 'დიაპაზონი',
  'widthSliderHint':
      'მინიშნება: შეგიძლიათ დაინახოთ დაფის სიგანის ცვლილებები რეალურ დროში სლაიდერის გადატანით',
  'gameRecords': 'თამაშის ჩანაწერები',
  'selectMapToViewRecords': 'აირჩიეთ რუკა ჩანაწერების სანახავად',
  'totalRecords': 'სულ',
  'gameRecordsTitle': 'თამაშის ჩანაწერების სია',
  'pleaseSelectMapFirst': 'საჭიროა პირველად აირჩიოთ რუკა',
  'noGameRecords': 'თამაშის ჩანაწერები არ არის',
  'miningMethodFlag': 'დროშის დაყენება',
  'miningMethodBlind': 'ბრმა ძიება',
  'statusPlaying': '▶️ მიმდინარეობს...',
  'statusWin': '🎉 გამარჯვება',
  'statusLose': '💥 წაგება',
  'actionsCount': 'მოქმედებების რაოდენობა',
  'miningMethod': 'მინაპოვების მეთოდი',
  'duration': 'ხანგრძლივობა',
  'seconds': 'წამი',
  'startTime': 'დაწყების დრო',
  'endTime': 'დასრულების დრო',
  'pauseTime': 'პაუზის დრო',
  'unlock': 'განბლოკვა',
  'lock': 'დაბლოკვა',
  'delete': 'წაშლა',
  'languageSetting': 'ენის პარამეტრი',
  'currentLanguage': 'მიმდინარე',
  'systemLanguage': 'სისტემური ენა',
  'chinese': 'ჩინური',
  'english': 'ინგლისური',
  'language': 'ენა',
  // Home page
  'newbie': 'მოწყობილები',
  'newBattle': 'ახალი ფრონტი',
  'continueChallenge': 'განტანტის გაგრძელება',
  'error': 'შეცდომა',
  'initializationFailed': 'ინიციალიზაცია ვერ მოხერხდა',
  // Game page
  'congratulations': 'გილოცავთ, თქვენ გაიარეთ დონე!',
  'gameOver': 'თამაში დასრულდა',
  'timeUsed': 'გამოყენებული დრო',
  'actionCount': 'მოქმედებების რაოდენობა',
  'mineCount': 'მინების რაოდენობა',
  'nextLevel': 'შემდეგი დონე: დონე {level}',
  'newbieNextLevel': 'შემდეგი დონე: მოწყობილ {level}',
  'nextLevelMines': 'მინების რაოდენობა',
  'mineIncrease': 'გაზრდა',
  'newbieFinish': 'მოწყობილების გაკვეთილი დასრულდა',
  'ok': 'კარგი',
  'continueNextLevel': 'შემდეგ დონეზე გადასვლა',
  'restart': 'გადატვირთვა',
  'level': 'დონე {level}',
  'newbieLevel': 'მოწყობილ დონე {level}',
  'operationFailed': 'ოპერაცია ვერ მოხერხდა',
  // Game status texts
  'returnHome': 'მთავარ გვერდზე დაბრუნება',
  'revealMode': 'გამოვლათი რეჟიმი',
  'flagMode': 'დროშის რეჟიმი',
  'newMap': 'ახალი რუკა (მინების რაოდენობა უცვლელია, ახალი რუკის შექმნა)',
  'resetMap': 'რუკის ხელახლა ჩატვირთვა (იგივე რუკა, მდგომარეობის აღდგენა)',
  'zoomOut': 'მცირება',
  'zoomIn': 'გადიდება',
  'resetZoom': 'ზუმის აღდგენა',
  'previousStep': 'წინა ნაბიჯი',
  'pause': 'პაუზა',
  'play': 'თამაშა',
  'nextStep': 'შემდეგი ნაბიჯი',
  'clickToStart': 'დააჭირეთ ნებისმიერ უჯრედს თამაშის დასაწყებად',
  'playing': 'თამაშდება...',
  'gameWin': 'გილოცავთ, თქვენ გაიარეთ დონე!',
  'gameLose': 'თამაში დასრულდა, მინას დაჯდა',
  'gamePaused': 'თამაში პაუზაზეა',
  'ready': 'მზადაა',
  'clickStartShort': 'დააჭირეთ დასაწყებად',
  'playingShort': 'თამაშდება',
  'winShort': 'გავლილია!',
  'loseShort': 'მინას დაჯდა',
  'pausedShort': 'პაუზაზე',
  // Counter strings
  'currentLevel': 'მიმდინარე დონე',
  'remainingMines': 'დარჩენილი მინები',
  'gameTime': 'თამაშის დრო (წამი)',
  'operationCount': 'ოპერაციების რაოდენობა',
  'previousLevel': 'წინა დონე',
  'nextLevelShort': 'შემდეგი დონე',
  // Battlefront strings
  'completed': 'დასრულებული',
  'inProgress': 'მიმდინარეობს',
  'continueGame': 'თამაშის გაგრძელება',
  'replay': 'გამოყვანა',
  'creater': 'მეთაური',
  'created': 'ბრძოლის დასაწყისი',
  'updated': 'განახლებული',
  // Dialog strings
  'confirm': 'დადასტურება',
  'cancel': 'გაუქმება',
  'yes': 'კი',
  'no': 'არა',
  'save': 'შენახვა',
  'edit': 'რედაქტირება',
  'levelFormat': 'დონე {level}',
  'newbieLevelFormat': 'მოწყობილ დონე {level}',
  'totalLevel': '{level}/{totalLevel} დონე',
  'totalLevelTooltip': 'მიმდინარე: დონე {level} / სულ {totalLevel} დონე',
  // Battlefront UI strings
  'noBattlefronts': 'ფრონტები არ არის',
  'battlefrontCount': '{count} ფრონტი',
  'levelPrefix': 'დონე {level}',
  'newbieLevelPrefix': 'მოწყობილ {level}',
  'minesCount': '{count} მინა',
  'notStarted': 'არ არის დაწყებული',
  'victory': 'გამარჯვება',
  'defeat': 'წაგება',
  'gameDurationParam': 'ხანგრძლივობა: {seconds} წამი',
  'actionsCountParam': 'მოქმედებები: {count} ჯერ',
  'actionsCountParamShort': '{count} ჯერ',
  'miningMethodParam': 'მეთოდი: {method}',
  'startTimeParam': 'დაწყების დრო: {time}',
  'endTimeParam': 'დასრულების დრო: {time}',
  'returnButton': 'დაბრუნება',
  'battlefrontDetails': 'ფრონტის დეტალები',
  'clickToEditName': 'დააჭირეთ სახელის შესაცვლელად',
  'clickToAddDescription': 'დააჭირეთ აღწერის დასამატებლად...',
  'noDescription': 'აღწერა არ არის',
  // Level record strings
  'levelCount': '{count} დონე',
  'noLevelRecords': 'აირჩიეთ ფრონტი',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'ფრონტის წაშლა',
  'deleteBattlefrontContent':
      'დარწმუნებული ხართ რომ გსურთ ფრონტის "{name}" წაშლა? ეს მოქმედება შეუქცევადია.',
  'battlefrontLockedCannotDelete': 'ფრონტი დაბლოკილია, ვერ წაიშლება',
  'unknownNavigationLevel': 'უცნობი ნავიგაციის დონე',
  'noBattlefrontSelected': 'ფრონტი არ არის არჩეული',
  'noBattlefrontToContinue': 'გაგრძელებისთვის ფრონტი არ არის',
  'synced': 'სინქრონიზებული',
  'notSynced': 'არ არის სინქრონიზებული',
  'newbieBattlefrontName': 'მოწყობილ ფრონტი {number}',
  'battlefrontName': 'ფრონტი {number}',
  'nickname': 'ნიკი',
  'nicknameSetting': 'ნიკის პარამეტრი',
  'nicknameDesc': 'დაყენეთ თქვენი ნიკი',
  'enterNickname': 'შეიყვანეთ ნიკი',
  'nicknameSaved': 'ნიკი შენახულია',
  'nicknameUpdated': 'ნიკი განახლებულია',
  'nicknameRequired': 'ნიკი სავალდებულოა',
  'nicknameTooLong': 'ნიკი არ უნდა აღემატებოდეს 30 სიმბოლოს',
  // Level top strings
  'levelTopCount': 'რეიტინგი ({count})',
  'levelTopCountShort': 'რეიტინგი ({count})',
  'retry': 'გაიმეორეთ',
  'noLevelTopData': 'მონაცემ არ არის',
  'remoteBattlefront': 'დისტანციური ფრონტი',
  'participated': 'მონაწილეობა მიიღო',
  'notParticipated': 'არ მონაწილეობს',
  'loadMore': 'მეტის ჩატვირთვა',

  'joinBattle': 'ბრძოლაში გაწევა',
  'joinBattleTooltip': 'ბრძოლაში გაწევა "{name}"',
  'joinBattleConfirm': 'დარწმუნებული ხართ რომ გსურთ ბრძოლაში გაწევა "{name}"?',
  'joinBattleSuccess': 'წარმატებით გაწევრით ბრძოლაში "{name}"',
  'joinBattleErrorSelf': 'ვერ გაწევრით საკუთარ ფრონტში',

  'replayBattlefront': 'ფრონტის გამოყვანა',
  'replayBattlefrontTooltip': 'ფრონტის გამოყვანა "{name}"',
  'getReplayBattlefrontConfirm':
      'დარწმუნებული ხართ რომ გსურთ "{name}" გამოყვანა?',
  'getReplayBattlefrontFailed': '"{name}" გამოყვანა ვერ მოხერხდა: {error}',

  'download': 'ჩამოტვირთვა',
  'downloadBattlefront': 'ფრონტის ჩამოტვირთვა',
  'downloadBattlefrontTooltip': 'ფრონტის ჩამოტვირთვა "{name}"',
  'getDownloadBattlefrontConfirm':
      'დარწმუნებული ხართ რომ გსურთ "{name}" ჩამოტვირთვა?',
  'getDownloadBattlefrontSuccess': 'ფრონტი "{name}" წარმატებით ჩამოიტვირთა',
  'downloadMyOwnBattlefrontError':
      'შეგიძლიათ ჩამოტვირთოთ მხოლოდ საკუთარი ფრონტები',
  'getDownloadBattlefrontFailed': '"{name}" ჩამოტვირთვა ვერ მოხერხდა: {error}',

  'continueGameShort': 'ბრძოლის გაგრძელება',
  'replayShort': 'გამოყვანა',
  'highestLevel': 'დონე {level}',
  'deviceNickname': 'მოწყობილობა',
  'createdTime': 'შექმნის დრო',
  'remoteBattlefrontDetail': 'დისტანციური ფრონტის დეტალები',
  'levelList': 'დონეების სია',
  'fastClearTimeParam': 'გავლის დრო: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'აირჩიეთ ადგილობრივი ფრონტი დეტალების სანახავად',
  'loadingRemoteDetail': 'დისტანციური ფრონტის დეტალების ჩატვირთვა...',
  'noRemoteBattlefrontSelected': 'დისტანციური ფრონტი არ არის არჩეული',
  'failedToLoadRemoteDetail': 'დისტანციური დეტალების ჩატვირთვა ვერ მოხერხდა',
  'fastestRecord': 'ყველაზე სწრაფი გავლა',
  'safestRecord': 'ყველაზე უსაფრთხო გავლა',
  'fastestRecordDesc': 'ყველაზე სწრაფი გავლა (მინიმალური დრო)',
  'safestRecordDesc': 'ყველაზე უსაფრთხო გავლა (მინიმალური მოქმედებები)',
  'creator': 'შემქმნელი',
  'player': 'მოთამაშე',
  // 分支地图字符串
  'getBranchMapCount': '{count} ასლი',
  'collapse': 'შეკაკვა',
  'expand': 'გაშვება',
  // 退出战线
  'quitBattlefront': 'ფრონტიდან გასვლა',
  'quitBattlefrontTooltip': 'დისტანციური ფრონტიდან გასვლა',
  'quitBattlefrontTitle': 'ფრონტიდან გასვლა',
  'quitBattlefrontContent':
      'დარწმუნებული ხართ რომ გსურთ ფრონტიდან "{name}" გასვლა? თქვენი ადგილობრივი პროგრესი წაიშლება.',

  // 下载页面
  'downloadClient': 'კლიენტის ჩამოტვირთვა',
  'browser': 'ბრაუზერი',
  'browserDesc': 'თამაშე პირდაპირ ბრაუზერში, ჩამოტვირთვის გარეშე',
  'windowsDesc': 'Windows 10 და უფრო მაღალი ვერსიებისთვის',
  'macosDesc': 'macOS 10.15 და უფრო მაღალი ვერსიებისთვის',
  'android': 'Android',
  'androidDesc': 'Android 8.0 და უფრო მაღალი ვერსიებისთვის',
  'iosDesc': 'iOS 14.0 და უფრო მაღალი ვერსიებისთვის',
  'linkAddress': 'ბმულის მისამართი',
  'downloadLink': 'ჩამოტვირთვის ბმული',
  'qrCode': 'QR კოდი',
  'scanToDownload': 'სკანირება ტელეფონით ჩამოტვირთვისთვის',
  'copy': 'კოპირება',
  'copiedToClipboard': 'კოპირებულია ბუფერში',
  'openLink': 'ბმულის გახსნა',
  'cannotOpenLink': 'ბმულის გახსნა ვერ მოხერხდა',
  // 游戏介绍
  'gameIntroduction':
      '1. "მოწყობილები" იწყება 15 მინით, შეიძლება მიაღწიოს 99 მინამდე;\n2. "ახალი ფრონტი" იწყება 81 მინით, ყოველ დონეს ემატება მინები, ზედა ზღვარი არ არსებობს.\n3. ინტერნეტთან კავშირის დროს "გავლილი" ფრონტები ავტომატურად იზიარება ღრუბლში სხვების სწავლისთვის.',
};
