// Greek（希腊语）
/// Ελληνικές συμβολοσειρές για την εφαρμογή DMine
const Map<String, String> stringsEl = {
  'appLabel': 'Κορυφαίο Αντιμινιστικό',
  'appTitle': 'DMine - Κορυφαίο Αντιμινιστικό',
  'settings': 'Ρυθμίσεις',
  'gameSettings': 'Ρυθμίσεις Παιχνιδιού',
  'showTimer': 'Εμφάνιση χρονοδιακόπτη',
  'showTimerDesc': 'Εμφάνιση του χρονοδιακόπτη του παιχνιδιού στη διεπαφή',
  'showActionCounter': 'Εμφάνιση μετρητή ενεργειών',
  'showActionCounterDesc':
      'Εμφάνιση του αριθμού των ενεργειών στη διεπαφή του παιχνιδιού',
  'autoAdjustBoardWidth': 'Αυτόματη προσαρμογή πλάτους πίνακα',
  'autoAdjustBoardWidthDesc':
      'Αυτόματη προσαρμογή του πλάτους του πίνακα σύμφωνα με το μέγεθος της οθόνης',
  'resetToDefaults': 'Επαναφορά στις προεπιλεγμένες τιμές',
  'resetToDefaultsDesc': 'Επαναφορά όλων των ρυθμίσεων στις αρχικές τιμές',
  'aboutDMine': 'Σχετικά με το DMine',
  'version': 'Έκδοση',
  'close': 'Κλείσιμο',
  'manualBoardWidth': 'Χειροκίνητη ρύθμιση πλάτους πίνακα',
  'currentWidth': 'Τρέχον',
  'range': 'Εύρος',
  'widthSliderHint':
      'Υπόδειξη: Μπορείτε να δείτε αλλαγές στο πλάτος του πίνακα σε πραγματικό χρόνο μετακινώντας το ρυθμιστή',
  'gameRecords': 'Αρχεία παιχνιδιού',
  'selectMapToViewRecords': 'Επιλέξτε έναν χάρτη για να δείτε τα αρχεία',
  'totalRecords': 'Σύνολο',
  'gameRecordsTitle': 'Λίστα αρχείων παιχνιδιού',
  'pleaseSelectMapFirst': 'Επιλέξτε πρώτα έναν χάρτη',
  'noGameRecords': 'Δεν υπάρχουν αρχεία παιχνιδιού',
  'miningMethodFlag': 'Τοποθέτηση σημαίας',
  'miningMethodBlind': 'Τυφλή αναζήτηση',
  'statusPlaying': '▶️ Παίζει...',
  'statusWin': '🎉 Νίκη',
  'statusLose': '💥 Ήττα',
  'actionsCount': 'Αριθμός ενεργειών',
  'miningMethod': 'Μέθοδος ανίχνευσης ορυκτών',
  'duration': 'Διάρκεια',
  'seconds': 'δευτερόλεπτα',
  'startTime': 'Ώρα έναρξης',
  'endTime': 'Ώρα λήξης',
  'pauseTime': 'Χρόνος παύσης',
  'unlock': 'Ξεκλείδωμα',
  'lock': 'Κλείδωμα',
  'delete': 'Διαγραφή',
  'languageSetting': 'Ρύθμιση γλώσσας',
  'currentLanguage': 'Τρέχουσα',
  'systemLanguage': 'Γλώσσα συστήματος',
  'chinese': 'Κινέζικα',
  'english': 'Αγγλικά',
  'language': 'Γλώσσα',
  // Home page
  'newbie': 'Νέος',
  'gameIntro': 'Περιγραφή παιχνιδιού',
  'newBattle': 'Νέο μέτωπο',
  'continueChallenge': 'Συνέχεια πρόκλησης',
  'error': 'Σφάλμα',
  'initializationFailed': 'Αποτυχία αρχικοποίησης',
  // Game page
  'congratulations': 'Συγχαρητήρια, περάσατε το επίπεδο!',
  'gameOver': 'Τέλος παιχνιδιού',
  'timeUsed': 'Χρόνος που χρησιμοποιήθηκε',
  'actionCount': 'Αριθμός ενεργειών',
  'mineCount': 'Αριθμός ναρκών',
  'nextLevel': 'Επόμενο επίπεδο: Επίπεδο {level}',
  'newbieNextLevel': 'Επόμενο επίπεδο: Νέος {level}',
  'nextLevelMines': 'Αριθμός ναρκών',
  'mineIncrease': 'Αύξηση',
  'newbieFinish': 'Οδηγός για νέους ολοκληρώθηκε',
  'ok': 'OK',
  'continueNextLevel': 'Συνέχεια στο επόμενο επίπεδο',
  'restart': 'Επανεκκίνηση',
  'level': 'Επίπεδο {level}',
  'newbieLevel': 'Επίπεδο νέου {level}',
  'operationFailed': 'Αποτυχία λειτουργίας',
  // Game status texts
  'returnHome': 'Επιστροφή στην αρχική',
  'revealMode': 'Κατάσταση αποκάλυψης',
  'flagMode': 'Κατάσταση σημαίας',
  'newMap': 'Νέος χάρτης (ίδιος αριθμός ναρκών, δημιουργία νέου χάρτη)',
  'resetMap': 'Επανφόρτωση χάρτη (ίδιος χάρτης, επαναφορά κατάστασης)',
  'zoomOut': 'Σμίκρυνση',
  'zoomIn': 'Μεγέθυνση',
  'resetZoom': 'Επαναφορά μεγέθυνσης',
  'previousStep': 'Προηγούμενο βήμα',
  'pause': 'Παύση',
  'play': 'Παιχνίδι',
  'nextStep': 'Επόμενο βήμα',
  'clickToStart':
      'Κάντε κλικ σε οποιοδήποτε κελί για να ξεκινήσετε το παιχνίδι',
  'playing': 'Παίζει...',
  'gameWin': 'Συγχαρητήρια, περάσατε το επίπεδο!',
  'gameLose': 'Τέλος παιχνιδιού, χτυπήσατε μια ναρκών',
  'gamePaused': 'Το παιχνίδι είναι σε παύση',
  'ready': 'Έτοιμος',
  'clickStartShort': 'Κάντε κλικ για έναρξη',
  'playingShort': 'Παίζει',
  'winShort': 'Ολοκληρώθηκε!',
  'loseShort': 'Χτύπησε ναρκών',
  'pausedShort': 'Σε παύση',
  // Counter strings
  'currentLevel': 'Τρέχον επίπεδο',
  'remainingMines': 'Υπόλοιπες ναρκών',
  'gameTime': 'Χρόνος παιχνιδιού (δευτερόλεπτα)',
  'operationCount': 'Αριθμός λειτουργιών',
  'previousLevel': 'Προηγούμενο επίπεδο',
  'nextLevelShort': 'Επόμενο επίπεδο',
  // Battlefront strings
  'completed': 'Ολοκληρωμένο',
  'inProgress': 'Σε εξέλιξη',
  'continueGame': 'Συνέχεια παιχνιδιού',
  'replay': 'Επαναληψη',
  'creater': 'Διοικητής',
  'created': 'Ώρα έναρξης μάχης',
  'updated': 'Ενημερώθηκε',
  // Dialog strings
  'confirm': 'Επιβεβαίωση',
  'cancel': 'Ακύρωση',
  'yes': 'Ναι',
  'no': 'Όχι',
  'save': 'Αποθήκευση',
  'edit': 'Επεξεργασία',
  'levelFormat': 'Επίπεδο {level}',
  'newbieLevelFormat': 'Επίπεδο νέου {level}',
  'totalLevel': '{level}/{totalLevel} επίπεδα',
  'totalLevelTooltip': 'Τρέχον: Επίπεδο {level} / Σύνολο {totalLevel} επίπεδα',
  // Battlefront UI strings
  'noBattlefronts': 'Δεν υπάρχουν μέτωπα',
  'battlefrontCount': '{count} μέτωπα',
  'levelPrefix': 'ΕΠ{level}',
  'newbieLevelPrefix': 'ΝΕ{level}',
  'minesCount': '{count} ναρκών',
  'notStarted': 'Δεν ξεκίνησε',
  'victory': 'Νίκη',
  'defeat': 'Ήττα',
  'gameDurationParam': 'Διάρκεια: {seconds} δευτερόλεπτα',
  'actionsCountParam': 'Ενέργειες: {count} φορές',
  'actionsCountParamShort': '{count} φορές',
  'miningMethodParam': 'Μέθοδος: {method}',
  'startTimeParam': 'Ώρα έναρξης: {time}',
  'endTimeParam': 'Ώρα λήξης: {time}',
  'returnButton': 'Επιστροφή',
  'battlefrontDetails': 'Λεπτομέρειες μέτωπου',
  'clickToEditName': 'Κάντε κλικ για αλλαγή ονόματος',
  'clickToAddDescription': 'Κάντε κλικ για προσθήκη περιγραφής...',
  'noDescription': 'Χωρίς περιγραφή',
  // Level record strings
  'levelCount': '{count} επίπεδα',
  'noLevelRecords': 'Επιλέξτε ένα μέτωπο',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Διαγραφή μέτωπου',
  'deleteBattlefrontContent':
      'Είστε σίγουροι ότι θέλετε να διαγράψετε το μέτωπο "{name}"; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
  'battlefrontLockedCannotDelete':
      'Το μέτωπο είναι κλειδωμένο, δεν μπορεί να διαγραφεί',
  'unknownNavigationLevel': 'Άγνωστο επίπεδο πλοήγησης',
  'noBattlefrontSelected': 'Δεν έχει επιλεγεί μέτωπο',
  'noBattlefrontToContinue': 'Δεν βρέθηκε μέτωπο για συνέχεια',
  'synced': 'Συγχρονισμένο',
  'notSynced': 'Μη συγχρονισμένο',
  'newbieBattlefrontName': 'Μέτωπο νέου {number}',
  'battlefrontName': 'Μέτωπο {number}',
  'nickname': 'Παρατσούκλι',
  'nicknameSetting': 'Ρύθμιση παρατσούκλι',
  'nicknameDesc': 'Ορίστε το παρατσούκλι σας',
  'enterNickname': 'Εισάγετε παρατσούκλι',
  'nicknameSaved': 'Το παρατσούκλι αποθηκεύτηκε',
  'nicknameUpdated': 'Το παρατσούκλι ενημερώθηκε',
  'nicknameRequired': 'Απαιτείται παρατσούκλι',
  'nicknameTooLong':
      'Το παρατσούκλι δεν μπορεί να υπερβαίνει τους 30 χαρακτήρες',
  // Level top strings
  'levelTopCount': 'Κατάταξη ({count})',
  'levelTopCountShort': 'Κατάταξη ({count})',
  'retry': 'Δοκιμή ξανά',
  'noLevelTopData': 'Δεν υπάρχουν δεδομένα',
  'remoteBattlefront': 'Απομακρυσμένο μέτωπο',
  'participated': 'Συμμετείχε',
  'notParticipated': 'Δεν συμμετείχε',
  'loadMore': 'Φόρτωση περισσότερων',

  'joinBattle': 'Ένταξη στη μάχη',
  'joinBattleTooltip': 'Ένταξη στη μάχη "{name}"',
  'joinBattleConfirm':
      'Είστε σίγουροι ότι θέλετε να συμμετάσχετε στη μάχη "{name}";',
  'joinBattleSuccess': 'Συμμετείχατε με επιτυχία στη μάχη "{name}"',
  'joinBattleErrorSelf': 'Δεν μπορείτε να συμμετάσχετε στο δικό σας μέτωπο',

  'replayBattlefront': 'Επαναληψη μέτωπου',
  'replayBattlefrontTooltip': 'Επαναληψη του μέτωπου "{name}"',
  'getReplayBattlefrontConfirm':
      'Είστε σίγουροι ότι θέλετε να επαναλάβετε το "{name}";',
  'getReplayBattlefrontFailed': 'Αποτυχία επανάληψης του "{name}": {error}',

  'download': 'Λήψη',
  'downloadBattlefront': 'Λήψη μέτωπου',
  'downloadBattlefrontTooltip': 'Λήψη του μέτωπου "{name}"',
  'getDownloadBattlefrontConfirm':
      'Είστε σίγουροι ότι θέλετε να κατεβάσετε το "{name}";',
  'getDownloadBattlefrontSuccess': 'Το μέτωπο "{name}" κατεβάστηκε με επιτυχία',
  'downloadMyOwnBattlefrontError':
      'Μπορείτε να κατεβάσετε μόνο τα δικά σας μέτωπα',
  'getDownloadBattlefrontFailed': 'Αποτυχία λήψης του "{name}": {error}',

  'continueGameShort': 'Συνέχεια μάχης',
  'replayShort': 'Επαναληψη',
  'highestLevel': 'Επίπεδο {level}',
  'deviceNickname': 'Συσκευή',
  'createdTime': 'Ώρα δημιουργίας',
  'remoteBattlefrontDetail': 'Λεπτομέρειες απομακρυσμένου μέτωπου',
  'levelList': 'Λίστα επιπέδων',
  'fastClearTimeParam': 'Χρόνος ολοκλήρωσης: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Επιλέξτε ένα τοπικό μέτωπο για να δείτε λεπτομέρειες',
  'loadingRemoteDetail': 'Φόρτωση λεπτομερειών απομακρυσμένου μέτωπου...',
  'noRemoteBattlefrontSelected': 'Δεν έχει επιλεγεί απομακρυσμένο μέτωπο',
  'failedToLoadRemoteDetail': 'Αποτυχία φόρτωσης απομακρυσμένων λεπτομερειών',
  'fastestRecord': 'Γρηγορότερη ολοκλήρωση',
  'safestRecord': 'Ασφαλέστερη ολοκλήρωση',
  'fastestRecordDesc': 'Γρηγορότερη ολοκλήρωση (λιγότερος χρόνος)',
  'safestRecordDesc': 'Ασφαλέστερη ολοκλήρωση (λιγότερες ενέργειες)',
  'creator': 'Δημιουργός',
  'player': 'Παίκτης',
  // 分支地图字符串
  'getBranchMapCount': '{count} αντίγραφα',
  'collapse': 'Σύμπτυξη',
  'expand': 'Διάταση',
  // 退出战线
  'quitBattlefront': 'Έξοδος από το μέτωπο',
  'quitBattlefrontTooltip': 'Έξοδος από το απομακρυσμένο μέτωπο',
  'quitBattlefrontTitle': 'Έξοδος από το μέτωπο',
  'quitBattlefrontContent':
      'Είστε σίγουροι ότι θέλετε να αποχωρήσετε από το μέτωπο "{name}"; Η τοπική σας πρόοδος θα διαγραφεί.',
  // 游戏介绍
  'gameIntroduction':
      '1. Το «Νέος» ξεκινά με 15 ναρκών και μπορεί να φτάσει έως 99 ναρκών.\n2. Το «Νέο μέτωπο» ξεκινά με 81 ναρκών, κάθε επίπεδο προσθέτει ναρκών χωρίς ανώτατο όριο.\n3. Με σύνδεση στο διαδίκτυο, τα «ολοκληρωμένα» μέτωπα μοιράζονται αυτόματα στο cloud για μάθηση από άλλους.',
};
