// Serbian（塞尔维亚语）
/// Serbian (Cyrillic) language strings for the DMine application
const Map<String, String> stringsSr = {
  'appLabel': 'Топ Минер',
  'appTitle': 'DMine - Топ Минер',
  'settings': 'Подешавања',
  'gameSettings': 'Подешавања игре',
  'showTimer': 'Прикажи тајмер',
  'showTimerDesc': 'Приказује тајмер игре на екрану игре',
  'showActionCounter': 'Прикажи бројач акција',
  'showActionCounterDesc': 'Приказује број акција на екрану игре',
  'autoAdjustBoardWidth': 'Аутоматско прилагођавање ширине табле',
  'autoAdjustBoardWidthDesc':
      'Аутоматски прилагођава ширину табле према величини екрана',
  'resetToDefaults': 'Врати подразумеване подешавања',
  'resetToDefaultsDesc': 'Враћа сва подешавања на подразумеване вредности',
  'aboutDMine': 'О DMine',
  'version': 'Верзија',
  'close': 'Затвори',
  'manualBoardWidth': 'Ручно подешавање ширине табле',
  'currentWidth': 'Тренутно',
  'range': 'Опсег',
  'widthSliderHint':
      'Савет: при превлачењу клизача видите промене ширине табле одмах',
  'gameRecords': 'Рекорди игре',
  'selectMapToViewRecords': 'Изаберите мапу за преглед рекорда',
  'totalRecords': 'Укупно',
  'gameRecordsTitle': 'Листа рекорда игре',
  'pleaseSelectMapFirst': 'Прво изаберите мапу',
  'noGameRecords': 'Нема рекорда игре',
  'miningMethodFlag': 'Ознаки заставом',
  'miningMethodBlind': 'Слепа размина',
  'statusPlaying': '▶️ У току...',
  'statusWin': '🎉 Победа',
  'statusLose': '💥 Пораз',
  'actionsCount': 'Број акција',
  'miningMethod': 'Начин игре',
  'duration': 'Трајање',
  'seconds': 'секунди',
  'startTime': 'Време почетка',
  'endTime': 'Време завршетка',
  'pauseTime': 'Време паузе',
  'unlock': 'Откључај',
  'lock': 'Закључај',
  'delete': 'Обриши',
  'languageSetting': 'Подешавање језика',
  'currentLanguage': 'Тренутни',
  'systemLanguage': 'Системски језик',
  'chinese': 'Кинески',
  'english': 'Енглески',
  'language': 'Језик',
  // Home page
  'newbie': 'Почетник',
  'gameIntro': 'Увод у игру',
  'newBattle': 'Нови фронт',
  'continueChallenge': 'Настави изазов',
  'error': 'Грешка',
  'initializationFailed': 'Иницијализација није успела',
  // Game page
  'congratulations': 'Честитамо, прошли сте ниво!',
  'gameOver': 'Крај игре',
  'timeUsed': 'Употребљено време',
  'actionCount': 'Акције',
  'mineCount': 'Мине',
  'nextLevel': 'Следећи ниво: Ниво {level}',
  'newbieNextLevel': 'Следећи ниво: Почетник {level}',
  'nextLevelMines': 'Мине',
  'mineIncrease': 'Повећање',
  'newbieFinish': 'Режим почетника завршен',
  'ok': 'У реду',
  'continueNextLevel': 'Настави на следећи ниво',
  'restart': 'Покрени поново',
  'level': 'Ниво {level}',
  'newbieLevel': 'Почетник {level}',
  'operationFailed': 'Операција није успела',
  // Game status texts
  'returnHome': 'Назад на почетну',
  'revealMode': 'Режим откривања',
  'flagMode': 'Режим заставе',
  'newMap': 'Нова мапа (исти број мина, нови распоред)',
  'resetMap': 'Ресетуј мапу (исти распоред, ресет стања)',
  'zoomOut': 'Умањи',
  'zoomIn': 'Увећај',
  'resetZoom': 'Врати оригинални зум',
  'previousStep': 'Претходни корак',
  'pause': 'Пауза',
  'play': 'Играј',
  'nextStep': 'Следећи корак',
  'clickToStart': 'Кликните било које поље да почнете игру',
  'playing': 'У игри...',
  'gameWin': 'Честитамо, прошли сте ниво!',
  'gameLose': 'Крај игре, ступили сте на мину',
  'gamePaused': 'Игра је паузирана',
  'ready': 'Спремно за почетак',
  'clickStartShort': 'Кликните да почнете',
  'playingShort': 'У игри',
  'winShort': 'Завршено!',
  'loseShort': 'Пораз',
  'pausedShort': 'Паузирано',
  // Counter strings
  'currentLevel': 'Тренутни ниво',
  'remainingMines': 'Преостале мине',
  'gameTime': 'Време игре (секунди)',
  'operationCount': 'Број операција',
  'previousLevel': 'Претходни ниво',
  'nextLevelShort': 'Следећи ниво',
  // Battlefront strings
  'completed': 'Завршено',
  'inProgress': 'У току',
  'continueGame': 'Настави игру',
  'replay': 'Поново',
  'creater': 'Командант',
  'created': 'Време креирања',
  'updated': 'Ажурирано',
  // Dialog strings
  'confirm': 'Потврди',
  'cancel': 'Откажи',
  'yes': 'Да',
  'no': 'Не',
  'save': 'Сачувај',
  'edit': 'Уреди',
  'levelFormat': 'Ниво {level}',
  'newbieLevelFormat': 'Почетник {level}',
  'totalLevel': '{level}/{totalLevel} нивоа',
  'totalLevelTooltip': 'Тренутно: Ниво {level} / Укупно {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Нема фронтова',
  'battlefrontCount': '{count} фронтова',
  'levelPrefix': 'НВ{level}',
  'newbieLevelPrefix': 'Почетник НВ{level}',
  'minesCount': '{count} мина',
  'notStarted': 'Није почето',
  'victory': 'Победа',
  'defeat': 'Пораз',
  'gameDurationParam': 'Трајање: {seconds}с',
  'actionsCountParam': 'Акције: {count} пута',
  'actionsCountParamShort': '{count} пута',
  'miningMethodParam': 'Начин: {method}',
  'startTimeParam': 'Почетак: {time}',
  'endTimeParam': 'Завршетак: {time}',
  'returnButton': 'Назад',
  'battlefrontDetails': 'Детаљи фронта',
  'clickToEditName': 'Кликните да уредите име',
  'clickToAddDescription': 'Кликните да додате опис...',
  'noDescription': 'Без описа',
  // Level record strings
  'levelCount': '{count} нивоа',
  'noLevelRecords': 'Изаберите фронт',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Обриши фронт',
  'deleteBattlefrontContent':
      'Да ли сте сигурни да желите да обришете фронт \'{name}\'? Ова акција се не може опозвати.',
  'battlefrontLockedCannotDelete': 'Фронт је закључан, не може се обрисати',
  'unknownNavigationLevel': 'Непознат ниво',
  'noBattlefrontSelected': 'Није изабран фронт',
  'noBattlefrontToContinue': 'Нема доступног фронта за наставак',
  'synced': 'Синхронизовано',
  'notSynced': 'Није синхронизовано',
  'newbieBattlefrontName': 'Фронт почетника {number}',
  'battlefrontName': 'Фронт {number}',
  'nickname': 'Надимак',
  'nicknameSetting': 'Подешавање надимка',
  'nicknameDesc': 'Подесите свој надимак',
  'enterNickname': 'Унесите надимак',
  'nicknameSaved': 'Надимак сачуван',
  'nicknameUpdated': 'Надимак ажуриран',
  'nicknameRequired': 'Надимак је обавезан',
  'nicknameTooLong': 'Надимак не сме бити дужи од 30 знакова',
  // Level top strings
  'levelTopCount': 'Рейтинг ({count})',
  'levelTopCountShort': 'Рейтинг ({count})',
  'retry': 'Покушај поново',
  'noLevelTopData': 'Нема података',
  'remoteBattlefront': 'Удаљени фронт',
  'participated': 'Учествовао',
  'notParticipated': 'Није учествовао',
  'loadMore': 'Учитај више',
  'joinBattle': 'Придружи се борби',
  'joinBattleTooltip': 'Придружи се борби \'{name}\'',
  'joinBattleConfirm':
      'Да ли сте сигурни да желите да се придружите борби \'{name}\'?',
  'joinBattleSuccess': 'Успешно сте се придружили борби \'{name}\'',
  'joinBattleErrorSelf': 'Не можете се придружити свом сопственом фронту',
  'replayBattlefront': 'Поново покрени фронт',
  'replayBattlefrontTooltip': 'Поново покрени фронт \'{name}\'',
  'getReplayBattlefrontConfirm':
      'Да ли сте сигурни да желите да поново покренете \'{name}\'?',
  'getReplayBattlefrontFailed':
      'Поновно покретање \'{name}\' није успело: {error}',
  'download': 'Преузми',
  'downloadBattlefront': 'Преузми фронт',
  'downloadBattlefrontTooltip': 'Преузми фронт \'{name}\'',
  'getDownloadBattlefrontConfirm':
      'Да ли сте сигурни да желите да преузмете \'{name}\'?',
  'getDownloadBattlefrontSuccess': '\'{name}\' успешно преузет',
  'downloadMyOwnBattlefrontError':
      'Можете преузети само своје сопствене фронтове',
  'getDownloadBattlefrontFailed': 'Преузимање \'{name}\' није успело: {error}',
  'continueGameShort': 'Настави борбу',
  'replayShort': 'Поново',
  'highestLevel': 'Ниво {level}',
  'deviceNickname': 'Уређај',
  'createdTime': 'Време креирања',
  'remoteBattlefrontDetail': 'Детаљи удаљеног фронта',
  'levelList': 'Листа нивоа',
  'fastClearTimeParam': 'Време завршетка: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint': 'Изаберите локални фронт за преглед детаља',
  'loadingRemoteDetail': 'Учитавање детаља удаљеног фронта...',
  'noRemoteBattlefrontSelected': 'Није изабран удаљени фронт',
  'failedToLoadRemoteDetail': 'Учитавање детаља није успело',
  'fastestRecord': 'Најбрже завршетак',
  'safestRecord': 'Најбезбедније завршетак',
  'fastestRecordDesc': 'Најбрже (најмање времена)',
  'safestRecordDesc': 'Најбезбедније (најмање акција)',
  'creator': 'Креатор',
  'player': 'Играч',
  // Branch maps
  'getBranchMapCount': '{count} копија',
  'collapse': 'Скупи',
  'expand': 'Прошири',
  // Quit battlefront
  'quitBattlefront': 'Напусти фронт',
  'quitBattlefrontTooltip': 'Напусти удаљени фронт',
  'quitBattlefrontTitle': 'Напусти фронт',
  'quitBattlefrontContent':
      'Да ли сте сигурни да желите да напустите фронт \'{name}\'? Ваш локални напредак ће бити обрисан.',
  // Download page
  'downloadClient': 'Преузми клијент',
  'browser': 'Претраживач',
  'browserDesc': 'Играјте директно у претраживачу, без преузимања',
  'windowsDesc': 'За Windows 10 и новије верзије',
  'macosDesc': 'За macOS 10.15 и новије верзије',
  'android': 'Android',
  'androidDesc': 'За Android 8.0 и новије верзије',
  'iosDesc': 'За iOS 14.0 и новије верзије',
  'linkAddress': 'Адреса везе',
  'downloadLink': 'Веза за преузимање',
  'qrCode': 'QR код',
  'scanToDownload': 'Скенирајте телефоном за преузимање',
  'copy': 'Копирај',
  'copiedToClipboard': 'Копирано у клипборд',
  'openLink': 'Отвори везу',
  'cannotOpenLink': 'Не може да се отвори веза',
  // Game introduction
  'gameIntroduction':
      '1. „Почетник“ почиње са 15 мина, максимум до 99 мина;\n2. „Нови фронт“ почиње са 81 мина, број се повећава сваки ниво, без горње границе.\n3. У мрежи, завршени фронтови се аутоматски деле у облаку за друге играче.',
};
