// Japanese（日语）
/// DMineアプリケーション用日本語文字列
const Map<String, String> stringsJa = {
  'appLabel': 'プレミアムマインスイーパー',
  'appTitle': 'DMine - プレミアムマインスイーパー',
  'settings': '設定',
  'gameSettings': 'ゲーム設定',
  'showTimer': 'タイマーを表示',
  'showTimerDesc': 'ゲームのタイマーを画面に表示します',
  'showActionCounter': '操作回数を表示',
  'showActionCounterDesc': 'ゲーム画面に操作回数を表示します',
  'autoAdjustBoardWidth': '盤面の幅を自動調整',
  'autoAdjustBoardWidthDesc': '画面サイズに合わせて盤面の幅を自動調整します',
  'resetToDefaults': '初期設定に戻す',
  'resetToDefaultsDesc': 'すべての設定を元の値にリセットします',
  'aboutDMine': 'DMineについて',
  'version': 'バージョン',
  'close': '閉じる',
  'manualBoardWidth': '盤面の幅を手動設定',
  'currentWidth': '現在',
  'range': '範囲',
  'widthSliderHint': 'ヒント：スライダーをドラッグするとリアルタイムで盤面の幅が変更されます',
  'gameRecords': 'ゲーム記録',
  'selectMapToViewRecords': '記録を表示するマップを選択',
  'totalRecords': '合計',
  'gameRecordsTitle': 'ゲーム記録一覧',
  'pleaseSelectMapFirst': '最初にマップを選択してください',
  'noGameRecords': 'ゲーム記録がありません',
  'miningMethodFlag': 'フラグを設置',
  'miningMethodBlind': 'ブラインド検索',
  'statusPlaying': '▶️ プレイ中...',
  'statusWin': '🎉 クリア',
  'statusLose': '💥 ゲームオーバー',
  'actionsCount': '操作回数',
  'miningMethod': '地雷探査方法',
  'duration': 'プレイ時間',
  'seconds': '秒',
  'startTime': '開始時間',
  'endTime': '終了時間',
  'pauseTime': '一時停止時間',
  'unlock': 'ロック解除',
  'lock': 'ロック',
  'delete': '削除',
  'languageSetting': '言語設定',
  'currentLanguage': '現在の言語',
  'systemLanguage': 'システム言語',
  'chinese': '中国語',
  'english': '英語',
  'language': '言語',
  // Home page
  'newbie': '初心者',
  'newBattle': '新規戦線',
  'continueChallenge': 'チャレンジを続ける',
  'error': 'エラー',
  'initializationFailed': '初期化に失敗しました',
  // Game page
  'congratulations': 'おめでとうございます！ステージクリア！',
  'gameOver': 'ゲームオーバー',
  'timeUsed': '使用時間',
  'actionCount': '操作回数',
  'mineCount': '地雷数',
  'nextLevel': '次のステージ：レベル{level}',
  'newbieNextLevel': '次のステージ：初心者{level}',
  'nextLevelMines': '地雷数',
  'mineIncrease': '増加量',
  'newbieFinish': '初心者チュートリアル完了',
  'ok': 'OK',
  'continueNextLevel': '次のステージへ',
  'restart': 'リスタート',
  'level': 'レベル{level}',
  'newbieLevel': '初心者レベル{level}',
  'operationFailed': '操作に失敗しました',
  // Game status texts
  'returnHome': 'ホームに戻る',
  'revealMode': '開示モード',
  'flagMode': 'フラグモード',
  'newMap': '新規マップ（地雷数は同じ、新しいマップを作成）',
  'resetMap': 'マップをリロード（同じマップ、状態をリセット）',
  'zoomOut': '縮小',
  'zoomIn': '拡大',
  'resetZoom': 'ズームリセット',
  'previousStep': '前のステップ',
  'pause': '一時停止',
  'play': 'プレイ',
  'nextStep': '次のステップ',
  'clickToStart': '任意のマスをクリックしてゲーム開始',
  'playing': 'プレイ中...',
  'gameWin': 'おめでとうございます！ステージクリア！',
  'gameLose': 'ゲームオーバー、地雷を踏みました',
  'gamePaused': 'ゲームを一時停止中',
  'ready': '準備完了',
  'clickStartShort': 'クリックでスタート',
  'playingShort': 'プレイ中',
  'winShort': 'クリア！',
  'loseShort': 'ゲームオーバー',
  'pausedShort': '一時停止',
  // Counter strings
  'currentLevel': '現在のレベル',
  'remainingMines': '残り地雷数',
  'gameTime': 'プレイ時間（秒）',
  'operationCount': '操作回数',
  'previousLevel': '前のレベル',
  'nextLevelShort': '次のレベル',
  // Battlefront strings
  'completed': '完了',
  'inProgress': '進行中',
  'continueGame': 'ゲームを続ける',
  'replay': 'リプレイ',
  'creater': '司令官',
  'created': '戦闘開始時間',
  'updated': '更新日時',
  // Dialog strings
  'confirm': '確定',
  'cancel': 'キャンセル',
  'yes': 'はい',
  'no': 'いいえ',
  'save': '保存',
  'edit': '編集',
  'levelFormat': 'レベル{level}',
  'newbieLevelFormat': '初心者レベル{level}',
  'totalLevel': '{level}/{totalLevel} ステージ',
  'totalLevelTooltip': '現在：レベル{level} / 全{totalLevel}ステージ',
  // Battlefront UI strings
  'noBattlefronts': '戦線がありません',
  'battlefrontCount': '{count} 戦線',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': '初心者{level}',
  'minesCount': '{count} 個の地雷',
  'notStarted': '未開始',
  'victory': '勝利',
  'defeat': '敗北',
  'gameDurationParam': 'プレイ時間：{seconds}秒',
  'actionsCountParam': '操作回数：{count}回',
  'actionsCountParamShort': '{count}回',
  'miningMethodParam': '方法：{method}',
  'startTimeParam': '開始時間：{time}',
  'endTimeParam': '終了時間：{time}',
  'returnButton': '戻る',
  'battlefrontDetails': '戦線詳細',
  'clickToEditName': 'クリックして名前を変更',
  'clickToAddDescription': 'クリックして説明を追加...',
  'noDescription': '説明なし',
  // Level record strings
  'levelCount': '{count} ステージ',
  'noLevelRecords': '戦線を選択してください',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': '戦線を削除',
  'deleteBattlefrontContent': '戦線「{name}」を削除してもよろしいですか？この操作は元に戻せません。',
  'battlefrontLockedCannotDelete': '戦線がロックされているため削除できません',
  'unknownNavigationLevel': '不明なナビゲーションレベル',
  'noBattlefrontSelected': '戦線が選択されていません',
  'noBattlefrontToContinue': '続行する戦線がありません',
  'synced': '同期済み',
  'notSynced': '未同期',
  'newbieBattlefrontName': '初心者戦線 {number}',
  'battlefrontName': '戦線 {number}',
  'nickname': 'ニックネーム',
  'nicknameSetting': 'ニックネーム設定',
  'nicknameDesc': 'ニックネームを設定してください',
  'enterNickname': 'ニックネームを入力',
  'nicknameSaved': 'ニックネームを保存しました',
  'nicknameUpdated': 'ニックネームを更新しました',
  'nicknameRequired': 'ニックネームは必須です',
  'nicknameTooLong': 'ニックネームは30文字以内で入力してください',
  // Level top strings
  'levelTopCount': 'ランキング（{count}）',
  'levelTopCountShort': 'ランキング（{count}）',
  'retry': 'リトライ',
  'noLevelTopData': 'データがありません',
  'remoteBattlefront': 'リモート戦線',
  'participated': '参加済み',
  'notParticipated': '未参加',
  'loadMore': 'さらに読み込む',

  'joinBattle': '戦闘に参加',
  'joinBattleTooltip': '「{name}」戦闘に参加',
  'joinBattleConfirm': '「{name}」戦闘に参加してもよろしいですか？',
  'joinBattleSuccess': '「{name}」戦闘に参加しました',
  'joinBattleErrorSelf': '自身の戦線には参加できません',

  'replayBattlefront': '戦線をリプレイ',
  'replayBattlefrontTooltip': '戦線「{name}」をリプレイ',
  'getReplayBattlefrontConfirm': '「{name}」をリプレイしてもよろしいですか？',
  'getReplayBattlefrontFailed': '「{name}」のリプレイに失敗しました：{error}',

  'download': 'ダウンロード',
  'downloadBattlefront': '戦線をダウンロード',
  'downloadBattlefrontTooltip': '戦線「{name}」をダウンロード',
  'getDownloadBattlefrontConfirm': '「{name}」をダウンロードしてもよろしいですか？',
  'getDownloadBattlefrontSuccess': '戦線「{name}」をダウンロードしました',
  'downloadMyOwnBattlefrontError': '自身の戦線のみダウンロードできます',
  'getDownloadBattlefrontFailed': '「{name}」のダウンロードに失敗しました：{error}',

  'continueGameShort': '戦闘続行',
  'replayShort': 'リプレイ',
  'highestLevel': 'レベル{level}',
  'deviceNickname': 'デバイス',
  'createdTime': '作成日時',
  'remoteBattlefrontDetail': 'リモート戦線詳細',
  'levelList': 'ステージ一覧',
  'fastClearTimeParam': 'クリアタイム：{time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'ローカル戦線を選択して詳細を表示',
  'loadingRemoteDetail': 'リモート戦線詳細を読み込み中...',
  'noRemoteBattlefrontSelected': 'リモート戦線が選択されていません',
  'failedToLoadRemoteDetail': 'リモート詳細の読み込みに失敗しました',
  'fastestRecord': '最速クリア',
  'safestRecord': '最安全クリア',
  'fastestRecordDesc': '最速クリア（時間が短い）',
  'safestRecordDesc': '最安全クリア（操作回数が少ない）',
  'creator': '作成者',
  'player': 'プレイヤー',
  // 分支地图字符串
  'getBranchMapCount': '{count}個のコピー',
  'collapse': '折りたたむ',
  'expand': '展開する',
  // 退出战线
  'quitBattlefront': '戦線を退出',
  'quitBattlefrontTooltip': 'リモート戦線を退出',
  'quitBattlefrontTitle': '戦線を退出',
  'quitBattlefrontContent': '戦線「{name}」を退出してもよろしいですか？ローカルの進行データは削除されます。',

  // 下载页面
  'downloadClient': 'クライアントをダウンロード',
  'browser': 'ブラウザ',
  'browserDesc': 'ダウンロード不要、ブラウザで直接プレイ',
  'windowsDesc': 'Windows 10 以降対応',
  'macosDesc': 'macOS 10.15 以降対応',
  'android': 'Android',
  'androidDesc': 'Android 8.0 以降対応',
  'iosDesc': 'iOS 14.0 以降対応',
  'linkAddress': 'リンクアドレス',
  'downloadLink': 'ダウンロードリンク',
  'qrCode': 'QRコード',
  'scanToDownload': 'スマホでスキャンしてダウンロード',
  'copy': 'コピー',
  'copiedToClipboard': 'クリップボードにコピーしました',
  'openLink': 'リンクを開く',
  'cannotOpenLink': 'リンクを開けませんでした',
  // 游戏介绍
  'gameIntroduction':
      '1. 「初心者」は15個の地雷からスタートし、最大99個まで挑戦できます。\n2. 「新規戦線」は81個の地雷からスタートし、ステージごとに上限なく地雷が増加します。\n3. インターネット接続時、「クリア済み」の戦線は自動的にクラウドに共有され、他のプレイヤーが参考にできます。',
};
