/// Traditional Chinese language strings for the DMine application
const Map<String, String> stringsZhHant = {
  'appLabel': '頂級掃雷',
  'appTitle': 'DMine - 頂級掃雷',
  'settings': '設定',
  'gameSettings': '遊戲設定',
  'showTimer': '顯示用時計時器',
  'showTimerDesc': '在遊戲介面顯示遊戲計時器',
  'showActionCounter': '顯示動作數計數器',
  'showActionCounterDesc': '在遊戲介面顯示動作次數統計',
  'autoAdjustBoardWidth': '自動調整棋盤寬度',
  'autoAdjustBoardWidthDesc': '自動根據螢幕大小調整棋盤寬度',
  'resetToDefaults': '重置為預設設定',
  'resetToDefaultsDesc': '恢復所有設定為預設值',
  'aboutDMine': '關於頂雷',
  'version': '版本',
  'close': '關閉',
  'manualBoardWidth': '手動設定棋盤寬度',
  'currentWidth': '當前',
  'range': '範圍',
  'widthSliderHint': '提示：滑塊拖動過程中可以即時預覽棋盤寬度變化',
  'gameRecords': '遊戲記錄',
  'selectMapToViewRecords': '請選擇一個地圖查看記錄',
  'totalRecords': '共',
  'gameRecordsTitle': '遊戲記錄列表',
  'pleaseSelectMapFirst': '請先選擇一個地圖',
  'noGameRecords': '暫無遊戲記錄',
  'miningMethodFlag': '插旗',
  'miningMethodBlind': '盲掃',
  'statusPlaying': '▶️ 進行中...',
  'statusWin': '🎉 勝利',
  'statusLose': '💥 失敗',
  'actionsCount': '操作數',
  'miningMethod': '掃雷方式',
  'duration': '時長',
  'seconds': '秒',
  'startTime': '開始時間',
  'endTime': '結束時間',
  'pauseTime': '暫停時間',
  'unlock': '解鎖',
  'lock': '鎖定',
  'delete': '刪除',
  'languageSetting': '語言設定',
  'currentLanguage': '當前',
  'systemLanguage': '系統語言',
  'chinese': '中文',
  'english': 'English',
  'language': '語言',
  // Home page
  'newbie': '新手入門',
  'gameIntro': '',
  'newBattle': '新戰線',
  'continueChallenge': '繼續挑戰',
  'error': '錯誤',
  'initializationFailed': '初始化失敗',
  // Game page
  'congratulations': '恭喜通關！',
  'gameOver': '遊戲結束',
  'timeUsed': '用時',
  'actionCount': '動作數',
  'mineCount': '地雷數',
  'nextLevel': '下一關: 第 {level} 關',
  'newbieNextLevel': '下一關: 新手第 {level} 關',
  'nextLevelMines': '地雷數',
  'mineIncrease': '增加',
  'newbieFinish': '新手入門已完成',
  'ok': '確定',
  'continueNextLevel': '繼續挑戰下一關',
  'restart': '重新開始',
  'level': '第 {level} 關',
  'newbieLevel': '新手第 {level} 關',
  'operationFailed': '操作失敗',
  // Game status texts
  'returnHome': '返回主頁',
  'revealMode': '揭開模式',
  'flagMode': '插旗模式',
  'newMap': '新地圖(地雷數不變,生成新地圖)',
  'resetMap': '重新載入地圖(地圖不變,重置狀態)',
  'zoomOut': '縮小',
  'zoomIn': '放大',
  'resetZoom': '恢復原樣',
  'previousStep': '上一步',
  'pause': '暫停',
  'play': '播放',
  'nextStep': '下一步',
  'clickToStart': '點擊任意格子開始遊戲',
  'playing': '遊戲中...',
  'gameWin': '恭喜通關！',
  'gameLose': '遊戲結束，踩到地雷了',
  'gamePaused': '遊戲暫停',
  'ready': '準備開始',
  'clickStartShort': '點擊開始',
  'playingShort': '遊戲中',
  'winShort': '通關！',
  'loseShort': '踩雷失敗',
  'pausedShort': '暫停',
  // Counter strings
  'currentLevel': '當前關次',
  'remainingMines': '剩餘地雷數',
  'gameTime': '遊戲用時（秒）',
  'operationCount': '操作次數',
  'previousLevel': '上一關',
  'nextLevelShort': '下一關',
  // Battlefront strings
  'completed': '已完成',
  'inProgress': '進行中',
  'continueGame': '繼續遊戲',
  'replay': '回放',
  'creater': '總司令',
  'created': '開戰時間',
  'updated': '更新',
  // Dialog strings
  'confirm': '確認',
  'cancel': '取消',
  'yes': '是',
  'no': '否',
  'save': '保存',
  'edit': '編輯',
  'levelFormat': '第 {level} 關',
  'newbieLevelFormat': '新手第 {level} 關',
  'totalLevel': '{level}/{totalLevel} 關',
  'totalLevelTooltip': '當前: 第 {level} 關 / 共 {totalLevel} 關',
  // Battlefront UI strings
  'noBattlefronts': '暫無戰線',
  'battlefrontCount': '{count}個戰線',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': '新手LV{level}',
  'minesCount': '{count}雷',
  'notStarted': '未開始',
  'victory': '勝利',
  'defeat': '失敗',
  'gameDurationParam': '時長: {seconds}秒',
  'actionsCountParam': '動作: {count}次',
  'actionsCountParamShort': '{count}次',
  'miningMethodParam': '方式: {method}',
  'startTimeParam': '開始時間: {time}',
  'endTimeParam': '結束時間: {time}',
  'returnButton': '返回',
  'battlefrontDetails': '戰線詳情',
  'clickToEditName': '點擊修改名稱',
  'clickToAddDescription': '點擊添加描述...',
  'noDescription': '暫無描述',
  // Level record strings
  'levelCount': '{count}個關次',
  'noLevelRecords': '請選擇戰線',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': '刪除戰線',
  'deleteBattlefrontContent': '確定要刪除戰線 "{name}" 嗎？此操作不可撤銷。',
  'battlefrontLockedCannotDelete': '戰線已鎖定，無法刪除',
  'unknownNavigationLevel': '未知層級',
  'noBattlefrontSelected': '未選擇戰線',
  'noBattlefrontToContinue': '沒有找到可繼續的戰線',
  'synced': '已同步',
  'notSynced': '未同步',
  'newbieBattlefrontName': '新手戰線{number}',
  'battlefrontName': '戰線{number}',
  'nickname': '暱稱',
  'nicknameSetting': '暱稱設定',
  'nicknameDesc': '設定您的暱稱',
  'enterNickname': '輸入暱稱',
  'nicknameSaved': '暱稱已保存',
  'nicknameUpdated': '暱稱更新成功',
  'nicknameRequired': '暱稱為必填項',
  'nicknameTooLong': '暱稱不能超過30個字符',
  // Level top strings
  'levelTopCount': '頂級榜 ({count})',
  'levelTopCountShort': '頂級 ({count})',
  'retry': '重試',
  'noLevelTopData': '暫無數據',
  'remoteBattlefront': '遠程戰線',
  'participated': '已參戰',
  'notParticipated': '未參戰',
  'loadMore': '加載更多',

  'joinBattle': '參戰',
  'joinBattleTooltip': '參戰"{name}"',
  'joinBattleConfirm': '確認要參戰"{name}"嗎？',
  'joinBattleSuccess': '成功參戰"{name}"',
  'joinBattleErrorSelf': '不能參戰自己創建的戰線',

  'replayBattlefront': '回放戰線',
  'replayBattlefrontTooltip': '回放戰線"{name}"',
  'getReplayBattlefrontConfirm': '確認要回放"{name}"嗎？',
  'getReplayBattlefrontFailed': '回放"{name}"失敗: {error}',

  'download': '下載',
  'downloadBattlefront': '下載戰線',
  'downloadBattlefrontTooltip': '下載戰線"{name}"',
  'getDownloadBattlefrontConfirm': '確認要下載"{name}"嗎？',
  'getDownloadBattlefrontSuccess': '成功下載"{name}"',
  'downloadMyOwnBattlefrontError': '只能下載自己創建的戰線',
  'getDownloadBattlefrontFailed': '下載"{name}"失敗: {error}',

  'continueGameShort': '繼續戰鬥',
  'replayShort': '回放',
  'highestLevel': '第 {level} 關',
  'deviceNickname': '設備',
  'createdTime': '創建時間',
  'remoteBattlefrontDetail': '戰線詳情',
  'levelList': '關次列表',
  'fastClearTimeParam': '通關時間: {time}',
  // 遠程戰線詳情字符串
  'selectLocalBattlefrontHint': '請選擇一個本地戰線查看詳情',
  'loadingRemoteDetail': '加載遠程戰線詳情中...',
  'noRemoteBattlefrontSelected': '未選擇遠程戰線',
  'failedToLoadRemoteDetail': '加載遠程戰線詳情失敗',
  'fastestRecord': '最快通關',
  'safestRecord': '最穩通關',
  'fastestRecordDesc': '最快通關(用時最少)',
  'safestRecordDesc': '最穩通關(動作數最少)',
  'creator': '開創者',
  'player': '玩家',
  // 分支地圖字符串
  'getBranchMapCount': '{count}個副本',
  'collapse': '折疊',
  'expand': '展開',
  // 退出戰線
  'quitBattlefront': '退出戰線',
  'quitBattlefrontTooltip': '退出遠程戰線',
  'quitBattlefrontTitle': '退出戰線',
  'quitBattlefrontContent': '確定要退出戰線 "{name}" 嗎？您的本地進度將被刪除。',

  // 下載頁面
  'downloadClient': '下載客戶端',
  'browser': '瀏覽器',
  'browserDesc': '直接在瀏覽器中遊玩，無需下載',
  'windowsDesc': '適用於Windows 10及以上系統',
  'macosDesc': '適用於macOS 10.15及以上系統',
  'android': '安卓系統',
  'androidDesc': '適用於Android 8.0及以上系統',
  'iosDesc': '適用於iOS 14.0及以上系統',
  'linkAddress': '連結地址',
  'downloadLink': '下載連結',
  'qrCode': '二維碼',
  'scanToDownload': '使用手機掃碼下載',
  'copy': '複製',
  'copiedToClipboard': '已複製到剪貼板',
  'openLink': '打開連結',
  'cannotOpenLink': '無法打開連結',
  // 遊戲介紹
  'gameIntroduction':
      '1. "新手入門"將從15雷開始,最高可以到99雷;\n2. "新戰線"從81雷開始,每關次會增加一定數量的地雷,上不封頂.\n3. 聯網情況下"已通關"的戰線會自動分享到雲端,供其他人學習.',
};
