/// Breton（布列塔尼语）
/// Stringioù brezhonek evit ar program DMine
const Map<String, String> stringsBr = {
  'appLabel': 'Velwour-muniloù diwezhañ',
  'appTitle': 'DMine - Velwour-muniloù diwezhañ',
  'settings': 'Arventennoù',
  'gameSettings': 'Arventennoù ar c\'hoari',
  'showTimer': 'Diskouez an timer',
  'showTimerDesc': 'Diskouez timer ar c\'hoari war urzh ar c\'hoari',
  'showActionCounter': 'Diskouez kontador ar reodoù',
  'showActionCounterDesc': 'Diskouez niver a reodoù war urzh ar c\'hoari',
  'autoAdjustBoardWidth': 'Kefluniaut automatikek ledander an daouarn',
  'autoAdjustBoardWidthDesc':
      'Kefluniaut automatikek ledander an daouarn hervez ment ar skramm',
  'resetToDefaults': 'Adkeghañ d\'arventennoù dre ziouer',
  'resetToDefaultsDesc':
      'Adkeghañ an holl arventennoù d\'ar valozienn dre ziouer',
  'aboutDMine': 'Diwar-benn DMine',
  'version': 'Diverzour',
  'close': 'Serriñ',
  'manualBoardWidth': 'Lakaat ledander an daouarn da zorn',
  'currentWidth': 'Bremañ',
  'range': 'Rann',
  'widthSliderHint':
      'Kinnig: Gallout a rit welout kemmoù ledander an daouarn en amzer real pa plakeit ar glizier',
  'gameRecords': 'Kadarnioù ar c\'hoari',
  'selectMapToViewRecords': 'Dibab ur c\'hervih evit gwelout ar kadarnioù',
  'totalRecords': 'Holl',
  'gameRecordsTitle': 'Roll kadarnioù ar c\'hoari',
  'pleaseSelectMapFirst': 'Dibab ur c\'hervih kentoc\'h',
  'noGameRecords': 'Cadarnioù c\'hoari ebet',
  'miningMethodFlag': 'Lakaat banniel',
  'miningMethodBlind': 'Velwout hep gwelout',
  'statusPlaying': '▶️ O c\'hoari...',
  'statusWin': '🎉 Yec\'hed',
  'statusLose': '💥 C\'hoant',
  'actionsCount': 'Niver a reodoù',
  'miningMethod': 'Doad velwout muniloù',
  'duration': 'Padout',
  'seconds': 'eilenn',
  'startTime': 'Emlagad deroù',
  'endTime': 'Emlagad deizhañ',
  'pauseTime': 'Emlagad ehan',
  'unlock': 'Dizhruget',
  'lock': 'Zruget',
  'delete': 'Dilemel',
  'languageSetting': 'Arventenn yezh',
  'currentLanguage': 'Bremañ',
  'systemLanguage': 'Yezh ar reizhiad',
  'chinese': 'Sinaeg',
  'english': 'Saozneg',
  'language': 'Yezh',
  // Home page
  'newbie': 'Deiziad da ziotaerien',
  'gameIntro': 'Deskrivadur ar c\'hoari',
  'newBattle': 'Kornog nevez',
  'continueChallenge': 'Kenderc\'hel ar c\'hungañ',
  'error': 'Fazi',
  'initializationFailed': 'C\'hwit derouiñ',
  // Game page
  'congratulations': 'Bravo! Bet embannet an nivel!',
  'gameOver': 'Distaolat ar c\'hoari',
  'timeUsed': 'Amzer implijet',
  'actionCount': 'Niver a reodoù',
  'mineCount': 'Niver a muniloù',
  'nextLevel': 'Nivel da heul: Nivel {level}',
  'newbieNextLevel': 'Nivel da heul: Ziotaer {level} nivel',
  'nextLevelMines': 'Niver a muniloù',
  'mineIncrease': 'Heuliañ',
  'newbieFinish': 'Distaolat an deiziad ziotaerien',
  'ok': 'Mat eo',
  'continueNextLevel': 'Kenderc\'hel d\'ar nivel da heul',
  'restart': 'Adloc\'hañ',
  'level': 'Nivel {level}',
  'newbieLevel': 'Nivel ziotaer {level}',
  'operationFailed': 'C\'hwit ar reod',
  // Game status texts
  'returnHome': 'Distagañ d\'ar penn',
  'revealMode': 'Mod diskloujañ',
  'flagMode': 'Mod banniel',
  'newMap': 'C\'hervih nevez (niver muniloù heñvel, krouiñ ur c\'hervih nevez)',
  'resetMap': 'Adkargañ ar c\'hervih (c\'hervih heñvel, adkeghañ an stad)',
  'zoomOut': 'Izelaat',
  'zoomIn': 'Uhelaat',
  'resetZoom': 'Adkeghañ ar gwel',
  'previousStep': 'Lec\'h diaraok',
  'pause': 'Ehan',
  'play': 'C\'hoari',
  'nextStep': 'Lec\'h da heul',
  'clickToStart': 'Klikit war un roadenn bennak evit loc\'hañ ar c\'hoari',
  'playing': 'O c\'hoari...',
  'gameWin': 'Bravo! Bet embannet an nivel!',
  'gameLose': 'Distaolat ar c\'hoari, bet war ur munil',
  'gamePaused': 'Ehan ar c\'hoari',
  'ready': 'Prest',
  'clickStartShort': 'Klikit evit loc\'hañ',
  'playingShort': 'O c\'hoari',
  'winShort': 'Embannet!',
  'loseShort': 'Bet war ur munil',
  'pausedShort': 'Ehan',
  // Counter strings
  'currentLevel': 'Nivel bremañ',
  'remainingMines': 'Muniloù a-zindan',
  'gameTime': 'Amzer c\'hoari (eilenn)',
  'operationCount': 'Niver a reodoù',
  'previousLevel': 'Nivel diaraok',
  'nextLevelShort': 'Nivel da heul',
  // Battlefront strings
  'completed': 'Embannet',
  'inProgress': 'O buan',
  'continueGame': 'Kenderc\'hel gant ar c\'hoari',
  'replay': 'Adc\'hoari',
  'creater': 'Kenderc\'hier',
  'created': 'Emlagad loc\'hañ ar vrezel',
  'updated': 'Nevesas',
  // Dialog strings
  'confirm': 'Kadarnaat',
  'cancel': 'Nullaat',
  'yes': 'Ya',
  'no': 'Nac\'h',
  'save': 'Saveteiñ',
  'edit': 'Trichelaat',
  'levelFormat': 'Nivel {level}',
  'newbieLevelFormat': 'Nivel ziotaer {level}',
  'totalLevel': '{level}/{totalLevel} nivel',
  'totalLevelTooltip': 'Bremañ: Nivel {level} / {totalLevel} nivel en holl',
  // Battlefront UI strings
  'noBattlefronts': 'Kornog ebet',
  'battlefrontCount': '{count} kornog',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'Ziotaer NV{level}',
  'minesCount': '{count} munil',
  'notStarted': 'Nac\'h loc\'het',
  'victory': 'Yec\'hed',
  'defeat': 'C\'hoant',
  'gameDurationParam': 'Padout: {seconds} eilenn',
  'actionsCountParam': 'Reodoù: {count} gwech',
  'actionsCountParamShort': '{count} gwech',
  'miningMethodParam': 'Doad: {method}',
  'startTimeParam': 'Emlagad deroù: {time}',
  'endTimeParam': 'Emlagad deizhañ: {time}',
  'returnButton': 'Distagañ',
  'battlefrontDetails': 'Munudoù ar c\'kornog',
  'clickToEditName': 'Klikit evit cheñch an anv',
  'clickToAddDescription': 'Klikit evit ouzhpennañ deskrivadur...',
  'noDescription': 'Deskrivadur ebet',
  // Level record strings
  'levelCount': '{count} nivel',
  'noLevelRecords': 'Dibab ur c\'kornog',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Dilemel ar c\'kornog',
  'deleteBattlefrontContent':
      'Ho peus sur da dilemel ar c\'kornog "{name}"? N\'haller ket nullaat ar reod-se.',
  'battlefrontLockedCannotDelete':
      'Ar c\'kornog zo zruget, n\'haller ket dilemel',
  'unknownNavigationLevel': 'Nivel morzhioù dianav',
  'noBattlefrontSelected': 'C\'kornog dibabet ebet',
  'noBattlefrontToContinue': 'C\'kornog ebet evit kenderc\'hel',
  'synced': 'Kevreet',
  'notSynced': 'Nac\'h kevreet',
  'newbieBattlefrontName': 'Kornog ziotaer {number}',
  'battlefrontName': 'Kornog {number}',
  'nickname': 'Anv-krenn',
  'nicknameSetting': 'Arventenn anv-krenn',
  'nicknameDesc': 'Lakaat ho anv-krenn',
  'enterNickname': 'Enankait ho anv-krenn',
  'nicknameSaved': 'Anv-krenn saveteet',
  'nicknameUpdated': 'Anv-krenn nevesaset',
  'nicknameRequired': 'Anv-krenn a zo reizhit',
  'nicknameTooLong':
      'N\'haller ket kaout muioc\'h eget 30 arouezenn er anv-krenn',
  // Level top strings
  'levelTopCount': 'Roll uhel ({count})',
  'levelTopCountShort': 'Uhel ({count})',
  'retry': 'Klask adarre',
  'noLevelTopData': 'Roadennoù ebet',
  'remoteBattlefront': 'Kornog pell',
  'participated': 'Bet partabet',
  'notParticipated': 'Nac\'h bet partabet',
  'loadMore': 'Kargañ mui',

  'joinBattle': 'Kenstagañ d\'ar vrezel',
  'joinBattleTooltip': 'Kenstagañ d\'ar vrezel "{name}"',
  'joinBattleConfirm': 'Ho peus sur da kenstagañ d\'ar vrezel "{name}"?',
  'joinBattleSuccess': 'Kenstaget ho peus d\'ar vrezel "{name}"',
  'joinBattleErrorSelf':
      'N\'haller ket kenstagañ d\'ur vrezel ho peus deuet krouet',

  'replayBattlefront': 'Adc\'hoari ar c\'kornog',
  'replayBattlefrontTooltip': 'Adc\'hoari ar c\'kornog "{name}"',
  'getReplayBattlefrontConfirm': 'Ho peus sur da adc\'hoari "{name}"?',
  'getReplayBattlefrontFailed': 'C\'hwit adc\'hoari "{name}": {error}',

  'download': 'Pellgargañ',
  'downloadBattlefront': 'Pellgargañ ar c\'kornog',
  'downloadBattlefrontTooltip': 'Pellgargañ ar c\'kornog "{name}"',
  'getDownloadBattlefrontConfirm': 'Ho peus sur da pellgargañ "{name}"?',
  'getDownloadBattlefrontSuccess': 'Pellgarget ar c\'kornog "{name}"',
  'downloadMyOwnBattlefrontError':
      'N\'haller ket pellgargañ nemet ar c\'kornogoù ho peus deuet krouet',
  'getDownloadBattlefrontFailed': 'C\'hwit pellgargañ "{name}": {error}',

  'continueGameShort': 'Kenderc\'hel gant ar vrezel',
  'replayShort': 'Adc\'hoari',
  'highestLevel': 'Nivel {level}',
  'deviceNickname': 'Troger',
  'createdTime': 'Emlagad krouiñ',
  'remoteBattlefrontDetail': 'Munudoù ar c\'kornog pell',
  'levelList': 'Roll nivelioù',
  'fastClearTimeParam': 'Amzer embann: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Dibab ur c\'kornog lec\'hel evit gwelout ar munudoù',
  'loadingRemoteDetail': 'O kargañ munudoù ar c\'kornog pell...',
  'noRemoteBattlefrontSelected': 'C\'kornog pell dibabet ebet',
  'failedToLoadRemoteDetail': 'C\'hwit kargañ munudoù ar c\'kornog pell',
  'fastestRecord': 'Embann buanoc\'h',
  'safestRecord': 'Embann suroc\'h',
  'fastestRecordDesc': 'Embann buanoc\'h (amzer biken)',
  'safestRecordDesc': 'Embann suroc\'h (reodoù biken)',
  'creator': 'Krouer',
  'player': 'C\'hoarier',
  // 分支地图字符串
  'getBranchMapCount': '{count} eil',
  'collapse': 'Lazhañ',
  'expand': 'Blozañ',
  // 退出战线
  'quitBattlefront': 'Mont eus ar c\'kornog',
  'quitBattlefrontTooltip': 'Mont eus ar c\'kornog pell',
  'quitBattlefrontTitle': 'Mont eus ar c\'kornog',
  'quitBattlefrontContent':
      'Ho peus sur da mont eus ar c\'kornog "{name}"? Ho treuzkas lec\'hel a vo dilemet.',

  // 下载页面
  'downloadClient': 'Pellgargañ ar kliant',
  'browser': 'Merdeer',
  'browserDesc': 'C\'hoari dre drezhoù er merdeer, hep pellgargañ',
  'windowsDesc': 'Evit Windows 10 ha hueloc\'h',
  'macosDesc': 'Evit macOS 10.15 ha hueloc\'h',
  'android': 'Android',
  'androidDesc': 'Evit Android 8.0 ha hueloc\'h',
  'iosDesc': 'Evit iOS 14.0 ha hueloc\'h',
  'linkAddress': 'Chomlec\'h al liamm',
  'downloadLink': 'Liamm pellgargañ',
  'qrCode': 'Kod QR',
  'scanToDownload': 'Skanit gant ho telefenn evit pellgargañ',
  'copy': 'Eilañ',
  'copiedToClipboard': 'Eilet er buhard-kelou',
  'openLink': 'Digeriñ al liamm',
  'cannotOpenLink': 'N\'haller ket digeriñ al liamm',
  // 游戏介绍
  'gameIntroduction':
      '1. "Deiziad ziotaerien" a loc\'hañ gant 15 munil, ha c\'haller kaout da 99 munil;\n2. "Kornog nevez" a loc\'hañ gant 81 munil, ha muioc\'h a muniloù a zo ouzhpennet dre nivel, hep benn uhel.\n3. Pa zo kevrinet er Internet, ar c\'kornogoù "embannet" a zo rannet automatikek er c\'heloud evit deskiñ reter.',
};
