// Catalan（加泰罗尼亚语）
/// Cadenes en català per a l'aplicació DMine
const Map<String, String> stringsCa = {
  'appLabel': 'Minesweeper Premium',
  'appTitle': 'DMine - Minesweeper Premium',
  'settings': 'Configuració',
  'gameSettings': 'Configuració del joc',
  'showTimer': 'Mostra temporitzador',
  'showTimerDesc': 'Mostra el temporitzador del joc a la interfície',
  'showActionCounter': 'Mostra comptador d\'accions',
  'showActionCounterDesc':
      'Mostra el nombre d\'accions a la interfície del joc',
  'autoAdjustBoardWidth': 'Ajusta automàticament l\'amplada del tauler',
  'autoAdjustBoardWidthDesc':
      'Ajusta automàticament l\'amplada del tauler segons la mida de la pantalla',
  'resetToDefaults': 'Restableix valors predeterminats',
  'resetToDefaultsDesc':
      'Restableix totes les configuracions als valors inicials',
  'aboutDMine': 'Quant a DMine',
  'version': 'Versió',
  'close': 'Tanca',
  'manualBoardWidth': 'Estableix manualment l\'amplada del tauler',
  'currentWidth': 'Actual',
  'range': 'Rang',
  'widthSliderHint':
      'Consell: Pots previsualitzar els canvis en temps real arrossegant el control lliscant',
  'gameRecords': 'Registres de joc',
  'selectMapToViewRecords': 'Selecciona un mapa per veure els registres',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Llista de registres de joc',
  'pleaseSelectMapFirst': 'Selecciona un mapa primer',
  'noGameRecords': 'Sense registres de joc',
  'miningMethodFlag': 'Posa bandera',
  'miningMethodBlind': 'Exploració a cegues',
  'statusPlaying': '▶️ En joc...',
  'statusWin': '🎉 Victòria',
  'statusLose': '💥 Derrota',
  'actionsCount': 'Nombre d\'accions',
  'miningMethod': 'Mètode de busqueda de mines',
  'duration': 'Durada',
  'seconds': 'segons',
  'startTime': 'Hora d\'inici',
  'endTime': 'Hora de fi',
  'pauseTime': 'Temps de pausa',
  'unlock': 'Desbloqueja',
  'lock': 'Bloca',
  'delete': 'Suprimeix',
  'languageSetting': 'Configuració d\'idioma',
  'currentLanguage': 'Actual',
  'systemLanguage': 'Idioma del sistema',
  'chinese': 'Xinès',
  'english': 'Anglès',
  'language': 'Idioma',
  // Home page
  'newbie': 'Iniciació per a nous',
  'newBattle': 'Nova batalla',
  'continueChallenge': 'Continua el desafiament',
  'error': 'Error',
  'initializationFailed': 'Error d\'inicialització',
  // Game page
  'congratulations': 'Felicitats, has superat el nivell!',
  'gameOver': 'Fi del joc',
  'timeUsed': 'Temps emprat',
  'actionCount': 'Nombre d\'accions',
  'mineCount': 'Nombre de mines',
  'nextLevel': 'Següent nivell: Nivell {level}',
  'newbieNextLevel': 'Següent nivell: Iniciació {level}',
  'nextLevelMines': 'Nombre de mines',
  'mineIncrease': 'Increment',
  'newbieFinish': 'Iniciació completada',
  'ok': 'D\'acord',
  'continueNextLevel': 'Continua al següent nivell',
  'restart': 'Reinicia',
  'level': 'Nivell {level}',
  'newbieLevel': 'Iniciació {level}',
  'operationFailed': 'Operació fallida',
  // Game status texts
  'returnHome': 'Torna a l\'inici',
  'revealMode': 'Mode revelació',
  'flagMode': 'Mode banderes',
  'newMap': 'Mapa nou (mateix nombre de mines, genera mapa nou)',
  'resetMap': 'Recarrega mapa (mateix mapa, reinicia estat)',
  'zoomOut': 'Redueix',
  'zoomIn': 'Augmenta',
  'resetZoom': 'Restableix zoom',
  'previousStep': 'Pas anterior',
  'pause': 'Pausa',
  'play': 'Reprodueix',
  'nextStep': 'Següent pas',
  'clickToStart': 'Clica qualsevol casella per començar el joc',
  'playing': 'Jugant...',
  'gameWin': 'Felicitats, has superat el nivell!',
  'gameLose': 'Fi del joc, has pitjado una mina',
  'gamePaused': 'Joc en pausa',
  'ready': 'Llest',
  'clickStartShort': 'Clica per començar',
  'playingShort': 'En joc',
  'winShort': 'Superat!',
  'loseShort': 'Mina pitjada',
  'pausedShort': 'Pausat',
  // Counter strings
  'currentLevel': 'Nivell actual',
  'remainingMines': 'Mines restants',
  'gameTime': 'Temps de joc (segons)',
  'operationCount': 'Nombre d\'operacions',
  'previousLevel': 'Nivell anterior',
  'nextLevelShort': 'Següent nivell',
  // Battlefront strings
  'completed': 'Completat',
  'inProgress': 'En curs',
  'continueGame': 'Continua el joc',
  'replay': 'Repetició',
  'creater': 'Comandant cap',
  'created': 'Hora d\'inici de batalla',
  'updated': 'Actualitzat',
  // Dialog strings
  'confirm': 'Confirma',
  'cancel': 'Cancel·la',
  'yes': 'Sí',
  'no': 'No',
  'save': 'Desa',
  'edit': 'Edita',
  'levelFormat': 'Nivell {level}',
  'newbieLevelFormat': 'Iniciació {level}',
  'totalLevel': '{level}/{totalLevel} nivells',
  'totalLevelTooltip': 'Actual: Nivell {level} / Total {totalLevel} nivells',
  // Battlefront UI strings
  'noBattlefronts': 'Sense batalles',
  'battlefrontCount': '{count} batalles',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'INI{level}',
  'minesCount': '{count} mines',
  'notStarted': 'No iniciat',
  'victory': 'Victòria',
  'defeat': 'Derrota',
  'gameDurationParam': 'Durada: {seconds} segons',
  'actionsCountParam': 'Accions: {count} vegades',
  'actionsCountParamShort': '{count} vegades',
  'miningMethodParam': 'Mètode: {method}',
  'startTimeParam': 'Hora inici: {time}',
  'endTimeParam': 'Hora fi: {time}',
  'returnButton': 'Torna',
  'battlefrontDetails': 'Detalls de la batalla',
  'clickToEditName': 'Clica per canviar el nom',
  'clickToAddDescription': 'Clica per afegir descripció...',
  'noDescription': 'Sense descripció',
  // Level record strings
  'levelCount': '{count} nivells',
  'noLevelRecords': 'Selecciona una batalla',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Suprimeix batalla',
  'deleteBattlefrontContent':
      'Segur que vols suprimir la batalla "{name}"? Aquesta acció no es pot desfer.',
  'battlefrontLockedCannotDelete': 'Batalla blocada, no es pot suprimir',
  'unknownNavigationLevel': 'Nivell desconegut',
  'noBattlefrontSelected': 'Cap batalla seleccionada',
  'noBattlefrontToContinue': 'No hi ha batalles per continuar',
  'synced': 'Sincronitzat',
  'notSynced': 'No sincronitzat',
  'newbieBattlefrontName': 'Batalla iniciació {number}',
  'battlefrontName': 'Batalla {number}',
  'nickname': 'Àlias',
  'nicknameSetting': 'Configuració d\'àlias',
  'nicknameDesc': 'Estableix el seu àlias',
  'enterNickname': 'Introdueix àlias',
  'nicknameSaved': 'Àlias desat',
  'nicknameUpdated': 'Àlias actualitzat',
  'nicknameRequired': 'Àlias obligatori',
  'nicknameTooLong': 'Àlias no pot superar els 30 caràcters',
  // Level top strings
  'levelTopCount': 'Rànquing ({count})',
  'levelTopCountShort': 'Rànquing ({count})',
  'retry': 'Torna a provar',
  'noLevelTopData': 'Sense dades',
  'remoteBattlefront': 'Batalla remota',
  'participated': 'Participat',
  'notParticipated': 'No participat',
  'loadMore': 'Carrega més',

  'joinBattle': 'Uneix-te a la batalla',
  'joinBattleTooltip': 'Uneix-te a la batalla "{name}"',
  'joinBattleConfirm': 'Segur que vols unir-te a la batalla "{name}"?',
  'joinBattleSuccess': 'T\'has unit correctament a la batalla "{name}"',
  'joinBattleErrorSelf': 'No pots unir-te a la teva pròpia batalla',

  'replayBattlefront': 'Repeteix la batalla',
  'replayBattlefrontTooltip': 'Repeteix la batalla "{name}"',
  'getReplayBattlefrontConfirm': 'Segur que vols repetir "{name}"?',
  'getReplayBattlefrontFailed': 'No s\'ha pogut repetir "{name}": {error}',

  'download': 'Descarrega',
  'downloadBattlefront': 'Descarrega batalla',
  'downloadBattlefrontTooltip': 'Descarrega la batalla "{name}"',
  'getDownloadBattlefrontConfirm': 'Segur que vols descarregar "{name}"?',
  'getDownloadBattlefrontSuccess': 'Batalla "{name}" descarregada correctament',
  'downloadMyOwnBattlefrontError':
      'Només pots descarregar les teves pròpies batalles',
  'getDownloadBattlefrontFailed':
      'No s\'ha pogut descarregar "{name}": {error}',

  'continueGameShort': 'Continua la batalla',
  'replayShort': 'Repeteix',
  'highestLevel': 'Nivell {level}',
  'deviceNickname': 'Dispositiu',
  'createdTime': 'Hora de creació',
  'remoteBattlefrontDetail': 'Detalls de batalla remota',
  'levelList': 'Llista de nivells',
  'fastClearTimeParam': 'Temps superació: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Selecciona una batalla local per veure els detalls',
  'loadingRemoteDetail': 'Carregant detalls de batalla remota...',
  'noRemoteBattlefrontSelected': 'Cap batalla remota seleccionada',
  'failedToLoadRemoteDetail': 'No s\'han pogut carregar els detalls remots',
  'fastestRecord': 'Superació més ràpida',
  'safestRecord': 'Superació més segura',
  'fastestRecordDesc': 'Superació més ràpida (menys temps)',
  'safestRecordDesc': 'Superació més segura (menys accions)',
  'creator': 'Creador',
  'player': 'Jugador',
  // 分支地图字符串
  'getBranchMapCount': '{count} còpies',
  'collapse': 'Redueix',
  'expand': 'Expandeix',
  // 退出战线
  'quitBattlefront': 'Abandona la batalla',
  'quitBattlefrontTooltip': 'Abandona la batalla remota',
  'quitBattlefrontTitle': 'Abandona batalla',
  'quitBattlefrontContent':
      'Segur que vols abandonar la batalla "{name}"? El seu progrés local s\'eliminarà.',

  // 下载页面
  'downloadClient': 'Descarrega client',
  'browser': 'Navegador',
  'browserDesc': 'Juga directament al navegador, sense descarregar',
  'windowsDesc': 'Per a Windows 10 i superior',
  'macosDesc': 'Per a macOS 10.15 i superior',
  'android': 'Android',
  'androidDesc': 'Per a Android 8.0 i superior',
  'iosDesc': 'Per a iOS 14.0 i superior',
  'linkAddress': 'Adreça de l\'enllaç',
  'downloadLink': 'Enllaç de descàrrega',
  'qrCode': 'Codi QR',
  'scanToDownload': 'Escaneja amb el mòbil per descarregar',
  'copy': 'Copia',
  'copiedToClipboard': 'Copiat al porta-retalls',
  'openLink': 'Obre enllaç',
  'cannotOpenLink': 'No es pot obrir l\'enllaç',
  // 游戏介绍
  'gameIntroduction':
      '1. "Iniciació" comença amb 15 mines, pot arribar fins a 99 mines;\n2. "Nova batalla" comença amb 81 mines, cada nivell afegeix mines, sense límit superior.\n3. Amb connexió a internet, les batalles "superades" es compartiran automàticament al núvol per a que altres puguin aprendre.',
};
