// Swedish（瑞典语）
/// Swedish language strings for the DMine application
const Map<String, String> stringsSv = {
  'appLabel': 'Topp Minesveipare',
  'appTitle': 'DMine - Topp Minesveipare',
  'settings': 'Inställningar',
  'gameSettings': 'Spelinställningar',
  'showTimer': 'Visa tidtagare',
  'showTimerDesc': 'Visar speltidstagaren på spelskärmen',
  'showActionCounter': 'Visa åtgärdsräknare',
  'showActionCounterDesc': 'Visar antal åtgärder på spelskärmen',
  'autoAdjustBoardWidth': 'Justera brickans bredd automatiskt',
  'autoAdjustBoardWidthDesc':
      'Justerar automatiskt brickans bredd efter skärmens storlek',
  'resetToDefaults': 'Återställ standardinställningar',
  'resetToDefaultsDesc': 'Återställ alla inställningar till standardvärden',
  'aboutDMine': 'Om DMine',
  'version': 'Version',
  'close': 'Stäng',
  'manualBoardWidth': 'Ställ in brickans bredd manuellt',
  'currentWidth': 'Nuvarande',
  'range': 'Intervall',
  'widthSliderHint':
      'Tips: Dra skjutreglaget för att se bredden ändras i realtid',
  'gameRecords': 'Spelresultat',
  'selectMapToViewRecords': 'Välj en karta för att visa resultat',
  'totalRecords': 'Totalt',
  'gameRecordsTitle': 'Lista över spelresultat',
  'pleaseSelectMapFirst': 'Välj en karta först',
  'noGameRecords': 'Inga spelresultat',
  'miningMethodFlag': 'Markera med flagga',
  'miningMethodBlind': 'Blind svepning',
  'statusPlaying': '▶️ Pågår...',
  'statusWin': '🎉 Seger',
  'statusLose': '💥 Förlust',
  'actionsCount': 'Antal åtgärder',
  'miningMethod': 'Spelsätt',
  'duration': 'Speltid',
  'seconds': 'sekunder',
  'startTime': 'Starttid',
  'endTime': 'Sluttid',
  'pauseTime': 'Paustid',
  'unlock': 'Lås upp',
  'lock': 'Lås',
  'delete': 'Ta bort',
  'languageSetting': 'Språkinställning',
  'currentLanguage': 'Nuvarande',
  'systemLanguage': 'Systemspråk',
  'chinese': 'Kinesiska',
  'english': 'Engelska',
  'language': 'Språk',
  // Home page
  'newbie': 'Nybörjare',
  'gameIntro': 'Spelintroduktion',
  'newBattle': 'Ny Framfront',
  'continueChallenge': 'Fortsätt utmaningen',
  'error': 'Fel',
  'initializationFailed': 'Initiering misslyckades',
  // Game page
  'congratulations': 'Grattis, du klarade nivån!',
  'gameOver': 'Spelet är över',
  'timeUsed': 'Använd tid',
  'actionCount': 'Åtgärder',
  'mineCount': 'Minor',
  'nextLevel': 'Nästa nivå: Nivå {level}',
  'newbieNextLevel': 'Nästa nivå: Nybörjare {level}',
  'nextLevelMines': 'Minor',
  'mineIncrease': 'Ökning',
  'newbieFinish': 'Nybörjarläge klart',
  'ok': 'OK',
  'continueNextLevel': 'Fortsätt till nästa nivå',
  'restart': 'Starta om',
  'level': 'Nivå {level}',
  'newbieLevel': 'Nybörjare {level}',
  'operationFailed': 'Åtgärd misslyckades',
  // Game status texts
  'returnHome': 'Tillbaka till startsidan',
  'revealMode': 'Upptäckningsläge',
  'flagMode': 'Flaggläge',
  'newMap': 'Ny karta (samma antal minor, nytt utseende)',
  'resetMap': 'Återställ karta (samma utseende, återställ tillstånd)',
  'zoomOut': 'Zooma ut',
  'zoomIn': 'Zooma in',
  'resetZoom': 'Återställ zoom',
  'previousStep': 'Föregående steg',
  'pause': 'Pausa',
  'play': 'Spela',
  'nextStep': 'Nästa steg',
  'clickToStart': 'Klicka på valfri ruta för att starta spelet',
  'playing': 'Spelet pågår...',
  'gameWin': 'Grattis, du klarade nivån!',
  'gameLose': 'Spelet är över, du träffade en mina',
  'gamePaused': 'Spelet pausat',
  'ready': 'Redo att starta',
  'clickStartShort': 'Klicka för att starta',
  'playingShort': 'Pågår',
  'winShort': 'Klarat!',
  'loseShort': 'Förlorat',
  'pausedShort': 'Pausat',
  // Counter strings
  'currentLevel': 'Aktuell nivå',
  'remainingMines': 'Återstående minor',
  'gameTime': 'Speltid (sekunder)',
  'operationCount': 'Antal operationer',
  'previousLevel': 'Föregående nivå',
  'nextLevelShort': 'Nästa nivå',
  // Battlefront strings
  'completed': 'Avslutad',
  'inProgress': 'Pågår',
  'continueGame': 'Fortsätt spelet',
  'replay': 'Spela om',
  'creater': 'Kommandant',
  'created': 'Starttid',
  'updated': 'Uppdaterad',
  // Dialog strings
  'confirm': 'Bekräfta',
  'cancel': 'Avbryt',
  'yes': 'Ja',
  'no': 'Nej',
  'save': 'Spara',
  'edit': 'Redigera',
  'levelFormat': 'Nivå {level}',
  'newbieLevelFormat': 'Nybörjare {level}',
  'totalLevel': '{level}/{totalLevel} nivåer',
  'totalLevelTooltip': 'Aktuell: Nivå {level} / Totalt {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Inga framfrontar',
  'battlefrontCount': '{count} framfrontar',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'Nybörjare NV{level}',
  'minesCount': '{count} minor',
  'notStarted': 'Ej startad',
  'victory': 'Seger',
  'defeat': 'Nederlag',
  'gameDurationParam': 'Speltid: {seconds}s',
  'actionsCountParam': 'Åtgärder: {count} gånger',
  'actionsCountParamShort': '{count} gånger',
  'miningMethodParam': 'Sätt: {method}',
  'startTimeParam': 'Start: {time}',
  'endTimeParam': 'Slut: {time}',
  'returnButton': 'Tillbaka',
  'battlefrontDetails': 'Framfrontdetaljer',
  'clickToEditName': 'Klicka för att ändra namn',
  'clickToAddDescription': 'Klicka för att lägga till beskrivning...',
  'noDescription': 'Ingen beskrivning',
  // Level record strings
  'levelCount': '{count} nivåer',
  'noLevelRecords': 'Välj en framfront',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Ta bort framfront',
  'deleteBattlefrontContent':
      'Är du säker på att du vill ta bort framfronten \'{name}\'? Detta går inte att ångra.',
  'battlefrontLockedCannotDelete': 'Framfronten är låst, kan inte tas bort',
  'unknownNavigationLevel': 'Okänd nivå',
  'noBattlefrontSelected': 'Ingen framfront vald',
  'noBattlefrontToContinue': 'Ingen framfront att fortsätta med',
  'synced': 'Synkroniserad',
  'notSynced': 'Ej synkroniserad',
  'newbieBattlefrontName': 'Nybörjarframfront {number}',
  'battlefrontName': 'Framfront {number}',
  'nickname': 'Smeknamn',
  'nicknameSetting': 'Smeknamnsinställning',
  'nicknameDesc': 'Ställ in ditt smeknamn',
  'enterNickname': 'Ange smeknamn',
  'nicknameSaved': 'Smeknamn sparat',
  'nicknameUpdated': 'Smeknamn uppdaterat',
  'nicknameRequired': 'Smeknamn krävs',
  'nicknameTooLong': 'Smeknamnet får inte vara längre än 30 tecken',
  // Level top strings
  'levelTopCount': 'Topplista ({count})',
  'levelTopCountShort': 'Topp ({count})',
  'retry': 'Försök igen',
  'noLevelTopData': 'Ingen data',
  'remoteBattlefront': 'Fjärrframfront',
  'participated': 'Deltog',
  'notParticipated': 'Deltog inte',
  'loadMore': 'Ladda mer',
  'joinBattle': 'Gå med i striden',
  'joinBattleTooltip': 'Gå med i striden \'{name}\'',
  'joinBattleConfirm':
      'Är du säker på att du vill gå med i striden \'{name}\'?',
  'joinBattleSuccess': 'Gick med i striden \'{name}\' framgångsrikt',
  'joinBattleErrorSelf': 'Du kan inte gå med i din egen framfront',
  'replayBattlefront': 'Spela om framfront',
  'replayBattlefrontTooltip': 'Spela om framfronten \'{name}\'',
  'getReplayBattlefrontConfirm':
      'Är du säker på att du vill spela om \'{name}\'?',
  'getReplayBattlefrontFailed': 'Misslyckades att spela om \'{name}\': {error}',
  'download': 'Ladda ner',
  'downloadBattlefront': 'Ladda ner framfront',
  'downloadBattlefrontTooltip': 'Ladda ner framfronten \'{name}\'',
  'getDownloadBattlefrontConfirm':
      'Är du säker på att du vill ladda ner \'{name}\'?',
  'getDownloadBattlefrontSuccess': '\'{name}\' laddades ner framgångsrikt',
  'downloadMyOwnBattlefrontError':
      'Du kan bara ladda ner dina egna framfrontar',
  'getDownloadBattlefrontFailed':
      'Misslyckades att ladda ner \'{name}\': {error}',
  'continueGameShort': 'Fortsätt striden',
  'replayShort': 'Spela om',
  'highestLevel': 'Nivå {level}',
  'deviceNickname': 'Enhet',
  'createdTime': 'Skapad',
  'remoteBattlefrontDetail': 'Fjärrframfrontdetaljer',
  'levelList': 'Nivålista',
  'fastClearTimeParam': 'Sluttid: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint': 'Välj en lokal framfront för att visa detaljer',
  'loadingRemoteDetail': 'Laddar fjärrframfrontdetaljer...',
  'noRemoteBattlefrontSelected': 'Ingen fjärrframfront vald',
  'failedToLoadRemoteDetail': 'Misslyckades att ladda detaljer',
  'fastestRecord': 'Snabbaste klarning',
  'safestRecord': 'Säkraste klarning',
  'fastestRecordDesc': 'Snabbast (minst tid)',
  'safestRecordDesc': 'Säkrast (minst åtgärder)',
  'creator': 'Skapare',
  'player': 'Spelare',
  // Branch maps
  'getBranchMapCount': '{count} kopior',
  'collapse': 'Dölj',
  'expand': 'Visa',
  // Quit battlefront
  'quitBattlefront': 'Lämna framfront',
  'quitBattlefrontTooltip': 'Lämna fjärrframfronten',
  'quitBattlefrontTitle': 'Lämna framfront',
  'quitBattlefrontContent':
      'Är du säker på att du vill lämna framfronten \'{name}\'? Din lokala förlopp kommer att raderas.',
  // Download page
  'downloadClient': 'Ladda ner klient',
  'browser': 'Webbläsare',
  'browserDesc': 'Spela direkt i webbläsaren, inget behov av nerladdning',
  'windowsDesc': 'För Windows 10 och senare',
  'macosDesc': 'För macOS 10.15 och senare',
  'android': 'Android',
  'androidDesc': 'För Android 8.0 och senare',
  'iosDesc': 'För iOS 14.0 och senare',
  'linkAddress': 'Länk',
  'downloadLink': 'Nedladdningslänk',
  'qrCode': 'QR-kod',
  'scanToDownload': 'Skanna med mobilen för att ladda ner',
  'copy': 'Kopiera',
  'copiedToClipboard': 'Kopierat till urklipp',
  'openLink': 'Öppna länk',
  'cannotOpenLink': 'Kan inte öppna länken',
  // Game introduction
  'gameIntroduction':
      '1. "Nybörjare" börjar med 15 minor, upp till 99;\n2. "Ny Framfront" börjar med 81 minor, ökar med varje nivå, utan övre gräns.\n3. Online delas klarade framfrontar automatiskt i molnet för andra att lära sig av.',
};
