// Slovenian（斯洛文尼亚语）
/// Slovenian language strings for the DMine application
const Map<String, String> stringsSl = {
  'appLabel': 'Top Iskanje Min',
  'appTitle': 'DMine - Top Iskanje Min',
  'settings': 'Nastavitve',
  'gameSettings': 'Nastavitve Igre',
  'showTimer': 'Prikaži časomer',
  'showTimerDesc': 'Prikaži časomer igre na igralnem zaslonu',
  'showActionCounter': 'Prikaži številec akcij',
  'showActionCounterDesc': 'Prikaži število akcij na igralnem zaslonu',
  'autoAdjustBoardWidth': 'Samodejno prilagodi širino plošče',
  'autoAdjustBoardWidthDesc':
      'Samodejno prilagodi širino plošče glede na velikost zaslona',
  'resetToDefaults': 'Ponastavi na privzete nastavitve',
  'resetToDefaultsDesc': 'Ponastavi vse nastavitve na privzete vrednosti',
  'aboutDMine': 'O DMine',
  'version': 'Različica',
  'close': 'Zapri',
  'manualBoardWidth': 'Ročno nastavi širino plošče',
  'currentWidth': 'Trenutna',
  'range': 'Območje',
  'widthSliderHint':
      'Namig: pri vlečenju drsnika vidite spremembe širine plošče takoj',
  'gameRecords': 'Igralne Zapise',
  'selectMapToViewRecords': 'Izberite karto za ogled zapisov',
  'totalRecords': 'Skupaj',
  'gameRecordsTitle': 'Seznam Igralnih Zapisov',
  'pleaseSelectMapFirst': 'Najprej izberite karto',
  'noGameRecords': 'Ni igralnih zapisov',
  'miningMethodFlag': 'Označi z zastavico',
  'miningMethodBlind': 'Slepo Odkrivanje',
  'statusPlaying': '▶️ V teku...',
  'statusWin': '🎉 Zmaga',
  'statusLose': '💥 Poraz',
  'actionsCount': 'Št. Akcij',
  'miningMethod': 'Način Igre',
  'duration': 'Trajanje',
  'seconds': 'sekund',
  'startTime': 'Čas Začetka',
  'endTime': 'Čas Konca',
  'pauseTime': 'Čas Pauze',
  'unlock': 'Odkleni',
  'lock': 'Zakleni',
  'delete': 'Izbriši',
  'languageSetting': 'Nastavitev jezika',
  'currentLanguage': 'Trenutni',
  'systemLanguage': 'Sistemski Jezik',
  'chinese': 'Kitajski',
  'english': 'Angleški',
  'language': 'Jezik',
  // Home page
  'newbie': 'Začetnik',
  'newBattle': 'Nova Fronta',
  'continueChallenge': 'Nadaljuj izziv',
  'error': 'Napaka',
  'initializationFailed': 'Inicializacija ni uspela',
  // Game page
  'congratulations': 'Čestitamo, uspešno ste opravili stopnjo!',
  'gameOver': 'Konec Igre',
  'timeUsed': 'Porabljen čas',
  'actionCount': 'Akcije',
  'mineCount': 'Mine',
  'nextLevel': 'Naslednja stopnja: Stopnja {level}',
  'newbieNextLevel': 'Naslednja stopnja: Začetnik {level}',
  'nextLevelMines': 'Mine',
  'mineIncrease': 'Povečanje',
  'newbieFinish': 'Režim Začetnika Zaključen',
  'ok': 'V redu',
  'continueNextLevel': 'Nadaljuj na naslednjo stopnjo',
  'restart': 'Ponovno Začni',
  'level': 'Stopnja {level}',
  'newbieLevel': 'Začetnik {level}',
  'operationFailed': 'Operacija ni uspela',
  // Game status texts
  'returnHome': 'Nazaj Domov',
  'revealMode': 'Način Odkrivanja',
  'flagMode': 'Način Zastavic',
  'newMap': 'Nova Karta (Enako Št. Min, Nov Razpored)',
  'resetMap': 'Ponastavi Karto (Enak Razpored, Ponastavi Stanje)',
  'zoomOut': 'Pomanjšaj',
  'zoomIn': 'Povečaj',
  'resetZoom': 'Ponastavi Povečavo',
  'previousStep': 'Predhodnji Korak',
  'pause': 'Pavza',
  'play': 'Igraj',
  'nextStep': 'Naslednji Korak',
  'clickToStart': 'Klikni poljubno polje za začetek igre',
  'playing': 'V igri...',
  'gameWin': 'Čestitamo, uspešno ste opravili stopnjo!',
  'gameLose': 'Konec igre, stopili ste na mino',
  'gamePaused': 'Igra zaustavljena',
  'ready': 'Pripravljeni za začetek',
  'clickStartShort': 'Klikni za začetek',
  'playingShort': 'V igri',
  'winShort': 'Opravljeno!',
  'loseShort': 'Poraz',
  'pausedShort': 'Pavza',
  // Counter strings
  'currentLevel': 'Trenutna Stopnja',
  'remainingMines': 'Preostale Mine',
  'gameTime': 'Čas Igre (sekund)',
  'operationCount': 'Št. Operacij',
  'previousLevel': 'Predhodnja Stopnja',
  'nextLevelShort': 'Naslednja Stopnja',
  // Battlefront strings
  'completed': 'Zaključeno',
  'inProgress': 'V teku',
  'continueGame': 'Nadaljuj Igro',
  'replay': 'Ponovi',
  'creater': 'Poveljnik',
  'created': 'Ustvarjeno',
  'updated': 'Posodobljeno',
  // Dialog strings
  'confirm': 'Potrdi',
  'cancel': 'Prekliči',
  'yes': 'Da',
  'no': 'Ne',
  'save': 'Shrani',
  'edit': 'Uredi',
  'levelFormat': 'Stopnja {level}',
  'newbieLevelFormat': 'Začetnik {level}',
  'totalLevel': '{level}/{totalLevel} stopenj',
  'totalLevelTooltip': 'Trenutno: Stopnja {level} / Skupaj {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Ni Front',
  'battlefrontCount': '{count} front',
  'levelPrefix': 'ST{level}',
  'newbieLevelPrefix': 'Začetnik ST{level}',
  'minesCount': '{count} min',
  'notStarted': 'Nič Začeto',
  'victory': 'Zmaga',
  'defeat': 'Poraz',
  'gameDurationParam': 'Trajanje: {seconds}s',
  'actionsCountParam': 'Akcije: {count} krat',
  'actionsCountParamShort': '{count} krat',
  'miningMethodParam': 'Način: {method}',
  'startTimeParam': 'Začetek: {time}',
  'endTimeParam': 'Konec: {time}',
  'returnButton': 'Nazaj',
  'battlefrontDetails': 'Podrobnosti Fronta',
  'clickToEditName': 'Klikni za urejanje imena',
  'clickToAddDescription': 'Klikni za dodajanje opisa...',
  'noDescription': 'Ni Opisa',
  // Level record strings
  'levelCount': '{count} stopenj',
  'noLevelRecords': 'Izberite fronto',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Izbriši Fronto',
  'deleteBattlefrontContent':
      'Ali ste prepričani, da želite izbrisati fronto \'{name}\'? Ta dejanja ni mogoče povrniti.',
  'battlefrontLockedCannotDelete': 'Fronta zaklenjena, ni mogoče izbrisati',
  'unknownNavigationLevel': 'Neznana Stopnja',
  'noBattlefrontSelected': 'Ni izbrane Front',
  'noBattlefrontToContinue': 'Ni najdene Front za Nadaljevanje',
  'synced': 'Sinhronizirano',
  'notSynced': 'Ni Sinhronizirano',
  'newbieBattlefrontName': 'Fronta Začetnika {number}',
  'battlefrontName': 'Fronta {number}',
  'nickname': 'Vzdevek',
  'nicknameSetting': 'Nastavitev Vzdevka',
  'nicknameDesc': 'Nastavite svoj vzdevek',
  'enterNickname': 'Vnesite vzdevek',
  'nicknameSaved': 'Vzdevek Shranjen',
  'nicknameUpdated': 'Vzdevek Posodobljen',
  'nicknameRequired': 'Vzdevek je obvezen',
  'nicknameTooLong': 'Vzdevek ne sme biti daljši od 30 znakov',
  // Level top strings
  'levelTopCount': ' lestvica ({count})',
  'levelTopCountShort': 'Lestvica ({count})',
  'retry': 'Poskusi Ponovno',
  'noLevelTopData': 'Ni Podatkov',
  'remoteBattlefront': 'Oddaljena Fronta',
  'participated': 'Sodeloval',
  'notParticipated': 'Ni Sodeloval',
  'loadMore': 'Naloži Več',
  'joinBattle': 'Pridruži se Bitki',
  'joinBattleTooltip': 'Pridruži se bitki \'{name}\'',
  'joinBattleConfirm':
      'Ali ste prepričani, da se želite pridružiti bitki \'{name}\'?',
  'joinBattleSuccess': 'Uspešno ste se pridružili bitki \'{name}\'',
  'joinBattleErrorSelf': 'Ni mogoče pridružiti lastni fronti',
  'replayBattlefront': 'Ponovi Fronto',
  'replayBattlefrontTooltip': 'Ponovi fronto \'{name}\'',
  'getReplayBattlefrontConfirm':
      'Ali ste prepričani, da želite ponoviti \'{name}\'?',
  'getReplayBattlefrontFailed': 'Ponovitev \'{name}\' ni uspela: {error}',
  'download': 'Prenesi',
  'downloadBattlefront': 'Prenesi Fronto',
  'downloadBattlefrontTooltip': 'Prenesi fronto \'{name}\'',
  'getDownloadBattlefrontConfirm':
      'Ali ste prepričani, da želite prenesti \'{name}\'?',
  'getDownloadBattlefrontSuccess': '\'{name}\' Uspešno Prenešen',
  'downloadMyOwnBattlefrontError': 'Prenešati lahko samo lastne fronte',
  'getDownloadBattlefrontFailed': 'Prenos \'{name}\' ni uspel: {error}',
  'continueGameShort': 'Nadaljuj Bitko',
  'replayShort': 'Ponovi',
  'highestLevel': 'Stopnja {level}',
  'deviceNickname': 'Naprava',
  'createdTime': 'Čas Ustvaritve',
  'remoteBattlefrontDetail': 'Podrobnosti Oddaljene Front',
  'levelList': 'Seznam Stopenj',
  'fastClearTimeParam': 'Čas Zaključitve: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint': 'Izberite lokalno fronto za ogled podrobnosti',
  'loadingRemoteDetail': 'Nalaganje podrobnosti oddaljene front...',
  'noRemoteBattlefrontSelected': 'Ni izbrane Oddaljene Front',
  'failedToLoadRemoteDetail': 'Nalaganje podrobnosti ni uspelo',
  'fastestRecord': 'Najhitrejše Zaključitev',
  'safestRecord': 'Najvarnejše Zaključitev',
  'fastestRecordDesc': 'Najhitrejše (najmanj časa)',
  'safestRecordDesc': 'Najvarnejše (najmanj akcij)',
  'creator': 'Ustvarjalec',
  'player': 'Igralec',
  // Branch maps
  'getBranchMapCount': '{count} kopij',
  'collapse': 'Strni',
  'expand': 'Razširi',
  // Quit battlefront
  'quitBattlefront': 'Zapusti Fronto',
  'quitBattlefrontTooltip': 'Zapusti oddaljeno fronto',
  'quitBattlefrontTitle': 'Zapusti Fronto',
  'quitBattlefrontContent':
      'Ali ste prepričani, da želite zapustiti fronto \'{name}\'? Vaš lokalni napredek bo izbrisan.',
  // Download page
  'downloadClient': 'Prenesi Odjemalec',
  'browser': 'Brskalnik',
  'browserDesc': 'Igraj neposredno v brskalniku, brez prenosa',
  'windowsDesc': 'Za Windows 10 in novejše',
  'macosDesc': 'Za macOS 10.15 in novejše',
  'android': 'Android',
  'androidDesc': 'Za Android 8.0 in novejše',
  'iosDesc': 'Za iOS 14.0 in novejše',
  'linkAddress': 'Naslov Povezave',
  'downloadLink': 'Povezava za Prenos',
  'qrCode': 'QR Koda',
  'scanToDownload': 'Oskenirajte s telefonom za prenos',
  'copy': 'Kopiraj',
  'copiedToClipboard': 'Kopirano v odložišče',
  'openLink': 'Odpri Povezavo',
  'cannotOpenLink': 'Ni mogoče odpreti povezave',
  // Game introduction
  'gameIntroduction':
      '1. „Začetnik“ se začne z 15 minami, največ do 99 min;\n2. „Nova Fronta“ se začne z 81 minami, število se povečuje vsako stopnjo, brez zgornje meje.\n3. V povezavi so zaključene fronte samodejno deljene v oblaku za druge igralce.',
};
