/// English language strings for the DMine application
const Map<String, String> stringsEn = {
  'appTitle': 'DMine Minesweeper Challenge',
  'settings': 'Settings',
  'gameSettings': 'Game Settings',
  'showTimer': 'Show Timer',
  'showTimerDesc': 'Display game timer on game interface',
  'showActionCounter': 'Show Action Counter',
  'showActionCounterDesc': 'Display action count statistics on game interface',
  'autoAdjustBoardWidth': 'Auto Adjust Board Width',
  'autoAdjustBoardWidthDesc':
      'Automatically adjust board width based on screen size',
  'resetToDefaults': 'Reset to Default Settings',
  'resetToDefaultsDesc': 'Restore all settings to default values',
  'aboutDMine': 'About DMine',
  'version': 'Version',
  'close': 'Close',
  'manualBoardWidth': 'Manual Board Width',
  'currentWidth': 'Current',
  'range': 'Range',
  'widthSliderHint':
      'Tip: You can preview board width changes while dragging the slider',
  'gameRecords': 'Game Records',
  'selectMapToViewRecords': 'Please select a map to view records',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Game Records List',
  'pleaseSelectMapFirst': 'Please select a map first',
  'noGameRecords': 'No game records',
  'miningMethodFlag': 'Flag',
  'miningMethodBlind': 'Blind',
  'statusPlaying': '▶️ Playing...',
  'statusWin': '🎉 Victory',
  'statusLose': '💥 Failure',
  'actionsCount': 'Actions',
  'miningMethod': 'Mining Method',
  'duration': 'Duration',
  'seconds': 'seconds',
  'startTime': 'Start Time',
  'endTime': 'End Time',
  'pauseTime': 'Pause Time',
  'unlock': 'Unlock',
  'lock': 'Lock',
  'delete': 'Delete',
  'languageSetting': 'Language Setting',
  'currentLanguage': 'Current',
  'systemLanguage': 'System Language',
  'chinese': 'Chinese',
  'english': 'English',
  'language': 'Language',
  // Home page
  'newBattle': 'New Battle',
  'continueChallenge': 'Continue Challenge',
  'error': 'Error',
  'initializationFailed': 'Initialization failed',
  // Game page
  'congratulations': 'Congratulations!',
  'gameOver': 'Game Over',
  'timeUsed': 'Time',
  'actionCount': 'Actions',
  'mineCount': 'Mines',
  'nextLevel': 'Next Level: Level {level}',
  'nextLevelMines': 'Mines',
  'mineIncrease': 'Increase',
  'ok': 'OK',
  'continueNextLevel': 'Continue to Next Level',
  'restart': 'Restart',
  'level': 'Level {level}',
  'operationFailed': 'Operation failed',
  // Game status texts
  'returnHome': 'Return Home',
  'revealMode': 'Reveal Mode',
  'flagMode': 'Flag Mode',
  'newMap': 'New Map (same mines, new layout)',
  'previousStep': 'Previous Step',
  'pause': 'Pause',
  'play': 'Play',
  'nextStep': 'Next Step',
  'clickToStart': 'Click any cell to start game',
  'playing': 'Playing...',
  'gameWin': 'Congratulations!',
  'gameLose': 'Game Over, stepped on a mine',
  'gamePaused': 'Game Paused',
  'ready': 'Ready to Start',
  'clickStartShort': 'Click Start',
  'playingShort': 'Playing',
  'winShort': 'Win!',
  'loseShort': 'Mine Failure',
  'pausedShort': 'Paused',
};
