/// Danish（丹麦语）
/// Danske strenge til DMine-applikationen
const Map<String, String> stringsDa = {
  'appLabel': 'Top Minesweeper',
  'appTitle': 'DMine - Top Minesweeper',
  'settings': 'Indstillinger',
  'gameSettings': 'Spilindstillinger',
  'showTimer': 'Vis tidsur',
  'showTimerDesc': 'Vis spiltidsur på spilskærmen',
  'showActionCounter': 'Vis handlingsteller',
  'showActionCounterDesc': 'Vis antal handlinger på spilskærmen',
  'autoAdjustBoardWidth': 'Justér automatisk bordbredde',
  'autoAdjustBoardWidthDesc':
      'Justér automatisk bordbredde ifølge skærmstørrelse',
  'resetToDefaults': 'Nulstil til standardindstillinger',
  'resetToDefaultsDesc': 'Gendan alle indstillinger til standardværdier',
  'aboutDMine': 'Om DMine',
  'version': 'Version',
  'close': 'Luk',
  'manualBoardWidth': 'Manuel indstilling af bordbredde',
  'currentWidth': 'Nuværende',
  'range': 'Interval',
  'widthSliderHint':
      'Tip: Du kan forhåndsvise ændringer i bordbredde i realtid, mens du trækked i skyderen',
  'gameRecords': 'Spilresultater',
  'selectMapToViewRecords': 'Vælg et kort for at se resultater',
  'totalRecords': 'I alt',
  'gameRecordsTitle': 'Liste over spilresultater',
  'pleaseSelectMapFirst': 'Vælg først et kort',
  'noGameRecords': 'Ingen spilresultater endnu',
  'miningMethodFlag': 'Sæt flag',
  'miningMethodBlind': 'Blind søgning',
  'statusPlaying': '▶️ I gang...',
  'statusWin': '🎉 Sejr',
  'statusLose': '💥 Tabt',
  'actionsCount': 'Antal handlinger',
  'miningMethod': 'Minesøgningsmetode',
  'duration': 'Varighed',
  'seconds': 'sekunder',
  'startTime': 'Starttidspunkt',
  'endTime': 'Sluttidspunkt',
  'pauseTime': 'Pause tid',
  'unlock': 'Lås op',
  'lock': 'Lås',
  'delete': 'Slet',
  'languageSetting': 'Sprogindstilling',
  'currentLanguage': 'Nuværende',
  'systemLanguage': 'Systemsprog',
  'chinese': 'Kinesisk',
  'english': 'Engelsk',
  'language': 'Sprog',
  // Home page
  'newbie': 'Nybegynder',
  'newBattle': 'Ny front',
  'continueChallenge': 'Fortsæt udfordringen',
  'error': 'Fejl',
  'initializationFailed': 'Initialisering mislykkedes',
  // Game page
  'congratulations': 'Tillykke, du klarede niveauet!',
  'gameOver': 'Spillet er slut',
  'timeUsed': 'Brugt tid',
  'actionCount': 'Antal handlinger',
  'mineCount': 'Antal miner',
  'nextLevel': 'Næste niveau: Niveau {level}',
  'newbieNextLevel': 'Næste niveau: Nybegynder {level}',
  'nextLevelMines': 'Antal miner',
  'mineIncrease': 'Forøgelse',
  'newbieFinish': 'Nybegynderkursus afsluttet',
  'ok': 'OK',
  'continueNextLevel': 'Fortsæt til næste niveau',
  'restart': 'Genstart',
  'level': 'Niveau {level}',
  'newbieLevel': 'Nybegynder niveau {level}',
  'operationFailed': 'Handling mislykkedes',
  // Game status texts
  'returnHome': 'Tilbage til startsiden',
  'revealMode': 'Afsløringstilstand',
  'flagMode': 'Flagtilstand',
  'newMap': 'Nyt kort (samme antal miner, generer nyt kort)',
  'resetMap': 'Genindlæs kort (samme kort, nulstil tilstand)',
  'zoomOut': 'Zoom ud',
  'zoomIn': 'Zoom ind',
  'resetZoom': 'Nulstil zoom',
  'previousStep': 'Forrige trin',
  'pause': 'Pause',
  'play': 'Afspil',
  'nextStep': 'Næste trin',
  'clickToStart': 'Klik på et felt for at starte spillet',
  'playing': 'Spiller...',
  'gameWin': 'Tillykke, du klarede niveauet!',
  'gameLose': 'Spillet er slut, du ramte en mine',
  'gamePaused': 'Spillet er sat på pause',
  'ready': 'Klar',
  'clickStartShort': 'Klik for at starte',
  'playingShort': 'I gang',
  'winShort': 'Klaret!',
  'loseShort': 'Ramte en mine',
  'pausedShort': 'Pauset',
  // Counter strings
  'currentLevel': 'Nuværende niveau',
  'remainingMines': 'Resterende miner',
  'gameTime': 'Spiltid (sekunder)',
  'operationCount': 'Antal handlinger',
  'previousLevel': 'Forrige niveau',
  'nextLevelShort': 'Næste niveau',
  // Battlefront strings
  'completed': 'Afsluttet',
  'inProgress': 'I gang',
  'continueGame': 'Fortsæt spillet',
  'replay': 'Genafspil',
  'creater': 'Kommandant',
  'created': 'Kamp starttid',
  'updated': 'Opdateret',
  // Dialog strings
  'confirm': 'Bekræft',
  'cancel': 'Annuller',
  'yes': 'Ja',
  'no': 'Nej',
  'save': 'Gem',
  'edit': 'Rediger',
  'levelFormat': 'Niveau {level}',
  'newbieLevelFormat': 'Nybegynder {level}',
  'totalLevel': '{level}/{totalLevel} niveauer',
  'totalLevelTooltip':
      'Nuværende: Niveau {level} / I alt {totalLevel} niveauer',
  // Battlefront UI strings
  'noBattlefronts': 'Ingen fronte',
  'battlefrontCount': '{count} fronte',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'NYB{level}',
  'minesCount': '{count} miner',
  'notStarted': 'Ikke startet',
  'victory': 'Sejr',
  'defeat': 'Nederlag',
  'gameDurationParam': 'Varighed: {seconds} sekunder',
  'actionsCountParam': 'Handlinger: {count} gange',
  'actionsCountParamShort': '{count} gange',
  'miningMethodParam': 'Metode: {method}',
  'startTimeParam': 'Starttid: {time}',
  'endTimeParam': 'Sluttid: {time}',
  'returnButton': 'Tilbage',
  'battlefrontDetails': 'Front detaljer',
  'clickToEditName': 'Klik for at ændre navn',
  'clickToAddDescription': 'Klik for at tilføje beskrivelse...',
  'noDescription': 'Ingen beskrivelse',
  // Level record strings
  'levelCount': '{count} niveauer',
  'noLevelRecords': 'Vælg en front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Slet front',
  'deleteBattlefrontContent':
      'Er du sikker på, at du vil slette fronten "{name}"? Denne handling kan ikke fortrydes.',
  'battlefrontLockedCannotDelete': 'Fronten er låst og kan ikke slettes',
  'unknownNavigationLevel': 'Ukendt niveau',
  'noBattlefrontSelected': 'Ingen front valgt',
  'noBattlefrontToContinue': 'Ingen front at fortsætte fra',
  'synced': 'Synkroniseret',
  'notSynced': 'Ikke synkroniseret',
  'newbieBattlefrontName': 'Nybegynder front {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Kaldenavn',
  'nicknameSetting': 'Indstilling af kaldenavn',
  'nicknameDesc': 'Indstil dit kaldenavn',
  'enterNickname': 'Indtast kaldenavn',
  'nicknameSaved': 'Kaldenavn gemt',
  'nicknameUpdated': 'Kaldenavn opdateret',
  'nicknameRequired': 'Kaldenavn er påkrævet',
  'nicknameTooLong': 'Kaldenavn må ikke overstige 30 tegn',
  // Level top strings
  'levelTopCount': 'Topliste ({count})',
  'levelTopCountShort': 'Top ({count})',
  'retry': 'Prøv igen',
  'noLevelTopData': 'Ingen data',
  'remoteBattlefront': 'Fjern front',
  'participated': 'Deltaget',
  'notParticipated': 'Ikke deltaget',
  'loadMore': 'Indlæs mere',

  'joinBattle': 'Deltag i kampen',
  'joinBattleTooltip': 'Deltag i kampen "{name}"',
  'joinBattleConfirm': 'Er du sikker på, at du vil deltage i kampen "{name}"?',
  'joinBattleSuccess': 'Du deltog succesfuldt i kampen "{name}"',
  'joinBattleErrorSelf': 'Du kan ikke deltage i din egen front',

  'replayBattlefront': 'Genafspil front',
  'replayBattlefrontTooltip': 'Genafspil fronten "{name}"',
  'getReplayBattlefrontConfirm':
      'Er du sikker på, at du vil genafspille "{name}"?',
  'getReplayBattlefrontFailed':
      'Genafspilning af "{name}" mislykkedes: {error}',

  'download': 'Hent',
  'downloadBattlefront': 'Hent front',
  'downloadBattlefrontTooltip': 'Hent fronten "{name}"',
  'getDownloadBattlefrontConfirm': 'Er du sikker på, at du vil hente "{name}"?',
  'getDownloadBattlefrontSuccess': 'Fronten "{name}" blev hentet succesfuldt',
  'downloadMyOwnBattlefrontError': 'Du kan kun hente dine egene fronte',
  'getDownloadBattlefrontFailed': 'Hentning af "{name}" mislykkedes: {error}',

  'continueGameShort': 'Fortsæt kampen',
  'replayShort': 'Genafspil',
  'highestLevel': 'Niveau {level}',
  'deviceNickname': 'Enhed',
  'createdTime': 'Oprettelsestid',
  'remoteBattlefrontDetail': 'Fjern front detaljer',
  'levelList': 'Niveauliste',
  'fastClearTimeParam': 'Klaretid: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Vælg en lokal front for at se detaljer',
  'loadingRemoteDetail': 'Indlæser fjernfront detaljer...',
  'noRemoteBattlefrontSelected': 'Ingen fjernfront valgt',
  'failedToLoadRemoteDetail': 'Kunne ikke indlæse fjernfront detaljer',
  'fastestRecord': 'Hurtigste klaretid',
  'safestRecord': 'Sikkerste klaretid',
  'fastestRecordDesc': 'Hurtigste klaretid (mindst tid)',
  'safestRecordDesc': 'Sikkerste klaretid (færrest handlinger)',
  'creator': 'Skaber',
  'player': 'Spiller',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopier',
  'collapse': 'Sammenfold',
  'expand': 'Udvid',
  // 退出战线
  'quitBattlefront': 'Forlad front',
  'quitBattlefrontTooltip': 'Forlad fjernfront',
  'quitBattlefrontTitle': 'Forlad front',
  'quitBattlefrontContent':
      'Er du sikker på, at du vil forlade fronten "{name}"? Din lokale fremskridt bliver slettet.',

  // 下载页面
  'downloadClient': 'Hent klient',
  'browser': 'Browser',
  'browserDesc': 'Spil direkte i browseren uden at hente',
  'windowsDesc': 'Til Windows 10 og nyere',
  'macosDesc': 'Til macOS 10.15 og nyere',
  'android': 'Android',
  'androidDesc': 'Til Android 8.0 og nyere',
  'iosDesc': 'Til iOS 14.0 og nyere',
  'linkAddress': 'Link adresse',
  'downloadLink': 'Downloadlink',
  'qrCode': 'QR-kode',
  'scanToDownload': 'Scan med telefon for at hente',
  'copy': 'Kopiér',
  'copiedToClipboard': 'Kopieret til udklipsholder',
  'openLink': 'Åbn link',
  'cannotOpenLink': 'Kan ikke åbne link',
  // 游戏介绍
  'gameIntroduction':
      '1. "Nybegynder" starter med 15 miner og kan gå op til 99 miner;\n2. "Ny front" starter med 81 miner, hvert niveau tilføjer flere miner uden øvre grænse.\n3. Når du er online, bliver "klarede" fronte automatisk delt i skyen til læring for andre.',
};
