// Luxembourgish（卢森堡语）
/// Lëtzebuergesch Texter fir d'App DMine
const Map<String, String> stringsLb = {
  'appLabel': 'Minesweeper Spill',
  'appTitle': 'DMine - Minesweeper Spill',
  'settings': 'Astellungen',
  'gameSettings': 'SpillAstellungen',
  'showTimer': 'Zäitweiser uweisen',
  'showTimerDesc': 'Weist den Zäitdriwwer am Spill u',
  'showActionCounter': 'Handlungszieler uweisen',
  'showActionCounterDesc': 'Weist d\'Zuel vun den Handlungen am Spill u',
  'autoAdjustBoardWidth': 'Breett automatesch uupassen',
  'autoAdjustBoardWidthDesc':
      'Passt d’Breett vum Spielfield automatesch un den Schiirmduerchmesser un',
  'resetToDefaults': 'Op Standard zrécksetzen',
  'resetToDefaultsDesc': 'All Astellungen op d’Ufankswäerter zrécksetzen',
  'aboutDMine': 'Iwwer DMine',
  'version': 'Versioun',
  'close': 'Zoumaachen',
  'manualBoardWidth': 'Breett vu Hand ustellen',
  'currentWidth': 'Momentan',
  'range': 'Gäichberech',
  'widthSliderHint':
      'Tip: Rielt den Schieber, fir d’Ännerunge vun der Breett am Echtzäit ze gesinn',
  'gameRecords': 'Spillrekorder',
  'selectMapToViewRecords': 'Wielt eng Kaart fir d’Rekorder ze kucken',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Lëscht vun den Spillrekorder',
  'pleaseSelectMapFirst': 'Wielt éischt eng Kaart',
  'noGameRecords': 'Keng Spillrekorder do',
  'miningMethodFlag': 'Fändel markéieren',
  'miningMethodBlind': 'Bloudsich',
  'statusPlaying': '▶️ Spillt...',
  'statusWin': '🎉 Gewonnen!',
  'statusLose': '💥 Verlueren!',
  'actionsCount': 'Handlungen',
  'miningMethod': 'Minersuchmethod',
  'duration': 'Dauer',
  'seconds': 'Sekonnen',
  'startTime': 'Ufankszäit',
  'endTime': 'Ennszäit',
  'pauseTime': 'Pausenzäit',
  'unlock': 'Opmaachen',
  'lock': 'Zoumaachen',
  'delete': 'Läschen',
  'languageSetting': 'SprochAstellung',
  'currentLanguage': 'Momentan',
  'systemLanguage': 'Systemsproch',
  'chinese': 'Chineesch',
  'english': 'Englesch',
  'language': 'Sproch',
  // Home page
  'newbie': 'Ufänger',
  'gameIntro': 'Spillbeschreiwung',
  'newBattle': 'Nei Front',
  'continueChallenge': 'Erausfuerung weiderfueren',
  'error': 'Fehler',
  'initializationFailed': 'Initialiséierung feelgeschloen',
  // Game page
  'congratulations': 'Gléckwonsch! Dir hutt de Level geschafft!',
  'gameOver': 'Spill iwwer',
  'timeUsed': 'Benotzt Zäit',
  'actionCount': 'Handlungen',
  'mineCount': 'Minenzuel',
  'nextLevel': 'Nächst Level: Level {level}',
  'newbieNextLevel': 'Nächst Level: Ufänger {level}',
  'nextLevelMines': 'Minenzuel',
  'mineIncrease': 'Erhéijung',
  'newbieFinish': 'Ufänger fäerdeg',
  'ok': 'OK',
  'continueNextLevel': 'Zum nächsten Level goen',
  'restart': 'Nei ufänken',
  'level': 'Level {level}',
  'newbieLevel': 'Ufänger Level {level}',
  'operationFailed': 'Operatioun feelgeschloen',
  // Game status texts
  'returnHome': 'Zréck op d’Heem',
  'revealMode': 'Opdecken Modus',
  'flagMode': 'Fändel Modus',
  'newMap': 'Nei Kaart (selwe Minenanzuel, nei Kaart erstellen)',
  'resetMap': 'Kaart zrécksetzen (selwe Kaart, Status zrécksetzen)',
  'zoomOut': 'Verklengeren',
  'zoomIn': 'Vergréisseren',
  'resetZoom': 'Zoom zrécksetzen',
  'previousStep': 'Vierä Schrëtt',
  'pause': 'Paus',
  'play': 'Spillen',
  'nextStep': 'Nächst Schrëtt',
  'clickToStart': 'Klickt op eng Zelle fir ze spillen',
  'playing': 'Spillt...',
  'gameWin': 'Gléckwonsch! Dir hutt de Level geschafft!',
  'gameLose': 'Spill iwwer, Dir hutt eng Mine getraff',
  'gamePaused': 'Spill pauséiert',
  'ready': 'Fäerdeg',
  'clickStartShort': 'Klickt fir unzefänken',
  'playingShort': 'Spillt',
  'winShort': 'Gewonnen!',
  'loseShort': 'Mine getraff',
  'pausedShort': 'Pauséiert',
  // Counter strings
  'currentLevel': 'Momentaner Level',
  'remainingMines': 'Minen iwwer',
  'gameTime': 'Spillzäit (Sekonnen)',
  'operationCount': 'Operatiounen',
  'previousLevel': 'Vierä Level',
  'nextLevelShort': 'Nächst Level',
  // Battlefront strings
  'completed': 'Ofgeschloss',
  'inProgress': 'Amgaang',
  'continueGame': 'Spill weiderfueren',
  'replay': 'Nochmals spillen',
  'creater': 'Schäffer',
  'created': 'Erstallt',
  'updated': 'Aktualiséiert',
  // Dialog strings
  'confirm': 'Bestätegen',
  'cancel': 'Ofbriechen',
  'yes': 'Jo',
  'no': 'Neen',
  'save': 'Späicheren',
  'edit': 'Beaarbechten',
  'levelFormat': 'Level {level}',
  'newbieLevelFormat': 'Ufänger Level {level}',
  'totalLevel': '{level}/{totalLevel} Level',
  'totalLevelTooltip': 'Momentan: Level {level} / Total {totalLevel} Level',
  // Battlefront UI strings
  'noBattlefronts': 'Keng Fronten',
  'battlefrontCount': '{count} Fronten',
  'levelPrefix': 'LV{level}',
  'newbiePrefix': 'UF{level}',
  'minesCount': '{count} Minen',
  'notStarted': 'Net ugefaangen',
  'victory': 'Sieg',
  'defeat': 'Niederlag',
  'gameDurationParam': 'Dauer: {seconds} Sekonnen',
  'actionsCountParam': 'Handlungen: {count} Mol',
  'actionsCountParamShort': '{count} Mol',
  'miningMethodParam': 'Method: {method}',
  'startTimeParam': 'Ufank: {time}',
  'endTimeParam': 'Enn: {time}',
  'returnButton': 'Zréck',
  'battlefrontDetails': 'Front Detailer',
  'clickToEditName': 'Klickt fir den Numm z\'änneren',
  'clickToAddDescription': 'Klickt fir eng Beschreiwung bäizefügen...',
  'noDescription': 'Keng Beschreiwung',
  // Level record strings
  'levelCount': '{count} Level',
  'noLevelRecords': 'Wielt eng Front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Front läschen',
  'deleteBattlefrontContent':
      'Sollt Dir wierklech d’Front "{name}" läschen? Dëst Operatioun ass net zréckkeesbar.',
  'battlefrontLockedCannotDelete': 'Front zou, kann net läschen',
  'unknownNavigationLevel': 'Onbekannte Navigatiounslevel',
  'noBattlefrontSelected': 'Keng Front gewielt',
  'noBattlefrontToContinue': 'Keng Front fir weiderzegoen',
  'synced': 'Synchronséiert',
  'notSynced': 'Net synchronséiert',
  'newbieBattlefrontName': 'Ufänger Front {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Spillnumm',
  'nicknameSetting': 'Spillnumm Astellung',
  'nicknameDesc': 'Stellt Äre Spillnumm an',
  'enterNickname': 'Gitt Äre Spillnumm an',
  'nicknameSaved': 'Spillnumm gespäichert',
  'nicknameUpdated': 'Spillnumm aktualiséiert',
  'nicknameRequired': 'Spillnumm ass erfuerderlech',
  'nicknameTooLong': 'Spillnumm däerf net méi wéi 30 Zeiche laang sinn',
  // Level top strings
  'levelTopCount': 'Ranking ({count})',
  'levelTopCountShort': 'Ranking ({count})',
  'retry': 'Nochmals probéieren',
  'noLevelTopData': 'Keng Donnéeën',
  'remoteBattlefront': 'Fern Front',
  'participated': 'Matgedeelt',
  'notParticipated': 'Keng Matdeelung',
  'loadMore': 'Méi lueden',

  'joinBattle': 'Uerkrich bäitreden',
  'joinBattleTooltip': 'Dem Uerkrich "{name}" bäitreden',
  'joinBattleConfirm': 'Sollt Dir wierklech dem Uerkrich "{name}" bäitreden?',
  'joinBattleSuccess':
      'Dir sidd dem Uerkrich "{name}" erfollegräich bäigetriede',
  'joinBattleErrorSelf': 'Dir kënnt Är eegen Front net bäitreden',

  'replayBattlefront': 'Front erëmspillen',
  'replayBattlefrontTooltip': 'D’Front "{name}" erëmspillen',
  'getReplayBattlefrontConfirm':
      'Sollt Dir wierklech d’Front "{name}" erëmspillen?',
  'getReplayBattlefrontFailed':
      'Front "{name}" konnt net erëmspillt ginn: {error}',

  'download': 'Eroflueden',
  'downloadBattlefront': 'Front eroflueden',
  'downloadBattlefrontTooltip': 'D’Front "{name}" eroflueden',
  'getDownloadBattlefrontConfirm':
      'Sollt Dir wierklech d’Front "{name}" eroflueden?',
  'getDownloadBattlefrontSuccess': 'Front "{name}" erfollegräich erofgelueden',
  'downloadMyOwnBattlefrontError':
      'Dir kënnt nëmmen Är eegen Fronten eroflueden',
  'getDownloadBattlefrontFailed':
      'Front "{name}" konnt net erofgelueden ginn: {error}',

  'continueGameShort': 'Uerkrich weiderfueren',
  'replayShort': 'Erëm',
  'highestLevel': 'Level {level}',
  'deviceNickname': 'Gerät',
  'createdTime': 'Erstellungszäit',
  'remoteBattlefrontDetail': 'Fern Front Detailer',
  'levelList': 'Level Lëscht',
  'fastClearTimeParam': 'Geschwindegkeet: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Wielt eng lokal Front fir Detailer ze kucken',
  'loadingRemoteDetail': 'Fern Detailer gi gelueden...',
  'noRemoteBattlefrontSelected': 'Keng Fern Front gewielt',
  'failedToLoadRemoteDetail': 'Fern Donnéeën konnten net gelueden ginn',
  'fastestRecord': 'Schnellst',
  'safestRecord': 'Sécherst',
  'fastestRecordDesc': 'Schnellst ofgeschloss ( manner Zäit )',
  'safestRecordDesc': 'Sécherst ofgeschloss ( manner Handlungen )',
  'creator': 'Schäffer',
  'player': 'Spiller',
  // 分支地图字符串
  'getBranchMapCount': '{count} Kopien',
  'collapse': 'Zoumaachen',
  'expand': 'Opmaachen',
  // 退出战线
  'quitBattlefront': 'Front verloossen',
  'quitBattlefrontTooltip': 'Fern Front verloossen',
  'quitBattlefrontTitle': 'Front verloossen',
  'quitBattlefrontContent':
      'Sollt Dir wierklech d’Front "{name}" verloossen? Äre lokal Fortschrët gëtt geläscht.',

  // 下载页面
  'downloadClient': 'Client eroflueden',
  'browser': 'Browser',
  'browserDesc': 'Spillt direkt am Browser, ouni erofzelueden',
  'windowsDesc': 'Windows 10 a méi nei',
  'macosDesc': 'macOS 10.15 a méi nei',
  'android': 'Android',
  'androidDesc': 'Android 8.0 a méi nei',
  'iosDesc': 'iOS 14.0 a méi nei',
  'linkAddress': 'Link Adress',
  'downloadLink': 'Erofluedslink',
  'qrCode': 'QR Code',
  'scanToDownload': 'Scannt mat Handy fir erofzelueden',
  'copy': 'Kopéieren',
  'copiedToClipboard': 'An d’Zwëschenlager kopéiert',
  'openLink': ' Link opmaachen',
  'cannotOpenLink': 'Link konnt net opgemaach ginn',
  // 游戏介绍
  'gameIntroduction':
      '1. „Ufänger“ fänkt mat 15 Minen un a kann bis 99 Minen ergoen.\n2. „Nei Front“ fänkt mat 81 Minen un, all Level erhéicht d’Minenzuel ouni Uewergrenz.\n3. Mat Internetverbindung ginn „ofgeschloss“ Fronten automatesch an der Cloud gespäichert, fir datt anerer se kënne benotzen.',
};
