// PortugueseBR（巴西葡萄牙语）
/// Brazilian Portuguese language strings for the DMine application
const Map<String, String> stringsPtBr = {
  'appLabel': 'Campo Minado Top',
  'appTitle': 'DMine - Campo Minado Top',
  'settings': 'Configurações',
  'gameSettings': 'Configurações do jogo',
  'showTimer': 'Mostrar cronômetro',
  'showTimerDesc': 'Exibe o cronômetro do jogo na tela',
  'showActionCounter': 'Mostrar contador de ações',
  'showActionCounterDesc': 'Exibe a contagem de ações na tela do jogo',
  'autoAdjustBoardWidth': 'Ajustar largura do tabuleiro automaticamente',
  'showUnrevealedCounter': 'Exibir contador de células não reveladas',
  'showUnrevealedCounterDesc': 'Mostrar quantidade de células não reveladas na interface do jogo',
  'showMineCounter': 'Exibir contador de minas',
  'showMineCounterDesc': 'Mostrar minas restantes na interface do jogo',
  'autoAdjustBoardWidthDesc':
      'Ajusta a largura do tabuleiro conforme o tamanho da tela',
  'resetToDefaults': 'Restaurar padrões',
  'resetToDefaultsDesc': 'Restaura todas as configurações aos valores padrão',
  'aboutDMine': 'Sobre o DMine',
  'version': 'Versão',
  'close': 'Fechar',
  'manualBoardWidth': 'Definir largura do tabuleiro manualmente',
  'currentWidth': 'Atual',
  'range': 'Intervalo',
  'widthSliderHint':
      'Dica: ao arrastar o controle, veja a mudança da largura em tempo real',
  'gameRecords': 'Registros de jogo',
  'selectMapToViewRecords': 'Selecione um mapa para ver os registros',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Lista de registros de jogo',
  'pleaseSelectMapFirst': 'Selecione um mapa primeiro',
  'noGameRecords': 'Nenhum registro de jogo',
  'miningMethodFlag': 'Marcar com bandeira',
  'miningMethodBlind': 'Varredura cega',
  'statusPlaying': '▶️ Em andamento...',
  'statusWin': '🎉 Vitória',
  'statusLose': '💥 Derrota',
  'actionsCount': 'Número de ações',
  'miningMethod': 'Modo de jogo',
  'duration': 'Duração',
  'seconds': 'segundos',
  'startTime': 'Hora de início',
  'endTime': 'Hora de término',
  'pauseTime': 'Tempo de pausa',
  'unlock': 'Desbloquear',
  'lock': 'Bloquear',
  'delete': 'Excluir',
  'languageSetting': 'Configuração de idioma',
  'currentLanguage': 'Atual',
  'systemLanguage': 'Idioma do sistema',
  'chinese': 'Chinês',
  'english': 'Inglês',
  'language': 'Idioma',
  // Home page
  'newbie': 'Iniciante',
  'gameIntro': 'Introdução ao jogo',
  'newBattle': 'Nova Frente de Batalha',
  'continueChallenge': 'Continuar desafio',
  'error': 'Erro',
  'initializationFailed': 'Falha na inicialização',
  // Game page
  'congratulations': 'Parabéns, você passou!',
  'gameOver': 'Fim de jogo',
  'timeUsed': 'Tempo',
  'actionCount': 'Ações',
  'mineCount': 'Minas',
  'nextLevel': 'Próximo nível: Nível {level}',
  'newbieNextLevel': 'Próximo nível: Iniciante {level}',
  'nextLevelMines': 'Minas',
  'mineIncrease': 'Aumento',
  'newbieFinish': 'Modo iniciante concluído',
  'ok': 'OK',
  'continueNextLevel': 'Continuar para o próximo nível',
  'restart': 'Reiniciar',
  'level': 'Nível {level}',
  'newbieLevel': 'Iniciante {level}',
  'operationFailed': 'Operação falhou',
  // Game status texts
  'returnHome': 'Voltar ao início',
  'revealMode': 'Modo revelar',
  'flagMode': 'Modo bandeira',
  'newMap': 'Novo mapa (mesmas minas, novo layout)',
  'resetMap': 'Redefinir mapa (mesmo layout, reiniciar)',
  'zoomOut': 'Diminuir zoom',
  'zoomIn': 'Aumentar zoom',
  'resetZoom': 'Restaurar zoom',
  'previousStep': 'Passo anterior',
  'pause': 'Pausar',
  'play': 'Jogar',
  'nextStep': 'Próximo passo',
  'clickToStart': 'Clique em qualquer quadrado para começar',
  'playing': 'Em jogo...',
  'gameWin': 'Parabéns, você passou!',
  'gameLose': 'Fim de jogo, você pisou em uma mina',
  'gamePaused': 'Jogo pausado',
  'ready': 'Pronto para começar',
  'clickStartShort': 'Clique para iniciar',
  'playingShort': 'Em jogo',
  'winShort': 'Concluído!',
  'loseShort': 'Derrota',
  'pausedShort': 'Pausado',
  // Counter strings
  'currentLevel': 'Nível atual',
  'remainingMines': 'Minas restantes',
  'unrevealedCells': 'Células não reveladas',
  'gameTime': 'Tempo de jogo (segundos)',
  'operationCount': 'Número de operações',
  'previousLevel': 'Nível anterior',
  'nextLevelShort': 'Próximo nível',
  // Battlefront strings
  'completed': 'Concluído',
  'inProgress': 'Em andamento',
  'continueGame': 'Continuar jogo',
  'replay': 'Replay',
  'creater': 'Comandante',
  'created': 'Hora de criação',
  'updated': 'Atualizado',
  // Dialog strings
  'confirm': 'Confirmar',
  'cancel': 'Cancelar',
  'yes': 'Sim',
  'no': 'Não',
  'save': 'Salvar',
  'edit': 'Editar',
  'levelFormat': 'Nível {level}',
  'newbieLevelFormat': 'Iniciante {level}',
  'totalLevel': '{level}/{totalLevel} níveis',
  'totalLevelTooltip': 'Atual: Nível {level} / Total {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Nenhuma frente de batalha',
  'battlefrontCount': '{count} frentes de batalha',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'Iniciante NV{level}',
  'minesCount': '{count} minas',
  'notStarted': 'Não iniciado',
  'victory': 'Vitória',
  'defeat': 'Derrota',
  'gameDurationParam': 'Duração: {seconds}s',
  'actionsCountParam': 'Ações: {count} vezes',
  'actionsCountParamShort': '{count} vezes',
  'miningMethodParam': 'Modo: {method}',
  'startTimeParam': 'Início: {time}',
  'endTimeParam': 'Término: {time}',
  'returnButton': 'Voltar',
  'battlefrontDetails': 'Detalhes da frente',
  'clickToEditName': 'Clique para editar o nome',
  'clickToAddDescription': 'Clique para adicionar descrição...',
  'noDescription': 'Sem descrição',
  // Level record strings
  'levelCount': '{count} níveis',
  'noLevelRecords': 'Selecione uma frente de batalha',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Excluir frente',
  'deleteBattlefrontContent':
      'Tem certeza que deseja excluir a frente \'{name}\'? Esta ação não pode ser desfeita.',
  'battlefrontLockedCannotDelete': 'Frente bloqueada, não pode excluir',
  'unknownNavigationLevel': 'Nível desconhecido',
  'noBattlefrontSelected': 'Nenhuma frente selecionada',
  'noBattlefrontToContinue': 'Nenhuma frente para continuar',
  'synced': 'Sincronizado',
  'notSynced': 'Não sincronizado',
  'newbieBattlefrontName': 'Frente iniciante {number}',
  'battlefrontName': 'Frente {number}',
  'nickname': 'Apelido',
  'nicknameSetting': 'Configuração de apelido',
  'nicknameDesc': 'Defina seu apelido',
  'enterNickname': 'Digite o apelido',
  'nicknameSaved': 'Apelido salvo',
  'nicknameUpdated': 'Apelido atualizado',
  'nicknameRequired': 'Apelido é obrigatório',
  'nicknameTooLong': 'Apelido não pode ter mais de 30 caracteres',
  // Level top strings
  'levelTopCount': 'Ranking ({count})',
  'levelTopCountShort': 'Ranking ({count})',
  'retry': 'Tentar novamente',
  'noLevelTopData': 'Sem dados',
  'remoteBattlefront': 'Frente remota',
  'participated': 'Participou',
  'notParticipated': 'Não participou',
  'loadMore': 'Carregar mais',
  'joinBattle': 'Entrar na batalha',
  'joinBattleTooltip': 'Entrar na batalha \'{name}\'',
  'joinBattleConfirm': 'Tem certeza que deseja entrar na batalha \'{name}\'?',
  'joinBattleSuccess': 'Entrou na batalha \'{name}\' com sucesso',
  'joinBattleErrorSelf': 'Não pode entrar na sua própria frente',
  'replayBattlefront': 'Replay da frente',
  'replayBattlefrontTooltip': 'Replay da frente \'{name}\'',
  'getReplayBattlefrontConfirm':
      'Tem certeza que deseja reproduzir \'{name}\'?',
  'getReplayBattlefrontFailed': 'Falha ao reproduzir \'{name}\': {error}',
  'download': 'Baixar',
  'downloadBattlefront': 'Baixar frente',
  'downloadBattlefrontTooltip': 'Baixar frente \'{name}\'',
  'getDownloadBattlefrontConfirm': 'Tem certeza que deseja baixar \'{name}\'?',
  'getDownloadBattlefrontSuccess': 'Baixou \'{name}\' com sucesso',
  'downloadMyOwnBattlefrontError': 'Só pode baixar suas próprias frentes',
  'getDownloadBattlefrontFailed': 'Falha ao baixar \'{name}\': {error}',
  'continueGameShort': 'Continuar batalha',
  'replayShort': 'Replay',
  'highestLevel': 'Nível {level}',
  'deviceNickname': 'Dispositivo',
  'createdTime': 'Data de criação',
  'remoteBattlefrontDetail': 'Detalhes da frente remota',
  'levelList': 'Lista de níveis',
  'fastClearTimeParam': 'Tempo de conclusão: {time}',
  // Detalhes da frente remota
  'selectLocalBattlefrontHint': 'Selecione uma frente local para ver detalhes',
  'loadingRemoteDetail': 'Carregando detalhes da frente remota...',
  'noRemoteBattlefrontSelected': 'Nenhuma frente remota selecionada',
  'failedToLoadRemoteDetail': 'Falha ao carregar detalhes',
  'fastestRecord': 'Conclusão mais rápida',
  'safestRecord': 'Conclusão mais segura',
  'fastestRecordDesc': 'Mais rápida (menos tempo)',
  'safestRecordDesc': 'Mais segura (menos ações)',
  'creator': 'Criador',
  'player': 'Jogador',
  // Mapas de branch
  'getBranchMapCount': '{count} cópias',
  'collapse': 'Recolher',
  'expand': 'Expandir',
  // Sair da frente
  'quitBattlefront': 'Sair da frente',
  'quitBattlefrontTooltip': 'Sair da frente remota',
  'quitBattlefrontTitle': 'Sair da frente',
  'quitBattlefrontContent':
      'Tem certeza que deseja sair da frente \'{name}\'? Seu progresso local será apagado.',
  // Introdução do jogo
  'gameIntroduction':
      '1. "Iniciante" começa com 15 minas, até 99 minas;\n2. "Nova Frente" começa com 81 minas, aumenta a cada nível, sem limite superior.\n3. Conectado, frentes concluídas são compartilhadas na nuvem para outros jogadores.',
};
