// Irish（爱尔兰语）
/// Teaghráin Gaeilge don fheidhmhlacht DMine
const Map<String, String> stringsGa = {
  'appLabel': 'Mineáilíoir is Fearr',
  'appTitle': 'DMine - Mineáilíoir is Fearr',
  'settings': 'Socruithe',
  'gameSettings': 'Socruithe Cluiche',
  'showTimer': 'Taispeáin amhrán',
  'showTimerDesc': 'Taispeáin amhrán an chluiche ar an chomhéadan',
  'showActionCounter': 'Taispeáin comhaireamh gníomhartha',
  'showActionCounterDesc':
      'Taispeáin líon na ngníomhartha ar chomhéadan an chluiche',
  'autoAdjustBoardWidth': 'Coigeartaigh leithead an bhord go huathoibríoch',
  'autoAdjustBoardWidthDesc':
      'Coigeartaigh leithead an bhord go huathoibríoch de réir méid na scáileáin',
  'resetToDefaults': 'Athshocraigh go réamhshocruithe',
  'resetToDefaultsDesc': 'Athshocraigh gach socrú go luachanna bunaidh',
  'aboutDMine': 'Maidir le DMine',
  'version': 'Leagan',
  'close': 'Dún',
  'manualBoardWidth': 'Socraigh leithead an bhord de láimh',
  'currentWidth': 'Reathaí',
  'range': 'Raon',
  'widthSliderHint':
      'Leid: Is féidir leat athruithe ar leithead an bhord a fheiceáil i bhfíor-am agus tú ag tarraingt an sleamáin',
  'gameRecords': 'Taifid cluiche',
  'selectMapToViewRecords': 'Roghnaigh léarscáil chun taifid a fheiceáil',
  'totalRecords': 'Iomlán',
  'gameRecordsTitle': 'Liosta taifid cluiche',
  'pleaseSelectMapFirst': 'Roghnaigh léarscáil ar dtús',
  'noGameRecords': 'Gan taifid cluiche ar fáil',
  'miningMethodFlag': 'Cuir brat suas',
  'miningMethodBlind': 'Cuardach dall',
  'statusPlaying': '▶️ Ag imirt...',
  'statusWin': '🎉 Bua',
  'statusLose': '💥 Cailleadh',
  'actionsCount': 'Líon na ngníomhartha',
  'miningMethod': 'Modh cuardaigh mianraí',
  'duration': 'Reacht',
  'seconds': 'soicind',
  'startTime': 'Am tosaigh',
  'endTime': 'Am deiridh',
  'pauseTime': 'Am sos',
  'unlock': 'Díghlasáil',
  'lock': 'Glasáil',
  'delete': 'Scrios',
  'languageSetting': 'Socrú teanga',
  'currentLanguage': 'Reathaí',
  'systemLanguage': 'Teanga an chórais',
  'chinese': 'Sínis',
  'english': 'Béarla',
  'language': 'Teanga',
  // Home page
  'newbie': 'Níos úire',
  'newBattle': 'Taoise nua',
  'continueChallenge': 'Lean ar aghaidh leis an dúshlán',
  'error': 'Earráid',
  'initializationFailed': 'Theip ar thúsú',
  // Game page
  'congratulations': 'Comhghairdeas, chríochnaigh tú an leibhéal!',
  'gameOver': 'Cluiche thart',
  'timeUsed': 'Am a úsáideadh',
  'actionCount': 'Líon na ngníomhartha',
  'mineCount': 'Líon na mianraí',
  'nextLevel': 'An chéad leibhéal eile: Leibhéal {level}',
  'newbieNextLevel': 'An chéad leibhéal eile: Níos úire {level}',
  'nextLevelMines': 'Líon na mianraí',
  'mineIncrease': 'Méadú',
  'newbieFinish': 'Túsú do nuúsáideoirí críochnaithe',
  'ok': 'OK',
  'continueNextLevel': 'Téigh go dtí an leibhéal seo chugainn',
  'restart': 'Atosaigh',
  'level': 'Leibhéal {level}',
  'newbieLevel': 'Leibhéal nuúsáideora {level}',
  'operationFailed': 'Theip ar an oibríocht',
  // Game status texts
  'returnHome': 'Téigh ar ais go dtí an bhaile',
  'revealMode': 'Mód nochta',
  'flagMode': 'Mód brataí',
  'newMap': 'Léarscáil nua (an líon céanna mianraí, cruthaigh léarscáil nua)',
  'resetMap':
      'Lódáil an léarscáil arís (an léarscáil chéanna, athshocraigh stádas)',
  'zoomOut': 'Síneadh amach',
  'zoomIn': 'Síneadh isteach',
  'resetZoom': 'Athshocraigh súmáil',
  'previousStep': 'Céim roimhe seo',
  'pause': 'Sos',
  'play': 'Imirt',
  'nextStep': 'An chéad chéim eile',
  'clickToStart': 'Cliceáil ar bhosca ar bith chun an cluiche a thosú',
  'playing': 'Ag imirt...',
  'gameWin': 'Comhghairdeas, chríochnaigh tú an leibhéal!',
  'gameLose': 'Cluiche thart, bhuail tú mianra',
  'gamePaused': 'Tá an cluiche ar sos',
  'ready': 'Réidh',
  'clickStartShort': 'Cliceáil le tosú',
  'playingShort': 'Ar siúl',
  'winShort': 'Críochnaithe!',
  'loseShort': 'Buail mianra',
  'pausedShort': 'Ar sos',
  // Counter strings
  'currentLevel': 'Leibhéal reatha',
  'remainingMines': 'Mianraí fágtha',
  'gameTime': 'Am cluiche (soicind)',
  'operationCount': 'Líon na n-oibríochtaí',
  'previousLevel': 'Leibhéal roimhe seo',
  'nextLevelShort': 'Leibhéal eile',
  // Battlefront strings
  'completed': 'Críochnaithe',
  'inProgress': 'Ar siúl',
  'continueGame': 'Lean ar aghaidh leis an gcluiche',
  'replay': 'Imirt arís',
  'creater': 'Ceannasaí',
  'created': 'Am tosaigh an chatha',
  'updated': 'Nuashonraithe',
  // Dialog strings
  'confirm': 'Deimhnigh',
  'cancel': 'Cealaigh',
  'yes': 'Tá',
  'no': 'Níl',
  'save': 'Sábháil',
  'edit': 'Cuir in eagar',
  'levelFormat': 'Leibhéal {level}',
  'newbieLevelFormat': 'Leibhéal nuúsáideora {level}',
  'totalLevel': '{level}/{totalLevel} leibhéal',
  'totalLevelTooltip':
      'Reathaí: Leibhéal {level} / Iomlán {totalLevel} leibhéal',
  // Battlefront UI strings
  'noBattlefronts': 'Gan taoisigh',
  'battlefrontCount': '{count} taoisigh',
  'levelPrefix': 'LB{level}',
  'newbieLevelPrefix': 'NU{level}',
  'minesCount': '{count} mianraí',
  'notStarted': 'Níor thosaigh',
  'victory': 'Bua',
  'defeat': 'Cailleadh',
  'gameDurationParam': 'Reacht: {seconds} soicind',
  'actionsCountParam': 'Gníomhartha: {count} uair',
  'actionsCountParamShort': '{count} uair',
  'miningMethodParam': 'Modh: {method}',
  'startTimeParam': 'Am tosaigh: {time}',
  'endTimeParam': 'Am deiridh: {time}',
  'returnButton': 'Ar ais',
  'battlefrontDetails': 'Sonraí taoise',
  'clickToEditName': 'Cliceáil chun an t-ainm a athrú',
  'clickToAddDescription': 'Cliceáil chun cur síos a chur leis...',
  'noDescription': 'Gan cur síos',
  // Level record strings
  'levelCount': '{count} leibhéal',
  'noLevelRecords': 'Roghnaigh taoise',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Scrios taoise',
  'deleteBattlefrontContent':
      'An bhfuil tú cinnte gur mian leat an taoise "{name}" a scriosadh? Níl féidir an ghníomh seo a dhíbhe.',
  'battlefrontLockedCannotDelete':
      'Tá an taoise glasáilte, ní féidir é a scriosadh',
  'unknownNavigationLevel': 'Leibhéal nascleanúina anaithnid',
  'noBattlefrontSelected': 'Gan taoise roghnaithe',
  'noBattlefrontToContinue': 'Gan taoise le leanúil ar aghaidh',
  'synced': 'Comhthaithe',
  'notSynced': 'Ní comhthaithe',
  'newbieBattlefrontName': 'Taoise nuúsáideora {number}',
  'battlefrontName': 'Taoise {number}',
  'nickname': 'Laochainn',
  'nicknameSetting': 'Socrú laochainne',
  'nicknameDesc': 'Socraigh do laochainn',
  'enterNickname': 'Iontráil laochainn',
  'nicknameSaved': 'Laochainn sábháilte',
  'nicknameUpdated': 'Laochainn nuashonraithe',
  'nicknameRequired': 'Tá laochainn ag teastáil',
  'nicknameTooLong':
      'Ní féidir leis an laochainn a bheith níos faide ná 30 carachtar',
  // Level top strings
  'levelTopCount': 'Rangú ({count})',
  'levelTopCountShort': 'Rangú ({count})',
  'retry': 'Déan iarracht arís',
  'noLevelTopData': 'Gan sonraí',
  'remoteBattlefront': 'Taoise i bhfad i gcéin',
  'participated': 'Ghlith páirt',
  'notParticipated': 'Níor ghlith páirt',
  'loadMore': 'Lódáil níos mó',

  'joinBattle': 'Glac páirt sa chath',
  'joinBattleTooltip': 'Glac páirt sa chath "{name}"',
  'joinBattleConfirm':
      'An bhfuil tú cinnte gur mian leat páirt a ghlacadh sa chath "{name}"?',
  'joinBattleSuccess': 'Ghlac tú páirt go rathúil sa chath "{name}"',
  'joinBattleErrorSelf': 'Ní féidir leat páirt a ghlacadh i do thaoise féin',

  'replayBattlefront': 'Imirt an taoise arís',
  'replayBattlefrontTooltip': 'Imirt an taoise "{name}" arís',
  'getReplayBattlefrontConfirm':
      'An bhfuil tú cinnte gur mian leat "{name}" a imirt arís?',
  'getReplayBattlefrontFailed': 'Theip ar "{name}" a imirt arís: {error}',

  'download': 'Íoslódáil',
  'downloadBattlefront': 'Íoslódáil taoise',
  'downloadBattlefrontTooltip': 'Íoslódáil an taoise "{name}"',
  'getDownloadBattlefrontConfirm':
      'An bhfuil tú cinnte gur mian leat "{name}" a íoslódáil?',
  'getDownloadBattlefrontSuccess':
      'Tá an taoise "{name}" íoslódáilte go rathúil',
  'downloadMyOwnBattlefrontError':
      'Ní féidir leat ach do thaoisigh féin a íoslódáil',
  'getDownloadBattlefrontFailed': 'Theip ar "{name}" a íoslódáil: {error}',

  'continueGameShort': 'Lean ar aghaidh leis an gcath',
  'replayShort': 'Imirt arís',
  'highestLevel': 'Leibhéal {level}',
  'deviceNickname': 'Gléas',
  'createdTime': 'Am cruthaithe',
  'remoteBattlefrontDetail': 'Sonraí taoise i bhfad i gcéin',
  'levelList': 'Liosta leibhéal',
  'fastClearTimeParam': 'Am críochnaithe: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Roghnaigh taoise áitiúil chun sonraí a fheiceáil',
  'loadingRemoteDetail': 'Ag lódáil sonraí taoise i bhfad i gcéin...',
  'noRemoteBattlefrontSelected': 'Gan taoise i bhfad i gcéin roghnaithe',
  'failedToLoadRemoteDetail': 'Theip ar shonraí i bhfad i gcéin a lódáil',
  'fastestRecord': 'Críochnaithe is gasta',
  'safestRecord': 'Críochnaithe is sábháilte',
  'fastestRecordDesc': 'Críochnaithe is gasta (níos lú am)',
  'safestRecordDesc': 'Críochnaithe is sábháilte (níos lú gníomhartha)',
  'creator': 'Cruthaitheoir',
  'player': 'Imreoir',
  // 分支地图字符串
  'getBranchMapCount': '{count} chóipeáil',
  'collapse': 'Lúbtha',
  'expand': 'Leathnú',
  // 退出战线
  'quitBattlefront': 'Scaoil taoise',
  'quitBattlefrontTooltip': 'Scaoil taoise i bhfad i gcéin',
  'quitBattlefrontTitle': 'Scaoil taoise',
  'quitBattlefrontContent':
      'An bhfuil tú cinnte gur mian leat an taoise "{name}" a scaoileadh? Scriosfar do dhul chun cinn áitiúil.',

  // 下载页面
  'downloadClient': 'Íoslódáil an cliant',
  'browser': 'Brabhsálaí',
  'browserDesc': 'Imirt go díreach sa bhrabhsálaí, gan íoslódáil',
  'windowsDesc': 'Le haghaidh Windows 10 agus níos déanaí',
  'macosDesc': 'Le haghaidh macOS 10.15 agus níos déanaí',
  'android': 'Android',
  'androidDesc': 'Le haghaidh Android 8.0 agus níos déanaí',
  'iosDesc': 'Le haghaidh iOS 14.0 agus níos déanaí',
  'linkAddress': 'Seoladh na n-aiseol',
  'downloadLink': 'Nasc íoslódála',
  'qrCode': 'Cód QR',
  'scanToDownload': 'Scan le do ghuthán chun íoslódáil',
  'copy': 'Cóipeáil',
  'copiedToClipboard': 'Cóipeáilte go dtí an gearrthaisce',
  'openLink': 'Oscail an nasc',
  'cannotOpenLink': 'Ní féidir an nasc a oscailt',
  // 游戏介绍
  'gameIntroduction':
      '1. Tosaíonn an "Níos úire" le 15 mianra agus is féidir leis suas le 99 mianra a bhaint amach.\n2. Tosaíonn an "Taoise nua" le 81 mianra, cuireann gach leibhéal mianraí leis gan teorainn uachtarach.\n3. Le nasc idirlín, roinntear taoisigh "críochnaithe" go huathoibríoch sa scamall do dhaoine eile.',
};
