// Pashto（普什图语）
/// Pashto language strings for the DMine application
const Map<String, String> stringsPs = {
  'appLabel': 'د ٹاپ ماین سایفر',
  'appTitle': 'DMine - د ټاپ ماین سایفر',
  'settings': 'تنظیمات',
  'gameSettings': 'د لوبې تنظیمات',
  'showTimer': 'د وخت ټایمر ښکاره کړئ',
  'showTimerDesc': 'د لوبې پاڼه کې د لوبې ټایمر ښکاره کړئ',
  'showActionCounter': 'د عملونو شمیرونکی ښکاره کړئ',
  'showActionCounterDesc': 'د لوبې پاڼه کې د عملونو شمیراتو احصایې ښکاره کړئ',
  'autoAdjustBoardWidth': 'د بورډ عرض خودکار تنظیم کړئ',
  'autoAdjustBoardWidthDesc':
      'د سکرین سایز پر بنسټ د بورډ عرض خودکار تنظیم کړئ',
  'resetToDefaults': 'په mặc định ته راستنیدل',
  'resetToDefaultsDesc': 'ټول تنظیمات په mặc định ارزښتونو ته بیرته راستنیدل',
  'aboutDMine': 'د DMine په اړه',
  'version': 'ورژن',
  'close': 'بند کړئ',
  'manualBoardWidth': 'د بورډ عرض لاسه تنظیم کړئ',
  'currentWidth': 'الحال',
  'range': 'حد',
  'widthSliderHint':
      'نکته: د سلاایډر حرکت په جریان کې د بورډ عرض بدلون فوری لیدل کیدی شي',
  'gameRecords': 'د لوبې ریکارډونه',
  'selectMapToViewRecords': 'ریکارډونه لیدلو لپاره لطفاً یو نقشه انتخاب کړئ',
  'totalRecords': 'مجموع',
  'gameRecordsTitle': 'د لوبې ریکارډونو لیست',
  'pleaseSelectMapFirst': 'لطفاً مخکې یو نقشه انتخاب کړئ',
  'noGameRecords': 'د لوبې ریکارډونه شتون نلري',
  'miningMethodFlag': 'پرچم ставول',
  'miningMethodBlind': 'بی دیده ماین سایفر',
  'statusPlaying': '▶️ پرمخ وړي...',
  'statusWin': '🎉 بریالی',
  'statusLose': '💥 ناکام',
  'actionsCount': 'د عملیاتو شمیر',
  'miningMethod': 'د ماین سایفر طریقه',
  'duration': 'مودت',
  'seconds': 'ثانیې',
  'startTime': 'د پیل وخت',
  'endTime': 'د پایانی وخت',
  'pauseTime': 'د توقف وخت',
  'unlock': 'بند له مینځه وړل',
  'lock': 'بند کړئ',
  'delete': 'هټ کړئ',
  'languageSetting': 'د ژبې تنظیمات',
  'currentLanguage': 'الحال',
  'systemLanguage': 'د سیسټم ژبه',
  'chinese': 'چینی',
  'english': 'انګلیسي',
  'language': 'ژبه',
  // Home page
  'newbie': 'نووکارانو لپاره لاسرسي',
  'gameIntro': 'د لوبې پیژندنه',
  'newBattle': 'نوې جګړه لاره',
  'continueChallenge': 'ننوتنې ته دوام ورکړئ',
  'error': 'خطا',
  'initializationFailed': 'د ابتدايي تنظیمات ناکامۍ',
  // Game page
  'congratulations': 'مبارک، توب بریالی شوی!',
  'gameOver': 'د لوبې پای',
  'timeUsed': 'استعمال شوی وخت',
  'actionCount': 'د عملونو شمیر',
  'mineCount': 'د ماینونو شمیر',
  'nextLevel': 'هغه بل لیول: {level} لیول',
  'newbieNextLevel': 'هغه بل لیول: نووکار {level} لیول',
  'nextLevelMines': 'د ماینونو شمیر',
  'mineIncrease': 'زیادیدل',
  'newbieFinish': 'د نووکارانو لپاره لاسرسي کامل شوی',
  'ok': 'تصدیق',
  'continueNextLevel': 'هغه بل لیول ته ننوتنې ته دوام ورکړئ',
  'restart': 'بیا پیل کړئ',
  'level': '{level} لیول',
  'newbieLevel': 'نووکار {level} لیول',
  'operationFailed': 'د عملیات ناکامۍ',
  // Game status texts
  'returnHome': 'په کور بیرته راستنیدل',
  'revealMode': 'د انګیرنې حالت',
  'flagMode': 'د پرچم ставولو حالت',
  'newMap': 'نوې نقشه(د ماینونو شمیر بې بدل، نوې نقشه رامینځته کړئ)',
  'resetMap': 'نقشه بیا بار کړئ(نقشه بې بدل، حالت راستنیدل)',
  'zoomOut': 'کوچک کړئ',
  'zoomIn': 'لوی کړئ',
  'resetZoom': 'په اصلي حالت بیرته راستنیدل',
  'previousStep': 'مخکینی ګام',
  'pause': 'توقف',
  'play': 'لوبو',
  'nextStep': 'هغه بل ګام',
  'clickToStart': 'د لوبې پیل لپاره کومه هم خونه کلیک کړئ',
  'playing': 'لوبه کې...',
  'gameWin': 'مبارک، توب بریالی شوی!',
  'gameLose': 'د لوبې پای، ماین ته ټکي ورکړی',
  'gamePaused': 'د لوبې توقف',
  'ready': 'په پیل لپاره چمتو',
  'clickStartShort': 'کلیک کړئ ترڅو پیل کړئ',
  'playingShort': 'لوبه کې',
  'winShort': 'بریالی!',
  'loseShort': 'د ماین ټکي ورکول ناکام',
  'pausedShort': 'توقف',
  // Counter strings
  'currentLevel': 'الحالي لیول',
  'remainingMines': 'د ماینونو پاتې شمیر',
  'gameTime': 'د لوبې وخت (ثانیې)',
  'operationCount': 'د عملیاتو شمیر',
  'previousLevel': 'مخکینی لیول',
  'nextLevelShort': 'هغه بل لیول',
  // Battlefront strings
  'completed': 'کامل شوی',
  'inProgress': 'پرمخ وړي',
  'continueGame': 'لوبه ته دوام ورکړئ',
  'replay': 'بیا لوبو',
  'creater': 'مشر کلوي',
  'created': 'د جګړې پیل وخت',
  'updated': 'بروزرسیدل',
  // Dialog strings
  'confirm': 'تصدیق',
  'cancel': 'منه کړئ',
  'yes': 'هو',
  'no': 'نه',
  'save': 'خوندي کړئ',
  'edit': 'اصلاح کړئ',
  'levelFormat': '{level} لیول',
  'newbieLevelFormat': 'نووکار {level} لیول',
  'totalLevel': '{level}/{totalLevel} لیول',
  'totalLevelTooltip': 'الحال: {level} لیول / مجموع {totalLevel} لیول',
  // Battlefront UI strings
  'noBattlefronts': 'جګړې لارې شتون نلري',
  'battlefrontCount': '{count} جګړې لارې',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'نووکار LV{level}',
  'minesCount': '{count} ماین',
  'notStarted': 'پیل نشوی',
  'victory': 'بریالی',
  'defeat': 'هزیمت',
  'gameDurationParam': 'مودت: {seconds} ثانیې',
  'actionsCountParam': 'عملونه: {count} ځل',
  'actionsCountParamShort': '{count} ځل',
  'miningMethodParam': 'طریقه: {method}',
  'startTimeParam': 'د پیل وخت: {time}',
  'endTimeParam': 'د پایانی وخت: {time}',
  'returnButton': 'بیرته راستنیدل',
  'battlefrontDetails': 'د جګړې لارې تفصیلات',
  'clickToEditName': 'د نوم بدلولو لپاره کلیک کړئ',
  'clickToAddDescription': 'د توضیحاتو اضافه کولو لپاره کلیک کړئ...',
  'noDescription': 'توضیحات شتون نلري',
  // Level record strings
  'levelCount': '{count} لیولونه',
  'noLevelRecords': 'لطفاً جګړې لاره انتخاب کړئ',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'د جګړې لاره هټ کړئ',
  'deleteBattlefrontContent':
      'ایا تاسو chắc یې د \'{name}\' جګړې لاره هټ کړئ؟ دا عملیات بیرته نشي راستنیدل کیدی.',
  'battlefrontLockedCannotDelete': 'د جګړې لاره بند شوی، هټ نشي کیدی',
  'unknownNavigationLevel': 'نامعلوم لیول',
  'noBattlefrontSelected': 'جګړې لاره انتخاب نشوی',
  'noBattlefrontToContinue': 'د دوام ورکولو لپاره جګړې لاره موندل نشي',
  'synced': 'همغږي شوی',
  'notSynced': 'همغږي نشوی',
  'newbieBattlefrontName': 'نووکار جګړې لاره{number}',
  'battlefrontName': 'جګړې لاره{number}',
  'nickname': 'خلاصه نوم',
  'nicknameSetting': 'د خلاصه نوم تنظیمات',
  'nicknameDesc': 'خپل خلاصه نوم تنظیم کړئ',
  'enterNickname': 'خلاصه نوم داخل کړئ',
  'nicknameSaved': 'خلاصه نوم خوندي شوی',
  'nicknameUpdated': 'د خلاصه نوم بروزرسانی بریالی',
  'nicknameRequired': 'خلاصه نوم لازمی ده',
  'nicknameTooLong': 'خلاصه نوم 30 حروف څخه ډیر نشي کیدی',
  // Level top strings
  'levelTopCount': 'د ټاپ جدول ({count})',
  'levelTopCountShort': 'ټاپ ({count})',
  'retry': 'بیا هڅه کړئ',
  'noLevelTopData': 'داتا شتون نلري',
  'remoteBattlefront': 'لېږد جګړې لارې',
  'participated': '참여 شوی',
  'notParticipated': '참여 نشوی',
  'loadMore': '더 ډیر بار کړئ',

  'joinBattle': 'په جګړه کې شامل شئ',
  'joinBattleTooltip': 'په \'{name}\' جګړه کې شامل شئ',
  'joinBattleConfirm': 'ایا تاسو chắc یې په \'{name}\' جګړه کې شامل شئ؟',
  'joinBattleSuccess': 'په \'{name}\' جګړه کې بریالی سره شامل شوی',
  'joinBattleErrorSelf':
      'نکولی شئ په خپل لخوا رامینځته شوي جګړې لاره کې شامل شئ',

  'replayBattlefront': 'د جګړې لاره بیا لوبو',
  'replayBattlefrontTooltip': 'د \'{name}\' جګړې لاره بیا لوبو',
  'getReplayBattlefrontConfirm': 'ایا تاسو chắc یې \'{name}\' بیا لوبو؟',
  'getReplayBattlefrontFailed': 'د \'{name}\' بیا لوبو ناکام: {error}',

  'download': 'ډاونلوډ کړئ',
  'downloadBattlefront': 'د جګړې لاره ډاونلوډ کړئ',
  'downloadBattlefrontTooltip': 'د \'{name}\' جګړې لاره ډاونلوډ کړئ',
  'getDownloadBattlefrontConfirm': 'ایا تاسو chắc یې \'{name}\' ډاونلوډ کړئ؟',
  'getDownloadBattlefrontSuccess': 'د \'{name}\' ډاونلوډ بریالی',
  'downloadMyOwnBattlefrontError':
      'تنها خپل لخوا رامینځته شوي جګړې لارې ډاونلوډ کیدی شي',
  'getDownloadBattlefrontFailed': 'د \'{name}\' ډاونلوډ ناکام: {error}',

  'continueGameShort': 'جګړه ته دوام ورکړئ',
  'replayShort': 'بیا لوبو',
  'highestLevel': '{level} لیول',
  'deviceNickname': 'د وسیله',
  'createdTime': 'د رامینځته کولو وخت',
  'remoteBattlefrontDetail': 'د جګړې لارې تفصیلات',
  'levelList': 'د لیولونو لیست',
  'fastClearTimeParam': 'د توب وخت: {time}',
  // د لېږد جګړې لارې تفصیلاتي تارونه
  'selectLocalBattlefrontHint':
      'لطفاً د محلي جګړې لاره انتخاب کړئ ترڅو تفصیلات لیدل',
  'loadingRemoteDetail': 'د لېږد جګړې لارې تفصیلات بار کېږي...',
  'noRemoteBattlefrontSelected': 'د لېږد جګړې لاره انتخاب نشوی',
  'failedToLoadRemoteDetail': 'د لېږد جګړې لارې تفصیلات بار کول ناکام',
  'fastestRecord': 'غوره تیز بریالی',
  'safestRecord': 'غوره محفوظ بریالی',
  'fastestRecordDesc': 'غوره تیز بریالی(لږ وخت)',
  'safestRecordDesc': 'غوره محفوظ بریالی(لږ عملیات)',
  'creator': 'ساختکار',
  'player': 'لوبغاړی',
  // د څانګې نقشې تارونه
  'getBranchMapCount': '{count} کاپي',
  'collapse': 'شکاف کړئ',
  'expand': 'پراخ کړئ',
  // د جګړې لاره څخه تښتیدل
  'quitBattlefront': 'د جګړې لاره څخه تښتیدل',
  'quitBattlefrontTooltip': 'د لېږد جګړې لاره څخه تښتیدل',
  'quitBattlefrontTitle': 'د جګړې لاره څخه تښتیدل',
  'quitBattlefrontContent':
      'ایا تاسو chắc یې د \'{name}\' جګړې لاره څخه تښتیدل؟ ستاسو محلي پرمختګ له مینځه ویخته به شي.',

  // د ډاونلوډ پاڼه
  'downloadClient': 'د کلاینټ ډاونلوډ کړئ',
  'browser': 'براوزر',
  'browserDesc': 'مستقیم په براوزر کې لوبه وکړئ، ډاونلوډ ته اړتیا نلري',
  'windowsDesc': 'د Windows 10 او د هغه څخه لوړ سیسټمونو لپاره مناسب',
  'macosDesc': 'د macOS 10.15 او د هغه څخه لوړ سیسټمونو لپاره مناسب',
  'android': 'اینډروید سیسټم',
  'androidDesc': 'د Android 8.0 او د هغه څخه لوړ سیسټمونو لپاره مناسب',
  'iosDesc': 'د iOS 14.0 او د هغه څخه لوړ سیسټمونو لپاره مناسب',
  'linkAddress': 'د لنک آدرس',
  'downloadLink': 'د ډاونلوډ لنک',
  'qrCode': 'کیو آر کوډ',
  'scanToDownload': 'د ډاونلوډ لپاره موبایل استعمال کړئ ترڅو اسکین کړئ',
  'copy': 'کاپي کړئ',
  'copiedToClipboard': 'په کلیپ بورډ کې کاپي شوی',
  'openLink': 'لنک خلاص کړئ',
  'cannotOpenLink': 'لنک نشي کیدی خلاص کړئ',
  // د لوبې معرفی
  'gameIntroduction':
      '1. "د نووکارانو لپاره لاسرسي" له 15 ماین څخه پیل شي، تر 99 ماین پورې لوړیږي;\n2. "نوې جګړه لاره" له 81 ماین څخه پیل شي، هر لیول کې د ماینونو شمیر یو څه زیادیدل به شي، لومړی حد نشته.\n3. په انټرنیټ حالت کې "کامل شوی" جګړې لارې په خودکار ډول په کلائوډ کې شریکېږي، ترڅو نورو لپاره زده کړې لپاره.',
};
