// Romanian（罗马尼亚语）
/// Romanian language strings for the DMine application
const Map<String, String> stringsRo = {
  'appLabel': 'Minesweeper de top',
  'appTitle': 'DMine - Minesweeper de top',
  'settings': 'Setări',
  'gameSettings': 'Setările jocului',
  'showTimer': 'Afișează cronometrul',
  'showTimerDesc': 'Afișează cronometrul jocului pe ecranul de joc',
  'showActionCounter': 'Afișează contorul de acțiuni',
  'showActionCounterDesc': 'Afișează numărul de acțiuni pe ecranul de joc',
  'autoAdjustBoardWidth': 'Ajustează automat lățimea tablei',
  'autoAdjustBoardWidthDesc':
      'Ajustează automat lățimea tablei în funcție de dimensiunea ecranului',
  'resetToDefaults': 'Restabilește setările implicite',
  'resetToDefaultsDesc': 'Restabilește toate setările la valorile implicite',
  'aboutDMine': 'Despre DMine',
  'version': 'Versiune',
  'close': 'Închide',
  'manualBoardWidth': 'Setează manual lățimea tablei',
  'currentWidth': 'Actual',
  'range': 'Interval',
  'widthSliderHint':
      'Sugestie: în timpul glisării slider-ului, poți vedea schimbarea lățimii tablei în timp real',
  'gameRecords': 'Înregistrările jocului',
  'selectMapToViewRecords': 'Selectează o hartă pentru a vedea înregistrările',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Lista înregistrărilor jocului',
  'pleaseSelectMapFirst': 'Selectează mai întâi o hartă',
  'noGameRecords': 'Fără înregistrări de joc',
  'miningMethodFlag': 'Marchează cu steag',
  'miningMethodBlind': 'Explorare orbă',
  'statusPlaying': '▶️ În curs...',
  'statusWin': '🎉 Victorie',
  'statusLose': '💥 Înfrângere',
  'actionsCount': 'Număr de acțiuni',
  'miningMethod': 'Mod de joc',
  'duration': 'Durată',
  'seconds': 'secunde',
  'startTime': 'Ora de început',
  'endTime': 'Ora de sfârșit',
  'pauseTime': 'Timp de pauză',
  'unlock': 'Deblochează',
  'lock': 'Blochează',
  'delete': 'Șterge',
  'languageSetting': 'Setări de limbă',
  'currentLanguage': 'Actual',
  'systemLanguage': 'Limba sistemului',
  'chinese': 'Chineză',
  'english': 'Engleză',
  'language': 'Limbă',
  // Home page
  'newbie': 'Începător',
  'gameIntro': 'Prezentarea jocului',
  'newBattle': 'Front nou',
  'continueChallenge': 'Continuă provocarea',
  'error': 'Eroare',
  'initializationFailed': 'Inițializarea a eșuat',
  // Game page
  'congratulations': 'Felicitări, ai trecut nivelul!',
  'gameOver': 'Joc terminat',
  'timeUsed': 'Timp',
  'actionCount': 'Acțiuni',
  'mineCount': 'Mine',
  'nextLevel': 'Nivelul următor: Nivelul {level}',
  'newbieNextLevel': 'Nivelul următor: Începător {level}',
  'nextLevelMines': 'Mine',
  'mineIncrease': 'Creștere',
  'newbieFinish': 'Mod începător finalizat',
  'ok': 'OK',
  'continueNextLevel': 'Continuă către nivelul următor',
  'restart': 'Repornește',
  'level': 'Nivelul {level}',
  'newbieLevel': 'Începător {level}',
  'operationFailed': 'Operația a eșuat',
  // Game status texts
  'returnHome': 'Întoarce-te la acasă',
  'revealMode': 'Mod dezvăluire',
  'flagMode': 'Mod steag',
  'newMap': 'Hartă nouă (același număr de mine, nou layout)',
  'resetMap': 'Resetează harta (același layout, resetează starea)',
  'zoomOut': 'Micșorează',
  'zoomIn': 'Mărește',
  'resetZoom': 'Resetează zoom-ul',
  'previousStep': 'Pasul anterior',
  'pause': 'Pauză',
  'play': 'Joacă',
  'nextStep': 'Pasul următor',
  'clickToStart': 'Apasă pe orice căsuță pentru a începe jocul',
  'playing': 'În joc...',
  'gameWin': 'Felicitări, ai trecut nivelul!',
  'gameLose': 'Joc terminat, ai calcat pe o mină',
  'gamePaused': 'Joc pe pauză',
  'ready': 'Gata de început',
  'clickStartShort': 'Apasă pentru a începe',
  'playingShort': 'În joc',
  'winShort': 'Finalizat!',
  'loseShort': 'Înfrângere',
  'pausedShort': 'Pe pauză',
  // Counter strings
  'currentLevel': 'Nivelul actual',
  'remainingMines': 'Mine rămase',
  'gameTime': 'Timp de joc (secunde)',
  'operationCount': 'Număr de operații',
  'previousLevel': 'Nivelul anterior',
  'nextLevelShort': 'Nivelul următor',
  // Battlefront strings
  'completed': 'Finalizat',
  'inProgress': 'În curs',
  'continueGame': 'Continuă jocul',
  'replay': 'Redă',
  'creater': 'Comandant',
  'created': 'Ora începerii',
  'updated': 'Actualizat',
  // Dialog strings
  'confirm': 'Confirmă',
  'cancel': 'Anulează',
  'yes': 'Da',
  'no': 'Nu',
  'save': 'Salvează',
  'edit': 'Editează',
  'levelFormat': 'Nivelul {level}',
  'newbieLevelFormat': 'Începător {level}',
  'totalLevel': '{level}/{totalLevel} niveluri',
  'totalLevelTooltip': 'Actual: Nivelul {level} / Total {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Fără fronturi',
  'battlefrontCount': '{count} fronturi',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'Începător NV{level}',
  'minesCount': '{count} mine',
  'notStarted': 'Neînceput',
  'victory': 'Victorie',
  'defeat': 'Înfrângere',
  'gameDurationParam': 'Durată: {seconds}s',
  'actionsCountParam': 'Acțiuni: {count} ori',
  'actionsCountParamShort': '{count} ori',
  'miningMethodParam': 'Mod: {method}',
  'startTimeParam': 'Început: {time}',
  'endTimeParam': 'Sfârșit: {time}',
  'returnButton': 'Întoarce-te',
  'battlefrontDetails': 'Detalii front',
  'clickToEditName': 'Apasă pentru a edita numele',
  'clickToAddDescription': 'Apasă pentru a adăuga o descriere...',
  'noDescription': 'Fără descriere',
  // Level record strings
  'levelCount': '{count} niveluri',
  'noLevelRecords': 'Selectează un front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Șterge frontul',
  'deleteBattlefrontContent':
      'Ești sigur că vrei să ștergi frontul \'{name}\'? Această acțiune nu poate fi anulată.',
  'battlefrontLockedCannotDelete': 'Front blocat, nu poate fi șters',
  'unknownNavigationLevel': 'Nivel necunoscut',
  'noBattlefrontSelected': 'Niciun front selectat',
  'noBattlefrontToContinue': 'Nu s-a găsit niciun front de continuat',
  'synced': 'Sincronizat',
  'notSynced': 'Nesincronizat',
  'newbieBattlefrontName': 'Front începător {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Pseudonim',
  'nicknameSetting': 'Setări pseudonim',
  'nicknameDesc': 'Setează-ți pseudonimul',
  'enterNickname': 'Introdu pseudonimul',
  'nicknameSaved': 'Pseudonim salvat',
  'nicknameUpdated': 'Pseudonim actualizat',
  'nicknameRequired': 'Pseudonimul este obligatoriu',
  'nicknameTooLong': 'Pseudonimul nu poate depăși 30 de caractere',
  // Level top strings
  'levelTopCount': 'Clasament ({count})',
  'levelTopCountShort': 'Clasament ({count})',
  'retry': 'Încearcă din nou',
  'noLevelTopData': 'Fără date',
  'remoteBattlefront': 'Front la distanță',
  'participated': 'A participat',
  'notParticipated': 'Nu a participat',
  'loadMore': 'Încarcă mai mult',
  'joinBattle': 'Alătură-te bătăliei',
  'joinBattleTooltip': 'Alătură-te bătăliei \'{name}\'',
  'joinBattleConfirm': 'Ești sigur că vrei să te alături bătăliei \'{name}\'?',
  'joinBattleSuccess': 'Te-ai alăturat cu succes bătăliei \'{name}\'',
  'joinBattleErrorSelf': 'Nu te poți alătura propriului tău front',
  'replayBattlefront': 'Redă frontul',
  'replayBattlefrontTooltip': 'Redă frontul \'{name}\'',
  'getReplayBattlefrontConfirm': 'Ești sigur că vrei să redați \'{name}\'?',
  'getReplayBattlefrontFailed': 'Redarea \'{name}\' a eșuat: {error}',
  'download': 'Descarcă',
  'downloadBattlefront': 'Descarcă frontul',
  'downloadBattlefrontTooltip': 'Descarcă frontul \'{name}\'',
  'getDownloadBattlefrontConfirm': 'Ești sigur că vrei să descarci \'{name}\'?',
  'getDownloadBattlefrontSuccess': '\'{name}\' descărcat cu succes',
  'downloadMyOwnBattlefrontError': 'Poți descărca doar propriile tale fronturi',
  'getDownloadBattlefrontFailed': 'Descărcarea \'{name}\' a eșuat: {error}',
  'continueGameShort': 'Continuă bătălia',
  'replayShort': 'Redă',
  'highestLevel': 'Nivelul {level}',
  'deviceNickname': 'Dispozitiv',
  'createdTime': 'Data creării',
  'remoteBattlefrontDetail': 'Detalii front la distanță',
  'levelList': 'Lista nivelurilor',
  'fastClearTimeParam': 'Timp finalizare: {time}',
  // Detalii front la distanță
  'selectLocalBattlefrontHint':
      'Selectează un front local pentru a vedea detalii',
  'loadingRemoteDetail': 'Se încarcă detaliile frontului la distanță...',
  'noRemoteBattlefrontSelected': 'Niciun front la distanță selectat',
  'failedToLoadRemoteDetail': 'Încărcarea detaliilor a eșuat',
  'fastestRecord': 'Finalizare cea mai rapidă',
  'safestRecord': 'Finalizare cea mai sigură',
  'fastestRecordDesc': 'Cea mai rapidă (timp minim)',
  'safestRecordDesc': 'Cea mai sigură (acțiuni minime)',
  'creator': 'Creator',
  'player': 'Jucător',
  // Hărți ramificate
  'getBranchMapCount': '{count} copii',
  'collapse': 'Restrânge',
  'expand': 'Extinde',
  // Parasirea frontului
  'quitBattlefront': 'Parăsește frontul',
  'quitBattlefrontTooltip': 'Parăsește frontul la distanță',
  'quitBattlefrontTitle': 'Parăsește frontul',
  'quitBattlefrontContent':
      'Ești sigur că vrei să parăsești frontul \'{name}\'? Progresul tău local va fi șters.',
  // Introducerea jocului
  'gameIntroduction':
      '1. „Începător” începe cu 15 mine, până la 99 mine;\n2. „Front nou” începe cu 81 mine, crește la fiecare nivel, fără limită superioară.\n3. În modul online, fronturile finalizate sunt partajate automat în cloud pentru alți jucători.',
};
