// Norwegian（挪威语）
/// Norsk tekst for DMine-appen
const Map<String, String> stringsNo = {
  'appLabel': 'Minesweeper Premium',
  'appTitle': 'DMine - Minesweeper Premium',
  'settings': 'Innstillinger',
  'gameSettings': 'Spinnstillinger',
  'showTimer': 'Vis timer',
  'showTimerDesc': 'Vis spiltiden i brukergrensesnittet',
  'showActionCounter': 'Vis handlingsteller',
  'showActionCounterDesc': 'Vis antall handlinger gjort i spillet',
  'autoAdjustBoardWidth': 'Juster brettbredde automatisk',
  'showUnrevealedCounter': 'Vis teller for uåpnede felt',
  'showUnrevealedCounterDesc': 'Vis antall uåpnede felt i spillgrensesnittet',
  'showMineCounter': 'Vis mineteller',
  'showMineCounterDesc': 'Vis antall gjenværende miner i spillgrensesnittet',
  'autoAdjustBoardWidthDesc':
      'Tilpass brettbredde automatisk etter skjermstørrelse',
  'resetToDefaults': 'Tilbakestill til standard',
  'resetToDefaultsDesc':
      'Tilbakestill alle innstillinger til opprinnelige verdier',
  'aboutDMine': 'Om DMine',
  'version': 'Versjon',
  'close': 'Lukk',
  'manualBoardWidth': 'Manuell brettbredde',
  'currentWidth': 'Nåværende',
  'range': 'Område',
  'widthSliderHint': 'Tips: Dra glidebryteren for å se endringer i sanntid',
  'gameRecords': 'Spillresultater',
  'selectMapToViewRecords': 'Velg et kart for å se resultater',
  'totalRecords': 'Totalt',
  'gameRecordsTitle': 'Liste over spillresultater',
  'pleaseSelectMapFirst': 'Velg først et kart',
  'noGameRecords': 'Ingen spillresultater',
  'miningMethodFlag': 'Merke med flagg',
  'miningMethodBlind': 'Blind søking',
  'statusPlaying': '▶️ Spiller...',
  'statusWin': '🎉 Vunnet!',
  'statusLose': '💥 Tapt!',
  'actionsCount': 'Antall handlinger',
  'miningMethod': 'Mine søkemetode',
  'duration': 'Varighet',
  'seconds': 'sekunder',
  'startTime': 'Starttid',
  'endTime': 'Sluttid',
  'pauseTime': 'Pause tid',
  'unlock': 'Lås opp',
  'lock': 'Lås',
  'delete': 'Slett',
  'languageSetting': 'Språkinnstillinger',
  'currentLanguage': 'Nåværende språk',
  'systemLanguage': 'Systemspråk',
  'chinese': 'Kinesisk',
  'english': 'Engelsk',
  'language': 'Språk',
  // Home page
  'newbie': 'Nybeginner',
  'gameIntro': 'Spillintroduksjon',
  'newBattle': 'Ny front',
  'continueChallenge': 'Fortsett utfordringen',
  'error': 'Feil',
  'initializationFailed': 'Initialisering mislyktes',
  // Game page
  'congratulations': 'Gratulerer! Du fullførte nivået!',
  'gameOver': 'Spillet er over',
  'timeUsed': 'Brukt tid',
  'actionCount': 'Antall handlinger',
  'mineCount': 'Antall miner',
  'nextLevel': 'Neste nivå: Nivå {level}',
  'newbieNextLevel': 'Neste nivå: Nybeginner {level}',
  'nextLevelMines': 'Antall miner',
  'mineIncrease': 'Økning',
  'newbieFinish': 'Nybeginner ferdig',
  'ok': 'OK',
  'continueNextLevel': 'Gå til neste nivå',
  'restart': 'Start på nytt',
  'level': 'Nivå {level}',
  'newbieLevel': 'Nybeginnersnivå {level}',
  'operationFailed': 'Handling mislyktes',
  // Game status texts
  'returnHome': 'Tilbake til hjem',
  'revealMode': 'Åpne modus',
  'flagMode': 'Flaggmodus',
  'newMap': 'Nytt kart (samme antall miner)',
  'resetMap': 'Tilbakestill kart',
  'zoomOut': 'Forminske',
  'zoomIn': 'Forstørre',
  'resetZoom': 'Tilbakestill zoom',
  'previousStep': 'Forrige trinn',
  'pause': 'Pause',
  'play': 'Spill',
  'nextStep': 'Neste trinn',
  'clickToStart': 'Klikk en hvilken som helst rute for å starte',
  'playing': 'Spiller...',
  'gameWin': 'Gratulerer! Du fullførte nivået!',
  'gameLose': 'Spillet er over, du traff en mine',
  'gamePaused': 'Spill satt på pause',
  'ready': 'Klar',
  'clickStartShort': 'Klikk for å starte',
  'playingShort': 'Spiller',
  'winShort': 'Vunnet!',
  'loseShort': 'Traff en mine',
  'pausedShort': 'Pause',
  // Counter strings
  'currentLevel': 'Nåværende nivå',
  'remainingMines': 'Gjenværende miner',
  'unrevealedCells': 'Uåpnede felt',
  'gameTime': 'Spiltid (sekunder)',
  'operationCount': 'Antall handlinger',
  'previousLevel': 'Forrige nivå',
  'nextLevelShort': 'Neste nivå',
  // Battlefront strings
  'completed': 'Fullført',
  'inProgress': 'Pågår',
  'continueGame': 'Fortsett spillet',
  'replay': 'Spill på nytt',
  'creater': 'Oppretter',
  'created': 'Opprettet',
  'updated': 'Oppdatert',
  // Dialog strings
  'confirm': 'Bekreft',
  'cancel': 'Avbryt',
  'yes': 'Ja',
  'no': 'Nei',
  'save': 'Lagre',
  'edit': 'Rediger',
  'levelFormat': 'Nivå {level}',
  'newbieLevelFormat': 'Nybeginnersnivå {level}',
  'totalLevel': '{level}/{totalLevel} nivåer',
  'totalLevelTooltip': 'Nå: Nivå {level} / Totalt {totalLevel} nivåer',
  // Battlefront UI strings
  'noBattlefronts': 'Ingen fronter',
  'battlefrontCount': '{count} fronter',
  'levelPrefix': 'NIV{level}',
  'newbiePrefix': 'NYB{level}',
  'minesCount': '{count} miner',
  'notStarted': 'Ikke startet',
  'victory': 'Seier',
  'defeat': 'Nederlag',
  'gameDurationParam': 'Varighet: {seconds} sekunder',
  'actionsCountParam': 'Handlinger: {count} ganger',
  'actionsCountShort': '{count} ganger',
  'miningMethodParam': 'Metode: {method}',
  'startTimeParam': 'Start: {time}',
  'endTimeParam': 'Slutt: {time}',
  'returnButton': 'Tilbake',
  'battlefrontDetails': 'Frontdetaljer',
  'clickToEditName': 'Klikk for å redigere navn',
  'clickToAddDescription': 'Klikk for å legge til beskrivelse...',
  'noDescription': 'Ingen beskrivelse',
  // Level record strings
  'levelCount': '{count} nivåer',
  'noLevelRecords': 'Velg en front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Slett front',
  'deleteBattlefrontContent':
      'Er du sikker på at du vil slette fronten «{name}»? Denne handlingen kan ikke angres.',
  'battlefrontLockedCannotDelete': 'Fronten er låst, kan ikke slettes',
  'unknownNavigationLevel': 'Ukjent navigasjonsnivå',
  'noBattlefrontSelected': 'Ingen front valgt',
  'noBattlefrontToContinue': 'Ingen front å fortsette på',
  'synced': 'Synkronisert',
  'notSynced': 'Ikke synkronisert',
  'newbieBattlefrontName': 'Nybeginnersfront {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Kallenavn',
  'nicknameSetting': 'Kallenavninnstillinger',
  'nicknameDesc': 'Angi ditt kallenavn',
  'enterNickname': 'Skriv inn kallenavn',
  'nicknameSaved': 'Kallenavn lagret',
  'nicknameUpdated': 'Kallenavn oppdatert',
  'nicknameRequired': 'Kallenavn er påkrevd',
  'nicknameTooLong': 'Kallenavn kan ikke være lenger enn 30 tegn',
  // Level top strings
  'levelTopCount': 'Rangering ({count})',
  'levelTopCountShort': 'Rangering ({count})',
  'retry': 'Prøv igjen',
  'noLevelTopData': 'Ingen data',
  'remoteBattlefront': 'Ekstern front',
  'participated': 'Deltatt',
  'notParticipated': 'Ikke deltatt',
  'loadMore': 'Last mer',

  'joinBattle': 'Bli med i kampen',
  'joinBattleTooltip': 'Bli med i kampen «{name}»',
  'joinBattleConfirm': 'Er du sikker på at du vil delta i kampen «{name}»?',
  'joinBattleSuccess': 'Du ble med i kampen «{name}»',
  'joinBattleErrorSelf': 'Kan ikke delta i egen front',

  'replayBattlefront': 'Spill fronten på nytt',
  'replayBattlefrontTooltip': 'Spill fronten «{name}» på nytt',
  'getReplayBattlefrontConfirm':
      'Er du sikker på at du vil spille «{name}» på nytt?',
  'getReplayBattlefrontFailed': 'Kunne ikke spille «{name}» på nytt: {error}',

  'download': 'Last ned',
  'downloadBattlefront': 'Last ned front',
  'downloadBattlefrontTooltip': 'Last ned fronten «{name}»',
  'getDownloadBattlefrontConfirm':
      'Er du sikker på at du vil laste ned «{name}»?',
  'getDownloadBattlefrontSuccess': 'Fronten «{name}» ble lastet ned',
  'downloadMyOwnBattlefrontError': 'Kan kun laste ned egne fronter',
  'getDownloadBattlefrontFailed': 'Kunne ikke laste ned «{name}»: {error}',

  'continueGameShort': 'Fortsett kampen',
  'replayShort': 'På nytt',
  'highestLevel': 'Nivå {level}',
  'deviceNickname': 'Enhet',
  'createdTime': 'Opprettet tidspunkt',
  'remoteBattlefrontDetail': 'Detaljer for ekstern front',
  'levelList': 'Nivåliste',
  'fastClearTimeParam': 'Raskest tid: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Velg lokal front for å se detaljer',
  'loadingRemoteDetail': 'Laster detaljer for ekstern front...',
  'noRemoteBattlefrontSelected': 'Ingen ekstern front valgt',
  'failedToLoadRemoteDetail': 'Kunne ikke hente eksterne data',
  'fastestRecord': 'Raskest fullført',
  'safestRecord': 'Sikkerest fullført',
  'fastestRecordDesc': 'Raskest fullført (minst tid)',
  'safestRecordDesc': 'Sikkerest fullført (færrest handlinger)',
  'creator': 'Oppretter',
  'player': 'Spiller',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopier',
  'collapse': 'Skjul',
  'expand': 'Vis',
  // 退出战线
  'quitBattlefront': 'Forlat fronten',
  'quitBattlefrontTooltip': 'Forlat ekstern front',
  'quitBattlefrontTitle': 'Forlat front',
  'quitBattlefrontContent':
      'Er du sikker på at du vil forlate fronten «{name}»? Fremdrift blir slettet.',
  // 游戏介绍
  'gameIntroduction':
      '1. «Nybeginner» starter med 15 miner og kan gå opp til 99 miner.\n2. «Ny front» starter med 81 miner, hvert nivå øker antallet uten øvre grense.\n3. Med internett blir fullførte fronter automatisk lagret i skyen.',
};
