// Persian（波斯语）
/// رشته‌های زبان فارسی برای اپلیکیشن DMine
const Map<String, String> stringsFa = {
  'appLabel': 'معدن‌یابی عالی',
  'appTitle': 'DMine - معدن‌یابی عالی',
  'settings': 'تنظیمات',
  'gameSettings': 'تنظیمات بازی',
  'showTimer': 'نمایش تایمر',
  'showTimerDesc': 'نمایش تایمر بازی در رابط کاربری',
  'showActionCounter': 'نمایش شمارنده اقدامات',
  'showActionCounterDesc': 'نمایش تعداد اقدامات در رابط بازی',
  'autoAdjustBoardWidth': 'تنظیم خودکار عرض تخته',
  'autoAdjustBoardWidthDesc': 'تنظیم خودکار عرض تخته بر اساس اندازه صفحه',
  'resetToDefaults': 'بازنشانی به پیش‌فرض',
  'resetToDefaultsDesc': 'بازگرداندن تمام تنظیمات به مقادیر اولیه',
  'aboutDMine': 'درباره DMine',
  'version': 'نسخه',
  'close': 'بستن',
  'manualBoardWidth': 'تنظیم دستی عرض تخته',
  'currentWidth': 'فعلی',
  'range': 'محدوده',
  'widthSliderHint':
      'نکته: می‌توانید تغییرات عرض تخته را در حین کشیدن لغزنده به صورت زنده ببینید',
  'gameRecords': 'سوابق بازی',
  'selectMapToViewRecords': 'لطفاً یک نقشه برای مشاهده سوابق انتخاب کنید',
  'totalRecords': 'مجموع',
  'gameRecordsTitle': 'لیست سوابق بازی',
  'pleaseSelectMapFirst': 'ابتدا یک نقشه انتخاب کنید',
  'noGameRecords': 'سابقه بازی وجود ندارد',
  'miningMethodFlag': 'چسباندن پرچم',
  'miningMethodBlind': 'جستجوی کور',
  'statusPlaying': '▶️ در حال بازی...',
  'statusWin': '🎉 پیروزی',
  'statusLose': '💥 بازده',
  'actionsCount': 'تعداد اقدامات',
  'miningMethod': 'روش معدن‌یابی',
  'duration': 'مدت زمان',
  'seconds': 'ثانیه',
  'startTime': 'زمان شروع',
  'endTime': 'زمان پایان',
  'pauseTime': 'زمان توقف',
  'unlock': 'باز کردن قفل',
  'lock': 'قفل کردن',
  'delete': 'حذف',
  'languageSetting': 'تنظیم زبان',
  'currentLanguage': 'فعلی',
  'systemLanguage': 'زبان سیستم',
  'chinese': 'چینی',
  'english': 'انگلیسی',
  'language': 'زبان',
  // Home page
  'newbie': 'مقدماتی',
  'newBattle': 'جبهه جدید',
  'continueChallenge': 'ادامه چالش',
  'error': 'خطا',
  'initializationFailed': 'مشکل در شروع',
  // Game page
  'congratulations': 'تبریک! مرحله را پاس کردید!',
  'gameOver': 'بازی تمام شد',
  'timeUsed': 'زمان صرف شده',
  'actionCount': 'تعداد اقدامات',
  'mineCount': 'تعداد مین',
  'nextLevel': 'مرحله بعدی: مرحله {level}',
  'newbieNextLevel': 'مرحله بعدی: مقدماتی {level}',
  'nextLevelMines': 'تعداد مین',
  'mineIncrease': 'افزایش',
  'newbieFinish': 'بخش مقدماتی کامل شد',
  'ok': 'تأیید',
  'continueNextLevel': 'ادامه به مرحله بعدی',
  'restart': 'راه‌اندازی مجدد',
  'level': 'مرحله {level}',
  'newbieLevel': 'مرحله مقدماتی {level}',
  'operationFailed': 'عملیات ناموفق',
  // Game status texts
  'returnHome': 'بازگشت به خانه',
  'revealMode': 'حالت آشکار کردن',
  'flagMode': 'حالت پرچم',
  'newMap': 'نقشه جدید (تعداد مین بدون تغییر، نقشه جدید)',
  'resetMap': 'بارگذاری مجدد نقشه (نقشه یکسان، وضعیت بازنشانی)',
  'zoomOut': 'کوچک کردن',
  'zoomIn': 'بزرگ کردن',
  'resetZoom': 'بازنشانی بزرگنمایی',
  'previousStep': 'گام قبلی',
  'pause': 'توقف',
  'play': 'بازی',
  'nextStep': 'گام بعدی',
  'clickToStart': 'برای شروع روی هر خانه‌ای کلیک کنید',
  'playing': 'در حال بازی...',
  'gameWin': 'تبریک! مرحله را پاس کردید!',
  'gameLose': 'بازی تمام شد، به مین برخوردید',
  'gamePaused': 'بازی متوقف شده',
  'ready': 'آماده',
  'clickStartShort': 'کلیک برای شروع',
  'playingShort': 'در حال بازی',
  'winShort': 'پاس شد!',
  'loseShort': 'به مین خوردید',
  'pausedShort': 'متوقف',
  // Counter strings
  'currentLevel': 'مرحله فعلی',
  'remainingMines': 'مین باقیمانده',
  'gameTime': 'زمان بازی (ثانیه)',
  'operationCount': 'تعداد اقدامات',
  'previousLevel': 'مرحله قبلی',
  'nextLevelShort': 'مرحله بعدی',
  // Battlefront strings
  'completed': 'تکمیل شده',
  'inProgress': 'در حال انجام',
  'continueGame': 'ادامه بازی',
  'replay': 'پخش مجدد',
  'creater': 'فرمانده',
  'created': 'زمان شروع نبرد',
  'updated': 'به‌روزشده',
  // Dialog strings
  'confirm': 'تأیید',
  'cancel': 'لغو',
  'yes': 'بله',
  'no': 'خیر',
  'save': 'ذخیره',
  'edit': 'ویرایش',
  'levelFormat': 'مرحله {level}',
  'newbieLevelFormat': 'مرحله مقدماتی {level}',
  'totalLevel': '{level}/{totalLevel} مرحله',
  'totalLevelTooltip': 'فعلی: مرحله {level} / کل {totalLevel} مرحله',
  // Battlefront UI strings
  'noBattlefronts': 'جبهه‌ای وجود ندارد',
  'battlefrontCount': '{count} جبهه',
  'levelPrefix': 'مرحله {level}',
  'newbieLevelPrefix': 'مقدماتی {level}',
  'minesCount': '{count} مین',
  'notStarted': 'شروع نشده',
  'victory': 'پیروزی',
  'defeat': 'بازده',
  'gameDurationParam': 'مدت زمان: {seconds} ثانیه',
  'actionsCountParam': 'اقدامات: {count} بار',
  'actionsCountParamShort': '{count} بار',
  'miningMethodParam': 'روش: {method}',
  'startTimeParam': 'زمان شروع: {time}',
  'endTimeParam': 'زمان پایان: {time}',
  'returnButton': 'بازگشت',
  'battlefrontDetails': 'جزئیات جبهه',
  'clickToEditName': 'کلیک برای تغییر نام',
  'clickToAddDescription': 'کلیک برای افزودن توضیحات...',
  'noDescription': 'بدون توضیحات',
  // Level record strings
  'levelCount': '{count} مرحله',
  'noLevelRecords': 'جبهه را انتخاب کنید',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'حذف جبهه',
  'deleteBattlefrontContent':
      'آیا مطمئن هستید که می‌خواهید جبهه "{name}" را حذف کنید؟ این عمل قابل بازگشت نیست.',
  'battlefrontLockedCannotDelete': 'جبهه قفل شده، قابل حذف نیست',
  'unknownNavigationLevel': 'مرحله ناوبری نامشخص',
  'noBattlefrontSelected': 'هیچ جبهه‌ای انتخاب نشده',
  'noBattlefrontToContinue': 'جبهه‌ای برای ادامه یافت نشد',
  'synced': 'همگام شده',
  'notSynced': 'همگام نشده',
  'newbieBattlefrontName': 'جبهه مقدماتی {number}',
  'battlefrontName': 'جبهه {number}',
  'nickname': 'نام مستعار',
  'nicknameSetting': 'تنظیم نام مستعار',
  'nicknameDesc': 'نام مستعار خود را تنظیم کنید',
  'enterNickname': 'نام مستعار را وارد کنید',
  'nicknameSaved': 'نام مستعار ذخیره شد',
  'nicknameUpdated': 'نام مستعار به‌روزشد',
  'nicknameRequired': 'نام مستعار الزامی است',
  'nicknameTooLong': 'نام مستعار نباید بیشتر از ۳۰ کاراکتر باشد',
  // Level top strings
  'levelTopCount': 'رتبه‌بندی ({count})',
  'levelTopCountShort': 'رتبه ({count})',
  'retry': 'تلاش مجدد',
  'noLevelTopData': 'داده‌ای وجود ندارد',
  'remoteBattlefront': 'جبهه دور',
  'participated': 'شرکت کرده',
  'notParticipated': 'شرکت نکرده',
  'loadMore': 'بارگذاری بیشتر',

  'joinBattle': 'پیوستن به نبرد',
  'joinBattleTooltip': 'پیوستن به نبرد "{name}"',
  'joinBattleConfirm':
      'آیا مطمئن هستید که می‌خواهید به نبرد "{name}" بپیوندید؟',
  'joinBattleSuccess': 'با موفقیت به نبرد "{name}" پیوستید',
  'joinBattleErrorSelf': 'نمی‌توانید به جبهه خودتان بپیوندید',

  'replayBattlefront': 'پخش مجدد جبهه',
  'replayBattlefrontTooltip': 'پخش مجدد جبهه "{name}"',
  'getReplayBattlefrontConfirm':
      'آیا مطمئن هستید که می‌خواهید "{name}" را مجدد پخش کنید؟',
  'getReplayBattlefrontFailed': 'پخش مجدد "{name}" ناموفق: {error}',

  'download': 'دانلود',
  'downloadBattlefront': 'دانلود جبهه',
  'downloadBattlefrontTooltip': 'دانلود جبهه "{name}"',
  'getDownloadBattlefrontConfirm':
      'آیا مطمئن هستید که می‌خواهید "{name}" را دانلود کنید؟',
  'getDownloadBattlefrontSuccess': 'جبهه "{name}" با موفقیت دانلود شد',
  'downloadMyOwnBattlefrontError':
      'فقط می‌توانید جبهه‌های خودتان را دانلود کنید',
  'getDownloadBattlefrontFailed': 'دانلود "{name}" ناموفق: {error}',

  'continueGameShort': 'ادامه نبرد',
  'replayShort': 'پخش مجدد',
  'highestLevel': 'مرحله {level}',
  'deviceNickname': 'دستگاه',
  'createdTime': 'زمان ایجاد',
  'remoteBattlefrontDetail': 'جزئیات جبهه دور',
  'levelList': 'لیست مراحل',
  'fastClearTimeParam': 'زمان پاس: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'یک جبهه محلی را برای مشاهده جزئیات انتخاب کنید',
  'loadingRemoteDetail': 'در حال بارگذاری جزئیات جبهه دور...',
  'noRemoteBattlefrontSelected': 'جبهه دور انتخاب نشده',
  'failedToLoadRemoteDetail': 'بارگذاری جزئیات ناموفق',
  'fastestRecord': 'سریع‌ترین پاس',
  'safestRecord': 'ایمن‌ترین پاس',
  'fastestRecordDesc': 'سریع‌ترین پاس (کمترین زمان)',
  'safestRecordDesc': 'ایمن‌ترین پاس (کمترین اقدامات)',
  'creator': 'سازنده',
  'player': 'بازیکن',
  // 分支地图字符串
  'getBranchMapCount': '{count} کپی',
  'collapse': 'جمع کردن',
  'expand': 'باز کردن',
  // 退出战线
  'quitBattlefront': 'خروج از جبهه',
  'quitBattlefrontTooltip': 'خروج از جبهه دور',
  'quitBattlefrontTitle': 'خروج از جبهه',
  'quitBattlefrontContent':
      'آیا مطمئن هستید که می‌خواهید از جبهه "{name}" خارج شوید؟ پیشرفت محلی شما حذف خواهد شد.',

  // 下载页面
  'downloadClient': 'دانلود کلاینت',
  'browser': 'مرورگر',
  'browserDesc': 'مستقیماً در مرورگر بازی کنید، بدون نیاز به دانلود',
  'windowsDesc': 'برای ویندوز ۱۰ و بالاتر',
  'macosDesc': 'برای macOS ۱۰.۱۵ و بالاتر',
  'android': 'اندروید',
  'androidDesc': 'برای اندروید ۸.۰ و بالاتر',
  'iosDesc': 'برای iOS ۱۴.۰ و بالاتر',
  'linkAddress': 'آدرس لینک',
  'downloadLink': 'لینک دانلود',
  'qrCode': 'کد QR',
  'scanToDownload': 'با گوشی اسکن کنید تا دانلود شود',
  'copy': 'کپی',
  'copiedToClipboard': 'در کلیپ‌بورد کپی شد',
  'openLink': 'باز کردن لینک',
  'cannotOpenLink': 'قابل باز کردن نیست',
  // 游戏介绍
  'gameIntroduction':
      '۱. «مقدماتی» با ۱۵ مین شروع می‌شود و حداکثر تا ۹۹ مین ادامه دارد.\n۲. «جبهه جدید» با ۸۱ مین شروع می‌شود و در هر مرحله مین‌های بیشتری اضافه می‌شود.\n۳. در صورت اتصال اینترنت، جبهه‌های «تکمیل شده» به صورت خودکار در ابر به اشتراک گذاشته می‌شوند.',
};
