// Hindi（印地语）
/// DMine एप्लिकेशन के लिए हिंदी स्ट्रिंग
const Map<String, String> stringsHi = {
  'appTitle': 'DMine - बेहतरीन माइनस्वीपर',
  'settings': 'सेटिंग्स',
  'gameSettings': 'खेल सेटिंग्स',
  'showTimer': 'टाइमर दिखाएं',
  'showTimerDesc': 'इंटरफेस में खेल का टाइमर दिखाएं',
  'showActionCounter': 'कार्य काउंटर दिखाएं',
  'showActionCounterDesc': 'खेल इंटरफेस में क्रियाओं की संख्या दिखाएं',
  'autoAdjustBoardWidth': 'बोर्ड की चौड़ाई स्वचालित रूप से समायोजित करें',
  'autoAdjustBoardWidthDesc':
      'स्क्रीन के आकार के अनुसार बोर्ड की चौड़ाई स्वचालित रूप से समायोजित करें',
  'resetToDefaults': 'डिफ़ॉल्ट पर रीसेट करें',
  'resetToDefaultsDesc': 'सभी सेटिंग्स को मूल मानों पर रीसेट करें',
  'aboutDMine': 'DMine के बारे में',
  'version': 'संस्करण',
  'close': 'बंद करें',
  'manualBoardWidth': 'बोर्ड की चौड़ाई मैन्युअल रूप से सेट करें',
  'currentWidth': 'वर्तमान',
  'range': 'सीमा',
  'widthSliderHint':
      'सुझाव: आप स्लाइडर को घुमाते समय वास्तविक समय में बोर्ड की चौड़ाई में परिवर्तन देख सकते हैं',
  'gameRecords': 'खेल रिकॉर्ड',
  'selectMapToViewRecords': 'रिकॉर्ड देखने के लिए मैप चुनें',
  'totalRecords': 'कुल',
  'gameRecordsTitle': 'खेल रिकॉर्ड की सूची',
  'pleaseSelectMapFirst': 'पहले एक मैप चुनें',
  'noGameRecords': 'कोई खेल रिकॉर्ड नहीं',
  'miningMethodFlag': 'झंडा लगाएं',
  'miningMethodBlind': 'अंधा खोज',
  'statusPlaying': '▶️ खेल रहे हैं...',
  'statusWin': '🎉 जीत',
  'statusLose': '💥 हार',
  'actionsCount': 'क्रियाओं की संख्या',
  'miningMethod': 'माइन खोजने की विधि',
  'duration': 'अवधि',
  'seconds': 'सेकंड',
  'startTime': 'शुरुआत का समय',
  'endTime': 'समाप्ति का समय',
  'pauseTime': 'विराम का समय',
  'unlock': 'अनलॉक करें',
  'lock': 'लॉक करें',
  'delete': 'हटाएं',
  'languageSetting': 'भाषा सेटिंग',
  'currentLanguage': 'वर्तमान',
  'systemLanguage': 'सिस्टम भाषा',
  'chinese': 'चीनी',
  'english': 'अंग्रेजी',
  'language': 'भाषा',
  // Home page
  'newbie': 'नौसिखिया',
  'newBattle': 'नया मोर्चा',
  'continueChallenge': 'चुनौती जारी रखें',
  'error': 'त्रुटि',
  'initializationFailed': 'आरंभ करने में विफल',
  // Game page
  'congratulations': 'बधाई हो, आपने लेवल पार कर लिया है!',
  'gameOver': 'खेल खत्म',
  'timeUsed': 'लगा समय',
  'actionCount': 'क्रियाओं की संख्या',
  'mineCount': 'माइनों की संख्या',
  'nextLevel': 'अगला लेवल: लेवल {level}',
  'newbieNextLevel': 'अगला लेवल: नौसिखिया {level}',
  'nextLevelMines': 'माइनों की संख्या',
  'mineIncrease': 'वृद्धि',
  'newbieFinish': 'नौसिखिया ट्यूटोरियल पूर्ण',
  'ok': 'ठीक है',
  'continueNextLevel': 'अगले लेवल पर जाएं',
  'restart': 'फिर से शुरू करें',
  'level': 'लेवल {level}',
  'newbieLevel': 'नौसिखिया लेवल {level}',
  'operationFailed': 'कार्रवाई विफल',
  // Game status texts
  'returnHome': 'होम पर वापस जाएं',
  'revealMode': 'खोलने का मोड',
  'flagMode': 'झंडा मोड',
  'newMap': 'नया मैप (समान माइन संख्या, नया मैप बनाएं)',
  'resetMap': 'मैप फिर से लोड करें (समान मैप, स्थिति रीसेट करें)',
  'zoomOut': 'ज़ूम आउट',
  'zoomIn': 'ज़ूम इन',
  'resetZoom': 'ज़ूम रीसेट करें',
  'previousStep': 'पिछला कदम',
  'pause': 'रोकें',
  'play': 'खेलें',
  'nextStep': 'अगला कदम',
  'clickToStart': 'खेल शुरू करने के लिए किसी भी बॉक्स पर क्लिक करें',
  'playing': 'खेल रहे हैं...',
  'gameWin': 'बधाई हो, आपने लेवल पार कर लिया है!',
  'gameLose': 'खेल खत्म, आपने माइन छू ली है',
  'gamePaused': 'खेल रोका हुआ है',
  'ready': 'तैयार',
  'clickStartShort': 'शुरू करने के लिए क्लिक करें',
  'playingShort': 'चालू है',
  'winShort': 'पूरा हुआ!',
  'loseShort': 'माइन लग गई',
  'pausedShort': 'रोका हुआ',
  // Counter strings
  'currentLevel': 'वर्तमान लेवल',
  'remainingMines': 'बाकी माइन',
  'gameTime': 'खेल का समय (सेकंड)',
  'operationCount': 'कार्रवाइयों की संख्या',
  'previousLevel': 'पिछला लेवल',
  'nextLevelShort': 'अगला लेवल',
  // Battlefront strings
  'completed': 'पूर्ण हुआ',
  'inProgress': 'चालू है',
  'continueGame': 'खेल जारी रखें',
  'replay': 'फिर से खेलें',
  'creater': 'कमांडर',
  'created': 'लड़ाई शुरू होने का समय',
  'updated': 'अपडेट किया गया',
  // Dialog strings
  'confirm': 'पुष्टि करें',
  'cancel': 'रद्द करें',
  'yes': 'हां',
  'no': 'नहीं',
  'save': 'सहेजें',
  'edit': 'संपादित करें',
  'levelFormat': 'लेवल {level}',
  'newbieLevelFormat': 'नौसिखिया लेवल {level}',
  'totalLevel': '{level}/{totalLevel} लेवल',
  'totalLevelTooltip': 'वर्तमान: लेवल {level} / कुल {totalLevel} लेवल',
  // Battlefront UI strings
  'noBattlefronts': 'कोई मोर्चा नहीं',
  'battlefrontCount': '{count} मोर्चे',
  'levelPrefix': 'लेवल {level}',
  'newbieLevelPrefix': 'नौसिखिया {level}',
  'minesCount': '{count} माइन',
  'notStarted': 'शुरू नहीं हुआ',
  'victory': 'जीत',
  'defeat': 'हार',
  'gameDurationParam': 'अवधि: {seconds} सेकंड',
  'actionsCountParam': 'क्रियाएं: {count} बार',
  'actionsCountParamShort': '{count} बार',
  'miningMethodParam': 'विधि: {method}',
  'startTimeParam': 'शुरुआत समय: {time}',
  'endTimeParam': 'समाप्ति समय: {time}',
  'returnButton': 'वापस',
  'battlefrontDetails': 'मोर्चे का विवरण',
  'clickToEditName': 'नाम बदलने के लिए क्लिक करें',
  'clickToAddDescription': 'विवरण जोड़ने के लिए क्लिक करें...',
  'noDescription': 'कोई विवरण नहीं',
  // Level record strings
  'levelCount': '{count} लेवल',
  'noLevelRecords': 'मोर्चा चुनें',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'मोर्चा हटाएं',
  'deleteBattlefrontContent':
      'क्या आप वाकई "{name}" मोर्चा हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।',
  'battlefrontLockedCannotDelete': 'मोर्चा लॉक है, हटाया नहीं जा सकता',
  'unknownNavigationLevel': 'अज्ञात नेविगेशन लेवल',
  'noBattlefrontSelected': 'कोई मोर्चा चुना नहीं गया',
  'noBattlefrontToContinue': 'जारी रखने के लिए कोई मोर्चा नहीं',
  'synced': 'सिंक्रोनाइज्ड',
  'notSynced': 'सिंक्रोनाइज्ड नहीं',
  'newbieBattlefrontName': 'नौसिखिया मोर्चा {number}',
  'battlefrontName': 'मोर्चा {number}',
  'nickname': 'उपनाम',
  'nicknameSetting': 'उपनाम सेटिंग',
  'nicknameDesc': 'अपना उपनाम सेट करें',
  'enterNickname': 'उपनाम डालें',
  'nicknameSaved': 'उपनाम सहेजा गया',
  'nicknameUpdated': 'उपनाम अपडेट किया गया',
  'nicknameRequired': 'उपनाम आवश्यक है',
  'nicknameTooLong': 'उपनाम 30 अक्षरों से ज्यादा नहीं हो सकता',
  // Level top strings
  'levelTopCount': 'रैंकिंग ({count})',
  'levelTopCountShort': 'रैंकिंग ({count})',
  'retry': 'फिर से कोशिश करें',
  'noLevelTopData': 'कोई डेटा नहीं',
  'remoteBattlefront': 'दूरस्थ मोर्चा',
  'participated': 'हिस्सा लिया',
  'notParticipated': 'हिस्सा नहीं लिया',
  'loadMore': 'और लोड करें',

  'joinBattle': 'लड़ाई में शामिल हों',
  'joinBattleTooltip': '"{name}" लड़ाई में शामिल हों',
  'joinBattleConfirm': 'क्या आप वाकई "{name}" लड़ाई में शामिल होना चाहते हैं?',
  'joinBattleSuccess': 'आप "{name}" लड़ाई में सफलतापूर्वक शामिल हो गए',
  'joinBattleErrorSelf': 'आप अपने खुद के मोर्चे में शामिल नहीं हो सकते',

  'replayBattlefront': 'मोर्चा फिर से खेलें',
  'replayBattlefrontTooltip': '"{name}" मोर्चा फिर से खेलें',
  'getReplayBattlefrontConfirm':
      'क्या आप वाकई "{name}" फिर से खेलना चाहते हैं?',
  'getReplayBattlefrontFailed': '"{name}" को फिर से खेलने में विफल: {error}',

  'download': 'डाउनलोड करें',
  'downloadBattlefront': 'मोर्चा डाउनलोड करें',
  'downloadBattlefrontTooltip': '"{name}" मोर्चा डाउनलोड करें',
  'getDownloadBattlefrontConfirm':
      'क्या आप वाकई "{name}" डाउनलोड करना चाहते हैं?',
  'getDownloadBattlefrontSuccess': 'मोर्चा "{name}" सफलतापूर्वक डाउनलोड हो गया',
  'downloadMyOwnBattlefrontError': 'आप केवल अपने मोर्चे ही डाउनलोड कर सकते हैं',
  'getDownloadBattlefrontFailed': '"{name}" डाउनलोड करने में विफल: {error}',

  'continueGameShort': 'लड़ाई जारी रखें',
  'replayShort': 'फिर से खेलें',
  'highestLevel': 'लेवल {level}',
  'deviceNickname': 'डिवाइस',
  'createdTime': 'बनाने का समय',
  'remoteBattlefrontDetail': 'दूरस्थ मोर्चे का विवरण',
  'levelList': 'लेवल सूची',
  'fastClearTimeParam': 'पूर्ण होने का समय: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'विवरण देखने के लिए स्थानीय मोर्चा चुनें',
  'loadingRemoteDetail': 'दूरस्थ मोर्चे का विवरण लोड हो रहा है...',
  'noRemoteBattlefrontSelected': 'कोई दूरस्थ मोर्चा चुना नहीं गया',
  'failedToLoadRemoteDetail': 'दूरस्थ विवरण लोड करने में विफल',
  'fastestRecord': 'सबसे तेज पूर्ण',
  'safestRecord': 'सबसे सुरक्षित पूर्ण',
  'fastestRecordDesc': 'सबसे तेज पूर्ण (कम समय)',
  'safestRecordDesc': 'सबसे सुरक्षित पूर्ण (कम क्रियाएं)',
  'creator': 'निर्माता',
  'player': 'खिलाड़ी',
  // 分支地图字符串
  'getBranchMapCount': '{count} कॉपियां',
  'collapse': 'संकुचित करें',
  'expand': 'विस्तृत करें',
  // 退出战线
  'quitBattlefront': 'मोर्चा छोड़ें',
  'quitBattlefrontTooltip': 'दूरस्थ मोर्चा छोड़ें',
  'quitBattlefrontTitle': 'मोर्चा छोड़ें',
  'quitBattlefrontContent':
      'क्या आप वाकई "{name}" मोर्चा छोड़ना चाहते हैं? आपका स्थानीय प्रगति हटा दी जाएगी।',

  // 下载页面
  'downloadClient': 'क्लाइंट डाउनलोड करें',
  'browser': 'ब्राउजर',
  'browserDesc': 'बिना डाउनलोड किए सीधे ब्राउजर में खेलें',
  'windowsDesc': 'Windows 10 और बाद के संस्करणों के लिए',
  'macosDesc': 'macOS 10.15 और बाद के संस्करणों के लिए',
  'android': 'Android',
  'androidDesc': 'Android 8.0 और बाद के संस्करणों के लिए',
  'iosDesc': 'iOS 14.0 और बाद के संस्करणों के लिए',
  'linkAddress': 'लिंक पता',
  'downloadLink': 'डाउनलोड लिंक',
  'qrCode': 'क्यूआर कोड',
  'scanToDownload': 'डाउनलोड करने के लिए फोन से स्कैन करें',
  'copy': 'कॉपी करें',
  'copiedToClipboard': 'क्लिपबोर्ड पर कॉपी किया गया',
  'openLink': 'लिंक खोलें',
  'cannotOpenLink': 'लिंक नहीं खोला जा सकता',
  // 游戏介绍
  'gameIntroduction':
      '1. "नौसिखिया" 15 माइन के साथ शुरू होता है, 99 माइन तक जा सकता है;\n2. "नया मोर्चा" 81 माइन के साथ शुरू होता है, हर लेवल में माइन बढ़ती हैं, कोई ऊपरी सीमा नहीं।\n3. इंटरनेट कनेक्शन के साथ, "पूर्ण" मोर्चे स्वचालित रूप से क्लाउड में दूसरों के लिए साझा किए जाते हैं।',
};
