// Thai（泰语）
/// Thai language strings for the DMine application
const Map<String, String> stringsTh = {
  'appLabel': 'ไมน์สวีปเปอร์ชั้นสูง',
  'appTitle': 'DMine - ไมน์สวีปเปอร์ชั้นสูง',
  'settings': 'การตั้งค่า',
  'gameSettings': 'ตั้งค่าเกม',
  'showTimer': 'แสดงตัวจับเวลา',
  'showTimerDesc': 'แสดงตัวจับเวลาเกมบนหน้าจอเกม',
  'showActionCounter': 'แสดงตัวนับจำนวนการกระทำ',
  'showActionCounterDesc': 'แสดงจำนวนครั้งการกระทำบนหน้าจอเกม',
  'autoAdjustBoardWidth': 'ปรับความกว้างของกระดานอัตโนมัติ',
  'showUnrevealedCounter': 'แสดงตัวนับช่องที่ยังไม่เปิด',
  'showUnrevealedCounterDesc': 'แสดงจำนวนช่องที่ยังไม่เปิดบนหน้าจอเกม',
  'showMineCounter': 'แสดงตัวนับระเบิด',
  'showMineCounterDesc': 'แสดงจำนวนระเบิดที่เหลือบนหน้าจอเกม',
  'autoAdjustBoardWidthDesc': 'ปรับความกว้างของกระดานตามขนาดหน้าจอโดยอัตโนมัติ',
  'resetToDefaults': 'รีเซ็ตเป็นค่าเริ่มต้น',
  'resetToDefaultsDesc': 'คืนค่าการตั้งค่าทั้งหมดเป็นค่าเริ่มต้น',
  'aboutDMine': 'เกี่ยวกับ DMine',
  'version': 'เวอร์ชัน',
  'close': 'ปิด',
  'manualBoardWidth': 'ตั้งค่าความกว้างของกระดานด้วยตนเอง',
  'currentWidth': 'ปัจจุบัน',
  'range': 'ช่วง',
  'widthSliderHint':
      'คำแนะนำ: ขณะลากตัวเลื่อนสามารถดูการเปลี่ยนแปลงความกว้างได้ทันที',
  'gameRecords': 'ประวัติการเล่นเกม',
  'selectMapToViewRecords': 'โปรดเลือกแผนที่เพื่อดูประวัติ',
  'totalRecords': 'ทั้งหมด',
  'gameRecordsTitle': 'รายการประวัติการเล่นเกม',
  'pleaseSelectMapFirst': 'โปรดเลือกแผนที่ก่อน',
  'noGameRecords': 'ไม่มีประวัติการเล่นเกม',
  'miningMethodFlag': 'ใส่ธง',
  'miningMethodBlind': 'กวาดลับ',
  'statusPlaying': '▶️ กำลังเล่น...',
  'statusWin': '🎉 ชนะ',
  'statusLose': '💥 แพ้',
  'actionsCount': 'จำนวนการกระทำ',
  'miningMethod': 'วิธีการเล่น',
  'duration': 'ระยะเวลา',
  'seconds': 'วินาที',
  'startTime': 'เวลาเริ่ม',
  'endTime': 'เวลาจบ',
  'pauseTime': 'เวลาพัก',
  'unlock': 'ปลดล็อก',
  'lock': 'ล็อก',
  'delete': 'ลบ',
  'languageSetting': 'ตั้งค่าภาษา',
  'currentLanguage': 'ปัจจุบัน',
  'systemLanguage': 'ภาษาของระบบ',
  'chinese': 'จีน',
  'english': 'อังกฤษ',
  'language': 'ภาษา',
  // Home page
  'newbie': 'มือใหม่',
  'gameIntro': 'แนะนำเกม',
  'newBattle': 'แนวรบใหม่',
  'continueChallenge': 'ดำเนินการต่อ',
  'error': 'ข้อผิดพลาด',
  'initializationFailed': 'การเริ่มต้นล้มเหลว',
  // Game page
  'congratulations': 'ยินดีด้วย! ผ่านด่านเรียบร้อย',
  'gameOver': 'จบเกม',
  'timeUsed': 'ใช้เวลา',
  'actionCount': 'จำนวนการกระทำ',
  'mineCount': 'จำนวนระเบิด',
  'nextLevel': 'ด่านต่อไป: ด่านที่ {level}',
  'newbieNextLevel': 'ด่านต่อไป: มือใหม่ {level}',
  'nextLevelMines': 'จำนวนระเบิด',
  'mineIncrease': 'เพิ่มจำนวน',
  'newbieFinish': 'ส่วนมือใหม่เสร็จสิ้น',
  'ok': 'ตกลง',
  'continueNextLevel': 'ดำเนินการต่อไปยังด่านถัดไป',
  'restart': 'เริ่มใหม่',
  'level': 'ด่านที่ {level}',
  'newbieLevel': 'มือใหม่ {level}',
  'operationFailed': 'การดำเนินการล้มเหลว',
  // Game status texts
  'returnHome': 'กลับหน้าหลัก',
  'revealMode': 'โหมดเปิดเผย',
  'flagMode': 'โหมดธง',
  'newMap': 'แผนที่ใหม่ (จำนวนระเบิดเท่าเดิม แผนผังใหม่)',
  'resetMap': 'รีเซ็ตแผนที่ (แผนผังเดิม รีเซ็ตสถานะ)',
  'zoomOut': 'ย่อขนาด',
  'zoomIn': 'ขยายขนาด',
  'resetZoom': 'คืนค่าขนาดเดิม',
  'previousStep': 'ขั้นตอนก่อนหน้า',
  'pause': 'หยุดชั่วคราว',
  'play': 'เล่น',
  'nextStep': 'ขั้นตอนต่อไป',
  'clickToStart': 'คลิกช่องใดก็ได้เพื่อเริ่มเกม',
  'playing': 'กำลังเล่น...',
  'gameWin': 'ยินดีด้วย! ผ่านด่านเรียบร้อย',
  'gameLose': 'จบเกม คุณกดปะทะระเบิด',
  'gamePaused': 'เกมหยุดชั่วคราว',
  'ready': 'พร้อมเริ่ม',
  'clickStartShort': 'คลิกเพื่อเริ่ม',
  'playingShort': 'กำลังเล่น',
  'winShort': 'ผ่าน!',
  'loseShort': 'แพ้',
  'pausedShort': 'หยุดชั่วคราว',
  // Counter strings
  'currentLevel': 'ด่านปัจจุบัน',
  'remainingMines': 'ระเบิดที่เหลือ',
  'unrevealedCells': 'จำนวนช่องที่ยังไม่เปิด',
  'gameTime': 'เวลาเล่นเกม (วินาที)',
  'operationCount': 'จำนวนการดำเนินการ',
  'previousLevel': 'ด่านก่อนหน้า',
  'nextLevelShort': 'ด่านต่อไป',
  // Battlefront strings
  'completed': 'เสร็จสิ้น',
  'inProgress': 'กำลังดำเนินการ',
  'continueGame': 'เล่นต่อ',
  'replay': 'เล่นซ้ำ',
  'creater': 'ผู้สร้าง',
  'created': 'เวลาสร้าง',
  'updated': 'อัปเดต',
  // Dialog strings
  'confirm': 'ยืนยัน',
  'cancel': 'ยกเลิก',
  'yes': 'ใช่',
  'no': 'ไม่ใช่',
  'save': 'บันทึก',
  'edit': 'แก้ไข',
  'levelFormat': 'ด่านที่ {level}',
  'newbieLevelFormat': 'มือใหม่ {level}',
  'totalLevel': '{level}/{totalLevel} ด่าน',
  'totalLevelTooltip': 'ปัจจุบัน: ด่านที่ {level} / ทั้งหมด {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'ไม่มีแนวรบ',
  'battlefrontCount': '{count} แนวรบ',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'มือใหม่ LV{level}',
  'minesCount': '{count} ระเบิด',
  'notStarted': 'ยังไม่เริ่ม',
  'victory': 'ชนะ',
  'defeat': 'แพ้',
  'gameDurationParam': 'เวลา: {seconds}วิ',
  'actionsCountParam': 'การกระทำ: {count} ครั้ง',
  'actionsCountParamShort': '{count} ครั้ง',
  'miningMethodParam': 'วิธี: {method}',
  'startTimeParam': 'เริ่ม: {time}',
  'endTimeParam': 'จบ: {time}',
  'returnButton': 'ย้อนกลับ',
  'battlefrontDetails': 'รายละเอียดแนวรบ',
  'clickToEditName': 'คลิกเพื่อแก้ไขชื่อ',
  'clickToAddDescription': 'คลิกเพื่อเพิ่มคำอธิบาย...',
  'noDescription': 'ไม่มีคำอธิบาย',
  // Level record strings
  'levelCount': '{count} ด่าน',
  'noLevelRecords': 'โปรดเลือกแนวรบ',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'ลบแนวรบ',
  'deleteBattlefrontContent':
      'คุณแน่ใจหรือไม่ว่าต้องการลบแนวรบ \'{name}\' ? การกระทำนี้ไม่สามารถยกเลิกได้',
  'battlefrontLockedCannotDelete': 'แนวรบถูกล็อก ไม่สามารถลบได้',
  'unknownNavigationLevel': 'ด่านไม่ทราบ',
  'noBattlefrontSelected': 'ไม่ได้เลือกแนวรบ',
  'noBattlefrontToContinue': 'ไม่พบแนวรบที่สามารถดำเนินการต่อได้',
  'synced': 'ซิงค์แล้ว',
  'notSynced': 'ยังไม่ซิงค์',
  'newbieBattlefrontName': 'แนวรบมือใหม่ {number}',
  'battlefrontName': 'แนวรบ {number}',
  'nickname': 'ชื่อเล่น',
  'nicknameSetting': 'ตั้งค่าชื่อเล่น',
  'nicknameDesc': 'ตั้งค่าชื่อเล่นของคุณ',
  'enterNickname': 'ใส่ชื่อเล่น',
  'nicknameSaved': 'บันทึกชื่อเล่นเรียบร้อย',
  'nicknameUpdated': 'อัปเดตชื่อเล่นเรียบร้อย',
  'nicknameRequired': 'ต้องใส่ชื่อเล่น',
  'nicknameTooLong': 'ชื่อเล่นห้ามเกิน 30 ตัวอักษร',
  // Level top strings
  'levelTopCount': 'อันดับสูงสุด ({count})',
  'levelTopCountShort': 'สูงสุด ({count})',
  'retry': 'ลองใหม่',
  'noLevelTopData': 'ไม่มีข้อมูล',
  'remoteBattlefront': 'แนวรบระยะไกล',
  'participated': 'เข้าร่วมแล้ว',
  'notParticipated': 'ยังไม่เข้าร่วม',
  'loadMore': 'โหลดเพิ่ม',
  'joinBattle': 'เข้าร่วมการต่อสู้',
  'joinBattleTooltip': 'เข้าร่วมการต่อสู้ \'{name}\'',
  'joinBattleConfirm':
      'คุณแน่ใจหรือไม่ว่าต้องการเข้าร่วมการต่อสู้ \'{name}\' ?',
  'joinBattleSuccess': 'เข้าร่วมการต่อสู้ \'{name}\' สำเร็จ',
  'joinBattleErrorSelf': 'ไม่สามารถเข้าร่วมแนวรบที่ตัวเองสร้างได้',
  'replayBattlefront': 'เล่นซ้ำแนวรบ',
  'replayBattlefrontTooltip': 'เล่นซ้ำแนวรบ \'{name}\'',
  'getReplayBattlefrontConfirm':
      'คุณแน่ใจหรือไม่ว่าต้องการเล่นซ้ำ \'{name}\' ?',
  'getReplayBattlefrontFailed': 'เล่นซ้ำ \'{name}\' ล้มเหลว: {error}',
  'download': 'ดาวน์โหลด',
  'downloadBattlefront': 'ดาวน์โหลดแนวรบ',
  'downloadBattlefrontTooltip': 'ดาวน์โหลดแนวรบ \'{name}\'',
  'getDownloadBattlefrontConfirm':
      'คุณแน่ใจหรือไม่ว่าต้องการดาวน์โหลด \'{name}\' ?',
  'getDownloadBattlefrontSuccess': 'ดาวน์โหลด \'{name}\' สำเร็จ',
  'downloadMyOwnBattlefrontError':
      'สามารถดาวน์โหลดเฉพาะแนวรบที่ตัวเองสร้างได้เท่านั้น',
  'getDownloadBattlefrontFailed': 'ดาวน์โหลด \'{name}\' ล้มเหลว: {error}',
  'continueGameShort': 'ต่อสู้ต่อ',
  'replayShort': 'เล่นซ้ำ',
  'highestLevel': 'ด่านที่ {level}',
  'deviceNickname': 'อุปกรณ์',
  'createdTime': 'เวลาสร้าง',
  'remoteBattlefrontDetail': 'รายละเอียดแนวรบระยะไกล',
  'levelList': 'รายการด่าน',
  'fastClearTimeParam': 'เวลาผ่านด่าน: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint': 'โปรดเลือกแนวรบในเครื่องเพื่อดูรายละเอียด',
  'loadingRemoteDetail': 'กำลังโหลดรายละเอียดแนวรบระยะไกล...',
  'noRemoteBattlefrontSelected': 'ไม่ได้เลือกแนวรบระยะไกล',
  'failedToLoadRemoteDetail': 'โหลดรายละเอียดล้มเหลว',
  'fastestRecord': 'ผ่านด่านเร็วที่สุด',
  'safestRecord': 'ผ่านด่านปลอดภัยที่สุด',
  'fastestRecordDesc': 'เร็วที่สุด (ใช้เวลาน้อยที่สุด)',
  'safestRecordDesc': 'ปลอดภัยที่สุด (ใช้การกระทำน้อยที่สุด)',
  'creator': 'ผู้สร้าง',
  'player': 'ผู้เล่น',
  // Branch maps
  'getBranchMapCount': '{count} แบบ',
  'collapse': 'ย่อ',
  'expand': 'ขยาย',
  // Quit battlefront
  'quitBattlefront': 'ออกจากแนวรบ',
  'quitBattlefrontTooltip': 'ออกจากแนวรบระยะไกล',
  'quitBattlefrontTitle': 'ออกจากแนวรบ',
  'quitBattlefrontContent':
      'คุณแน่ใจหรือไม่ว่าต้องการออกจากแนวรบ \'{name}\' ? ความคืบหน้าในเครื่องจะถูกลบ',
  // Game introduction
  'gameIntroduction':
      '1. "มือใหม่" เริ่มต้นด้วย 15 ระเบิด สูงสุดถึง 99 ระเบิด;\n2. "แนวรบใหม่" เริ่มต้นด้วย 81 ระเบิด เพิ่มจำนวนในแต่ละด่าน ไม่มีขีดจำกัดสูงสุด.\n3. เมื่อออนไลน์ แนวรบที่ผ่านแล้วจะถูกแชร์อัตโนมัติไปยังคลาวด์ เพื่อให้ผู้อื่นเรียนรู้',
};
