// Croatian（克罗地亚语）
/// Hrvatski jezični stringovi za DMine aplikaciju
const Map<String, String> stringsHr = {
  'appLabel': 'Premium Minolovac',
  'appTitle': 'DMine - Premium Minolovac',
  'settings': 'Postavke',
  'gameSettings': 'Postavke igre',
  'showTimer': 'Prikaži timer',
  'showTimerDesc': 'Prikaži timer igre na sučelju',
  'showActionCounter': 'Prikaži brojač akcija',
  'showActionCounterDesc': 'Prikaži broj akcija na sučelju igre',
  'autoAdjustBoardWidth': 'Automatski prilagodi širinu ploče',
  'autoAdjustBoardWidthDesc':
      'Automatski prilagodi širinu ploče prema veličini ekrana',
  'resetToDefaults': 'Vrati na zadane postavke',
  'resetToDefaultsDesc': 'Vrati sve postavke na zadane vrijednosti',
  'aboutDMine': 'O DMine',
  'version': 'Verzija',
  'close': 'Zatvori',
  'manualBoardWidth': 'Ručno podesi širinu ploče',
  'currentWidth': 'Trenutno',
  'range': 'Raspon',
  'widthSliderHint':
      'Savjet: Možete pregledati promjene širine ploče u realnom vremenu povlačenjem klizača',
  'gameRecords': 'Igrećevi zapisi',
  'selectMapToViewRecords': 'Odaberite mapu za pregled zapisa',
  'totalRecords': 'Ukupno',
  'gameRecordsTitle': 'Lista zapisa igre',
  'pleaseSelectMapFirst': 'Prvo odaberite mapu',
  'noGameRecords': 'Nema zapisa igre',
  'miningMethodFlag': 'Postavi zastavicu',
  'miningMethodBlind': 'Slijepo traženje',
  'statusPlaying': '▶️ U tijeku...',
  'statusWin': '🎉 Pobjeda',
  'statusLose': '💥 Poraz',
  'actionsCount': 'Broj akcija',
  'miningMethod': 'Način minolova',
  'duration': 'Trajanje',
  'seconds': 'sekundi',
  'startTime': 'Vrijeme početka',
  'endTime': 'Vrijeme završetka',
  'pauseTime': 'Vrijeme pauze',
  'unlock': 'Otključaj',
  'lock': 'Zaključaj',
  'delete': 'Izbriši',
  'languageSetting': 'Postavka jezika',
  'currentLanguage': 'Trenutni',
  'systemLanguage': 'Jezik sustava',
  'chinese': 'Kineski',
  'english': 'Engleski',
  'language': 'Jezik',
  // Home page
  'newbie': 'Početnička nastava',
  'gameIntro': 'Uvod u igru',
  'newBattle': 'Nova fronta',
  'continueChallenge': 'Nastavi izazov',
  'error': 'Greška',
  'initializationFailed': 'Inicijalizacija nije uspjela',
  // Game page
  'congratulations': 'Čestitamo, prošli ste razinu!',
  'gameOver': 'Kraj igre',
  'timeUsed': 'Utrošeno vrijeme',
  'actionCount': 'Broj akcija',
  'mineCount': 'Broj mina',
  'nextLevel': 'Sljedeća razina: Razina {level}',
  'newbieNextLevel': 'Sljedeća razina: Početnička {level} razina',
  'nextLevelMines': 'Broj mina',
  'mineIncrease': 'Povećanje',
  'newbieFinish': 'Početnička nastava završena',
  'ok': 'U redu',
  'continueNextLevel': 'Nastavi sljedeću razinu',
  'restart': 'Restartaj',
  'level': 'Razina {level}',
  'newbieLevel': 'Početnička razina {level}',
  'operationFailed': 'Operacija nije uspjela',
  // Game status texts
  'returnHome': 'Povratak na početnu',
  'revealMode': 'Način otkrivanja',
  'flagMode': 'Način zastavica',
  'newMap': 'Nova mapa (broj mina nepromijenjen, generiraj novu mapu)',
  'resetMap': 'Ponovo učitaj mapu (ista mapa, resetaj stanje)',
  'zoomOut': 'Smanji',
  'zoomIn': 'Povećaj',
  'resetZoom': 'Vrati originalni zoom',
  'previousStep': 'Prethodni korak',
  'pause': 'Pauziraj',
  'play': 'Pokreni',
  'nextStep': 'Sljedeći korak',
  'clickToStart': 'Kliknite bilo koje polje za početak igre',
  'playing': 'Igra u tijeku...',
  'gameWin': 'Čestitamo, prošli ste razinu!',
  'gameLose': 'Kraj igre, stepnuli ste minu',
  'gamePaused': 'Igra pauzirana',
  'ready': 'Spremno',
  'clickStartShort': 'Klikni za početak',
  'playingShort': 'U tijeku',
  'winShort': 'Prošlo!',
  'loseShort': 'Stepnuli minu',
  'pausedShort': 'Pauzirano',
  // Counter strings
  'currentLevel': 'Trenutna razina',
  'remainingMines': 'Preostalih mina',
  'gameTime': 'Vrijeme igre (sekundi)',
  'operationCount': 'Broj akcija',
  'previousLevel': 'Prethodna razina',
  'nextLevelShort': 'Sljedeća razina',
  // Battlefront strings
  'completed': 'Završeno',
  'inProgress': 'U tijeku',
  'continueGame': 'Nastavi igru',
  'replay': 'Ponovi',
  'creater': 'Glavni komandant',
  'created': 'Vrijeme početka bitke',
  'updated': 'Ažurirano',
  // Dialog strings
  'confirm': 'Potvrdi',
  'cancel': 'Odustani',
  'yes': 'Da',
  'no': 'Ne',
  'save': 'Spremi',
  'edit': 'Uredi',
  'levelFormat': 'Razina {level}',
  'newbieLevelFormat': 'Početnička razina {level}',
  'totalLevel': '{level}/{totalLevel} razina',
  'totalLevelTooltip': 'Trenutno: Razina {level} / Ukupno {totalLevel} razina',
  // Battlefront UI strings
  'noBattlefronts': 'Nema fronti',
  'battlefrontCount': '{count} fronti',
  'levelPrefix': 'RZ{level}',
  'newbieLevelPrefix': 'Početnička RZ{level}',
  'minesCount': '{count} mina',
  'notStarted': 'Nije počelo',
  'victory': 'Pobjeda',
  'defeat': 'Poraz',
  'gameDurationParam': 'Trajanje: {seconds} sekundi',
  'actionsCountParam': 'Akcije: {count} puta',
  'actionsCountParamShort': '{count} puta',
  'miningMethodParam': 'Način: {method}',
  'startTimeParam': 'Vrijeme početka: {time}',
  'endTimeParam': 'Vrijeme završetka: {time}',
  'returnButton': 'Natrag',
  'battlefrontDetails': 'Detalji fronte',
  'clickToEditName': 'Klikni za promjenu imena',
  'clickToAddDescription': 'Klikni za dodavanje opisa...',
  'noDescription': 'Bez opisa',
  // Level record strings
  'levelCount': '{count} razina',
  'noLevelRecords': 'Odaberite frontu',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Izbriši frontu',
  'deleteBattlefrontContent':
      'Jeste li sigurni da želite izbrisati frontu "{name}"? Ova akcija je nepovratna.',
  'battlefrontLockedCannotDelete': 'Fronta je zaključana, ne može se izbrisati',
  'unknownNavigationLevel': 'Nepoznata razina navigacije',
  'noBattlefrontSelected': 'Nije odabrana fronta',
  'noBattlefrontToContinue': 'Nema fronti za nastavak',
  'synced': 'Sinkronizirano',
  'notSynced': 'Nije sinkronizirano',
  'newbieBattlefrontName': 'Početnička fronta {number}',
  'battlefrontName': 'Fronta {number}',
  'nickname': 'Nadimak',
  'nicknameSetting': 'Postavka nadimka',
  'nicknameDesc': 'Postavite svoj nadimak',
  'enterNickname': 'Unesite nadimak',
  'nicknameSaved': 'Nadimak spremljen',
  'nicknameUpdated': 'Nadimak ažuriran',
  'nicknameRequired': 'Nadimak je obavezan',
  'nicknameTooLong': 'Nadimak ne smije biti duži od 30 znakova',
  // Level top strings
  'levelTopCount': 'Rang lista ({count})',
  'levelTopCountShort': 'Rang ({count})',
  'retry': 'Pokušaj ponovo',
  'noLevelTopData': 'Nema podataka',
  'remoteBattlefront': 'Udaljena fronta',
  'participated': 'Učestvovano',
  'notParticipated': 'Nije učestvovano',
  'loadMore': 'Učitaj više',

  'joinBattle': 'Pridruži se bitci',
  'joinBattleTooltip': 'Pridruži se bitci "{name}"',
  'joinBattleConfirm':
      'Jeste li sigurni da želite pridružiti se bitci "{name}"?',
  'joinBattleSuccess': 'Uspješno ste se pridružili bitci "{name}"',
  'joinBattleErrorSelf': 'Ne možete se pridružiti vlastitoj fronti',

  'replayBattlefront': 'Ponovi frontu',
  'replayBattlefrontTooltip': 'Ponovi frontu "{name}"',
  'getReplayBattlefrontConfirm':
      'Jeste li sigurni da želite ponoviti "{name}"?',
  'getReplayBattlefrontFailed': 'Ponavljanje "{name}" nije uspjelo: {error}',

  'download': 'Preuzmi',
  'downloadBattlefront': 'Preuzmi frontu',
  'downloadBattlefrontTooltip': 'Preuzmi frontu "{name}"',
  'getDownloadBattlefrontConfirm':
      'Jeste li sigurni da želite preuzeti "{name}"?',
  'getDownloadBattlefrontSuccess': 'Fronta "{name}" uspješno preuzeta',
  'downloadMyOwnBattlefrontError': 'Možete preuzeti samo vlastite fronte',
  'getDownloadBattlefrontFailed': 'Preuzimanje "{name}" nije uspjelo: {error}',

  'continueGameShort': 'Nastavi bitku',
  'replayShort': 'Ponovi',
  'highestLevel': 'Razina {level}',
  'deviceNickname': 'Uređaj',
  'createdTime': 'Vrijeme stvaranja',
  'remoteBattlefrontDetail': 'Detalji udaljene fronte',
  'levelList': 'Lista razina',
  'fastClearTimeParam': 'Vrijeme prolaska: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Odaberite lokalnu frontu za pregled detalja',
  'loadingRemoteDetail': 'Učitavanje detalja udaljene fronte...',
  'noRemoteBattlefrontSelected': 'Nije odabrana udaljena fronta',
  'failedToLoadRemoteDetail': 'Učitavanje detalja nije uspjelo',
  'fastestRecord': 'Najbrži prolaz',
  'safestRecord': 'Najsigurniji prolaz',
  'fastestRecordDesc': 'Najbrži prolaz (najmanje vremena)',
  'safestRecordDesc': 'Najsigurniji prolaz (najmanje akcija)',
  'creator': 'Stvoritelj',
  'player': 'Igrač',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopija',
  'collapse': 'Sažmi',
  'expand': 'Proširi',
  // 退出战线
  'quitBattlefront': 'Napusti frontu',
  'quitBattlefrontTooltip': 'Napusti udaljenu frontu',
  'quitBattlefrontTitle': 'Napusti frontu',
  'quitBattlefrontContent':
      'Jeste li sigurni da želite napustiti frontu "{name}"? Vaš lokalni napredak će biti izbrisan.',

  // 下载页面
  'downloadClient': 'Preuzmi klijenta',
  'browser': 'Preglednik',
  'browserDesc': 'Igrajte izravno u pregledniku, bez preuzimanja',
  'windowsDesc': 'Za Windows 10 i novije',
  'macosDesc': 'Za macOS 10.15 i novije',
  'android': 'Android',
  'androidDesc': 'Za Android 8.0 i novije',
  'iosDesc': 'Za iOS 14.0 i novije',
  'linkAddress': 'Adresa linka',
  'downloadLink': 'Link za preuzimanje',
  'qrCode': 'QR kod',
  'scanToDownload': 'Skenirajte telefonom za preuzimanje',
  'copy': 'Kopiraj',
  'copiedToClipboard': 'Kopirano u međuspremnik',
  'openLink': 'Otvori link',
  'cannotOpenLink': 'Ne može otvoriti link',
  // 游戏介绍
  'gameIntroduction':
      '1. "Početnička nastava" počinje s 15 mina, maksimalno do 99 mina;\n2. "Nova fronta" počinje s 81 mine, na svakoj razini se dodaje određeni broj mina, bez gornjeg ograničenja.\n3. Pri spajanju na internet, "prošle" fronte se automatski dijele u oblaku za učenje drugih.',
};
