// Malay（马来语）
/// Teks Melayu untuk aplikasi DMine
const Map<String, String> stringsMs = {
  'appLabel': 'Permainan Minesweeper Top',
  'appTitle': 'DMine - Permainan Minesweeper',
  'settings': 'Tetapan',
  'gameSettings': 'Tetapan Permainan',
  'showTimer': 'Papar pemasa',
  'showTimerDesc': 'Memaparkan pemasa permainan pada antara muka',
  'showActionCounter': 'Papar bilangan tindakan',
  'showActionCounterDesc': 'Memaparkan bilangan tindakan yang dibuat',
  'autoAdjustBoardWidth': 'Lebar papan automatik',
  'showUnrevealedCounter': 'Tunjukkan pengira sel belum didedahkan',
  'showUnrevealedCounterDesc': 'Tunjukkan bilangan sel belum didedahkan pada antara muka permainan',
  'showMineCounter': 'Tunjukkan pengira lombong',
  'showMineCounterDesc': 'Tunjukkan baki lombong pada antara muka permainan',
  'autoAdjustBoardWidthDesc':
      'Laraskan lebar papan permainan mengikut saiz skrin secara automatik',
  'resetToDefaults': 'Set semula tetapan',
  'resetToDefaultsDesc': 'Kembalikan semua tetapan ke nilai asal',
  'aboutDMine': 'Mengenai DMine',
  'version': 'Versi',
  'close': 'Tutup',
  'manualBoardWidth': 'Lebar papan manual',
  'currentWidth': 'Semasa',
  'range': 'Julat',
  'widthSliderHint':
      'Petua: Luncurkan slider untuk lihat perubahan serta-merta',
  'gameRecords': 'Rekod Permainan',
  'selectMapToViewRecords': 'Pilih peta untuk lihat rekod',
  'totalRecords': 'Jumlah',
  'gameRecordsTitle': 'Senarai Rekod Permainan',
  'pleaseSelectMapFirst': 'Sila pilih peta terlebih dahulu',
  'noGameRecords': 'Tiada rekod permainan',
  'miningMethodFlag': 'Tandakan bendera',
  'miningMethodBlind': 'Klik terus',
  'statusPlaying': '▶️ Bermain...',
  'statusWin': '🎉 Menang!',
  'statusLose': '💥 Kalah!',
  'actionsCount': 'Tindakan',
  'miningMethod': 'Kaedah mencari periuk api',
  'duration': 'Tempoh',
  'seconds': 'saat',
  'startTime': 'Masa mula',
  'endTime': 'Masa tamat',
  'pauseTime': 'Masa jeda',
  'unlock': 'Buka kunci',
  'lock': 'Kunci',
  'delete': 'Padam',
  'languageSetting': 'Tetapan Bahasa',
  'currentLanguage': 'Bahasa semasa',
  'systemLanguage': 'Bahasa sistem',
  'chinese': 'Cina',
  'english': 'Inggeris',
  'language': 'Bahasa',
  // Home page
  'newbie': 'Pemula',
  'gameIntro': 'Pengenalan Permainan',
  'newBattle': 'Front Baru',
  'continueChallenge': 'Teruskan cabaran',
  'error': 'Ralat',
  'initializationFailed': 'Pemulaan gagal',
  // Game page
  'congratulations': 'Tahniah! Anda telah selesai peringkat!',
  'gameOver': 'Permainan Tamat',
  'timeUsed': 'Masa digunakan',
  'actionCount': 'Bilangan tindakan',
  'mineCount': 'Bilangan periuk api',
  'nextLevel': 'Peringkat seterusnya: Peringkat {level}',
  'newbieNextLevel': 'Peringkat seterusnya: Pemula {level}',
  'nextLevelMines': 'Bilangan periuk api',
  'mineIncrease': 'Peningkatan',
  'newbieFinish': 'Mod pemula selesai',
  'ok': 'OK',
  'continueNextLevel': 'Ke peringkat seterusnya',
  'restart': 'Mula semula',
  'level': 'Peringkat {level}',
  'newbieLevel': 'Peringkat Pemula {level}',
  'operationFailed': 'Operasi gagal',
  // Game status texts
  'returnHome': 'Kembali ke Laman Utama',
  'revealMode': 'Mod dedahkan',
  'flagMode': 'Mod bendera',
  'newMap': 'Peta baru (bilangan periuk api sama)',
  'resetMap': 'Set semula peta',
  'zoomOut': 'Zum keluar',
  'zoomIn': 'Zum masuk',
  'resetZoom': 'Set semula zum',
  'previousStep': 'Langkah sebelumnya',
  'pause': 'Jeda',
  'play': 'Main',
  'nextStep': 'Langkah seterusnya',
  'clickToStart': 'Klik mana-mana sel untuk mula',
  'playing': 'Bermain...',
  'gameWin': 'Tahniah! Anda menang!',
  'gameLose': 'Permainan tamat, anda terkena periuk api',
  'gamePaused': 'Permainan dijeda',
  'ready': 'Sedia',
  'clickStartShort': 'Klik untuk mula',
  'playingShort': 'Bermain',
  'winShort': 'Menang!',
  'loseShort': 'Terkena periuk api',
  'pausedShort': 'Jeda',
  // Counter strings
  'currentLevel': 'Peringkat semasa',
  'remainingMines': 'Periuk api tinggal',
  'unrevealedCells': 'Sel belum didedahkan',
  'gameTime': 'Masa permainan (saat)',
  'operationCount': 'Tindakan',
  'previousLevel': 'Peringkat sebelumnya',
  'nextLevelShort': 'Peringkat seterusnya',
  // Battlefront strings
  'completed': 'Selesai',
  'inProgress': 'Dalam proses',
  'continueGame': 'Teruskan permainan',
  'replay': 'Main semula',
  'creater': 'Pencipta',
  'created': 'Dicipta pada',
  'updated': 'Dikemas kini pada',
  // Dialog strings
  'confirm': 'Sahkan',
  'cancel': 'Batal',
  'yes': 'Ya',
  'no': 'Tidak',
  'save': 'Simpan',
  'edit': 'Sunting',
  'levelFormat': 'Peringkat {level}',
  'newbieLevelFormat': 'Peringkat Pemula {level}',
  'totalLevel': '{level}/{totalLevel} peringkat',
  'totalLevelTooltip':
      'Semasa: Peringkat {level} / Jumlah {totalLevel} peringkat',
  // Battlefront UI strings
  'noBattlefronts': 'Tiada front',
  'battlefrontCount': '{count} front',
  'levelPrefix': 'PK{level}',
  'newbiePrefix': 'PM{level}',
  'minesCount': '{count} periuk api',
  'notStarted': 'Belum mula',
  'victory': 'Menang',
  'defeat': 'Kalah',
  'gameDurationParam': 'Tempoh: {seconds} saat',
  'actionsCountParam': 'Tindakan: {count} kali',
  'actionsCountParamShort': '{count} kali',
  'miningMethodParam': 'Kaedah: {method}',
  'startTimeParam': 'Mula: {time}',
  'endTimeParam': 'Tamat: {time}',
  'returnButton': 'Kembali',
  'battlefrontDetails': 'Butiran Front',
  'clickToEditName': 'Klik untuk sunting nama',
  'clickToAddDescription': 'Klik untuk tambah deskripsi...',
  'noDescription': 'Tiada deskripsi',
  // Level record strings
  'levelCount': '{count} peringkat',
  'noLevelRecords': 'Pilih front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Padam Front',
  'deleteBattlefrontContent':
      'Anda pasti ingin memadam front "{name}"? Tindakan ini tidak boleh dibatalkan.',
  'battlefrontLockedCannotDelete': 'Front dikunci, tidak boleh dipadam',
  'unknownNavigationLevel': 'Peringkat navigasi tidak diketahui',
  'noBattlefrontSelected': 'Tiada front dipilih',
  'noBattlefrontToContinue': 'Tiada front untuk diteruskan',
  'synced': 'Disegerakankan',
  'notSynced': 'Tidak disegerakankan',
  'newbieBattlefrontName': 'Front Pemula {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Nama samaran',
  'nicknameSetting': 'Tetapan Nama Samaran',
  'nicknameDesc': 'Tetapkan nama samaran anda',
  'enterNickname': 'Masukkan nama samaran',
  'nicknameSaved': 'Nama samaran disimpan',
  'nicknameUpdated': 'Nama samaran dikemas kini',
  'nicknameRequired': 'Nama samaran diperlukan',
  'nicknameTooLong': 'Nama samaran tidak melebihi 30 aksara',
  // Level top strings
  'levelTopCount': 'Kedudukan ({count})',
  'levelTopCountShort': 'Kedudukan ({count})',
  'retry': 'Cuba lagi',
  'noLevelTopData': 'Tiada data',
  'remoteBattlefront': 'Front Jauh',
  'participated': 'Bertaubat',
  'notParticipated': 'Tidak bertaubat',
  'loadMore': 'Muat lebih',

  'joinBattle': 'Sertai pertempuran',
  'joinBattleTooltip': 'Sertai pertempuran "{name}"',
  'joinBattleConfirm': 'Anda pasti ingin sertai "{name}"?',
  'joinBattleSuccess': 'Berjaya sertai "{name}"',
  'joinBattleErrorSelf': 'Tidak boleh sertai front anda sendiri',

  'replayBattlefront': 'Main semula front',
  'replayBattlefrontTooltip': 'Main semula front "{name}"',
  'getReplayBattlefrontConfirm': 'Anda pasti ingin main semula "{name}"?',
  'getReplayBattlefrontFailed': 'Gagal main semula "{name}": {error}',

  'download': 'Muat turun',
  'downloadBattlefront': 'Muat turun front',
  'downloadBattlefrontTooltip': 'Muat turun front "{name}"',
  'getDownloadBattlefrontConfirm': 'Anda pasti ingin muat turun "{name}"?',
  'getDownloadBattlefrontSuccess': 'Front "{name}" berjaya dimuat turun',
  'downloadMyOwnBattlefrontError': 'Hanya boleh muat turun front anda sendiri',
  'getDownloadBattlefrontFailed': 'Gagal muat turun "{name}": {error}',

  'continueGameShort': 'Teruskan pertempuran',
  'replayShort': 'Semula',
  'highestLevel': 'Peringkat {level}',
  'deviceNickname': 'Peranti',
  'createdTime': 'Masa cipta',
  'remoteBattlefrontDetail': 'Butiran Front Jauh',
  'levelList': 'Senarai Peringkat',
  'fastClearTimeParam': 'Kelajuan: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Pilih front tempatan untuk lihat butiran',
  'loadingRemoteDetail': 'Memuat butiran front jauh...',
  'noRemoteBattlefrontSelected': 'Tiada front jauh dipilih',
  'failedToLoadRemoteDetail': 'Gagal memuat butiran jauh',
  'fastestRecord': 'Paling cepat',
  'safestRecord': 'Paling selamat',
  'fastestRecordDesc': 'Selesai paling cepat (masa minima)',
  'safestRecordDesc': 'Selesai paling selamat (tindakan minima)',
  'creator': 'Pencipta',
  'player': 'Pemain',
  // 分支地图字符串
  'getBranchMapCount': '{count} salinan',
  'collapse': 'Lipat',
  'expand': 'Buka',
  // 退出战线
  'quitBattlefront': 'Keluar front',
  'quitBattlefrontTooltip': 'Keluar front jauh',
  'quitBattlefrontTitle': 'Keluar Front',
  'quitBattlefrontContent':
      'Anda pasti ingin keluar front "{name}"? Kemajuan tempatan akan dipadam.',
  // 游戏介绍
  'gameIntroduction':
      '1. "Pemula" bermula dengan 15 periuk api, sehingga 99 periuk api.\n2. "Front Baru" bermula dengan 81 periuk api, setiap peringkat tambah bilangan tanpa had.\n3. Dengan internet, front "selesai" disimpan automatik di awan untuk pemain lain.',
};
