// SerbianLatin（塞尔维亚语拉丁字母）
/// Serbian (Latin) language strings for the DMine application
const Map<String, String> stringsSrLatn = {
  'appLabel': 'Top Miner',
  'appTitle': 'DMine - Top Miner',
  'settings': 'Podešavanja',
  'gameSettings': 'Podešavanja igre',
  'showTimer': 'Prikaži tajmer',
  'showTimerDesc': 'Prikazuje tajmer igre na ekranu igre',
  'showActionCounter': 'Prikaži brojač akcija',
  'showActionCounterDesc': 'Prikazuje broj akcija na ekranu igre',
  'autoAdjustBoardWidth': 'Automatsko prilagođavanje širine table',
  'autoAdjustBoardWidthDesc':
      'Automatski prilagođava širinu table prema veličini ekrana',
  'resetToDefaults': 'Vrati podrazumevane podešavanja',
  'resetToDefaultsDesc': 'Vraća sva podešavanja na podrazumevane vrednosti',
  'aboutDMine': 'O DMine',
  'version': 'Verzija',
  'close': 'Zatvori',
  'manualBoardWidth': 'Ručno podešavanje širine table',
  'currentWidth': 'Trenutno',
  'range': 'Opseg',
  'widthSliderHint':
      'Sovet: pri prevlačenju klizača vidite promene širine table odmah',
  'gameRecords': 'Rekordi igre',
  'selectMapToViewRecords': 'Izaberite mapu za pregled rekordâ',
  'totalRecords': 'Ukupno',
  'gameRecordsTitle': 'Lista rekordâ igre',
  'pleaseSelectMapFirst': 'Prvo izaberite mapu',
  'noGameRecords': 'Nema rekordâ igre',
  'miningMethodFlag': 'Oznaka zastavom',
  'miningMethodBlind': 'Slepa razmina',
  'statusPlaying': '▶️ U toku...',
  'statusWin': '🎉 Pobeda',
  'statusLose': '💥 Poraz',
  'actionsCount': 'Broj akcija',
  'miningMethod': 'Način igre',
  'duration': 'Trajanje',
  'seconds': 'sekundi',
  'startTime': 'Vreme početka',
  'endTime': 'Vreme završetka',
  'pauseTime': 'Vreme pauze',
  'unlock': 'Otključaj',
  'lock': 'Zaključaj',
  'delete': 'Obriši',
  'languageSetting': 'Podešavanje jezika',
  'currentLanguage': 'Trenutni',
  'systemLanguage': 'Sistemski jezik',
  'chinese': 'Kineski',
  'english': 'Engleski',
  'language': 'Jezik',
  // Home page
  'newbie': 'Početnik',
  'newBattle': 'Novi front',
  'continueChallenge': 'Nastavi izazov',
  'error': 'Greška',
  'initializationFailed': 'Inicijalizacija nije uspela',
  // Game page
  'congratulations': 'Čestitamo, prošli ste nivo!',
  'gameOver': 'Kraj igre',
  'timeUsed': 'Upotrebljeno vreme',
  'actionCount': 'Akcije',
  'mineCount': 'Mine',
  'nextLevel': 'Sledeći nivo: Nivo {level}',
  'newbieNextLevel': 'Sledeći nivo: Početnik {level}',
  'nextLevelMines': 'Mine',
  'mineIncrease': 'Povećanje',
  'newbieFinish': 'Režim početnika završen',
  'ok': 'U redu',
  'continueNextLevel': 'Nastavi na sledeći nivo',
  'restart': 'Pokreni ponovo',
  'level': 'Nivo {level}',
  'newbieLevel': 'Početnik {level}',
  'operationFailed': 'Operacija nije uspela',
  // Game status texts
  'returnHome': 'Nazad na početnu',
  'revealMode': 'Režim otkrivanja',
  'flagMode': 'Režim zastave',
  'newMap': 'Nova mapa (isti broj mina, novi raspored)',
  'resetMap': 'Resetuj mapu (isti raspored, reset stanja)',
  'zoomOut': 'Umanji',
  'zoomIn': 'Uvećaj',
  'resetZoom': 'Vrati originalni zum',
  'previousStep': 'Prethodni korak',
  'pause': 'Pauza',
  'play': 'Igraj',
  'nextStep': 'Sledeći korak',
  'clickToStart': 'Kliknite bilo koje polje da počnete igru',
  'playing': 'U igri...',
  'gameWin': 'Čestitamo, prošli ste nivo!',
  'gameLose': 'Kraj igre, stupili ste na minu',
  'gamePaused': 'Igra je pauzirana',
  'ready': 'Spremno za početak',
  'clickStartShort': 'Kliknite da počnete',
  'playingShort': 'U igri',
  'winShort': 'Završeno!',
  'loseShort': 'Poraz',
  'pausedShort': 'Pauzirano',
  // Counter strings
  'currentLevel': 'Trenutni nivo',
  'remainingMines': 'Preostale mine',
  'gameTime': 'Vreme igre (sekundi)',
  'operationCount': 'Broj operacija',
  'previousLevel': 'Prethodni nivo',
  'nextLevelShort': 'Sledeći nivo',
  // Battlefront strings
  'completed': 'Završeno',
  'inProgress': 'U toku',
  'continueGame': 'Nastavi igru',
  'replay': 'Ponovo',
  'creater': 'Komandant',
  'created': 'Vreme kreiranja',
  'updated': 'Ažurirano',
  // Dialog strings
  'confirm': 'Potvrdi',
  'cancel': 'Otkaži',
  'yes': 'Da',
  'no': 'Ne',
  'save': 'Sačuvaj',
  'edit': 'Uredi',
  'levelFormat': 'Nivo {level}',
  'newbieLevelFormat': 'Početnik {level}',
  'totalLevel': '{level}/{totalLevel} nivoa',
  'totalLevelTooltip': 'Trenutno: Nivo {level} / Ukupno {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Nema frontova',
  'battlefrontCount': '{count} frontova',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'Početnik NV{level}',
  'minesCount': '{count} mina',
  'notStarted': 'Nije početo',
  'victory': 'Pobeda',
  'defeat': 'Poraz',
  'gameDurationParam': 'Trajanje: {seconds}s',
  'actionsCountParam': 'Akcije: {count} puta',
  'actionsCountParamShort': '{count} puta',
  'miningMethodParam': 'Način: {method}',
  'startTimeParam': 'Početak: {time}',
  'endTimeParam': 'Završetak: {time}',
  'returnButton': 'Nazad',
  'battlefrontDetails': 'Detalji fronta',
  'clickToEditName': 'Kliknite da uredite ime',
  'clickToAddDescription': 'Kliknite da dodate opis...',
  'noDescription': 'Bez opisa',
  // Level record strings
  'levelCount': '{count} nivoa',
  'noLevelRecords': 'Izaberite front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Obriši front',
  'deleteBattlefrontContent':
      'Da li ste sigurni da želite da obrišete front \'{name}\'? Ova akcija se ne može opozvati.',
  'battlefrontLockedCannotDelete': 'Front je zaključan, ne može se obrisati',
  'unknownNavigationLevel': 'Nepoznat nivo',
  'noBattlefrontSelected': 'Nije izabran front',
  'noBattlefrontToContinue': 'Nema dostupnog fronta za nastavak',
  'synced': 'Sinhronizovano',
  'notSynced': 'Nije sinhronizovano',
  'newbieBattlefrontName': 'Front početnika {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Nadimak',
  'nicknameSetting': 'Podešavanje nadimka',
  'nicknameDesc': 'Podesite svoj nadimak',
  'enterNickname': 'Unesite nadimak',
  'nicknameSaved': 'Nadimak sačuvan',
  'nicknameUpdated': 'Nadimak ažuriran',
  'nicknameRequired': 'Nadimak je obavezan',
  'nicknameTooLong': 'Nadimak ne sme biti duži od 30 znakova',
  // Level top strings
  'levelTopCount': 'Rejting ({count})',
  'levelTopCountShort': 'Rejting ({count})',
  'retry': 'Pokušaj ponovo',
  'noLevelTopData': 'Nema podataka',
  'remoteBattlefront': 'Udaljeni front',
  'participated': 'Učestvovao',
  'notParticipated': 'Nije učestvovao',
  'loadMore': 'Učitaj više',
  'joinBattle': 'Pridruži se borbi',
  'joinBattleTooltip': 'Pridruži se borbi \'{name}\'',
  'joinBattleConfirm':
      'Da li ste sigurni da želite da se pridružite borbi \'{name}\'?',
  'joinBattleSuccess': 'Uspešno ste se pridružili borbi \'{name}\'',
  'joinBattleErrorSelf': 'Ne možete se pridružiti svom sopstvenom frontu',
  'replayBattlefront': 'Ponovo pokreni front',
  'replayBattlefrontTooltip': 'Ponovo pokreni front \'{name}\'',
  'getReplayBattlefrontConfirm':
      'Da li ste sigurni da želite da ponovo pokrenete \'{name}\'?',
  'getReplayBattlefrontFailed':
      'Ponovno pokretanje \'{name}\' nije uspelo: {error}',
  'download': 'Preuzmi',
  'downloadBattlefront': 'Preuzmi front',
  'downloadBattlefrontTooltip': 'Preuzmi front \'{name}\'',
  'getDownloadBattlefrontConfirm':
      'Da li ste sigurni da želite da preuzmete \'{name}\'?',
  'getDownloadBattlefrontSuccess': '\'{name}\' uspešno preuzet',
  'downloadMyOwnBattlefrontError':
      'Možete preuzeti samo svoje sopstvene frontove',
  'getDownloadBattlefrontFailed': 'Preuzimanje \'{name}\' nije uspelo: {error}',
  'continueGameShort': 'Nastavi borbu',
  'replayShort': 'Ponovo',
  'highestLevel': 'Nivo {level}',
  'deviceNickname': 'Uređaj',
  'createdTime': 'Vreme kreiranja',
  'remoteBattlefrontDetail': 'Detalji udaljenog fronta',
  'levelList': 'Lista nivoa',
  'fastClearTimeParam': 'Vreme završetka: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint': 'Izaberite lokalni front za pregled detalja',
  'loadingRemoteDetail': 'Učitavanje detalja udaljenog fronta...',
  'noRemoteBattlefrontSelected': 'Nije izabran udaljeni front',
  'failedToLoadRemoteDetail': 'Učitavanje detalja nije uspelo',
  'fastestRecord': 'Najbrži završetak',
  'safestRecord': 'Najbezbedniji završetak',
  'fastestRecordDesc': 'Najbrže (najmanje vremena)',
  'safestRecordDesc': 'Najbezbednije (najmanje akcija)',
  'creator': 'Kreator',
  'player': 'Igrač',
  // Branch maps
  'getBranchMapCount': '{count} kopija',
  'collapse': 'Skupi',
  'expand': 'Proširi',
  // Quit battlefront
  'quitBattlefront': 'Napusti front',
  'quitBattlefrontTooltip': 'Napusti udaljeni front',
  'quitBattlefrontTitle': 'Napusti front',
  'quitBattlefrontContent':
      'Da li ste sigurni da želite da napustite front \'{name}\'? Vaš lokalni napredak biće obrisan.',
  // Download page
  'downloadClient': 'Preuzmi klijenta',
  'browser': 'Pretraživač',
  'browserDesc': 'Igrajte direktno u pretraživaču, bez preuzimanja',
  'windowsDesc': 'Za Windows 10 i novije verzije',
  'macosDesc': 'Za macOS 10.15 i novije verzije',
  'android': 'Android',
  'androidDesc': 'Za Android 8.0 i novije verzije',
  'iosDesc': 'Za iOS 14.0 i novije verzije',
  'linkAddress': 'Adresa veze',
  'downloadLink': 'Veza za preuzimanje',
  'qrCode': 'QR kod',
  'scanToDownload': 'Skenirajte telefonom za preuzimanje',
  'copy': 'Kopiraj',
  'copiedToClipboard': 'Kopirano u klipbord',
  'openLink': 'Otvori vezu',
  'cannotOpenLink': 'Ne može da se otvori veza',
  // Game introduction
  'gameIntroduction':
      '1. „Početnik“ počinje sa 15 mina, maksimalno do 99 mina;\n2. „Novi front“ počinje sa 81 mina, broj se povećava svaki nivo, bez gornje granice.\n3. U mreži, završeni frontovi se automatski dele u oblaku za druge igrače.',
};
