// Polish（波兰语）
/// Polish language strings for the DMine application
const Map<String, String> stringsPl = {
  'appLabel': 'Najlepsze Saper',
  'appTitle': 'DMine - Najlepsze Saper',
  'settings': 'Ustawienia',
  'gameSettings': 'Ustawienia gry',
  'showTimer': 'Pokaż licznik czasu',
  'showTimerDesc': 'Wyświetla licznik czasu gry na ekranie gry',
  'showActionCounter': 'Pokaż licznik akcji',
  'showActionCounterDesc': 'Wyświetla liczbę wykonanych akcji na ekranie gry',
  'autoAdjustBoardWidth': 'Automatycznie dopasuj szerokość planszy',
  'autoAdjustBoardWidthDesc':
      'Automatycznie dostosuj szerokość planszy do rozmiaru ekranu',
  'resetToDefaults': 'Przywróć domyślne ustawienia',
  'resetToDefaultsDesc': 'Przywróć wszystkie ustawienia do wartości domyślnych',
  'aboutDMine': 'O DMine',
  'version': 'Wersja',
  'close': 'Zamknij',
  'manualBoardWidth': 'Ręcznie ustaw szerokość planszy',
  'currentWidth': 'Aktualnie',
  'range': 'Zakres',
  'widthSliderHint':
      'Wskazówka: podczas przesuwania suwaka można natychmiast zobaczyć zmianę szerokości planszy',
  'gameRecords': 'Rekordy gry',
  'selectMapToViewRecords': 'Wybierz mapę, aby zobaczyć rekordy',
  'totalRecords': 'Łącznie',
  'gameRecordsTitle': 'Lista rekordów gry',
  'pleaseSelectMapFirst': 'Najpierw wybierz mapę',
  'noGameRecords': 'Brak rekordów gry',
  'miningMethodFlag': 'Oznacz flagą',
  'miningMethodBlind': 'Odkrywanie na ślepo',
  'statusPlaying': '▶️ W trakcie...',
  'statusWin': '🎉 Wygrana',
  'statusLose': '💥 Przegrana',
  'actionsCount': 'Liczba akcji',
  'miningMethod': 'Sposób gry',
  'duration': 'Czas trwania',
  'seconds': 'sekund',
  'startTime': 'Czas rozpoczęcia',
  'endTime': 'Czas zakończenia',
  'pauseTime': 'Czas pauzy',
  'unlock': 'Odblokuj',
  'lock': 'Zablokuj',
  'delete': 'Usuń',
  'languageSetting': 'Ustawienia języka',
  'currentLanguage': 'Aktualnie',
  'systemLanguage': 'Język systemowy',
  'chinese': 'Chiński',
  'english': 'Angielski',
  'language': 'Język',
  // Home page
  'newbie': 'Początkujący',
  'newBattle': 'Nowa linia frontu',
  'continueChallenge': 'Kontynuuj wyzwanie',
  'error': 'Błąd',
  'initializationFailed': 'Inicjalizacja nie powiodła się',
  // Game page
  'congratulations': 'Gratulacje, ukończono poziom!',
  'gameOver': 'Koniec gry',
  'timeUsed': 'Czas',
  'actionCount': 'Liczba akcji',
  'mineCount': 'Liczba min',
  'nextLevel': 'Następny poziom: Poziom {level}',
  'newbieNextLevel': 'Następny poziom: Początkujący {level}',
  'nextLevelMines': 'Liczba min',
  'mineIncrease': 'Zwiększenie',
  'newbieFinish': 'Tryb początkujący ukończony',
  'ok': 'OK',
  'continueNextLevel': 'Kontynuuj następny poziom',
  'restart': 'Zacznij od nowa',
  'level': 'Poziom {level}',
  'newbieLevel': 'Początkujący {level}',
  'operationFailed': 'Operacja nie powiodła się',
  // Game status texts
  'returnHome': 'Wróć do menu',
  'revealMode': 'Tryb odkrywania',
  'flagMode': 'Tryb flagowania',
  'newMap': 'Nowa mapa (ta sama liczba min, nowy układ)',
  'resetMap': 'Przywróć mapę (ten sam układ, reset stanu)',
  'zoomOut': 'Pomniejsz',
  'zoomIn': 'Powiększ',
  'resetZoom': 'Przywróć domyślny rozmiar',
  'previousStep': 'Poprzedni krok',
  'pause': 'Pauza',
  'play': 'Graj',
  'nextStep': 'Następny krok',
  'clickToStart': 'Kliknij dowolne pole, aby rozpocząć grę',
  'playing': 'W trakcie gry...',
  'gameWin': 'Gratulacje, ukończono poziom!',
  'gameLose': 'Koniec gry, wkroczyłeś na minę',
  'gamePaused': 'Gra wstrzymana',
  'ready': 'Gotowe do rozpoczęcia',
  'clickStartShort': 'Kliknij, aby zacząć',
  'playingShort': 'W grze',
  'winShort': 'Ukończono!',
  'loseShort': 'Przegrana',
  'pausedShort': 'Wstrzymano',
  // Counter strings
  'currentLevel': 'Aktualny poziom',
  'remainingMines': 'Pozostałe miny',
  'gameTime': 'Czas gry (sekundy)',
  'operationCount': 'Liczba operacji',
  'previousLevel': 'Poprzedni poziom',
  'nextLevelShort': 'Następny poziom',
  // Battlefront strings
  'completed': 'Ukończono',
  'inProgress': 'W trakcie',
  'continueGame': 'Kontynuuj grę',
  'replay': 'Powtórz',
  'creater': 'Dowódca',
  'created': 'Czas rozpoczęcia',
  'updated': 'Zaktualizowano',
  // Dialog strings
  'confirm': 'Potwierdź',
  'cancel': 'Anuluj',
  'yes': 'Tak',
  'no': 'Nie',
  'save': 'Zapisz',
  'edit': 'Edytuj',
  'levelFormat': 'Poziom {level}',
  'newbieLevelFormat': 'Początkujący {level}',
  'totalLevel': '{level}/{totalLevel} poziomów',
  'totalLevelTooltip': 'Aktualnie: Poziom {level} / Łącznie {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Brak linii frontu',
  'battlefrontCount': '{count} linii frontu',
  'levelPrefix': 'POZ{level}',
  'newbieLevelPrefix': 'Początkujący POZ{level}',
  'minesCount': '{count} min',
  'notStarted': 'Nie rozpoczęto',
  'victory': 'Wygrana',
  'defeat': 'Przegrana',
  'gameDurationParam': 'Czas: {seconds} s',
  'actionsCountParam': 'Akcje: {count} razy',
  'actionsCountParamShort': '{count} razy',
  'miningMethodParam': 'Sposób: {method}',
  'startTimeParam': 'Czas rozpoczęcia: {time}',
  'endTimeParam': 'Czas zakończenia: {time}',
  'returnButton': 'Wróć',
  'battlefrontDetails': 'Szczegóły linii frontu',
  'clickToEditName': 'Kliknij, aby zmienić nazwę',
  'clickToAddDescription': 'Kliknij, aby dodać opis...',
  'noDescription': 'Brak opisu',
  // Level record strings
  'levelCount': '{count} poziomów',
  'noLevelRecords': 'Wybierz linię frontu',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Usuń linię frontu',
  'deleteBattlefrontContent':
      'Czy na pewno chcesz usunąć linię frontu \'{name}\'? Tej operacji nie można cofnąć.',
  'battlefrontLockedCannotDelete': 'Linia frontu zablokowana, nie można usunąć',
  'unknownNavigationLevel': 'Nieznany poziom',
  'noBattlefrontSelected': 'Nie wybrano linii frontu',
  'noBattlefrontToContinue': 'Nie znaleziono linii frontu do kontynuacji',
  'synced': 'Zsynchronizowano',
  'notSynced': 'Nie zsynchronizowano',
  'newbieBattlefrontName': 'Linia frontu początkującego {number}',
  'battlefrontName': 'Linia frontu {number}',
  'nickname': 'Pseudonim',
  'nicknameSetting': 'Ustawienia pseudonimu',
  'nicknameDesc': 'Ustaw swój pseudonim',
  'enterNickname': 'Wprowadź pseudonim',
  'nicknameSaved': 'Pseudonim zapisany',
  'nicknameUpdated': 'Pseudonim zaktualizowany',
  'nicknameRequired': 'Pseudonim jest wymagany',
  'nicknameTooLong': 'Pseudonim nie może mieć więcej niż 30 znaków',
  // Level top strings
  'levelTopCount': 'Ranking ({count})',
  'levelTopCountShort': 'Ranking ({count})',
  'retry': 'Spróbuj ponownie',
  'noLevelTopData': 'Brak danych',
  'remoteBattlefront': 'Zdalna linia frontu',
  'participated': 'Uczestniczył',
  'notParticipated': 'Nie uczestniczył',
  'loadMore': 'Wczytaj więcej',
  'joinBattle': 'Dołącz do walki',
  'joinBattleTooltip': 'Dołącz do walki \'{name}\'',
  'joinBattleConfirm': 'Czy na pewno chcesz dołączyć do walki \'{name}\'?',
  'joinBattleSuccess': 'Pomyślnie dołączono do walki \'{name}\'',
  'joinBattleErrorSelf': 'Nie możesz dołączyć do własnej linii frontu',
  'replayBattlefront': 'Odtwórz linię frontu',
  'replayBattlefrontTooltip': 'Odtwórz linię frontu \'{name}\'',
  'getReplayBattlefrontConfirm': 'Czy na pewno chcesz odtworzyć \'{name}\'?',
  'getReplayBattlefrontFailed': 'Nie udało się odtworzyć \'{name}\': {error}',
  'download': 'Pobierz',
  'downloadBattlefront': 'Pobierz linię frontu',
  'downloadBattlefrontTooltip': 'Pobierz linię frontu \'{name}\'',
  'getDownloadBattlefrontConfirm': 'Czy na pewno chcesz pobrać \'{name}\'?',
  'getDownloadBattlefrontSuccess': 'Pomyślnie pobrano \'{name}\'',
  'downloadMyOwnBattlefrontError': 'Możesz pobierać tylko własne linie frontu',
  'getDownloadBattlefrontFailed': 'Nie udało się pobrać \'{name}\': {error}',
  'continueGameShort': 'Kontynuuj walkę',
  'replayShort': 'Odtwórz',
  'highestLevel': 'Poziom {level}',
  'deviceNickname': 'Urządzenie',
  'createdTime': 'Czas utworzenia',
  'remoteBattlefrontDetail': 'Szczegóły linii frontu',
  'levelList': 'Lista poziomów',
  'fastClearTimeParam': 'Czas ukończenia: {time}',
  // Szczegóły zdalnej linii frontu
  'selectLocalBattlefrontHint':
      'Wybierz lokalną linię frontu, aby zobaczyć szczegóły',
  'loadingRemoteDetail': 'Ładowanie szczegółów zdalnej linii frontu...',
  'noRemoteBattlefrontSelected': 'Nie wybrano zdalnej linii frontu',
  'failedToLoadRemoteDetail': 'Nie udało się załadować szczegółów',
  'fastestRecord': 'Najszybsze ukończenie',
  'safestRecord': 'Najbezpieczniejsze ukończenie',
  'fastestRecordDesc': 'Najszybsze (najmniej czasu)',
  'safestRecordDesc': 'Najbezpieczniejsze (najmniej akcji)',
  'creator': 'Twórca',
  'player': 'Gracz',
  // Mapki rozgałęzione
  'getBranchMapCount': '{count} kopii',
  'collapse': 'Zwiń',
  'expand': 'Rozwiń',
  // Wyjście z linii frontu
  'quitBattlefront': 'Opuść linię frontu',
  'quitBattlefrontTooltip': 'Opuść zdalną linię frontu',
  'quitBattlefrontTitle': 'Opuść linię frontu',
  'quitBattlefrontContent':
      'Czy na pewno chcesz opuścić linię frontu \'{name}\'? Twój lokalny postęp zostanie usunięty.',
  // Strona pobierania
  'downloadClient': 'Pobierz klienta',
  'browser': 'Przeglądarka',
  'browserDesc': 'Graj bezpośrednio w przeglądarce, bez pobierania',
  'windowsDesc': 'Dla systemu Windows 10 i nowszego',
  'macosDesc': 'Dla systemu macOS 10.15 i nowszego',
  'android': 'Android',
  'androidDesc': 'Dla systemu Android 8.0 i nowszego',
  'iosDesc': 'Dla systemu iOS 14.0 i nowszego',
  'linkAddress': 'Adres linku',
  'downloadLink': 'Link do pobrania',
  'qrCode': 'Kod QR',
  'scanToDownload': 'Zeskanuj kod, aby pobrać na telefon',
  'copy': 'Kopiuj',
  'copiedToClipboard': 'Skopiowano do schowka',
  'openLink': 'Otwórz link',
  'cannotOpenLink': 'Nie można otworzyć linku',
  // Opis gry
  'gameIntroduction':
      '1. „Początkujący” zaczyna od 15 min, maksymalnie do 99 min;\n2. „Nowa linia frontu” zaczyna od 81 min, co poziom liczba min rośnie, bez górnego limitu.\n3. W trybie online ukończone linie frontu są automatycznie udostępniane w chmurze do nauki dla innych.',
};
