// Italian（意大利语）
/// Stringhe in italiano per l'app DMine
const Map<String, String> stringsIt = {
  'appTitle': 'DMine - Minesweeper Premium',
  'settings': 'Impostazioni',
  'gameSettings': 'Impostazioni di gioco',
  'showTimer': 'Mostra timer',
  'showTimerDesc': 'Mostra il timer di gioco nell\'interfaccia',
  'showActionCounter': 'Mostra contatore azioni',
  'showActionCounterDesc':
      'Mostra il numero di azioni nell\'interfaccia di gioco',
  'autoAdjustBoardWidth': 'Regola larghezza tavola automaticamente',
  'autoAdjustBoardWidthDesc':
      'Adatta la larghezza della tavola alle dimensioni dello schermo',
  'resetToDefaults': 'Ripristina impostazioni predefinite',
  'resetToDefaultsDesc': 'Ripristina tutte le impostazioni ai valori originali',
  'aboutDMine': 'Informazioni su DMine',
  'version': 'Versione',
  'close': 'Chiudi',
  'manualBoardWidth': 'Imposta larghezza tavola manualmente',
  'currentWidth': 'Attuale',
  'range': 'Intervallo',
  'widthSliderHint':
      'Suggerimento: puoi vedere le modifiche alla larghezza in tempo reale trascinando il cursore',
  'gameRecords': 'Record di gioco',
  'selectMapToViewRecords': 'Seleziona una mappa per vedere i record',
  'totalRecords': 'Totale',
  'gameRecordsTitle': 'Elenco record di gioco',
  'pleaseSelectMapFirst': 'Seleziona prima una mappa',
  'noGameRecords': 'Nessun record di gioco',
  'miningMethodFlag': 'Posiziona bandiera',
  'miningMethodBlind': 'Ricerca alla cieca',
  'statusPlaying': '▶️ In gioco...',
  'statusWin': '🎉 Vittoria',
  'statusLose': '💥 Sconfitta',
  'actionsCount': 'Numero di azioni',
  'miningMethod': 'Metodo di ricerca mine',
  'duration': 'Durata',
  'seconds': 'secondi',
  'startTime': 'Ora inizio',
  'endTime': 'Ora fine',
  'pauseTime': 'Tempo di pausa',
  'unlock': 'Sblocca',
  'lock': 'Blocca',
  'delete': 'Elimina',
  'languageSetting': 'Impostazione lingua',
  'currentLanguage': 'Attuale',
  'systemLanguage': 'Lingua di sistema',
  'chinese': 'Cinese',
  'english': 'Inglese',
  'language': 'Lingua',
  // Home page
  'newbie': 'Principiante',
  'newBattle': 'Nuovo fronte',
  'continueChallenge': 'Continua la sfida',
  'error': 'Errore',
  'initializationFailed': 'Inizializzazione fallita',
  // Game page
  'congratulations': 'Complimenti, hai completato il livello!',
  'gameOver': 'Fine gioco',
  'timeUsed': 'Tempo impiegato',
  'actionCount': 'Numero di azioni',
  'mineCount': 'Numero di mine',
  'nextLevel': 'Livello successivo: Livello {level}',
  'newbieNextLevel': 'Livello successivo: Principiante {level}',
  'nextLevelMines': 'Numero di mine',
  'mineIncrease': 'Aumento',
  'newbieFinish': 'Tutorial per principianti completato',
  'ok': 'OK',
  'continueNextLevel': 'Vai al livello successivo',
  'restart': 'Riavvia',
  'level': 'Livello {level}',
  'newbieLevel': 'Livello principiante {level}',
  'operationFailed': 'Operazione fallita',
  // Game status texts
  'returnHome': 'Torna alla home',
  'revealMode': 'Modalità scopri',
  'flagMode': 'Modalità bandiera',
  'newMap': 'Nuova mappa (stesso numero di mine, crea nuova mappa)',
  'resetMap': 'Ricarica mappa (stessa mappa, ripristina stato)',
  'zoomOut': 'Riduci zoom',
  'zoomIn': 'Ingrandisci zoom',
  'resetZoom': 'Ripristina zoom',
  'previousStep': 'Passo precedente',
  'pause': 'Pausa',
  'play': 'Gioca',
  'nextStep': 'Passo successivo',
  'clickToStart': 'Clicca su qualsiasi cella per iniziare il gioco',
  'playing': 'In gioco...',
  'gameWin': 'Complimenti, hai completato il livello!',
  'gameLose': 'Fine gioco, hai colpito una mina',
  'gamePaused': 'Gioco in pausa',
  'ready': 'Pronto',
  'clickStartShort': 'Clicca per iniziare',
  'playingShort': 'In corso',
  'winShort': 'Completato!',
  'loseShort': 'Mina colpita',
  'pausedShort': 'In pausa',
  // Counter strings
  'currentLevel': 'Livello attuale',
  'remainingMines': 'Mine rimanenti',
  'gameTime': 'Tempo di gioco (secondi)',
  'operationCount': 'Numero di operazioni',
  'previousLevel': 'Livello precedente',
  'nextLevelShort': 'Livello successivo',
  // Battlefront strings
  'completed': 'Completato',
  'inProgress': 'In corso',
  'continueGame': 'Continua gioco',
  'replay': 'Rigioca',
  'creater': 'Comandante',
  'created': 'Ora inizio battaglia',
  'updated': 'Aggiornato',
  // Dialog strings
  'confirm': 'Conferma',
  'cancel': 'Annulla',
  'yes': 'Sì',
  'no': 'No',
  'save': 'Salva',
  'edit': 'Modifica',
  'levelFormat': 'Livello {level}',
  'newbieLevelFormat': 'Livello principiante {level}',
  'totalLevel': '{level}/{totalLevel} livelli',
  'totalLevelTooltip': 'Attuale: Livello {level} / Totale {totalLevel} livelli',
  // Battlefront UI strings
  'noBattlefronts': 'Nessun fronte',
  'battlefrontCount': '{count} fronti',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'PR{level}',
  'minesCount': '{count} mine',
  'notStarted': 'Non iniziato',
  'victory': 'Vittoria',
  'defeat': 'Sconfitta',
  'gameDurationParam': 'Durata: {seconds} secondi',
  'actionsCountParam': 'Azioni: {count} volte',
  'actionsCountParamShort': '{count} volte',
  'miningMethodParam': 'Metodo: {method}',
  'startTimeParam': 'Inizio: {time}',
  'endTimeParam': 'Fine: {time}',
  'returnButton': 'Indietro',
  'battlefrontDetails': 'Dettagli fronte',
  'clickToEditName': 'Clicca per modificare il nome',
  'clickToAddDescription': 'Clicca per aggiungere descrizione...',
  'noDescription': 'Nessuna descrizione',
  // Level record strings
  'levelCount': '{count} livelli',
  'noLevelRecords': 'Seleziona un fronte',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Elimina fronte',
  'deleteBattlefrontContent':
      'Sei sicuro di voler eliminare il fronte "{name}"? Questa azione non può essere annullata.',
  'battlefrontLockedCannotDelete': 'Fronte bloccato, impossibile eliminare',
  'unknownNavigationLevel': 'Livello navigazione sconosciuto',
  'noBattlefrontSelected': 'Nessun fronte selezionato',
  'noBattlefrontToContinue': 'Nessun fronte da continuare',
  'synced': 'Sincronizzato',
  'notSynced': 'Non sincronizzato',
  'newbieBattlefrontName': 'Fronte principiante {number}',
  'battlefrontName': 'Fronte {number}',
  'nickname': 'Nickname',
  'nicknameSetting': 'Impostazione nickname',
  'nicknameDesc': 'Imposta il tuo nickname',
  'enterNickname': 'Inserisci nickname',
  'nicknameSaved': 'Nickname salvato',
  'nicknameUpdated': 'Nickname aggiornato',
  'nicknameRequired': 'Nickname obbligatorio',
  'nicknameTooLong': 'Nickname non può superare i 30 caratteri',
  // Level top strings
  'levelTopCount': 'Classifica ({count})',
  'levelTopCountShort': 'Classifica ({count})',
  'retry': 'Riprova',
  'noLevelTopData': 'Nessun dato',
  'remoteBattlefront': 'Fronte remoto',
  'participated': 'Ha partecipato',
  'notParticipated': 'Non ha partecipato',
  'loadMore': 'Carica altro',

  'joinBattle': 'Uniti alla battaglia',
  'joinBattleTooltip': 'Uniti alla battaglia "{name}"',
  'joinBattleConfirm':
      'Sei sicuro di voler partecipare alla battaglia "{name}"?',
  'joinBattleSuccess': 'Ti sei unito con successo alla battaglia "{name}"',
  'joinBattleErrorSelf': 'Non puoi unirti al tuo stesso fronte',

  'replayBattlefront': 'Rigioca fronte',
  'replayBattlefrontTooltip': 'Rigioca il fronte "{name}"',
  'getReplayBattlefrontConfirm': 'Sei sicuro di voler rigiocare "{name}"?',
  'getReplayBattlefrontFailed': 'Impossibile rigiocare "{name}": {error}',

  'download': 'Scarica',
  'downloadBattlefront': 'Scarica fronte',
  'downloadBattlefrontTooltip': 'Scarica il fronte "{name}"',
  'getDownloadBattlefrontConfirm': 'Sei sicuro di voler scaricare "{name}"?',
  'getDownloadBattlefrontSuccess': 'Fronte "{name}" scaricato con successo',
  'downloadMyOwnBattlefrontError': 'Puoi scaricare solo i tuoi fronti',
  'getDownloadBattlefrontFailed': 'Scaricamento di "{name}" fallito: {error}',

  'continueGameShort': 'Continua battaglia',
  'replayShort': 'Rigioca',
  'highestLevel': 'Livello {level}',
  'deviceNickname': 'Dispositivo',
  'createdTime': 'Ora creazione',
  'remoteBattlefrontDetail': 'Dettagli fronte remoto',
  'levelList': 'Elenco livelli',
  'fastClearTimeParam': 'Tempo completamento: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Seleziona un fronte locale per vedere i dettagli',
  'loadingRemoteDetail': 'Caricamento dettagli fronte remoto...',
  'noRemoteBattlefrontSelected': 'Nessun fronte remoto selezionato',
  'failedToLoadRemoteDetail': 'Caricamento dettagli remoti fallito',
  'fastestRecord': 'Completamento più veloce',
  'safestRecord': 'Completamento più sicuro',
  'fastestRecordDesc': 'Completamento più veloce (meno tempo)',
  'safestRecordDesc': 'Completamento più sicuro (meno azioni)',
  'creator': 'Creatore',
  'player': 'Giocatore',
  // 分支地图字符串
  'getBranchMapCount': '{count} copie',
  'collapse': 'Comprimi',
  'expand': 'Espandi',
  // 退出战线
  'quitBattlefront': 'Abbandona fronte',
  'quitBattlefrontTooltip': 'Abbandona fronte remoto',
  'quitBattlefrontTitle': 'Abbandona fronte',
  'quitBattlefrontContent':
      'Sei sicuro di voler abbandonare il fronte "{name}"? I tuoi progressi locali verranno eliminati.',

  // 下载页面
  'downloadClient': 'Scarica client',
  'browser': 'Browser',
  'browserDesc': 'Gioca direttamente nel browser, senza scaricare',
  'windowsDesc': 'Per Windows 10 e versioni successive',
  'macosDesc': 'Per macOS 10.15 e versioni successive',
  'android': 'Android',
  'androidDesc': 'Per Android 8.0 e versioni successive',
  'iosDesc': 'Per iOS 14.0 e versioni successive',
  'linkAddress': 'Indirizzo link',
  'downloadLink': 'Link di download',
  'qrCode': 'Codice QR',
  'scanToDownload': 'Scansiona con il telefono per scaricare',
  'copy': 'Copia',
  'copiedToClipboard': 'Copiato negli appunti',
  'openLink': 'Apri link',
  'cannotOpenLink': 'Impossibile aprire il link',
  // 游戏介绍
  'gameIntroduction':
      '1. Il "Principiante" inizia con 15 mine e può arrivare fino a 99 mine.\n2. Il "Nuovo fronte" inizia con 81 mine, ogni livello aggiunge mine senza limite superiore.\n3. Con connessione internet, i fronti "completati" vengono condivisi automaticamente nel cloud per gli altri.',
};
