// NorwegianNynorsk（新挪威语）
/// Norsk nynorsk tekst for appen DMine
const Map<String, String> stringsNn = {
  'appLabel': 'Minesweeper Premium',
  'appTitle': 'DMine - Minesweeper Premium',
  'settings': 'Innstillingar',
  'gameSettings': 'Spinnstillingar',
  'showTimer': 'Vis timer',
  'showTimerDesc': 'Vis speltida i brukargrensesnittet',
  'showActionCounter': 'Vis handlingsteller',
  'showActionCounterDesc': 'Vis talet på handlingar gjort i spelet',
  'autoAdjustBoardWidth': 'Juster brettbreidde automatisk',
  'autoAdjustBoardWidthDesc':
      'Tilpass brettbreidde automatisk etter skjermstorleik',
  'resetToDefaults': 'Tilbakestill til standard',
  'resetToDefaultsDesc':
      'Tilbakestill alle innstillingar til opprunnelege verdiar',
  'aboutDMine': 'Om DMine',
  'version': 'Versjon',
  'close': 'Lukk',
  'manualBoardWidth': 'Manuell brettbreidde',
  'currentWidth': 'Noverande',
  'range': 'Område',
  'widthSliderHint': 'Tips: Dra glidebryteren for å sjå endringar i sanntid',
  'gameRecords': 'Spelresultat',
  'selectMapToViewRecords': 'Vel eit kart for å sjå resultat',
  'totalRecords': 'Totalt',
  'gameRecordsTitle': 'Liste over spelresultat',
  'pleaseSelectMapFirst': 'Vel først eit kart',
  'noGameRecords': 'Ingen spelresultat',
  'miningMethodFlag': 'Merke med flagg',
  'miningMethodBlind': 'Blind søkjing',
  'statusPlaying': '▶️ Spelar...',
  'statusWin': '🎉 Vunne!',
  'statusLose': '💥 Tapt!',
  'actionsCount': 'Tal på handlingar',
  'miningMethod': 'Mine søkjemetode',
  'duration': 'Varleik',
  'seconds': 'sekund',
  'startTime': 'Starttid',
  'endTime': 'Sluttid',
  'pauseTime': 'Pausetid',
  'unlock': 'Lås opp',
  'lock': 'Lås',
  'delete': 'Slett',
  'languageSetting': 'Språkinnstillingar',
  'currentLanguage': 'Noverande språk',
  'systemLanguage': 'Systemspråk',
  'chinese': 'Kinesisk',
  'english': 'Engelsk',
  'language': 'Språk',
  // Home page
  'newbie': 'Nybyrjar',
  'gameIntro': 'Spelintroduksjon',
  'newBattle': 'Ny front',
  'continueChallenge': 'Hald fram utfordringa',
  'error': 'Feil',
  'initializationFailed': 'Initialisering mislukkast',
  // Game page
  'congratulations': 'Gratulerer! Du fullførte nivået!',
  'gameOver': 'Spelet er over',
  'timeUsed': 'Brukt tid',
  'actionCount': 'Tal på handlingar',
  'mineCount': 'Tal på miner',
  'nextLevel': 'Neste nivå: Nivå {level}',
  'newbieNextLevel': 'Neste nivå: Nybyrjar {level}',
  'nextLevelMines': 'Tal på miner',
  'mineIncrease': 'Økning',
  'newbieFinish': 'Nybyrjar ferdig',
  'ok': 'OK',
  'continueNextLevel': 'Gå til neste nivå',
  'restart': 'Start på nytt',
  'level': 'Nivå {level}',
  'newbieLevel': 'Nybyrjar-nivå {level}',
  'operationFailed': 'Handling mislukkast',
  // Game status texts
  'returnHome': 'Tilbake til heimen',
  'revealMode': 'Opne modus',
  'flagMode': 'Flaggmodus',
  'newMap': 'Nytt kart (samme tal på miner)',
  'resetMap': 'Tilbakestill kart',
  'zoomOut': 'Forminske',
  'zoomIn': 'Forstørre',
  'resetZoom': 'Tilbakestill zoom',
  'previousStep': 'Førre trinn',
  'pause': 'Pause',
  'play': 'Spel',
  'nextStep': 'Neste trinn',
  'clickToStart': 'Klikk ein rute for å starte',
  'playing': 'Spelar...',
  'gameWin': 'Gratulerer! Du fullførte nivået!',
  'gameLose': 'Spelet er over, du traff ein mine',
  'gamePaused': 'Spel sett på pause',
  'ready': 'Klar',
  'clickStartShort': 'Klikk for å starte',
  'playingShort': 'Spelar',
  'winShort': 'Vunne!',
  'loseShort': 'Traff ein mine',
  'pausedShort': 'Pause',
  // Counter strings
  'currentLevel': 'Noverande nivå',
  'remainingMines': 'Gjenverande miner',
  'gameTime': 'Speltid (sekund)',
  'operationCount': 'Tal på handlingar',
  'previousLevel': 'Førre nivå',
  'nextLevelShort': 'Neste nivå',
  // Battlefront strings
  'completed': 'Fullført',
  'inProgress': 'Pågår',
  'continueGame': 'Hald fram spelet',
  'replay': 'Spel på nytt',
  'creater': 'Opprettar',
  'created': 'Oppretta',
  'updated': 'Oppdatert',
  // Dialog strings
  'confirm': 'Bekreft',
  'cancel': 'Avbryt',
  'yes': 'Ja',
  'no': 'Nei',
  'save': 'Lagra',
  'edit': 'Rediger',
  'levelFormat': 'Nivå {level}',
  'newbieLevelFormat': 'Nybyrjar-nivå {level}',
  'totalLevel': '{level}/{totalLevel} nivå',
  'totalLevelTooltip': 'No: Nivå {level} / Totalt {totalLevel} nivå',
  // Battlefront UI strings
  'noBattlefronts': 'Ingen fronter',
  'battlefrontCount': '{count} fronter',
  'levelPrefix': 'NIV{level}',
  'newbiePrefix': 'NYB{level}',
  'minesCount': '{count} miner',
  'notStarted': 'Ikke starta',
  'victory': 'Siger',
  'defeat': 'Nedlag',
  'gameDurationParam': 'Varleik: {seconds} sekund',
  'actionsCountParam': 'Handlingar: {count} gonger',
  'actionsCountShort': '{count} gonger',
  'miningMethodParam': 'Metode: {method}',
  'startTimeParam': 'Start: {time}',
  'endTimeParam': 'Slutt: {time}',
  'returnButton': 'Tilbake',
  'battlefrontDetails': 'Frontdetaljar',
  'clickToEditName': 'Klikk for å redigere namn',
  'clickToAddDescription': 'Klikk for å leggje til skildring...',
  'noDescription': 'Ingen skildring',
  // Level record strings
  'levelCount': '{count} nivå',
  'noLevelRecords': 'Vel ein front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Slett front',
  'deleteBattlefrontContent':
      'Er du sikker på at du vil slette fronten «{name}»? Denne handlinga kan ikkje angrefast.',
  'battlefrontLockedCannotDelete': 'Fronten er låst, kan ikkje slettast',
  'unknownNavigationLevel': 'Ukjend navigasjonsnivå',
  'noBattlefrontSelected': 'Ingen front vald',
  'noBattlefrontToContinue': 'Ingen front å halde fram på',
  'synced': 'Synkronisert',
  'notSynced': 'Ikke synkronisert',
  'newbieBattlefrontName': 'Nybyrjar-front {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Kallenamn',
  'nicknameSetting': 'Kallenavnsinnstillingar',
  'nicknameDesc': 'Vel ditt kallenavn',
  'enterNickname': 'Skriv inn kallenavn',
  'nicknameSaved': 'Kallenavn lagra',
  'nicknameUpdated': 'Kallenavn oppdatert',
  'nicknameRequired': 'Kallenavn er påkravd',
  'nicknameTooLong': 'Kallenavn kan ikkje vere lengre enn 30 teikn',
  // Level top strings
  'levelTopCount': 'Rangering ({count})',
  'levelTopCountShort': 'Rangering ({count})',
  'retry': 'Prøv igjen',
  'noLevelTopData': 'Ingen data',
  'remoteBattlefront': 'Ekstern front',
  'participated': 'Deltatt',
  'notParticipated': 'Ikke deltatt',
  'loadMore': 'Last meir',

  'joinBattle': 'Bli med i kampen',
  'joinBattleTooltip': 'Bli med i kampen «{name}»',
  'joinBattleConfirm': 'Er du sikker på at du vil delta i kampen «{name}»?',
  'joinBattleSuccess': 'Du vart med i kampen «{name}»',
  'joinBattleErrorSelf': 'Kan ikkje delta i eigen front',

  'replayBattlefront': 'Spel fronten på nytt',
  'replayBattlefrontTooltip': 'Spel fronten «{name}» på nytt',
  'getReplayBattlefrontConfirm':
      'Er du sikker på at du vil spel «{name}» på nytt?',
  'getReplayBattlefrontFailed': 'Kunne ikkje spel «{name}» på nytt: {error}',

  'download': 'Last ned',
  'downloadBattlefront': 'Last ned front',
  'downloadBattlefrontTooltip': 'Last ned fronten «{name}»',
  'getDownloadBattlefrontConfirm':
      'Er du sikker på at du vil laste ned «{name}»?',
  'getDownloadBattlefrontSuccess': 'Fronten «{name}» vart lasta ned',
  'downloadMyOwnBattlefrontError': 'Kan berre laste ned eigne fronter',
  'getDownloadBattlefrontFailed': 'Kunne ikkje laste ned «{name}»: {error}',

  'continueGameShort': 'Hald fram kampen',
  'replayShort': 'På nytt',
  'highestLevel': 'Nivå {level}',
  'deviceNickname': 'Eining',
  'createdTime': 'Opprettingstidspunkt',
  'remoteBattlefrontDetail': 'Detaljar for ekstern front',
  'levelList': 'Nivåliste',
  'fastClearTimeParam': 'Raskast tid: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Vel lokal front for å sjå detaljar',
  'loadingRemoteDetail': 'Lastar detaljar for ekstern front...',
  'noRemoteBattlefrontSelected': 'Ingen ekstern front vald',
  'failedToLoadRemoteDetail': 'Kunne ikkje hente eksterne data',
  'fastestRecord': 'Raskast fullført',
  'safestRecord': 'Sikkerast fullført',
  'fastestRecordDesc': 'Raskast fullført (minst tid)',
  'safestRecordDesc': 'Sikkerast fullført (færrast handlingar)',
  'creator': 'Opprettar',
  'player': 'Spelar',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopi',
  'collapse': 'Skjul',
  'expand': 'Vis',
  // 退出战线
  'quitBattlefront': 'Forlat fronten',
  'quitBattlefrontTooltip': 'Forlat ekstern front',
  'quitBattlefrontTitle': 'Forlat front',
  'quitBattlefrontContent':
      'Er du sikker på at du vil forlate fronten «{name}»? Framdrift blir sletta.',
  // 游戏介绍
  'gameIntroduction':
      '1. «Nybyrjar» startar med 15 miner og kan gå opp til 99 miner.\n2. «Ny front» startar med 81 miner, kvart nivå aukar talet utan øvre grense.\n3. Med internett vert fullførte fronter automatisk lagra i skyen.',
};
