// Korean（韩语）
/// DMine 애플리케이션 한국어 문자열
const Map<String, String> stringsKo = {
  'appTitle': 'DMine - 프리미엄 지뢰찾기',
  'settings': '설정',
  'gameSettings': '게임 설정',
  'showTimer': '타이머 표시',
  'showTimerDesc': '인터페이스에 게임 타이머를 표시합니다',
  'showActionCounter': '동작 횟수 표시',
  'showActionCounterDesc': '게임 화면에 동작 횟수를 표시합니다',
  'autoAdjustBoardWidth': '보드 너비 자동 조절',
  'autoAdjustBoardWidthDesc': '화면 크기에 맞춰 보드 너비를 자동으로 조절합니다',
  'resetToDefaults': '기본값으로 초기화',
  'resetToDefaultsDesc': '모든 설정을 원래 값으로 초기화합니다',
  'aboutDMine': 'DMine 정보',
  'version': '버전',
  'close': '닫기',
  'manualBoardWidth': '보드 너비 수동 설정',
  'currentWidth': '현재',
  'range': '범위',
  'widthSliderHint': '팁: 슬라이더를 드래그하면 실시간으로 보드 너비 변화를 확인할 수 있습니다',
  'gameRecords': '게임 기록',
  'selectMapToViewRecords': '기록을 볼 맵을 선택하세요',
  'totalRecords': '전체',
  'gameRecordsTitle': '게임 기록 목록',
  'pleaseSelectMapFirst': '먼저 맵을 선택해 주세요',
  'noGameRecords': '게임 기록이 없습니다',
  'miningMethodFlag': '깃발 표시',
  'miningMethodBlind': '블라인드 탐색',
  'statusPlaying': '▶️ 플레이 중...',
  'statusWin': '🎉 승리',
  'statusLose': '💥 패배',
  'actionsCount': '동작 횟수',
  'miningMethod': '지뢰 탐색 방식',
  'duration': '소요 시간',
  'seconds': '초',
  'startTime': '시작 시간',
  'endTime': '종료 시간',
  'pauseTime': '일시 정지 시간',
  'unlock': '잠금 해제',
  'lock': '잠금',
  'delete': '삭제',
  'languageSetting': '언어 설정',
  'currentLanguage': '현재',
  'systemLanguage': '시스템 언어',
  'chinese': '중국어',
  'english': '영어',
  'language': '언어',
  // Home page
  'newbie': '초보자',
  'newBattle': '새 전선',
  'continueChallenge': '도전 계속하기',
  'error': '오류',
  'initializationFailed': '초기화 실패',
  // Game page
  'congratulations': '축하합니다! 스테이지를 클리어했습니다!',
  'gameOver': '게임 오버',
  'timeUsed': '소요 시간',
  'actionCount': '동작 횟수',
  'mineCount': '지뢰 개수',
  'nextLevel': '다음 레벨: 레벨 {level}',
  'newbieNextLevel': '다음 레벨: 초보자 {level}',
  'nextLevelMines': '지뢰 개수',
  'mineIncrease': '증가량',
  'newbieFinish': '초보자 튜토리얼 완료',
  'ok': '확인',
  'continueNextLevel': '다음 레벨로',
  'restart': '다시 시작',
  'level': '레벨 {level}',
  'newbieLevel': '초보자 레벨 {level}',
  'operationFailed': '동작 실패',
  // Game status texts
  'returnHome': '홈으로 돌아가기',
  'revealMode': '열기 모드',
  'flagMode': '깃발 모드',
  'newMap': '새 맵 (지뢰 수 동일, 새로운 맵 생성)',
  'resetMap': '맵 다시 로드 (동일 맵, 상태 초기화)',
  'zoomOut': '축소',
  'zoomIn': '확대',
  'resetZoom': '줌 초기화',
  'previousStep': '이전 단계',
  'pause': '일시 정지',
  'play': '시작',
  'nextStep': '다음 단계',
  'clickToStart': '아무 칸이나 클릭하여 게임 시작',
  'playing': '플레이 중...',
  'gameWin': '축하합니다! 스테이지를 클리어했습니다!',
  'gameLose': '게임 오버, 지뢰를 밟았습니다',
  'gamePaused': '게임이 일시 정지되었습니다',
  'ready': '준비 완료',
  'clickStartShort': '클릭하여 시작',
  'playingShort': '진행 중',
  'winShort': '클리어!',
  'loseShort': '지뢰 폭발',
  'pausedShort': '일시 정지',
  // Counter strings
  'currentLevel': '현재 레벨',
  'remainingMines': '남은 지뢰',
  'gameTime': '게임 시간 (초)',
  'operationCount': '동작 횟수',
  'previousLevel': '이전 레벨',
  'nextLevelShort': '다음 레벨',
  // Battlefront strings
  'completed': '완료',
  'inProgress': '진행 중',
  'continueGame': '게임 계속하기',
  'replay': '다시 플레이',
  'creater': '사령관',
  'created': '전투 시작 시간',
  'updated': '업데이트 시간',
  // Dialog strings
  'confirm': '확인',
  'cancel': '취소',
  'yes': '예',
  'no': '아니오',
  'save': '저장',
  'edit': '수정',
  'levelFormat': '레벨 {level}',
  'newbieLevelFormat': '초보자 레벨 {level}',
  'totalLevel': '{level}/{totalLevel} 레벨',
  'totalLevelTooltip': '현재: 레벨 {level} / 전체 {totalLevel} 레벨',
  // Battlefront UI strings
  'noBattlefronts': '전선이 없습니다',
  'battlefrontCount': '{count}개 전선',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': '초보{level}',
  'minesCount': '{count}개 지뢰',
  'notStarted': '시작 안함',
  'victory': '승리',
  'defeat': '패배',
  'gameDurationParam': '소요 시간: {seconds}초',
  'actionsCountParam': '동작 횟수: {count}회',
  'actionsCountParamShort': '{count}회',
  'miningMethodParam': '방식: {method}',
  'startTimeParam': '시작 시간: {time}',
  'endTimeParam': '종료 시간: {time}',
  'returnButton': '뒤로',
  'battlefrontDetails': '전선 상세 정보',
  'clickToEditName': '클릭하여 이름 수정',
  'clickToAddDescription': '클릭하여 설명 추가...',
  'noDescription': '설명 없음',
  // Level record strings
  'levelCount': '{count}개 레벨',
  'noLevelRecords': '전선을 선택하세요',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': '전선 삭제',
  'deleteBattlefrontContent': '전선 "{name}"을(를) 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
  'battlefrontLockedCannotDelete': '전선이 잠겨 있어 삭제할 수 없습니다',
  'unknownNavigationLevel': '알 수 없는 레벨',
  'noBattlefrontSelected': '선택된 전선이 없습니다',
  'noBattlefrontToContinue': '계속할 전선이 없습니다',
  'synced': '동기화 완료',
  'notSynced': '동기화 안됨',
  'newbieBattlefrontName': '초보자 전선 {number}',
  'battlefrontName': '전선 {number}',
  'nickname': '닉네임',
  'nicknameSetting': '닉네임 설정',
  'nicknameDesc': '사용할 닉네임을 설정하세요',
  'enterNickname': '닉네임을 입력하세요',
  'nicknameSaved': '닉네임이 저장되었습니다',
  'nicknameUpdated': '닉네임이 수정되었습니다',
  'nicknameRequired': '닉네임은 필수입니다',
  'nicknameTooLong': '닉네임은 30자를 초과할 수 없습니다',
  // Level top strings
  'levelTopCount': '순위 ({count})',
  'levelTopCountShort': '순위 ({count})',
  'retry': '다시 시도',
  'noLevelTopData': '데이터가 없습니다',
  'remoteBattlefront': '원격 전선',
  'participated': '참여함',
  'notParticipated': '참여 안함',
  'loadMore': '더 불러오기',

  'joinBattle': '전투 참가',
  'joinBattleTooltip': '"{name}" 전투에 참가합니다',
  'joinBattleConfirm': '"{name}" 전투에 정말 참가하시겠습니까?',
  'joinBattleSuccess': '"{name}" 전투에 성공적으로 참가했습니다',
  'joinBattleErrorSelf': '자신의 전선에는 참가할 수 없습니다',

  'replayBattlefront': '전선 다시 플레이',
  'replayBattlefrontTooltip': '전선 "{name}"을(를) 다시 플레이합니다',
  'getReplayBattlefrontConfirm': '"{name}"을(를) 다시 플레이하시겠습니까?',
  'getReplayBattlefrontFailed': '"{name}" 다시 플레이 실패: {error}',

  'download': '다운로드',
  'downloadBattlefront': '전선 다운로드',
  'downloadBattlefrontTooltip': '전선 "{name}"을(를) 다운로드합니다',
  'getDownloadBattlefrontConfirm': '"{name}"을(를) 정말 다운로드하시겠습니까?',
  'getDownloadBattlefrontSuccess': '전선 "{name}"이(가) 다운로드되었습니다',
  'downloadMyOwnBattlefrontError': '자신의 전선만 다운로드할 수 있습니다',
  'getDownloadBattlefrontFailed': '"{name}" 다운로드 실패: {error}',

  'continueGameShort': '전투 계속',
  'replayShort': '다시 플레이',
  'highestLevel': '레벨 {level}',
  'deviceNickname': '기기',
  'createdTime': '생성 시간',
  'remoteBattlefrontDetail': '원격 전선 상세',
  'levelList': '레벨 목록',
  'fastClearTimeParam': '클리어 시간: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': '로컬 전선을 선택하여 상세 정보를 보세요',
  'loadingRemoteDetail': '원격 전선 정보 불러오는 중...',
  'noRemoteBattlefrontSelected': '선택된 원격 전선이 없습니다',
  'failedToLoadRemoteDetail': '원격 정보 불러오기 실패',
  'fastestRecord': '최속 클리어',
  'safestRecord': '최안전 클리어',
  'fastestRecordDesc': '가장 빠른 클리어 (짧은 시간)',
  'safestRecordDesc': '가장 안전한 클리어 (적은 동작)',
  'creator': '제작자',
  'player': '플레이어',
  // 分支地图字符串
  'getBranchMapCount': '{count}개 복사본',
  'collapse': '접기',
  'expand': '펼치기',
  // 退出战线
  'quitBattlefront': '전선 나가기',
  'quitBattlefrontTooltip': '원격 전선에서 나갑니다',
  'quitBattlefrontTitle': '전선 나가기',
  'quitBattlefrontContent': '전선 "{name}"에서 나가시겠습니까? 로컬 진행 상황이 삭제됩니다.',

  // 下载页面
  'downloadClient': '클라이언트 다운로드',
  'browser': '브라우저',
  'browserDesc': '다운로드 없이 브라우저에서 바로 플레이',
  'windowsDesc': 'Windows 10 이상 지원',
  'macosDesc': 'macOS 10.15 이상 지원',
  'android': '안드로이드',
  'androidDesc': 'Android 8.0 이상 지원',
  'iosDesc': 'iOS 14.0 이상 지원',
  'linkAddress': '링크 주소',
  'downloadLink': '다운로드 링크',
  'qrCode': 'QR 코드',
  'scanToDownload': '휴대폰으로 스캔하여 다운로드',
  'copy': '복사',
  'copiedToClipboard': '클립보드에 복사되었습니다',
  'openLink': '링크 열기',
  'cannotOpenLink': '링크를 열 수 없습니다',
  // 游戏介绍
  'gameIntroduction':
      '1. "초보자"는 15개의 지뢰로 시작하여 최대 99개까지 도전할 수 있습니다.\n2. "새 전선"은 81개 지뢰로 시작하며, 레벨마다 지뢰가 무제한으로 증가합니다.\n3. 인터넷 연결 시 "클리어한" 전선은 자동으로 클라우드에 공유되어 다른 사람이 참고할 수 있습니다.',
};
