// Russian（俄语）
/// Russian language strings for the DMine application
const Map<String, String> stringsRu = {
  'appLabel': 'Лучший Сапёр',
  'appTitle': 'DMine - Лучший Сапёр',
  'settings': 'Настройки',
  'gameSettings': 'Настройки игры',
  'showTimer': 'Показать таймер',
  'showTimerDesc': 'Показать таймер игры на экране',
  'showActionCounter': 'Показать счётчик действий',
  'showActionCounterDesc': 'Показать количество действий на экране игры',
  'autoAdjustBoardWidth': 'Автоматически подстроить ширину поля',
  'autoAdjustBoardWidthDesc':
      'Автоматически подстроить ширину поля под размер экрана',
  'resetToDefaults': 'Сбросить настройки по умолчанию',
  'resetToDefaultsDesc': 'Вернуть все настройки к значениям по умолчанию',
  'aboutDMine': 'О DMine',
  'version': 'Версия',
  'close': 'Закрыть',
  'manualBoardWidth': 'Задать ширину поля вручную',
  'currentWidth': 'Текущая',
  'range': 'Диапазон',
  'widthSliderHint':
      'Подсказка: при перетаскивании ползунка изменения ширины поля видны сразу',
  'gameRecords': 'Результаты игр',
  'selectMapToViewRecords': 'Выберите карту для просмотра результатов',
  'totalRecords': 'Всего',
  'gameRecordsTitle': 'Список результатов игр',
  'pleaseSelectMapFirst': 'Сначала выберите карту',
  'noGameRecords': 'Нет результатов игр',
  'miningMethodFlag': 'Поставить флаг',
  'miningMethodBlind': 'Слепая разметка',
  'statusPlaying': '▶️ Идёт игра...',
  'statusWin': '🎉 Победа',
  'statusLose': '💥 Поражение',
  'actionsCount': 'Количество действий',
  'miningMethod': 'Способ игры',
  'duration': 'Длительность',
  'seconds': 'секунд',
  'startTime': 'Время начала',
  'endTime': 'Время окончания',
  'pauseTime': 'Время паузы',
  'unlock': 'Разблокировать',
  'lock': 'Заблокировать',
  'delete': 'Удалить',
  'languageSetting': 'Настройка языка',
  'currentLanguage': 'Текущий',
  'systemLanguage': 'Язык системы',
  'chinese': 'Китайский',
  'english': 'Английский',
  'language': 'Язык',
  // Home page
  'newbie': 'Новичок',
  'gameIntro': 'Описание игры',
  'newBattle': 'Новый фронт',
  'continueChallenge': 'Продолжить испытание',
  'error': 'Ошибка',
  'initializationFailed': 'Ошибка инициализации',
  // Game page
  'congratulations': 'Поздравляем, уровень пройден!',
  'gameOver': 'Игра окончена',
  'timeUsed': 'Затраченное время',
  'actionCount': 'Действия',
  'mineCount': 'Мины',
  'nextLevel': 'Следующий уровень: Уровень {level}',
  'newbieNextLevel': 'Следующий уровень: Новичок {level}',
  'nextLevelMines': 'Мины',
  'mineIncrease': 'Увеличение',
  'newbieFinish': 'Режим новичка завершён',
  'ok': 'ОК',
  'continueNextLevel': 'Продолжить на следующий уровень',
  'restart': 'Начать заново',
  'level': 'Уровень {level}',
  'newbieLevel': 'Новичок {level}',
  'operationFailed': 'Операция не удалась',
  // Game status texts
  'returnHome': 'Вернуться на главную',
  'revealMode': 'Режим открытия',
  'flagMode': 'Режим флагов',
  'newMap': 'Новая карта (те же мины, новое поле)',
  'resetMap': 'Сбросить карту (то же поле, сброс состояния)',
  'zoomOut': 'Уменьшить',
  'zoomIn': 'Увеличить',
  'resetZoom': 'Сбросить масштаб',
  'previousStep': 'Предыдущий шаг',
  'pause': 'Пауза',
  'play': 'Играть',
  'nextStep': 'Следующий шаг',
  'clickToStart': 'Нажмите на любую клетку, чтобы начать игру',
  'playing': 'Идёт игра...',
  'gameWin': 'Поздравляем, уровень пройден!',
  'gameLose': 'Игра окончена, вы подорвались на мине',
  'gamePaused': 'Игра на паузе',
  'ready': 'Готово к началу',
  'clickStartShort': 'Нажмите, чтобы начать',
  'playingShort': 'В игре',
  'winShort': 'Пройдено!',
  'loseShort': 'Поражение',
  'pausedShort': 'Пауза',
  // Counter strings
  'currentLevel': 'Текущий уровень',
  'remainingMines': 'Осталось мин',
  'gameTime': 'Время игры (секунд)',
  'operationCount': 'Количество операций',
  'previousLevel': 'Предыдущий уровень',
  'nextLevelShort': 'Следующий уровень',
  // Battlefront strings
  'completed': 'Завершено',
  'inProgress': 'В процессе',
  'continueGame': 'Продолжить игру',
  'replay': 'Повтор',
  'creater': 'Командир',
  'created': 'Время начала',
  'updated': 'Обновлено',
  // Dialog strings
  'confirm': 'Подтвердить',
  'cancel': 'Отмена',
  'yes': 'Да',
  'no': 'Нет',
  'save': 'Сохранить',
  'edit': 'Редактировать',
  'levelFormat': 'Уровень {level}',
  'newbieLevelFormat': 'Новичок {level}',
  'totalLevel': '{level}/{totalLevel} уровней',
  'totalLevelTooltip': 'Текущий: Уровень {level} / Всего {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Нет фронтов',
  'battlefrontCount': '{count} фронтов',
  'levelPrefix': 'УР{level}',
  'newbieLevelPrefix': 'Новичок УР{level}',
  'minesCount': '{count} мин',
  'notStarted': 'Не начато',
  'victory': 'Победа',
  'defeat': 'Поражение',
  'gameDurationParam': 'Длительность: {seconds} с',
  'actionsCountParam': 'Действия: {count} раз',
  'actionsCountParamShort': '{count} раз',
  'miningMethodParam': 'Способ: {method}',
  'startTimeParam': 'Начало: {time}',
  'endTimeParam': 'Окончание: {time}',
  'returnButton': 'Назад',
  'battlefrontDetails': 'Детали фронта',
  'clickToEditName': 'Нажмите, чтобы изменить имя',
  'clickToAddDescription': 'Нажмите, чтобы добавить описание...',
  'noDescription': 'Нет описания',
  // Level record strings
  'levelCount': '{count} уровней',
  'noLevelRecords': 'Выберите фронт',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Удалить фронт',
  'deleteBattlefrontContent':
      'Вы уверены, что хотите удалить фронт \'{name}\'? Это действие нельзя отменить.',
  'battlefrontLockedCannotDelete': 'Фронт заблокирован, удаление невозможно',
  'unknownNavigationLevel': 'Неизвестный уровень',
  'noBattlefrontSelected': 'Фронт не выбран',
  'noBattlefrontToContinue': 'Нет доступного фронта для продолжения',
  'synced': 'Синхронизировано',
  'notSynced': 'Не синхронизировано',
  'newbieBattlefrontName': 'Фронт новичка {number}',
  'battlefrontName': 'Фронт {number}',
  'nickname': 'Никнейм',
  'nicknameSetting': 'Настройка никнейма',
  'nicknameDesc': 'Задайте свой никнейм',
  'enterNickname': 'Введите никнейм',
  'nicknameSaved': 'Никнейм сохранён',
  'nicknameUpdated': 'Никнейм обновлён',
  'nicknameRequired': 'Никнейм обязателен',
  'nicknameTooLong': 'Никнейм не может быть длиннее 30 символов',
  // Level top strings
  'levelTopCount': 'Рейтинг ({count})',
  'levelTopCountShort': 'Рейтинг ({count})',
  'retry': 'Попробовать снова',
  'noLevelTopData': 'Нет данных',
  'remoteBattlefront': 'Удалённый фронт',
  'participated': 'Участвовал',
  'notParticipated': 'Не участвовал',
  'loadMore': 'Загрузить ещё',
  'joinBattle': 'Присоединиться к битве',
  'joinBattleTooltip': 'Присоединиться к битве \'{name}\'',
  'joinBattleConfirm':
      'Вы уверены, что хотите присоединиться к битве \'{name}\'?',
  'joinBattleSuccess': 'Вы успешно присоединились к битве \'{name}\'',
  'joinBattleErrorSelf': 'Нельзя присоединяться к своему фронту',
  'replayBattlefront': 'Повторить фронт',
  'replayBattlefrontTooltip': 'Повторить фронт \'{name}\'',
  'getReplayBattlefrontConfirm': 'Вы уверены, что хотите повторить \'{name}\'?',
  'getReplayBattlefrontFailed': 'Не удалось повторить \'{name}\': {error}',
  'download': 'Скачать',
  'downloadBattlefront': 'Скачать фронт',
  'downloadBattlefrontTooltip': 'Скачать фронт \'{name}\'',
  'getDownloadBattlefrontConfirm': 'Вы уверены, что хотите скачать \'{name}\'?',
  'getDownloadBattlefrontSuccess': '\'{name}\' успешно скачан',
  'downloadMyOwnBattlefrontError': 'Можно скачивать только свои фронты',
  'getDownloadBattlefrontFailed': 'Не удалось скачать \'{name}\': {error}',
  'continueGameShort': 'Продолжить битву',
  'replayShort': 'Повтор',
  'highestLevel': 'Уровень {level}',
  'deviceNickname': 'Устройство',
  'createdTime': 'Время создания',
  'remoteBattlefrontDetail': 'Детали удалённого фронта',
  'levelList': 'Список уровней',
  'fastClearTimeParam': 'Время прохождения: {time}',
  // Детали удалённого фронта
  'selectLocalBattlefrontHint':
      'Выберите локальный фронт для просмотра деталей',
  'loadingRemoteDetail': 'Загрузка деталей удалённого фронта...',
  'noRemoteBattlefrontSelected': 'Удалённый фронт не выбран',
  'failedToLoadRemoteDetail': 'Не удалось загрузить детали',
  'fastestRecord': 'Самое быстрое прохождение',
  'safestRecord': 'Самое безопасное прохождение',
  'fastestRecordDesc': 'Самое быстрое (минимальное время)',
  'safestRecordDesc': 'Самое безопасное (минимальное количество действий)',
  'creator': 'Создатель',
  'player': 'Игрок',
  // Ветви карт
  'getBranchMapCount': '{count} копий',
  'collapse': 'Свернуть',
  'expand': 'Развернуть',
  // Выход с фронта
  'quitBattlefront': 'Покинуть фронт',
  'quitBattlefrontTooltip': 'Покинуть удалённый фронт',
  'quitBattlefrontTitle': 'Покинуть фронт',
  'quitBattlefrontContent':
      'Вы уверены, что хотите покинуть фронт \'{name}\'? Ваш локальный прогресс будет удалён.',
  // Описание игры
  'gameIntroduction':
      '1. «Новичок» начинается с 15 мин, максимум до 99 мин;\n2. «Новый фронт» начинается с 81 мин, количество увеличивается каждый уровень, без верхнего лимита.\n3. При подключении к сети пройденные фронты автоматически публикуются в облако для других игроков.',
};
