// Uzbek（乌兹别克语）
/// Uzbek (Latin) language strings for the DMine application
const Map<String, String> stringsUz = {
  'appTitle': 'DMine - Eng Yuqori Minlenish O\'yini',
  'settings': 'Sozlamalar',
  'gameSettings': 'O\'yin sozlamalari',
  'showTimer': 'Vaqt hisoblagichini ko\'rsatish',
  'showTimerDesc': 'O\'yin ekrani vaqt hisoblagichini ko\'rsatadi',
  'showActionCounter': 'Harakatlar sonini ko\'rsatish',
  'showActionCounterDesc': 'O\'yin ekrani harakatlar sonini ko\'rsatadi',
  'autoAdjustBoardWidth': 'Tahtaning kengligini avtomatik sozlash',
  'autoAdjustBoardWidthDesc':
      'Ekran o\'lchamiga ko\'ra tahtaning kengligini avtomatik moslashtirish',
  'resetToDefaults': 'Boshlang\'ich sozlamalariga tiklash',
  'resetToDefaultsDesc':
      'Barcha sozlamalarni boshlang\'ich qiymatlariga qaytarish',
  'aboutDMine': 'DMine haqida',
  'version': 'Versiya',
  'close': 'Yopish',
  'manualBoardWidth': 'Tahtaning kengligini qo\'lda sozlash',
  'currentWidth': 'Joriy',
  'range': 'Diapazon',
  'widthSliderHint':
      'Maslahat: slayderni tortayotganda tahta kengligi o\'zgarishini darhol ko\'rasiz',
  'gameRecords': 'O\'yin yozuvlari',
  'selectMapToViewRecords': 'Yozuvlarni ko\'rish uchun xaritani tanlang',
  'totalRecords': 'Jami',
  'gameRecordsTitle': 'O\'yin yozuvlari ro\'yxati',
  'pleaseSelectMapFirst': 'Avval xaritani tanlang',
  'noGameRecords': 'O\'yin yozuvlari mavjud emas',
  'miningMethodFlag': 'Bayroq belgilash',
  'miningMethodBlind': 'Ko\'rinmas qidirish',
  'statusPlaying': '▶️ O\'ynalmoqda...',
  'statusWin': '🎉 G\'alaba',
  'statusLose': '💥 Mag\'lubiyat',
  'actionsCount': 'Harakatlar soni',
  'miningMethod': 'O\'yin usuli',
  'duration': 'Davomiyligi',
  'seconds': 'soniya',
  'startTime': 'Boshlash vaqti',
  'endTime': 'Tugash vaqti',
  'pauseTime': 'Pauza vaqti',
  'unlock': 'Qulfni ochish',
  'lock': 'Qulflash',
  'delete': 'O\'chirish',
  'languageSetting': 'Til sozlamasi',
  'currentLanguage': 'Joriy',
  'systemLanguage': 'Tizim tili',
  'chinese': 'Xitoycha',
  'english': 'Inglizcha',
  'language': 'Til',
  // Home page
  'newbie': 'Yangi boshlovchi',
  'newBattle': 'Yangi jang chizig\'i',
  'continueChallenge': 'Qiyinchilikni davom ettirish',
  'error': 'Xato',
  'initializationFailed': 'Boshlash muvaffaqiyatsiz bo\'ldi',
  // Game page
  'congratulations': 'Tabriklaymiz, darajani tugatdingiz!',
  'gameOver': 'O\'yin tugadi',
  'timeUsed': 'Vaqt',
  'actionCount': 'Harakatlar',
  'mineCount': 'Minlar soni',
  'nextLevel': 'Keyingi daraja: {level}-daraja',
  'newbieNextLevel': 'Keyingi daraja: Yangi boshlovchi {level}',
  'nextLevelMines': 'Minlar soni',
  'mineIncrease': 'Ko\'payish',
  'newbieFinish': 'Yangi boshlovchi rejimi tugallandi',
  'ok': 'OK',
  'continueNextLevel': 'Keyingi darajaga o\'tish',
  'restart': 'Qayta boshlash',
  'level': '{level}-daraja',
  'newbieLevel': 'Yangi boshlovchi {level}',
  'operationFailed': 'Amal bajarilmadi',
  // Game status texts
  'returnHome': 'Asosiy sahifaga qaytish',
  'revealMode': 'Oshkorlash rejimi',
  'flagMode': 'Bayroq rejimi',
  'newMap': 'Yangi xarita (minlar soni o\'zgarmaydi, yangi tartib)',
  'resetMap': 'Xaritani qayta yuklash (xarita o\'zgarmaydi, holatni tiklash)',
  'zoomOut': 'Kichiklashtirish',
  'zoomIn': 'Kattalashtirish',
  'resetZoom': 'Asl o\'lchamga qaytish',
  'previousStep': 'Oldingi qadam',
  'pause': 'Pauza',
  'play': 'O\'ynash',
  'nextStep': 'Keyingi qadam',
  'clickToStart': 'O\'yinni boshlash uchun istalgan katakchani bosing',
  'playing': 'O\'ynalmoqda...',
  'gameWin': 'Tabriklaymiz, darajani tugatdingiz!',
  'gameLose': 'O\'yin tugadi, minga tegdingiz',
  'gamePaused': 'O\'yin pauzaga olindi',
  'ready': 'Boshlashga tayyor',
  'clickStartShort': 'Boshlash uchun bosing',
  'playingShort': 'O\'ynalmoqda',
  'winShort': 'Tugallandi!',
  'loseShort': 'Mag\'lubiyat',
  'pausedShort': 'Pauzada',
  // Counter strings
  'currentLevel': 'Joriy daraja',
  'remainingMines': 'Qolgan minlar',
  'gameTime': 'O\'yin vaqti (soniya)',
  'operationCount': 'Amallar soni',
  'previousLevel': 'Oldingi daraja',
  'nextLevelShort': 'Keyingi daraja',
  // Battlefront strings
  'completed': 'Tugallandi',
  'inProgress': 'Jarayonda',
  'continueGame': 'O\'yinni davom ettirish',
  'replay': 'Qayta o\'ynash',
  'creater': 'Qo\'mondon',
  'created': 'Yaratilgan vaqti',
  'updated': 'Yangilangan',
  // Dialog strings
  'confirm': 'Tasdiqlash',
  'cancel': 'Bekor qilish',
  'yes': 'Ha',
  'no': 'Yo\'q',
  'save': 'Saqlash',
  'edit': 'Tahrirlash',
  'levelFormat': '{level}-daraja',
  'newbieLevelFormat': 'Yangi boshlovchi {level}',
  'totalLevel': '{level}/{totalLevel} daraja',
  'totalLevelTooltip': 'Joriy: {level}-daraja / Jami {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Jang chizig\'lari mavjud emas',
  'battlefrontCount': '{count} ta jang chizig\'i',
  'levelPrefix': 'DR{level}',
  'newbieLevelPrefix': 'Boshlang\'ich DR{level}',
  'minesCount': '{count} ta min',
  'notStarted': 'Boshlanmagan',
  'victory': 'G\'alaba',
  'defeat': 'Mag\'lubiyat',
  'gameDurationParam': 'Davomiyligi: {seconds}son',
  'actionsCountParam': 'Harakatlar: {count} marta',
  'actionsCountParamShort': '{count} marta',
  'miningMethodParam': 'Usul: {method}',
  'startTimeParam': 'Boshlash: {time}',
  'endTimeParam': 'Tugash: {time}',
  'returnButton': 'Orqaga',
  'battlefrontDetails': 'Jang chizig\'i tafsilotlari',
  'clickToEditName': 'Nomni tahrirlash uchun bosing',
  'clickToAddDescription': 'Tavsif qo\'shish uchun bosing...',
  'noDescription': 'Tavsif yo\'q',
  // Level record strings
  'levelCount': '{count} daraja',
  'noLevelRecords': 'Jang chizig\'ini tanlang',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Jang chizig\'ini o\'chirish',
  'deleteBattlefrontContent':
      'Siz \'{name}\' jang chizig\'ini o\'chirishni istaysizmi? Bu amal qaytarilmaydi.',
  'battlefrontLockedCannotDelete':
      'Jang chizig\'i qulflangan, o\'chirib bo\'lmaydi',
  'unknownNavigationLevel': 'Noma\'lum daraja',
  'noBattlefrontSelected': 'Jang chizig\'i tanlanmagan',
  'noBattlefrontToContinue': 'Davom ettirish uchun jang chizig\'i topilmadi',
  'synced': 'Sinxronlashtirildi',
  'notSynced': 'Sinxronlashtirilmadi',
  'newbieBattlefrontName': 'Boshlang\'ich jang chizig\'i {number}',
  'battlefrontName': 'Jang chizig\'i {number}',
  'nickname': 'Taxallus',
  'nicknameSetting': 'Taxallus sozlamasi',
  'nicknameDesc': 'Taxallusingizni belgilang',
  'enterNickname': 'Taxallus kiriting',
  'nicknameSaved': 'Taxallus saqlandi',
  'nicknameUpdated': 'Taxallus yangilandi',
  'nicknameRequired': 'Taxallus majburiy',
  'nicknameTooLong': 'Taxallus 30 belgidan oshmasligi kerak',
  // Level top strings
  'levelTopCount': 'Reyting ({count})',
  'levelTopCountShort': 'Reyting ({count})',
  'retry': 'Qayta urinish',
  'noLevelTopData': 'Ma\'lumot yo\'q',
  'remoteBattlefront': 'Masofadagi jang chizig\'i',
  'participated': 'Ishtirok etdi',
  'notParticipated': 'Ishtirok etmadi',
  'loadMore': 'Ko\'proq yuklash',
  'joinBattle': 'Jangga qo\'shilish',
  'joinBattleTooltip': '\'{name}\' jangga qo\'shilish',
  'joinBattleConfirm': 'Siz \'{name}\' jangga qo\'shilishni istaysizmi?',
  'joinBattleSuccess': '\'{name}\' jangga muvaffaqiyatli qo\'shildingiz',
  'joinBattleErrorSelf':
      'O\'zingizning jang chizig\'ingizga qo\'shila olmaysiz',
  'replayBattlefront': 'Jang chizig\'ini qayta o\'ynash',
  'replayBattlefrontTooltip': '\'{name}\' jang chizig\'ini qayta o\'ynash',
  'getReplayBattlefrontConfirm':
      'Siz \'{name}\'ni qayta o\'ynashni istaysizmi?',
  'getReplayBattlefrontFailed':
      '\'{name}\'ni qayta o\'ynash muvaffaqiyatsiz: {error}',
  'download': 'Yuklab olish',
  'downloadBattlefront': 'Jang chizig\'ini yuklab olish',
  'downloadBattlefrontTooltip': '\'{name}\' jang chizig\'ini yuklab olish',
  'getDownloadBattlefrontConfirm':
      'Siz \'{name}\'ni yuklab olishni istaysizmi?',
  'getDownloadBattlefrontSuccess': '\'{name}\' muvaffaqiyatli yuklandi',
  'downloadMyOwnBattlefrontError':
      'Faqat o\'zingizning jang chizig\'laringizni yuklab olishingiz mumkin',
  'getDownloadBattlefrontFailed':
      '\'{name}\'ni yuklab olish muvaffaqiyatsiz: {error}',
  'continueGameShort': 'Jangni davom ettirish',
  'replayShort': 'Qayta o\'ynash',
  'highestLevel': '{level}-daraja',
  'deviceNickname': 'Qurilma',
  'createdTime': 'Yaratilgan vaqti',
  'remoteBattlefrontDetail': 'Masofadagi jang chizig\'i tafsilotlari',
  'levelList': 'Darajalar ro\'yxati',
  'fastClearTimeParam': 'Tugatish vaqti: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint':
      'Tafsilotlarni ko\'rish uchun mahalliy jang chizig\'ini tanlang',
  'loadingRemoteDetail':
      'Masofadagi jang chizig\'i tafsilotlari yuklanmoqda...',
  'noRemoteBattlefrontSelected': 'Masofadagi jang chizig\'i tanlanmagan',
  'failedToLoadRemoteDetail': 'Tafsilotlarni yuklash muvaffaqiyatsiz bo\'ldi',
  'fastestRecord': 'Eng tez tugatish',
  'safestRecord': 'Eng xavfsiz tugatish',
  'fastestRecordDesc': 'Eng tez (eng kam vaqt)',
  'safestRecordDesc': 'Eng xavfsiz (eng kam harakat)',
  'creator': 'Yaratuvchi',
  'player': 'O\'yinchi',
  // Branch maps
  'getBranchMapCount': '{count} nusxa',
  'collapse': 'Yig\'ish',
  'expand': 'Kengaytirish',
  // Quit battlefront
  'quitBattlefront': 'Jang chizig\'idan chiqish',
  'quitBattlefrontTooltip': 'Masofadagi jang chizig\'idan chiqish',
  'quitBattlefrontTitle': 'Jang chizig\'idan chiqish',
  'quitBattlefrontContent':
      'Siz \'{name}\' jang chizig\'idan chiqishni istaysizmi? Sizning mahalliy yutuqlaringiz o\'chiriladi.',
  // Download page
  'downloadClient': 'Klientni yuklab olish',
  'browser': 'Brauzer',
  'browserDesc': 'Yuklab olishsiz brauzerda to\'g\'ridan-to\'g\'ri o\'ynang',
  'windowsDesc': 'Windows 10 va undan yuqori uchun',
  'macosDesc': 'macOS 10.15 va undan yuqori uchun',
  'android': 'Android',
  'androidDesc': 'Android 8.0 va undan yuqori uchun',
  'iosDesc': 'iOS 14.0 va undan yuqori uchun',
  'linkAddress': 'Havola manzili',
  'downloadLink': 'Yuklab olish havolasi',
  'qrCode': 'QR-kod',
  'scanToDownload': 'Yuklab olish uchun telefon bilan skanering',
  'copy': 'Nusxa olish',
  'copiedToClipboard': 'Xotirga nusxa olindi',
  'openLink': 'Havolani ochish',
  'cannotOpenLink': 'Havolani ochib bo\'lmadi',
  // Game introduction
  'gameIntroduction':
      '1. "Yangi boshlovchi" 15 min bilan boshlanadi, maksimal 95 mingacha;\n2. "Yangi jang chizig\'i" 81 min bilan boshlanadi, har darajada ortadi, yuqori cheklanmagan.\n3. Onlayn rejimida tugallangan jang chizig\'lari avtomatik tarzda bulutga taqdim etiladi.',
};
