// French（法语）
/// Chaînes en français pour l'application DMine
const Map<String, String> stringsFr = {
  'appLabel': 'Démineur de Luxe',
  'appTitle': 'DMine - Démineur de Luxe',
  'settings': 'Paramètres',
  'gameSettings': 'Paramètres du jeu',
  'showTimer': 'Afficher le chronomètre',
  'showTimerDesc': 'Afficher le chronomètre du jeu dans l\'interface',
  'showActionCounter': 'Afficher le compteur d\'actions',
  'showActionCounterDesc':
      'Afficher le nombre d\'actions dans l\'interface du jeu',
  'autoAdjustBoardWidth': 'Ajuster automatiquement la largeur du plateau',
  'autoAdjustBoardWidthDesc':
      'Ajuster automatiquement la largeur du plateau selon la taille de l\'écran',
  'resetToDefaults': 'Réinitialiser les paramètres par défaut',
  'resetToDefaultsDesc':
      'Réinitialiser tous les paramètres aux valeurs par défaut',
  'aboutDMine': 'À propos de DMine',
  'version': 'Version',
  'close': 'Fermer',
  'manualBoardWidth': 'Définir manuellement la largeur du plateau',
  'currentWidth': 'Actuel',
  'range': 'Plage',
  'widthSliderHint':
      'Conseil : vous pouvez prévisualiser les changements de largeur en temps réel en glissant le curseur',
  'gameRecords': 'Records de jeu',
  'selectMapToViewRecords': 'Sélectionnez une carte pour voir les records',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Liste des records de jeu',
  'pleaseSelectMapFirst': 'Sélectionnez d\'abord une carte',
  'noGameRecords': 'Aucun record de jeu',
  'miningMethodFlag': 'Poser un drapeau',
  'miningMethodBlind': 'Exploration à l\'aveugle',
  'statusPlaying': '▶️ En cours...',
  'statusWin': '🎉 Victoire',
  'statusLose': '💥 Défaite',
  'actionsCount': 'Nombre d\'actions',
  'miningMethod': 'Méthode de déminage',
  'duration': 'Durée',
  'seconds': 'secondes',
  'startTime': 'Heure de début',
  'endTime': 'Heure de fin',
  'pauseTime': 'Temps de pause',
  'unlock': 'Déverrouiller',
  'lock': 'Verrouiller',
  'delete': 'Supprimer',
  'languageSetting': 'Paramètre de langue',
  'currentLanguage': 'Actuel',
  'systemLanguage': 'Langue du système',
  'chinese': 'Chinois',
  'english': 'Anglais',
  'language': 'Langue',
  // Home page
  'newbie': 'Débutant',
  'gameIntro': 'Présentation du jeu',
  'newBattle': 'Nouveau front',
  'continueChallenge': 'Continuer le défi',
  'error': 'Erreur',
  'initializationFailed': 'Échec de l\'initialisation',
  // Game page
  'congratulations': 'Félicitations, vous avez terminé le niveau !',
  'gameOver': 'Fin du jeu',
  'timeUsed': 'Temps utilisé',
  'actionCount': 'Nombre d\'actions',
  'mineCount': 'Nombre de mines',
  'nextLevel': 'Niveau suivant : Niveau {level}',
  'newbieNextLevel': 'Niveau suivant : Débutant {level}',
  'nextLevelMines': 'Nombre de mines',
  'mineIncrease': 'Augmentation',
  'newbieFinish': ' initiation terminée',
  'ok': 'OK',
  'continueNextLevel': 'Continuer au niveau suivant',
  'restart': 'Redémarrer',
  'level': 'Niveau {level}',
  'newbieLevel': 'Niveau débutant {level}',
  'operationFailed': 'Opération échouée',
  // Game status texts
  'returnHome': 'Retour à l\'accueil',
  'revealMode': 'Mode révélation',
  'flagMode': 'Mode drapeau',
  'newMap': 'Nouvelle carte (même nombre de mines, générer une nouvelle carte)',
  'resetMap': 'Recharger la carte (même carte, réinitialiser l\'état)',
  'zoomOut': 'Dézoomer',
  'zoomIn': 'Zoomer',
  'resetZoom': 'Réinitialiser le zoom',
  'previousStep': 'Étape précédente',
  'pause': 'Pause',
  'play': 'Jouer',
  'nextStep': 'Étape suivante',
  'clickToStart': 'Cliquez sur n\'importe quelle case pour commencer le jeu',
  'playing': 'En jeu...',
  'gameWin': 'Félicitations, vous avez terminé le niveau !',
  'gameLose': 'Fin du jeu, vous avez touché une mine',
  'gamePaused': 'Jeu en pause',
  'ready': 'Prêt',
  'clickStartShort': 'Cliquez pour commencer',
  'playingShort': 'En cours',
  'winShort': 'Terminé !',
  'loseShort': 'Mine touchée',
  'pausedShort': 'En pause',
  // Counter strings
  'currentLevel': 'Niveau actuel',
  'remainingMines': 'Mines restantes',
  'gameTime': 'Temps de jeu (secondes)',
  'operationCount': 'Nombre d\'opérations',
  'previousLevel': 'Niveau précédent',
  'nextLevelShort': 'Niveau suivant',
  // Battlefront strings
  'completed': 'Terminé',
  'inProgress': 'En cours',
  'continueGame': 'Continuer le jeu',
  'replay': 'Rejouer',
  'creater': 'Commandant',
  'created': 'Heure de début de bataille',
  'updated': 'Mis à jour',
  // Dialog strings
  'confirm': 'Confirmer',
  'cancel': 'Annuler',
  'yes': 'Oui',
  'no': 'Non',
  'save': 'Enregistrer',
  'edit': 'Modifier',
  'levelFormat': 'Niveau {level}',
  'newbieLevelFormat': 'Niveau débutant {level}',
  'totalLevel': '{level}/{totalLevel} niveaux',
  'totalLevelTooltip': 'Actuel : Niveau {level} / Total {totalLevel} niveaux',
  // Battlefront UI strings
  'noBattlefronts': 'Aucun front',
  'battlefrontCount': '{count} fronts',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'DEB{level}',
  'minesCount': '{count} mines',
  'notStarted': 'Non commencé',
  'victory': 'Victoire',
  'defeat': 'Défaite',
  'gameDurationParam': 'Durée : {seconds} secondes',
  'actionsCountParam': 'Actions : {count} fois',
  'actionsCountParamShort': '{count} fois',
  'miningMethodParam': 'Méthode : {method}',
  'startTimeParam': 'Heure de début : {time}',
  'endTimeParam': 'Heure de fin : {time}',
  'returnButton': 'Retour',
  'battlefrontDetails': 'Détails du front',
  'clickToEditName': 'Cliquez pour modifier le nom',
  'clickToAddDescription': 'Cliquez pour ajouter une description...',
  'noDescription': 'Aucune description',
  // Level record strings
  'levelCount': '{count} niveaux',
  'noLevelRecords': 'Sélectionnez un front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Supprimer le front',
  'deleteBattlefrontContent':
      'Êtes-vous sûr de vouloir supprimer le front "{name}" ? Cette action est irréversible.',
  'battlefrontLockedCannotDelete': 'Front verrouillé, impossible de supprimer',
  'unknownNavigationLevel': 'Niveau de navigation inconnu',
  'noBattlefrontSelected': 'Aucun front sélectionné',
  'noBattlefrontToContinue': 'Aucun front à continuer',
  'synced': 'Synchronisé',
  'notSynced': 'Non synchronisé',
  'newbieBattlefrontName': 'Front débutant {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Pseudo',
  'nicknameSetting': 'Paramètre du pseudo',
  'nicknameDesc': 'Définissez votre pseudo',
  'enterNickname': 'Entrez le pseudo',
  'nicknameSaved': 'Pseudo enregistré',
  'nicknameUpdated': 'Pseudo mis à jour',
  'nicknameRequired': 'Le pseudo est obligatoire',
  'nicknameTooLong': 'Le pseudo ne peut pas dépasser 30 caractères',
  // Level top strings
  'levelTopCount': 'Classement ({count})',
  'levelTopCountShort': 'Classement ({count})',
  'retry': 'Réessayer',
  'noLevelTopData': 'Aucune donnée',
  'remoteBattlefront': 'Front distant',
  'participated': 'Participé',
  'notParticipated': 'Non participé',
  'loadMore': 'Charger plus',

  'joinBattle': 'Rejoindre la bataille',
  'joinBattleTooltip': 'Rejoindre la bataille "{name}"',
  'joinBattleConfirm':
      'Êtes-vous sûr de vouloir rejoindre la bataille "{name}" ?',
  'joinBattleSuccess': 'Vous avez rejoint la bataille "{name}" avec succès',
  'joinBattleErrorSelf': 'Vous ne pouvez pas rejoindre votre propre front',

  'replayBattlefront': 'Rejouer le front',
  'replayBattlefrontTooltip': 'Rejouer le front "{name}"',
  'getReplayBattlefrontConfirm': 'Êtes-vous sûr de vouloir rejouer "{name}" ?',
  'getReplayBattlefrontFailed': 'Échec de la replay de "{name}" : {error}',

  'download': 'Télécharger',
  'downloadBattlefront': 'Télécharger le front',
  'downloadBattlefrontTooltip': 'Télécharger le front "{name}"',
  'getDownloadBattlefrontConfirm':
      'Êtes-vous sûr de vouloir télécharger "{name}" ?',
  'getDownloadBattlefrontSuccess': 'Front "{name}" téléchargé avec succès',
  'downloadMyOwnBattlefrontError':
      'Vous ne pouvez télécharger que vos propres fronts',
  'getDownloadBattlefrontFailed':
      'Échec du téléchargement de "{name}" : {error}',

  'continueGameShort': 'Continuer la bataille',
  'replayShort': 'Rejouer',
  'highestLevel': 'Niveau {level}',
  'deviceNickname': 'Appareil',
  'createdTime': 'Heure de création',
  'remoteBattlefrontDetail': 'Détails du front distant',
  'levelList': 'Liste des niveaux',
  'fastClearTimeParam': 'Temps de complétion : {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Sélectionnez un front local pour voir les détails',
  'loadingRemoteDetail': 'Chargement des détails du front distant...',
  'noRemoteBattlefrontSelected': 'Aucun front distant sélectionné',
  'failedToLoadRemoteDetail': 'Échec du chargement des détails distants',
  'fastestRecord': 'Complétion la plus rapide',
  'safestRecord': 'Complétion la plus sûre',
  'fastestRecordDesc': 'Complétion la plus rapide (moins de temps)',
  'safestRecordDesc': 'Complétion la plus sûre (moins d\'actions)',
  'creator': 'Créateur',
  'player': 'Joueur',
  // 分支地图字符串
  'getBranchMapCount': '{count} copies',
  'collapse': 'Réduire',
  'expand': 'Développer',
  // 退出战线
  'quitBattlefront': 'Quitter le front',
  'quitBattlefrontTooltip': 'Quitter le front distant',
  'quitBattlefrontTitle': 'Quitter le front',
  'quitBattlefrontContent':
      'Êtes-vous sûr de vouloir quitter le front "{name}" ? Votre progression locale sera supprimée.',
  // 游戏介绍
  'gameIntroduction':
      '1. "Débutant" commence avec 15 mines, peut aller jusqu\'à 99 mines ;\n2. "Nouveau front" commence avec 81 mines, chaque niveau ajoute des mines sans limite supérieure.\n3. Avec connexion Internet, les fronts "terminés" sont partagés automatiquement dans le cloud pour les autres.',
};
