// ScotsGaelic（苏格兰盖尔语）
/// Scottish Gaelic (Gàidhlig) strings for the DMine application
const Map<String, String> stringsGd = {
  'appLabel': 'Mèinnear Àrd-ìre',
  'appTitle': 'DMine - Mèinnear Àrd-ìre',
  'settings': 'Roghainnean',
  'gameSettings': 'Roghainnean a\' Gheama',
  'showTimer': 'Seall an clag-ùine',
  'showTimerDesc': 'Seall clag-ùine a\' gheama air sgrìn a\' gheama',
  'showActionCounter': 'Seall cunntar gnìomhan',
  'showActionCounterDesc': 'Seall àireamh gnìomhan air sgrìn a\' gheama',
  'autoAdjustBoardWidth': 'Atharraich leud a\' bhùird gu fèin-ghluasadach',
  'autoAdjustBoardWidthDesc':
      'Atharraich leud a\' bhùird a rèir meud an sgrìn gu fèin-ghluasadach',
  'resetToDefaults': 'Ath-nuadhachadh gu roghainnean bunaiteach',
  'resetToDefaultsDesc': 'Cuir a h-uile roghainn air ais gu luachan bunaiteach',
  'aboutDMine': 'Mu DMine',
  'version': 'Leabhar',
  'close': 'Dùin',
  'manualBoardWidth': 'Suidhich leud a\' bhùird le làimh',
  'currentWidth': 'An-dràsta',
  'range': 'Raon',
  'widthSliderHint':
      'Comhairle: chì thu atharrachadh leud a\' bhùird sa bhad nuair a sleamhnachas tu an slaider',
  'gameRecords': 'Clàran a\' Gheama',
  'selectMapToViewRecords': 'Tagh mapa gus clàran fhaicinn',
  'totalRecords': 'Iomlan',
  'gameRecordsTitle': 'Liosta Clàran a\' Gheama',
  'pleaseSelectMapFirst': 'Tagh mapa an toiseach',
  'noGameRecords': 'Chan eil clàran geama ann',
  'miningMethodFlag': 'Comharraich le bratach',
  'miningMethodBlind': 'Lorg gun fhaicinn',
  'statusPlaying': '▶️ A\' cluich...',
  'statusWin': '🎉 Buaidh',
  'statusLose': '💥 Call',
  'actionsCount': 'Àireamh Gnìomhan',
  'miningMethod': 'Dòigh Cluich',
  'duration': 'Fad',
  'seconds': 'diog',
  'startTime': 'Àm tòiseachaidh',
  'endTime': 'Àm crìochnachaidh',
  'pauseTime': 'Ùine stad',
  'unlock': 'Fuasgladh',
  'lock': 'Glasachadh',
  'delete': 'Sguab às',
  'languageSetting': 'Roghainnean Cànain',
  'currentLanguage': 'An-dràsta',
  'systemLanguage': 'Cànan an t-siostaim',
  'chinese': 'Sìnis',
  'english': 'Beurla',
  'language': 'Cànan',
  // Home page
  'newbie': 'Neach-tòiseachaidh',
  'gameIntro': 'Ro-ràdh geama',
  'newBattle': 'Aghaidh Ùr',
  'continueChallenge': 'Lean air adhart leis an dùbhlan',
  'error': 'Mearachd',
  'initializationFailed': 'Dh\'fhailich an tòiseachadh',
  // Game page
  'congratulations': 'Coinnichidh mi ribh! Chaidh an ìre seachad!',
  'gameOver': 'Crìochnaich an geama',
  'timeUsed': 'Ùine air a chleachdadh',
  'actionCount': 'Gnìomhan',
  'mineCount': 'Mèinnean',
  'nextLevel': 'An ath ìre: Ìre {level}',
  'newbieNextLevel': 'An ath ìre: Tòiseachaidh {level}',
  'nextLevelMines': 'Mèinnean',
  'mineIncrease': 'Meudachadh',
  'newbieFinish': 'Chrìochnaich modh neach-tòiseachaidh',
  'ok': 'Ceart ma-thà',
  'continueNextLevel': 'Lean air adhart don ath ìre',
  'restart': 'Tòisich a-rithist',
  'level': 'Ìre {level}',
  'newbieLevel': 'Tòiseachaidh {level}',
  'operationFailed': 'Dh\'fhailich an gnìomh',
  // Game status texts
  'returnHome': 'Till air ais chun dachaigh',
  'revealMode': 'Modh nochdaidh',
  'flagMode': 'Modh bratach',
  'newMap': 'Mapa ùr (an aon àireamh de mèinnean, dealbhadh ùr)',
  'resetMap': 'Ath-nuadhachadh mapa (an aon dealbhadh, ath-nuadhachadh staid)',
  'zoomOut': 'Lùghdaich',
  'zoomIn': 'Meudaich',
  'resetZoom': 'Ath-nuadhachadh sùim',
  'previousStep': 'An ceum roimhe',
  'pause': 'Stad',
  'play': 'Cluich',
  'nextStep': 'An ath cheum',
  'clickToStart': 'Cliog air ceàrnag sam bith gus an geama a thòiseachadh',
  'playing': 'A\' cluich...',
  'gameWin': 'Coinnichidh mi ribh! Chaidh an ìre seachad!',
  'gameLose': 'Crìochnaich an geama, bhuail thu air mèinn',
  'gamePaused': 'Tha an geama air stad',
  'ready': 'Deiseil airson tòiseachadh',
  'clickStartShort': 'Cliog gus tòiseachadh',
  'playingShort': 'A\' cluich',
  'winShort': 'Air a chrìochnachadh!',
  'loseShort': 'Call',
  'pausedShort': 'Air stad',
  // Counter strings
  'currentLevel': 'An ìre làithreach',
  'remainingMines': 'Mèinnean air fhàgail',
  'gameTime': 'Ùine a\' gheama (diogan)',
  'operationCount': 'Àireamh Gnìomhan',
  'previousLevel': 'An ìre roimhe',
  'nextLevelShort': 'An ath ìre',
  // Battlefront strings
  'completed': 'Air a chrìochnachadh',
  'inProgress': 'Ga dhèanamh',
  'continueGame': 'Lean air adhart leis a\' gheama',
  'replay': 'Ath-chluich',
  'creater': 'Ceannard',
  'created': 'Àm tòiseachaidh',
  'updated': 'Ùraichte',
  // Dialog strings
  'confirm': 'Dearbhaich',
  'cancel': 'Sguir',
  'yes': 'Tha',
  'no': 'Chan eil',
  'save': 'Sàbhail',
  'edit': 'Deasaich',
  'levelFormat': 'Ìre {level}',
  'newbieLevelFormat': 'Tòiseachaidh {level}',
  'totalLevel': '{level}/{totalLevel} ìrean',
  'totalLevelTooltip': 'Làithreach: Ìre {level} / Iomlan {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Chan eil aghaidhean ann',
  'battlefrontCount': '{count} aghaidhean',
  'levelPrefix': 'ÌR{level}',
  'newbieLevelPrefix': 'Tòiseachaidh ÌR{level}',
  'minesCount': '{count} mèinnean',
  'notStarted': 'Cha deach tòiseachadh',
  'victory': 'Buaidh',
  'defeat': 'Call',
  'gameDurationParam': 'Fad: {seconds}d',
  'actionsCountParam': 'Gnìomhan: {count} uair',
  'actionsCountParamShort': '{count} uair',
  'miningMethodParam': 'Dòigh: {method}',
  'startTimeParam': 'Tòiseachadh: {time}',
  'endTimeParam': 'Crìochnachadh: {time}',
  'returnButton': 'Air ais',
  'battlefrontDetails': 'Fiosrachadh mun aghaidh',
  'clickToEditName': 'Cliog gus an t-ainm a dheasachadh',
  'clickToAddDescription': 'Cliog gus tuairisgeul a chur ris...',
  'noDescription': 'Gun tuairisgeul',
  // Level record strings
  'levelCount': '{count} ìrean',
  'noLevelRecords': 'Tagh aghaidh',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Sguab às an aghaidh',
  'deleteBattlefrontContent':
      'A bheil thu cinnteach gu bheil thu airson an aghaidh \'{name}\' a sguabadh às? Chan urrainn an gnìomh seo a thilleadh.',
  'battlefrontLockedCannotDelete':
      'Tha an aghaidh glaiste, chan urrainnear a sguabadh às',
  'unknownNavigationLevel': 'Ìre neo-aithnichte',
  'noBattlefrontSelected': 'Cha deach aghaidh a thaghadh',
  'noBattlefrontToContinue': 'Cha deach aghaidh a lorg airson leantainn',
  'synced': 'Air a shioncronachadh',
  'notSynced': 'Gun sioncronachadh',
  'newbieBattlefrontName': 'Aghaidh neach-tòiseachaidh {number}',
  'battlefrontName': 'Aghaidh {number}',
  'nickname': 'Far-ainm',
  'nicknameSetting': 'Roghainnean Far-ainm',
  'nicknameDesc': 'Suidhich do far-ainm',
  'enterNickname': 'Cuir a-steach am far-ainm',
  'nicknameSaved': 'Chaidh am far-ainm a shàbhaladh',
  'nicknameUpdated': 'Chaidh am far-ainm ùrachadh',
  'nicknameRequired': 'Tha far-ainm riatanach',
  'nicknameTooLong': 'Chan fhaod am far-ainm a bhith nas fhaide na 30 caractar',
  // Level top strings
  'levelTopCount': 'Clàr-àrd ({count})',
  'levelTopCountShort': 'Àrd ({count})',
  'retry': 'Feuch a-rithist',
  'noLevelTopData': 'Gun dàta',
  'remoteBattlefront': 'Aghaidh iomallach',
  'participated': 'Ghabh e pàirt',
  'notParticipated': 'Cha ghabh e pàirt',
  'loadMore': 'Luchdaich barrachd',
  'joinBattle': 'Thig a-steach don bhlàr',
  'joinBattleTooltip': 'Thig a-steach don bhlàr \'{name}\'',
  'joinBattleConfirm':
      'A bheil thu cinnteach gu bheil thu airson a dhol a-steach don bhlàr \'{name}\'?',
  'joinBattleSuccess':
      'Chaidh thu a-steach don bhlàr \'{name}\' gu soirbheachail',
  'joinBattleErrorSelf':
      'Chan urrainn dhut a dhol a-steach don agaidh agad fhèin',
  'replayBattlefront': 'Ath-chluich an aghaidh',
  'replayBattlefrontTooltip': 'Ath-chluich an aghaidh \'{name}\'',
  'getReplayBattlefrontConfirm':
      'A bheil thu cinnteach gu bheil thu airson \'{name}\' ath-chluich?',
  'getReplayBattlefrontFailed': 'Dh\'fhailich ath-chluich \'{name}\': {error}',
  'download': 'Luchdaich sìos',
  'downloadBattlefront': 'Luchdaich sìos an aghaidh',
  'downloadBattlefrontTooltip': 'Luchdaich sìos an aghaidh \'{name}\'',
  'getDownloadBattlefrontConfirm':
      'A bheil thu cinnteach gu bheil thu airson \'{name}\' a luchdachadh sìos?',
  'getDownloadBattlefrontSuccess':
      'Chaidh \'{name}\' a luchdachadh sìos gu soirbheachail',
  'downloadMyOwnBattlefrontError':
      'Chan urrainn dhut ach na h-aghaidhean agad fhèin a luchdachadh sìos',
  'getDownloadBattlefrontFailed':
      'Dh\'fhailich luchdachadh sìos \'{name}\': {error}',
  'continueGameShort': 'Lean air adhart leis a\' bhlàr',
  'replayShort': 'Ath-chluich',
  'highestLevel': 'Ìre {level}',
  'deviceNickname': 'Inneal',
  'createdTime': 'Àm cruthachaidh',
  'remoteBattlefrontDetail': 'Fiosrachadh mun aghaidh iomallach',
  'levelList': 'Liosta nan ìrean',
  'fastClearTimeParam': 'Ùine glanaidh: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint':
      'Tagh aghaidh ionadail gus fiosrachadh fhaicinn',
  'loadingRemoteDetail':
      'A\' luchdachadh fiosrachaidh mun aghaidh iomallach...',
  'noRemoteBattlefrontSelected': 'Cha deach aghaidh iomallach a thaghadh',
  'failedToLoadRemoteDetail': 'Dh\'fhailich luchdachadh fiosrachaidh',
  'fastestRecord': 'An glanadh as luaithe',
  'safestRecord': 'An glanadh as sàbhailte',
  'fastestRecordDesc': 'As luaithe (ùine as lugha)',
  'safestRecordDesc': 'As sàbhailte (gnìomhan as lugha)',
  'creator': 'Cruthadair',
  'player': 'Cluicheadair',
  // Branch maps
  'getBranchMapCount': '{count} leth-bhreacan',
  'collapse': 'Tarraing còmhla',
  'expand': 'Leudaich',
  // Quit battlefront
  'quitBattlefront': 'Leig seachad an aghaidh',
  'quitBattlefrontTooltip': 'Leig seachad an aghaidh iomallach',
  'quitBattlefrontTitle': 'Leig seachad an aghaidh',
  'quitBattlefrontContent':
      'A bheil thu cinnteach gu bheil thu airson leigeil seachad an aghaidh \'{name}\'? Thèid do adhartas ionadail a sguabadh às.',
  // Download page
  'downloadClient': 'Luchdaich sìos an neach-dèiligidh',
  'browser': 'Brabhsair',
  'browserDesc': 'Cluich gu dìreach sa bhrabhsair, gun luchdachadh sìos',
  'windowsDesc': 'Airson Windows 10 agus nas ùire',
  'macosDesc': 'Airson macOS 10.15 agus nas ùire',
  'android': 'Android',
  'androidDesc': 'Airson Android 8.0 agus nas ùire',
  'iosDesc': 'Airson iOS 14.0 agus nas ùire',
  'linkAddress': 'Seòladh ceangail',
  'downloadLink': 'Ceangal luchdaidh sìos',
  'qrCode': 'Còd QR',
  'scanToDownload': 'Sganail leis a\' fòn gus luchdachadh sìos',
  'copy': 'Dèan leth-bhreac',
  'copiedToClipboard': 'Chaidh a chopaigeadh don chlàr-bùird',
  'openLink': 'Fosgail an ceangal',
  'cannotOpenLink': 'Chan urrainnear an ceangal fhosgladh',
  // Game introduction
  'gameIntroduction':
      '1. Tha "Neach-tòiseachaidh" a\' tòiseachadh le 15 mèinnean, suas gu 99 mèinnean;\n2. Tha "Aghaidh Ùr" a\' tòiseachadh le 81 mèinnean, a\' meudachadh gach ìre, gun chrìoch àrd.\n3. Air loidhne, thèid aghaidhean crìochnaichte a roinn anns a\' sgòthan gu fèin-ghluasadach airson cluicheadairean eile.',
};
