// Kurdish（库尔德语）
/// Stringên Kurdî yên berepêya DMine
const Map<String, String> stringsKu = {
  'appLabel': 'Minesweeper Premium',
  'appTitle': 'DMine - Minesweeper Premium',
  'settings': 'Mîhengan',
  'gameSettings': 'Mîhengan Lîstîkê',
  'showTimer': 'Timer nîşan bide',
  'showTimerDesc': 'Timerê lîstikê li ser pelabêrê nîşan bide',
  'showActionCounter': 'Hejmara karan nîşan bide',
  'showActionCounterDesc': 'Hejmara karan li ser pelabêra lîstikê nîşan bide',
  'autoAdjustBoardWidth': 'Berhêla tabloya awtomatîk hilbijêre',
  'autoAdjustBoardWidthDesc': 'Berhêla tabloya bi pelabêrê awtomatîk hilbijêre',
  'resetToDefaults': 'Mîhenganan ve avake',
  'resetToDefaultsDesc': 'Hemû mîhenganan bi nirxên avakî ve avake',
  'aboutDMine': 'Derbarî DMine',
  'version': 'Versiyon',
  'close': 'Bigire',
  'manualBoardWidth': 'Berhêla tabloya bi elî bikir',
  'currentWidth': 'Niha',
  'range': 'Bereh',
  'widthSliderHint':
      'Îşaret: Tu dikarî guhartinên berhêla tabloya bi demqî bînî',
  'gameRecords': 'Teyfedaranî Lîstîkê',
  'selectMapToViewRecords': 'Xeriteyê hilbijêre da teyfedaran bînî',
  'totalRecords': 'Hemû',
  'gameRecordsTitle': 'Lîsteya Teyfedaranî Lîstîkê',
  'pleaseSelectMapFirst': 'Yekem Xeriteyê hilbijêre',
  'noGameRecords': 'Teyfedarek lîstîk tune',
  'miningMethodFlag': 'Alam bike',
  'miningMethodBlind': 'Lêgerîna Bêbin',
  'statusPlaying': '▶️ Lîstîk dêkim...',
  'statusWin': '🎉 Serkeftî',
  'statusLose': '💥 Betal bî',
  'actionsCount': 'Hejmara Karan',
  'miningMethod': 'Rêbaza Lêgerîna Zevî',
  'duration': 'Demê',
  'seconds': 'saniye',
  'startTime': 'Demê Destnêşî',
  'endTime': 'Demê Dawî',
  'pauseTime': 'Demê Wergirtin',
  'unlock': 'Kilîdê vekî',
  'lock': 'Kilîdê bike',
  'delete': 'Jê bibe',
  'languageSetting': 'Mîhenga Zimanê',
  'currentLanguage': 'Niha',
  'systemLanguage': 'Zimanê Pergalê',
  'chinese': 'Çînî',
  'english': 'Îngilîzî',
  'language': 'Ziman',
  // Home page
  'newbie': 'Nûte',
  'newBattle': 'Herêma Nû',
  'continueChallenge': 'Çalakî bidewê',
  'error': 'Xeta',
  'initializationFailed': 'Destnêşî qet bû',
  // Game page
  'congratulations': 'Mîlbîjî, te statîyê qedi!',
  'gameOver': 'Lîstîk qet',
  'timeUsed': 'Demê hat bikirtîn',
  'actionCount': 'Hejmara Karan',
  'mineCount': 'Hejmara Zevî',
  'nextLevel': 'Statiya Pêş: Statîya {level}',
  'newbieNextLevel': 'Statiya Pêş: Nûte {level}',
  'nextLevelMines': 'Hejmara Zevî',
  'mineIncrease': 'Zêdeyî',
  'newbieFinish': 'Saşîza nûtiyan qedi',
  'ok': 'OK',
  'continueNextLevel': 'Bi statîya pêşê re',
  'restart': 'Dîsa bide destnêşî',
  'level': 'Statîya {level}',
  'newbieLevel': 'Statîya Nûte {level}',
  'operationFailed': 'Kar qet bû',
  // Game status texts
  'returnHome': 'Vegere malperê',
  'revealMode': 'Moda Zindîkirin',
  'flagMode': 'Moda Alamê',
  'newMap': 'Xeriteya nû (hejmara zevî yek hez, xeriteya nû biafirînî)',
  'resetMap': 'Xeriteyê dîsa bikelê (xeriteya yek hez, rewşa vekî)',
  'zoomOut': 'Bi qetê biaxistîne',
  'zoomIn': 'Mezin bikerê',
  'resetZoom': 'Zoom vekî',
  'previousStep': 'Gêza Pêş',
  'pause': 'Wergirtin',
  'play': 'Bidewê',
  'nextStep': 'Gêza Pêş',
  'clickToStart': 'Li her xekê bikirtîne da lîstîk bide destnêşî',
  'playing': 'Lîstîk dêkim...',
  'gameWin': 'Mîlbîjî, te statîyê qedi!',
  'gameLose': 'Lîstîk qet, te zevî girt',
  'gamePaused': 'Lîstîk wergirtî ye',
  'ready': 'Amade',
  'clickStartShort': 'Bikirtîne da destnêşî bike',
  'playingShort': 'Dêkim',
  'winShort': 'Qedi!',
  'loseShort': 'Zevî girt',
  'pausedShort': 'Wergirtî',
  // Counter strings
  'currentLevel': 'Statîya Niha',
  'remainingMines': 'Zevîyên Maqewî',
  'gameTime': 'Demê Lîstîkê (saniye)',
  'operationCount': 'Hejmara Karan',
  'previousLevel': 'Statîya Pêş',
  'nextLevelShort': 'Statîya Pêş',
  // Battlefront strings
  'completed': 'Qedi',
  'inProgress': 'Dêkim',
  'continueGame': 'Lîstîk bidewê',
  'replay': 'Dîsa bidewê',
  'creater': 'Serheskar',
  'created': 'Demê Destnêşîya Herêma',
  'updated': 'Nûkirî',
  // Dialog strings
  'confirm': 'Piştrast bikin',
  'cancel': 'Betal bikin',
  'yes': 'Erê',
  'no': 'Na',
  'save': 'Parêz bikin',
  'edit': 'Sererast bikin',
  'levelFormat': 'Statîya {level}',
  'newbieLevelFormat': 'Statîya Nûte {level}',
  'totalLevel': '{level}/{totalLevel} statî',
  'totalLevelTooltip': 'Niha: Statîya {level} / Hemû {totalLevel} statî',
  // Battlefront UI strings
  'noBattlefronts': 'Herêma tune',
  'battlefrontCount': '{count} herêm',
  'levelPrefix': 'ST{level}',
  'newbieLevelPrefix': 'NT{level}',
  'minesCount': '{count} zevî',
  'notStarted': 'Destnêşî neqet',
  'victory': 'Serkeftî',
  'defeat': 'Betal',
  'gameDurationParam': 'Demê: {seconds} saniye',
  'actionsCountParam': 'Karan: {count} car',
  'actionsCountParamShort': '{count} car',
  'miningMethodParam': 'Rêbaz: {method}',
  'startTimeParam': 'Destnêşî: {time}',
  'endTimeParam': 'Dawî: {time}',
  'returnButton': 'Vegere',
  'battlefrontDetails': 'Detayên Herêma',
  'clickToEditName': 'Bikirtîne da navê sererast bikin',
  'clickToAddDescription': 'Bikirtîne da tercîfê zêde bikin...',
  'noDescription': 'Tercîf tune',
  // Level record strings
  'levelCount': '{count} statî',
  'noLevelRecords': 'Herêma hilbijêre',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Herêma jê bibe',
  'deleteBattlefrontContent':
      'Tu bi rastî dixwazî herêma "{name}" jê bibî? Ev kar nayê vegerin.',
  'battlefrontLockedCannotDelete': 'Herêma kilîdî ye, nayê jê birin',
  'unknownNavigationLevel': 'Statîya navgîdanê nayên zanîn',
  'noBattlefrontSelected': 'Herêma hilbijêrî neqet',
  'noBattlefrontToContinue': 'Herêma bidewê tune',
  'synced': 'Hemakirdî',
  'notSynced': 'Hemakar neqet',
  'newbieBattlefrontName': 'Herêma Nûte {number}',
  'battlefrontName': 'Herêma {number}',
  'nickname': 'Navê Kûçik',
  'nicknameSetting': 'Mîhenga Navê Kûçikê',
  'nicknameDesc': 'Navê kûçikê te mîhen bikin',
  'enterNickname': 'Navê kûçikê bikin',
  'nicknameSaved': 'Navê kûçikê parêz kirî',
  'nicknameUpdated': 'Navê kûçikê nû kirî',
  'nicknameRequired': 'Navê kûçikê hewce ye',
  'nicknameTooLong': 'Navê kûçikê ne dikarin zêde bî 30 karakter bîn',
  // Level top strings
  'levelTopCount': 'Rêzîk ({count})',
  'levelTopCountShort': 'Rêzîk ({count})',
  'retry': 'Dîsa biceribîne',
  'noLevelTopData': 'Daneyê tune',
  'remoteBattlefront': 'Herêma Dûr',
  'participated': 'Beşdar bû',
  'notParticipated': 'Beşdar nebû',
  'loadMore': 'Zêdetir bikelê',

  'joinBattle': 'Bi herêma re beşdar bikin',
  'joinBattleTooltip': 'Bi herêma "{name}" re beşdar bikin',
  'joinBattleConfirm': 'Tu bi rastî dixwazî bi herêma "{name}" re beşdar bî?',
  'joinBattleSuccess': 'Tu bi serkeftî bi herêma "{name}" re beşdar bû',
  'joinBattleErrorSelf': 'Tu nikarî bi herêma xwe re beşdar bî',

  'replayBattlefront': 'Herêma dîsa bidewê',
  'replayBattlefrontTooltip': 'Herêma "{name}" dîsa bidewê',
  'getReplayBattlefrontConfirm': 'Tu bi rastî dixwazî "{name}" dîsa bidewê?',
  'getReplayBattlefrontFailed': 'Herêma "{name}" dîsa bidewê qet bû: {error}',

  'download': 'Da bikin',
  'downloadBattlefront': 'Herêma da bikin',
  'downloadBattlefrontTooltip': 'Herêma "{name}" da bikin',
  'getDownloadBattlefrontConfirm': 'Tu bi rastî dixwazî "{name}" da bî?',
  'getDownloadBattlefrontSuccess': 'Herêma "{name}" bi serkeftî hat da bikin',
  'downloadMyOwnBattlefrontError': 'Tu tenê dikarî herêmên xwe da bî',
  'getDownloadBattlefrontFailed': 'Herêma "{name}" da bikin qet bû: {error}',

  'continueGameShort': 'Herêma bidewê',
  'replayShort': 'Dîsa bidewê',
  'highestLevel': 'Statîya {level}',
  'deviceNickname': 'Cîhaz',
  'createdTime': 'Demê Afirandinê',
  'remoteBattlefrontDetail': 'Detayên Herêma Dûr',
  'levelList': 'Lîsteya Statîyan',
  'fastClearTimeParam': 'Demê Qedî: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Herêma herêmî hilbijêre da detayên bînî',
  'loadingRemoteDetail': 'Detayên herêma dûr dê bikirtînin...',
  'noRemoteBattlefrontSelected': 'Herêma dûr hilbijêrî neqet',
  'failedToLoadRemoteDetail': 'Detayên dûr bikirtîn qet bû',
  'fastestRecord': 'Qedîya Zû',
  'safestRecord': 'Qedîya Ewle',
  'fastestRecordDesc': 'Qedîya zû (dem kêm)',
  'safestRecordDesc': 'Qedîya ewle (kar kêm)',
  'creator': 'Afirand',
  'player': 'Lîstikdar',
  // 分支地图字符串
  'getBranchMapCount': '{count} koopya',
  'collapse': 'Biaxistîne',
  'expand': 'Biaxistîne',
  // 退出战线
  'quitBattlefront': 'Herêma jê bibe',
  'quitBattlefrontTooltip': 'Herêma dûr jê bibe',
  'quitBattlefrontTitle': 'Herêma jê bibe',
  'quitBattlefrontContent':
      'Tu bi rastî dixwazî herêma "{name}" jê bibî? Pêşketina we herêmî jê dibe.',

  // 下载页面
  'downloadClient': 'Mîster da bikin',
  'browser': 'Berserêro',
  'browserDesc': 'Lîstîkê herçawa li berserêroyê bikin, bê da bikin',
  'windowsDesc': 'Ji bo Windows 10 û nûntir',
  'macosDesc': 'Ji bo macOS 10.15 û nûntir',
  'android': 'Android',
  'androidDesc': 'Ji bo Android 8.0 û nûntir',
  'iosDesc': 'Ji bo iOS 14.0 û nûntir',
  'linkAddress': 'Navê Girê',
  'downloadLink': 'Girê Da Bikin',
  'qrCode': 'Kodê QR',
  'scanToDownload': 'Bi telefona scan bikin da da bikin',
  'copy': 'Kopyê bikin',
  'copiedToClipboard': 'Kopyê kirî li klipborda',
  'openLink': 'Girê vekî',
  'cannotOpenLink': 'Girê nayê vekirin',
  // 游戏介绍
  'gameIntroduction':
      '1. "Nûte" bi 15 zevî destnêşî dike û dikarin heta 99 zevî bikin.\n2. "Herêma Nû" bi 81 zevî destnêşî dike, her statî zevî zêde dike bê sînorkirina jorîn.\n3. Bi girêya internetê, herêmên "qedî" bi awtomatîk li bulûtê parêz dibin da başk biajin.',
};
