//Esperanto（世界语）
/// Esperanto-stlingoj por la DMine-aplikaĵo
const Map<String, String> stringsEo = {
  'appLabel': 'Supra Minomapilo',
  'appTitle': 'DMine - Supra Minomapilo',
  'settings': 'Agordoj',
  'gameSettings': 'Ludagordoj',
  'showTimer': 'Montri tempomezurilon',
  'showTimerDesc': 'Montri la ludtempomezurilon en la luda interfaco',
  'showActionCounter': 'Montri agadnombron',
  'showActionCounterDesc': 'Montri nombron da agadoj en la luda interfaco',
  'autoAdjustBoardWidth': 'Aŭtomate ĝustigi tabularon larĝecon',
  'autoAdjustBoardWidthDesc':
      'Aŭtomate ĝustigi tabularon larĝecon laŭ ekrana grandeco',
  'resetToDefaults': 'Reenigi al defaŭltoj',
  'resetToDefaultsDesc': 'Reenigi ĉiujn agordojn al defaŭlta valoroj',
  'aboutDMine': 'Pri DMine',
  'version': 'Versio',
  'close': 'Fermi',
  'manualBoardWidth': 'Manuele agordi tabularon larĝecon',
  'currentWidth': 'Nuna',
  'range': 'Intervalo',
  'widthSliderHint':
      'Consilo: Vi povas antauvidi ŝanĝojn de tabulara larĝeco en realtempo dum treni la ŝovilon',
  'gameRecords': 'Ludrekoroj',
  'selectMapToViewRecords': 'Elektu mapon por vidi la rekordojn',
  'totalRecords': 'Sume',
  'gameRecordsTitle': 'Listo de ludrekordoj',
  'pleaseSelectMapFirst': 'Unue elektu mapon',
  'noGameRecords': 'Neniu ludrekordo',
  'miningMethodFlag': 'Meti flagon',
  'miningMethodBlind': 'Blinda serĉado',
  'statusPlaying': '▶️ En kurso...',
  'statusWin': '🎉 Venko',
  'statusLose': '💥 Malvenko',
  'actionsCount': 'Nombro da agadoj',
  'miningMethod': 'Minoserĉmetodo',
  'duration': 'Daŭro',
  'seconds': 'sekundoj',
  'startTime': 'Komenca tempo',
  'endTime': 'Fina tempo',
  'pauseTime': 'Paŭza tempo',
  'unlock': 'Malŝlosi',
  'lock': 'Ŝlosi',
  'delete': 'Forigi',
  'languageSetting': 'Lingva agordo',
  'currentLanguage': 'Nuna',
  'systemLanguage': 'Sistema lingvo',
  'chinese': 'Ĉina',
  'english': 'Angla',
  'language': 'Lingvo',
  // Home page
  'newbie': 'Komencanto',
  'newBattle': 'Nova Batalfrontujo',
  'continueChallenge': 'Daŭrigi defion',
  'error': 'Eraro',
  'initializationFailed': 'Inicialigo malsukcesis',
  // Game page
  'congratulations': 'Gratulon, vi trapasis la nivelon!',
  'gameOver': 'Ludo finita',
  'timeUsed': 'Uzita tempo',
  'actionCount': 'Nombro da agadoj',
  'mineCount': 'Nombro da minoj',
  'nextLevel': 'Sekva nivelo: Nivelo {level}',
  'newbieNextLevel': 'Sekva nivelo: Komencanta {level}',
  'nextLevelMines': 'Nombro da minoj',
  'mineIncrease': 'Pliigo',
  'newbieFinish': 'Komencanta instruo finita',
  'ok': 'Bone',
  'continueNextLevel': 'Daŭrigi al sekva nivelo',
  'restart': 'Rekomencigi',
  'level': 'Nivelo {level}',
  'newbieLevel': 'Komencanta nivelo {level}',
  'operationFailed': 'Operacio malsukcesis',
  // Game status texts
  'returnHome': 'Reeniri hejmen',
  'revealMode': 'Malkaŝa reĝimo',
  'flagMode': 'Flaga reĝimo',
  'newMap': 'Nova mapo (samnumero da minoj, generi novan mapon)',
  'resetMap': 'Reŝargi mapon (sama mapo, reenigi staton)',
  'zoomOut': 'Malgrandigi',
  'zoomIn': 'Grandigi',
  'resetZoom': 'Reenigi zomon',
  'previousStep': 'Antaŭa paŝo',
  'pause': 'Paŭzi',
  'play': 'Ludi',
  'nextStep': 'Sekva paŝo',
  'clickToStart': 'Klaku ajnan kadron por komenci la ludon',
  'playing': 'Ludante...',
  'gameWin': 'Gratulon, vi trapasis la nivelon!',
  'gameLose': 'Ludo finita, vi trapasis minon',
  'gamePaused': 'Ludo paŭzita',
  'ready': 'Preta',
  'clickStartShort': 'Klaku por komenci',
  'playingShort': 'En kurso',
  'winShort': 'Trapasita!',
  'loseShort': 'Trapasis minon',
  'pausedShort': 'Paŭzita',
  // Counter strings
  'currentLevel': 'Nuna nivelo',
  'remainingMines': 'Restantaj minoj',
  'gameTime': 'Luda tempo (sekundoj)',
  'operationCount': 'Nombro da operacioj',
  'previousLevel': 'Antaŭa nivelo',
  'nextLevelShort': 'Sekva nivelo',
  // Battlefront strings
  'completed': 'Finita',
  'inProgress': 'Enkurso',
  'continueGame': 'Daŭrigi ludon',
  'replay': 'Relerpi',
  'creater': 'Ĉefkomandanto',
  'created': 'Batalkomenca tempo',
  'updated': 'Ĝisdatigita',
  // Dialog strings
  'confirm': 'Konfirmi',
  'cancel': 'Nuligi',
  'yes': 'Jes',
  'no': 'Ne',
  'save': 'Konservi',
  'edit': 'Redakti',
  'levelFormat': 'Nivelo {level}',
  'newbieLevelFormat': 'Komencanta nivelo {level}',
  'totalLevel': '{level}/{totalLevel} niveloj',
  'totalLevelTooltip': 'Nuna: Nivelo {level} / Sume {totalLevel} niveloj',
  // Battlefront UI strings
  'noBattlefronts': 'Neniu batalfrontujo',
  'battlefrontCount': '{count} batalfrontujoj',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'KOM{level}',
  'minesCount': '{count} minoj',
  'notStarted': 'Ne komencita',
  'victory': 'Venko',
  'defeat': 'Malvenko',
  'gameDurationParam': 'Daŭro: {seconds} sekundoj',
  'actionsCountParam': 'Agadoj: {count} fojojn',
  'actionsCountParamShort': '{count} fojojn',
  'miningMethodParam': 'Metodo: {method}',
  'startTimeParam': 'Komenca tempo: {time}',
  'endTimeParam': 'Fina tempo: {time}',
  'returnButton': 'Reeniri',
  'battlefrontDetails': 'Detaloj de batalfrontujo',
  'clickToEditName': 'Klaku por ŝanĝi nomon',
  'clickToAddDescription': 'Klaku por aldoni priskribon...',
  'noDescription': 'Neniu priskribo',
  // Level record strings
  'levelCount': '{count} niveloj',
  'noLevelRecords': 'Elektu batalfrontujon',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Forigi batalfrontujon',
  'deleteBattlefrontContent':
      'Ĉu vi certas, ke vi volas forigi la batalfrontujon "{name}"? Ĉi tiu ago estas nerevokebla.',
  'battlefrontLockedCannotDelete':
      'Batalfrontujo estas ŝlosita, ne povas forigi',
  'unknownNavigationLevel': 'Nekonata navigada nivelo',
  'noBattlefrontSelected': 'Neniu batalfrontujo elektita',
  'noBattlefrontToContinue': 'Neniu batalfrontujo por daŭrigi',
  'synced': 'Sinkronigita',
  'notSynced': 'Ne sinkronigita',
  'newbieBattlefrontName': 'Komencanta batalfrontujo {number}',
  'battlefrontName': 'Batalfrontujo {number}',
  'nickname': 'Elstarnomo',
  'nicknameSetting': 'Agordo de elstarnomo',
  'nicknameDesc': 'Agordu vian elstarnomon',
  'enterNickname': 'Enigu elstarnomon',
  'nicknameSaved': 'Elstarnomo konservita',
  'nicknameUpdated': 'Elstarnomo ĝisdatigita',
  'nicknameRequired': 'Elstarnomo estas deviga',
  'nicknameTooLong': 'Elstarnomo ne povas superi 30 signojn',
  // Level top strings
  'levelTopCount': 'Plej bonaj ({count})',
  'levelTopCountShort': 'Plej bonaj ({count})',
  'retry': 'Provi denove',
  'noLevelTopData': 'Neniu datumoj',
  'remoteBattlefront': 'Fora batalfrontujo',
  'participated': 'Partoprenis',
  'notParticipated': 'Ne partoprenis',
  'loadMore': 'Ŝarĝi pli',

  'joinBattle': 'Partopreni batalon',
  'joinBattleTooltip': 'Partopreni la batalon "{name}"',
  'joinBattleConfirm':
      'Ĉu vi certas, ke vi volas partopreni la batalon "{name}"?',
  'joinBattleSuccess': 'Vi sukcese partoprenis la batalon "{name}"',
  'joinBattleErrorSelf': 'Vi ne povas partopreni vian propran batalfrontujon',

  'replayBattlefront': 'Relerpi batalfrontujon',
  'replayBattlefrontTooltip': 'Relerpi la batalfrontujon "{name}"',
  'getReplayBattlefrontConfirm': 'Ĉu vi certas, ke vi volas relerpi "{name}"?',
  'getReplayBattlefrontFailed': 'Relerpado de "{name}" malsukcesis: {error}',

  'download': 'Elŝuti',
  'downloadBattlefront': 'Elŝuti batalfrontujon',
  'downloadBattlefrontTooltip': 'Elŝuti la batalfrontujon "{name}"',
  'getDownloadBattlefrontConfirm': 'Ĉu vi certas, ke vi volas elŝuti "{name}"?',
  'getDownloadBattlefrontSuccess': 'Batalfrontujo "{name}" sukcese elŝutita',
  'downloadMyOwnBattlefrontError':
      'Vi povas elŝuti nur viajn proprajn batalfrontujojn',
  'getDownloadBattlefrontFailed': 'Elŝutado de "{name}" malsukcesis: {error}',

  'continueGameShort': 'Daŭrigi batalon',
  'replayShort': 'Relerpi',
  'highestLevel': 'Nivelo {level}',
  'deviceNickname': 'Aparato',
  'createdTime': 'Kreotempo',
  'remoteBattlefrontDetail': 'Detaloj de fora batalfrontujo',
  'levelList': 'Listo de niveloj',
  'fastClearTimeParam': 'Trapasa tempo: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Elektu lokan batalfrontujon por vidi detalojn',
  'loadingRemoteDetail': 'Ŝarĝante detalojn de fora batalfrontujo...',
  'noRemoteBattlefrontSelected': 'Neniu fora batalfrontujo elektita',
  'failedToLoadRemoteDetail': 'Malsukcesis ŝargi fora detalojn',
  'fastestRecord': 'Plej rapida trapaso',
  'safestRecord': 'Plej sekura trapaso',
  'fastestRecordDesc': 'Plej rapida trapaso (malplej da tempo)',
  'safestRecordDesc': 'Plej sekura trapaso (malplej da agadoj)',
  'creator': 'Kreinto',
  'player': 'Ludanto',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopioj',
  'collapse': 'Faldi',
  'expand': 'Malfaldi',
  // 退出战线
  'quitBattlefront': 'Forlasi batalfrontujon',
  'quitBattlefrontTooltip': 'Forlasi fora batalfrontujon',
  'quitBattlefrontTitle': 'Forlasi batalfrontujon',
  'quitBattlefrontContent':
      'Ĉu vi certas, ke vi volas forlasi la batalfrontujon "{name}"? Via loka progreso estos forigita.',

  // 下载页面
  'downloadClient': 'Elŝuti klienton',
  'browser': 'Retumilo',
  'browserDesc': 'Ludu rekte en la retumilo, sen elŝutado',
  'windowsDesc': 'Por Windows 10 kaj pli novaj',
  'macosDesc': 'Por macOS 10.15 kaj pli novaj',
  'android': 'Android',
  'androidDesc': 'Por Android 8.0 kaj pli novaj',
  'iosDesc': 'Por iOS 14.0 kaj pli novaj',
  'linkAddress': 'Ligadreso',
  'downloadLink': 'Elŝuta ligilo',
  'qrCode': 'QR-kodo',
  'scanToDownload': 'Skanu per telefono por elŝuti',
  'copy': 'Kopii',
  'copiedToClipboard': 'Kopiita al poŝo',
  'openLink': 'Malfermi ligilon',
  'cannotOpenLink': 'Ne povas malfermi ligilon',
  // 游戏介绍
  'gameIntroduction':
      '1. "Komencanto" komenciĝas kun 15 minoj, povas atingi ĝis 99 minoj;\n2. "Nova batalfrontujo" komenciĝas kun 81 minoj, ĉiu nivelo aldonas minojn sen supra limo.\n3. Kun interreto, "finitaj" batalfrontujoj aŭtomate disiĝas en la nubon por aliaj lernado.',
};
