// Slovak（斯洛伐克语）
/// Slovak language strings for the DMine application
const Map<String, String> stringsSk = {
  'appLabel': 'Top Hra v Míny',
  'appTitle': 'DMine - Top Hra v Míny',
  'settings': 'Nastavenia',
  'gameSettings': 'Nastavenia hry',
  'showTimer': 'Zobraziť časovač',
  'showTimerDesc': 'Zobrazí časovač hry na hernej obrazovke',
  'showActionCounter': 'Zobraziť počítadlo akcií',
  'showActionCounterDesc': 'Zobrazí počet akcií na hernej obrazovke',
  'autoAdjustBoardWidth': 'Automaticky prispôsobiť šírku dosky',
  'showUnrevealedCounter': 'Zobraziť počítadlo neodhalených políčok',
  'showUnrevealedCounterDesc': 'Zobraziť počet neodhalených políčok v hernom rozhraní',
  'showMineCounter': 'Zobraziť počítadlo mín',
  'showMineCounterDesc': 'Zobraziť zostávajúci počet mín v hernom rozhraní',
  'autoAdjustBoardWidthDesc':
      'Automaticky prispôsobí šírku dosky podľa veľkosti obrazovky',
  'resetToDefaults': 'Obnoviť predvolené nastavenia',
  'resetToDefaultsDesc': 'Obnoví všetky nastavenia na predvolené hodnoty',
  'aboutDMine': 'O DMine',
  'version': 'Verzia',
  'close': 'Zavrieť',
  'manualBoardWidth': 'Manuálne nastaviť šírku dosky',
  'currentWidth': 'Aktuálna',
  'range': 'Rozsah',
  'widthSliderHint':
      'Tip: pri ťahaní posuvníka vidíte zmenu šírky dosky okamžite',
  'gameRecords': 'Herné záznamy',
  'selectMapToViewRecords': 'Vyberte mapu na zobrazenie záznamov',
  'totalRecords': 'Celkom',
  'gameRecordsTitle': 'Zoznam herných záznamov',
  'pleaseSelectMapFirst': 'Najskôr vyberte mapu',
  'noGameRecords': 'Žiadne herné záznamy',
  'miningMethodFlag': 'Označiť vlajkou',
  'miningMethodBlind': 'Slepé odhalovanie',
  'statusPlaying': '▶️ Prebieha...',
  'statusWin': '🎉 Víťazstvo',
  'statusLose': '💥 Prehra',
  'actionsCount': 'Počet akcií',
  'miningMethod': 'Spôsob hry',
  'duration': 'Trvanie',
  'seconds': 'sekúnd',
  'startTime': 'Čas začiatku',
  'endTime': 'Čas konca',
  'pauseTime': 'Čas pauzy',
  'unlock': 'Odomknúť',
  'lock': 'Zamknúť',
  'delete': 'Vymazať',
  'languageSetting': 'Nastavenie jazyka',
  'currentLanguage': 'Aktuálny',
  'systemLanguage': 'Systémový jazyk',
  'chinese': 'Čínsky',
  'english': 'Angličtina',
  'language': 'Jazyk',
  // Home page
  'newbie': 'Začiatočník',
  'gameIntro': 'Popis hry',
  'newBattle': 'Nová fronta',
  'continueChallenge': 'Pokračovať vo výzve',
  'error': 'Chyba',
  'initializationFailed': 'Inicializácia zlyhala',
  // Game page
  'congratulations': 'Gratulujeme, úroveň prešla!',
  'gameOver': 'Koniec hry',
  'timeUsed': 'Čas',
  'actionCount': 'Akcie',
  'mineCount': 'Míny',
  'nextLevel': 'Ďalšia úroveň: Úroveň {level}',
  'newbieNextLevel': 'Ďalšia úroveň: Začiatočník {level}',
  'nextLevelMines': 'Míny',
  'mineIncrease': 'Prírastok',
  'newbieFinish': 'Režim začiatočníka dokončený',
  'ok': 'OK',
  'continueNextLevel': 'Pokračovať na ďalšiu úroveň',
  'restart': 'Reštartovať',
  'level': 'Úroveň {level}',
  'newbieLevel': 'Začiatočník {level}',
  'operationFailed': 'Operácia zlyhala',
  // Game status texts
  'returnHome': 'Návrat domov',
  'revealMode': 'Režim odhalovania',
  'flagMode': 'Režim vlajok',
  'newMap': 'Nová mapa (rovnaký počet mín, nový rozloženie)',
  'resetMap': 'Obnoviť mapu (rovnaké rozloženie, reset stavu)',
  'zoomOut': 'Zmenšiť',
  'zoomIn': 'Zväčšiť',
  'resetZoom': 'Obnoviť orig. veľkosť',
  'previousStep': 'Predchádzajúci krok',
  'pause': 'Pauza',
  'play': 'Hrať',
  'nextStep': 'Ďalší krok',
  'clickToStart': 'Kliknite na ľubovoľné políčko na začatie hry',
  'playing': 'V hre...',
  'gameWin': 'Gratulujeme, úroveň prešla!',
  'gameLose': 'Koniec hry, stali ste na mínu',
  'gamePaused': 'Hra pozastavená',
  'ready': 'Pripravené na začatie',
  'clickStartShort': 'Kliknite pre začatie',
  'playingShort': 'V hre',
  'winShort': 'Dokončené!',
  'loseShort': 'Prehra',
  'pausedShort': 'Pozastavené',
  // Counter strings
  'currentLevel': 'Aktuálna úroveň',
  'remainingMines': 'Zostávajúce míny',
  'unrevealedCells': 'Neodhalené políčka',
  'gameTime': 'Čas hry (sekúnd)',
  'operationCount': 'Počet operácií',
  'previousLevel': 'Predchádzajúca úroveň',
  'nextLevelShort': 'Ďalšia úroveň',
  // Battlefront strings
  'completed': 'Dokončené',
  'inProgress': 'Prebieha',
  'continueGame': 'Pokračovať v hre',
  'replay': 'Prehrať',
  'creater': 'Veliteľ',
  'created': 'Čas vytvorenia',
  'updated': 'Aktualizované',
  // Dialog strings
  'confirm': 'Potvrdiť',
  'cancel': 'Zrušiť',
  'yes': 'Áno',
  'no': 'Nie',
  'save': 'Uložiť',
  'edit': 'Upraviť',
  'levelFormat': 'Úroveň {level}',
  'newbieLevelFormat': 'Začiatočník {level}',
  'totalLevel': '{level}/{totalLevel} úrovní',
  'totalLevelTooltip': 'Aktuálne: Úroveň {level} / Celkom {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Žiadne fronty',
  'battlefrontCount': '{count} frontov',
  'levelPrefix': 'ÚR{level}',
  'newbieLevelPrefix': 'Začiatočník ÚR{level}',
  'minesCount': '{count} mín',
  'notStarted': 'Nezapočaté',
  'victory': 'Víťazstvo',
  'defeat': 'Prehra',
  'gameDurationParam': 'Trvanie: {seconds}s',
  'actionsCountParam': 'Akcie: {count} krát',
  'actionsCountParamShort': '{count} krát',
  'miningMethodParam': 'Spôsob: {method}',
  'startTimeParam': 'Začiatok: {time}',
  'endTimeParam': 'Koniec: {time}',
  'returnButton': 'Späť',
  'battlefrontDetails': 'Detaily frontu',
  'clickToEditName': 'Kliknite pre úpravu názvu',
  'clickToAddDescription': 'Kliknite pre pridanie popisu...',
  'noDescription': 'Žiadny popis',
  // Level record strings
  'levelCount': '{count} úrovní',
  'noLevelRecords': 'Vyberte front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Vymazať front',
  'deleteBattlefrontContent':
      'Naozaj chcete vymazať front \'{name}\'? Táto akcia sa nedá vrátiť.',
  'battlefrontLockedCannotDelete': 'Front je zamknutý, nie je možné vymazať',
  'unknownNavigationLevel': 'Neznáma úroveň',
  'noBattlefrontSelected': 'Žiadny front vybraný',
  'noBattlefrontToContinue': 'Žiadny front na pokračovanie',
  'synced': 'Synchronizované',
  'notSynced': 'Nesynchronizované',
  'newbieBattlefrontName': 'Front začiatočníka {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Prezývka',
  'nicknameSetting': 'Nastavenie prezývky',
  'nicknameDesc': 'Nastavte svoju prezývku',
  'enterNickname': 'Zadajte prezývku',
  'nicknameSaved': 'Prezývka uložená',
  'nicknameUpdated': 'Prezývka aktualizovaná',
  'nicknameRequired': 'Prezývka je povinná',
  'nicknameTooLong': 'Prezývka nemôže mať viac ako 30 znakov',
  // Level top strings
  'levelTopCount': 'Rebríček ({count})',
  'levelTopCountShort': 'Rebríček ({count})',
  'retry': 'Skúsiť znova',
  'noLevelTopData': 'Žiadne dáta',
  'remoteBattlefront': 'Vzdialený front',
  'participated': 'Zúčastnil sa',
  'notParticipated': 'Nezúčastnil sa',
  'loadMore': 'Načítať viac',
  'joinBattle': 'Pripojiť k bitke',
  'joinBattleTooltip': 'Pripojiť k bitke \'{name}\'',
  'joinBattleConfirm': 'Naozaj sa chcete pripojiť k bitke \'{name}\'?',
  'joinBattleSuccess': 'Úspešne ste sa pripojili k bitke \'{name}\'',
  'joinBattleErrorSelf': 'Nemôžete sa pripojiť k vlastnému frontu',
  'replayBattlefront': 'Prehrať front',
  'replayBattlefrontTooltip': 'Prehrať front \'{name}\'',
  'getReplayBattlefrontConfirm': 'Naozaj chcete prehrať \'{name}\'?',
  'getReplayBattlefrontFailed': 'Prehratie \'{name}\' zlyhalo: {error}',
  'download': 'Stiahnuť',
  'downloadBattlefront': 'Stiahnuť front',
  'downloadBattlefrontTooltip': 'Stiahnuť front \'{name}\'',
  'getDownloadBattlefrontConfirm': 'Naozaj chcete stiahnuť \'{name}\'?',
  'getDownloadBattlefrontSuccess': '\'{name}\' úspešne stiahnuté',
  'downloadMyOwnBattlefrontError': 'Môžete stiahnuť len vlastné fronty',
  'getDownloadBattlefrontFailed': 'Sťahovanie \'{name}\' zlyhalo: {error}',
  'continueGameShort': 'Pokračovať v bitke',
  'replayShort': 'Prehrať',
  'highestLevel': 'Úroveň {level}',
  'deviceNickname': 'Zariadenie',
  'createdTime': 'Čas vytvorenia',
  'remoteBattlefrontDetail': 'Detaily vzdialeného frontu',
  'levelList': 'Zoznam úrovní',
  'fastClearTimeParam': 'Čas dokončenia: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint': 'Vyberte lokálny front na zobrazenie detailov',
  'loadingRemoteDetail': 'Načítavanie detailov vzdialeného frontu...',
  'noRemoteBattlefrontSelected': 'Žiadny vzdialený front vybraný',
  'failedToLoadRemoteDetail': 'Načítavanie detailov zlyhalo',
  'fastestRecord': 'Najrýchlejšie dokončenie',
  'safestRecord': 'Najbezpečnejšie dokončenie',
  'fastestRecordDesc': 'Najrýchlejšie (najmenej času)',
  'safestRecordDesc': 'Najbezpečnejšie (najmenej akcií)',
  'creator': 'Vytvoril',
  'player': 'Hráč',
  // Branch maps
  'getBranchMapCount': '{count} kópií',
  'collapse': 'Zvinúť',
  'expand': 'Rozvinúť',
  // Quit battlefront
  'quitBattlefront': 'Opustiť front',
  'quitBattlefrontTooltip': 'Opustiť vzdialený front',
  'quitBattlefrontTitle': 'Opustiť front',
  'quitBattlefrontContent':
      'Naozaj chcete opustiť front \'{name}\'? Váš lokálny pokrok bude vymazaný.',
  // Game introduction
  'gameIntroduction':
      '1. „Začiatočník“ začína s 15 mínami, maximálne do 99 mín;\n2. „Nová fronta“ začína s 81 mínami, počet sa zvyšuje každú úroveň, bez horného limitu.\n3. Pri pripojení k sieti sú dokončené fronty automaticky zdieľané v cloude pre ostatných hráčov.',
};
