/// Chinese language strings for the DMine application
const Map<String, String> stringsZh = {
  'appTitle': 'DMine - 顶级扫雷',
  'settings': '设置',
  'gameSettings': '游戏设置',
  'showTimer': '显示用时计时器',
  'showTimerDesc': '在游戏界面显示游戏计时器',
  'showActionCounter': '显示动作数计数器',
  'showActionCounterDesc': '在游戏界面显示动作次数统计',
  'autoAdjustBoardWidth': '自动调整棋盘宽度',
  'autoAdjustBoardWidthDesc': '自动根据屏幕大小调整棋盘宽度',
  'resetToDefaults': '重置为默认设置',
  'resetToDefaultsDesc': '恢复所有设置为默认值',
  'aboutDMine': '关于顶雷',
  'version': '版本',
  'close': '关闭',
  'manualBoardWidth': '手动设置棋盘宽度',
  'currentWidth': '当前',
  'range': '范围',
  'widthSliderHint': '提示：滑块拖动过程中可以即时预览棋盘宽度变化',
  'gameRecords': '游戏记录',
  'selectMapToViewRecords': '请选择一个地图查看记录',
  'totalRecords': '共',
  'gameRecordsTitle': '游戏记录列表',
  'pleaseSelectMapFirst': '请先选择一个地图',
  'noGameRecords': '暂无游戏记录',
  'miningMethodFlag': '插旗',
  'miningMethodBlind': '盲扫',
  'statusPlaying': '▶️ 进行中...',
  'statusWin': '🎉 胜利',
  'statusLose': '💥 失败',
  'actionsCount': '操作数',
  'miningMethod': '扫雷方式',
  'duration': '时长',
  'seconds': '秒',
  'startTime': '开始时间',
  'endTime': '结束时间',
  'pauseTime': '暂停时间',
  'unlock': '解锁',
  'lock': '锁定',
  'delete': '删除',
  'languageSetting': '语言设置',
  'currentLanguage': '当前',
  'systemLanguage': '系统语言',
  'chinese': '中文',
  'english': 'English',
  'language': '语言',
  // Home page
  'newBattle': '新战线',
  'continueChallenge': '继续挑战',
  'error': '错误',
  'initializationFailed': '初始化失败',
  // Game page
  'congratulations': '恭喜通关！',
  'gameOver': '游戏结束',
  'timeUsed': '用时',
  'actionCount': '动作数',
  'mineCount': '地雷数',
  'nextLevel': '下一关: 第 {level} 关',
  'nextLevelMines': '地雷数',
  'mineIncrease': '增加数量',
  'ok': '确定',
  'continueNextLevel': '继续挑战下一关',
  'restart': '重新开始',
  'level': '第 {level} 关',
  'operationFailed': '操作失败',
  // Game status texts
  'returnHome': '返回主页',
  'revealMode': '揭开模式',
  'flagMode': '插旗模式',
  'newMap': '新地图(地雷数不变,生成新地图)',
  'previousStep': '上一步',
  'pause': '暂停',
  'play': '播放',
  'nextStep': '下一步',
  'clickToStart': '点击任意格子开始游戏',
  'playing': '游戏中...',
  'gameWin': '恭喜通关！',
  'gameLose': '游戏结束，踩到地雷了',
  'gamePaused': '游戏暂停',
  'ready': '准备开始',
  'clickStartShort': '点击开始',
  'playingShort': '游戏中',
  'winShort': '通关！',
  'loseShort': '踩雷失败',
  'pausedShort': '暂停',
  // Counter strings
  'currentLevel': '当前关次',
  'remainingMines': '剩余地雷数',
  'gameTime': '游戏用时（秒）',
  'operationCount': '操作次数',
  'previousLevel': '上一关',
  'nextLevelShort': '下一关',
  // Battlefront strings
  'completed': '已完成',
  'inProgress': '进行中',
  'continueGame': '继续游戏',
  'replay': '回放',
  'created': '创建',
  'updated': '更新',
  // Dialog strings
  'confirm': '确认',
  'cancel': '取消',
  'yes': '是',
  'no': '否',
  'save': '保存',
  'edit': '编辑',
  'levelFormat': '第 {level} 关',
  // Battlefront UI strings
  'noBattlefronts': '暂无战线',
  'battlefrontCount': '{count}个战线',
  'levelPrefix': 'LV{level}',
  'minesCount': '{count}雷',
  'notStarted': '未开始',
  'victory': '胜利',
  'defeat': '失败',
  'gameDurationParam': '游戏时长: {seconds}秒',
  'actionsCountParam': '动作数: {count}',
  'miningMethodParam': '扫雷方式: {method}',
  'startTimeParam': '开始时间: {time}',
  'endTimeParam': '结束时间: {time}',
  'returnButton': '返回',
  'battlefrontDetails': '战线详情',
  'clickToEditName': '点击修改名称',
  'clickToAddDescription': '点击添加描述...',
  // Level record strings
  'levelCount': '{count}个关次',
  'noLevelRecords': '请选择战线',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': '删除战线',
  'deleteBattlefrontContent': '确定要删除战线 "{name}" 吗？此操作不可撤销。',
  'battlefrontLockedCannotDelete': '战线已锁定，无法删除',
  'unknownNavigationLevel': '未知层级',
  'noBattlefrontSelected': '未选择战线',
  'noBattlefrontToContinue': '没有找到可继续的战线',
};
