// Lithuanian（立陶宛语）
/// Lietuvių kalbos tekstai DMine programai
const Map<String, String> stringsLt = {
  'appLabel': 'Minų Nukreipimo Žaidimas',
  'appTitle': 'DMine - Minų Nukreipimo Žaidimas',
  'settings': 'Nustatymai',
  'gameSettings': 'Žaidimo Nustatymai',
  'showTimer': 'Rodyti laikmatį',
  'showTimerDesc': 'Rodyti žaidimo laikmatį ekrane',
  'showActionCounter': 'Rodyti veiksmų skaičių',
  'showActionCounterDesc': 'Rodyti atliktų veiksmų skaičių žaidime',
  'autoAdjustBoardWidth': 'Automatiškai pritaikyti lentos plotį',
  'autoAdjustBoardWidthDesc':
      'Automatiškai pritaikyti lentos plotį ekrano dydžiui',
  'resetToDefaults': 'Atstatyti numatytas reikšmes',
  'resetToDefaultsDesc': 'Visus nustatymus atstatyti į pradinę būseną',
  'aboutDMine': 'Apie DMine',
  'version': 'Versija',
  'close': 'Uždaryti',
  'manualBoardWidth': 'Rankiniu būdu nustatyti lentos plotį',
  'currentWidth': 'Dabartinis',
  'range': 'Diapazonas',
  'widthSliderHint':
      'Patarimas: tempite slankiklį, kad realiu laiku matytumėte lentos pločio pokyčius',
  'gameRecords': 'Žaidimų Rezultatai',
  'selectMapToViewRecords':
      'Pasirinkite žemėlapį, kad peržiūrėtumėte rezultatus',
  'totalRecords': 'Iš viso',
  'gameRecordsTitle': 'Žaidimų Rezultatų Sąrašas',
  'pleaseSelectMapFirst': 'Pirma pasirinkite žemėlapį',
  'noGameRecords': 'Nėra žaidimų rezultatų',
  'miningMethodFlag': 'Žymėti vėliavute',
  'miningMethodBlind': 'Aklasis paieška',
  'statusPlaying': '▶️ Žaidžiama...',
  'statusWin': '🎉 Laimėta!',
  'statusLose': '💥 Pralaimėta!',
  'actionsCount': 'Veiksmų Skaičius',
  'miningMethod': 'Minų Rasti Metodas',
  'duration': 'Trukmė',
  'seconds': 'sekundžių',
  'startTime': 'Pradžios Laikas',
  'endTime': 'Pabaigos Laikas',
  'pauseTime': 'Pauzės Laikas',
  'unlock': 'Atrakinti',
  'lock': 'Užrakinti',
  'delete': 'Ištrinti',
  'languageSetting': 'Kalbos Nustatymas',
  'currentLanguage': 'Dabartinė',
  'systemLanguage': 'Sistemos Kalba',
  'chinese': 'Kinų',
  'english': 'Anglų',
  'language': 'Kalba',
  // Home page
  'newbie': 'Pradedantysis',
  'gameIntro': 'Žaidimo aprašymas',
  'newBattle': 'Nauja Fronte',
  'continueChallenge': 'Tęsti Iššūkį',
  'error': 'Klaida',
  'initializationFailed': 'Inicializacija nepavyko',
  // Game page
  'congratulations': 'Sveikiname! Jūs įveikėte lygį!',
  'gameOver': 'Žaidimas Baigtas',
  'timeUsed': 'Sugaištas Laikas',
  'actionCount': 'Veiksmų Skaičius',
  'mineCount': 'Minų Skaičius',
  'nextLevel': 'Kitas Lygis: Lygis {level}',
  'newbieNextLevel': 'Kitas Lygis: Pradedantysis {level}',
  'nextLevelMines': 'Minų Skaičius',
  'mineIncrease': 'Padidėjimas',
  'newbieFinish': 'Pradedantysis Baigtas',
  'ok': 'Gerai',
  'continueNextLevel': 'Pereiti į kitą lygį',
  'restart': 'Pradėti iš naujo',
  'level': 'Lygis {level}',
  'newbieLevel': 'Pradedantysis Lygis {level}',
  'operationFailed': 'Operacija nepavyko',
  // Game status texts
  'returnHome': 'Grįžti į pradžią',
  'revealMode': 'Atidengimo Veiksena',
  'flagMode': 'Vėliavų Veiksena',
  'newMap': 'Naujas Žemėlapis (tas pats minų skaičius, sukurti naują žemėlapį)',
  'resetMap': 'Atstatyti Žemėlapį (tas pats žemėlapis, atstatyti būseną)',
  'zoomOut': 'Sumažinti',
  'zoomIn': 'Padidinti',
  'resetZoom': 'Atstatyti Mastelį',
  'previousStep': 'Ankstesnis Žingsnis',
  'pause': 'Pauzė',
  'play': 'Žaisti',
  'nextStep': 'Kitas Žingsnis',
  'clickToStart': 'Spustelėkite bet kurį langelį, kad pradėtumėte žaidimą',
  'playing': 'Žaidžiama...',
  'gameWin': 'Sveikiname! Jūs įveikėte lygį!',
  'gameLose': 'Žaidimas baigtas, Jūs pataikėte į miną',
  'gamePaused': 'Žaidimas sustabdytas',
  'ready': 'Paruošta',
  'clickStartShort': 'Spustelėkite pradėti',
  'playingShort': 'Žaidžiama',
  'winShort': 'Laimėta!',
  'loseShort': 'Pataikyta į miną',
  'pausedShort': 'Pauzė',
  // Counter strings
  'currentLevel': 'Dabartinis Lygis',
  'remainingMines': 'Liko Minų',
  'gameTime': 'Žaidimo Laikas (sekundėmis)',
  'operationCount': 'Operacijų Skaičius',
  'previousLevel': 'Ankstesnis Lygis',
  'nextLevelShort': 'Kitas Lygis',
  // Battlefront strings
  'completed': 'Įvykdytas',
  'inProgress': 'Vykdomas',
  'continueGame': 'Tęsti Žaidimą',
  'replay': 'Pakartoti Žaidimą',
  'creater': 'Kūrėjas',
  'created': 'Sukurta',
  'updated': 'Atnaujinta',
  // Dialog strings
  'confirm': 'Patvirtinti',
  'cancel': 'Atšaukti',
  'yes': 'Taip',
  'no': 'Ne',
  'save': 'Išsaugoti',
  'edit': 'Redaguoti',
  'levelFormat': 'Lygis {level}',
  'newbieLevelFormat': 'Pradedantysis Lygis {level}',
  'totalLevel': '{level}/{totalLevel} lygiai',
  'totalLevelTooltip': 'Dabar: Lygis {level} / Iš viso {totalLevel} lygiai',
  // Battlefront UI strings
  'noBattlefronts': 'Nėra frontų',
  'battlefrontCount': '{count} frontai',
  'levelPrefix': 'LYG{level}',
  'newbiePrefix': 'PR{level}',
  'minesCount': '{count} minos',
  'notStarted': 'Nepradėtas',
  'victory': 'Pergalė',
  'defeat': 'Pralaimėjimas',
  'gameDurationParam': 'Trukmė: {seconds} sekundžių',
  'actionsCountParam': 'Veiksmai: {count} kartų',
  'actionsCountParamShort': '{count} kartų',
  'miningMethodParam': 'Metodas: {method}',
  'startTimeParam': 'Pradžia: {time}',
  'endTimeParam': 'Pabaiga: {time}',
  'returnButton': 'Atgal',
  'battlefrontDetails': 'Frono Detalės',
  'clickToEditName': 'Spustelėkite, kad pakeistumėte pavadinimą',
  'clickToAddDescription': 'Spustelėkite, kad pridėtumėte aprašymą...',
  'noDescription': 'Nėra aprašymo',
  // Level record strings
  'levelCount': '{count} lygiai',
  'noLevelRecords': 'Pasirinkite frontą',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Ištrinti frontą',
  'deleteBattlefrontContent':
      'Ar tikrai norite ištrinti frontą "{name}"? Ši operacija yra grįžtamoji.',
  'battlefrontLockedCannotDelete': 'Frontas užrakintas, negalima ištrinti',
  'unknownNavigationLevel': 'Nežinomas navigacijos lygis',
  'noBattlefrontSelected': 'Nepasirinktas joks frontas',
  'noBattlefrontToContinue': 'Nėra frontų, kuriuos galima tęsti',
  'synced': 'Sinchronizuotas',
  'notSynced': 'Nesinchronizuotas',
  'newbieBattlefrontName': 'Pradedantysis Frontas {number}',
  'battlefrontName': 'Frontas {number}',
  'nickname': 'Slapyvardis',
  'nicknameSetting': 'Slapyvardžio Nustatymas',
  'nicknameDesc': 'Nustatykite savo slapyvardį',
  'enterNickname': 'Įveskite slapyvardį',
  'nicknameSaved': 'Slapyvardis išsaugotas',
  'nicknameUpdated': 'Slapyvardis atnaujintas',
  'nicknameRequired': 'Slapyvardis yra privalomas',
  'nicknameTooLong': 'Slapyvardis negali būti ilgesnis nei 30 simbolių',
  // Level top strings
  'levelTopCount': 'Rezultatai ({count})',
  'levelTopCountShort': 'Rezultatai ({count})',
  'retry': 'Bandyti dar kartą',
  'noLevelTopData': 'Nėra duomenų',
  'remoteBattlefront': 'Tolimusis Frontas',
  'participated': 'Dalyvauta',
  'notParticipated': 'Dalyvauta nebuvo',
  'loadMore': 'Įkelti daugiau',

  'joinBattle': 'Prisijungti prie kovos',
  'joinBattleTooltip': 'Prisijungti prie kovos "{name}"',
  'joinBattleConfirm': 'Ar tikrai norite prisijungti prie kovos "{name}"?',
  'joinBattleSuccess': 'Jūs sėkmingai prisijungėte prie kovos "{name}"',
  'joinBattleErrorSelf': 'Negalite prisijungti prie savo fronto',

  'replayBattlefront': 'Pakartoti frontą',
  'replayBattlefrontTooltip': 'Pakartoti frontą "{name}"',
  'getReplayBattlefrontConfirm': 'Ar tikrai norite pakartoti frontą "{name}"?',
  'getReplayBattlefrontFailed': 'Nepavyko pakartoti fronto "{name}": {error}',

  'download': 'Atsisiųsti',
  'downloadBattlefront': 'Atsisiųsti frontą',
  'downloadBattlefrontTooltip': 'Atsisiųsti frontą "{name}"',
  'getDownloadBattlefrontConfirm':
      'Ar tikrai norite atsisiųsti frontą "{name}"?',
  'getDownloadBattlefrontSuccess': 'Frontas "{name}" sėkmingai atsisiųstas',
  'downloadMyOwnBattlefrontError': 'Galite atsisiųsti tik savo fronto',
  'getDownloadBattlefrontFailed':
      'Nepavyko atsisiųsti fronto "{name}": {error}',

  'continueGameShort': 'Tęsti kovą',
  'replayShort': 'Pakartoti',
  'highestLevel': 'Lygis {level}',
  'deviceNickname': 'Įrenginys',
  'createdTime': 'Sukūrimo Laikas',
  'remoteBattlefrontDetail': 'Tolimo Fronto Detalės',
  'levelList': 'Lygių Sąrašas',
  'fastClearTimeParam': 'Įveikimo Laikas: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Pasirinkite vietinį frontą, kad peržiūrėtumėte detales',
  'loadingRemoteDetail': 'Įkeliamos tolimo fronto detalės...',
  'noRemoteBattlefrontSelected': 'Nepasirinktas joks tolimasis frontas',
  'failedToLoadRemoteDetail': 'Nepavyko įkelti tolimų duomenų',
  'fastestRecord': 'Greičiausias Įveikimas',
  'safestRecord': 'Saugiausias Įveikimas',
  'fastestRecordDesc': 'Greičiausias įveikimas (mažiausiai laiko)',
  'safestRecordDesc': 'Saugiausias įveikimas (mažiausiai veiksmų)',
  'creator': 'Kūrėjas',
  'player': 'Žaidėjas',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopijos',
  'collapse': 'Suglaudinti',
  'expand': 'Išskleisti',
  // 退出战线
  'quitBattlefront': 'Išeiti iš fronto',
  'quitBattlefrontTooltip': 'Išeiti iš tolimo fronto',
  'quitBattlefrontTitle': 'Išeiti iš fronto',
  'quitBattlefrontContent':
      'Ar tikrai norite išeiti iš fronto "{name}"? Jūsų vietinis progresas bus ištrintas.',

  // 下载页面
  'downloadClient': 'Atsisiųsti Klientą',
  'browser': 'Naršytuvas',
  'browserDesc': 'Žaiskite tiesiogiai naršytyje, nereikia atsisiųsti',
  'windowsDesc': 'Windows 10 ir naujesnės versijos',
  'macosDesc': 'macOS 10.15 ir naujesnės versijos',
  'android': 'Android',
  'androidDesc': 'Android 8.0 ir naujesnės versijos',
  'iosDesc': 'iOS 14.0 ir naujesnės versijos',
  'linkAddress': 'Nuorodos Adresas',
  'downloadLink': 'Atsisiuntimo Nuoroda',
  'qrCode': 'QR Kodas',
  'scanToDownload': 'Nuskenuokite telefonu, kad atsisiųstumėte',
  'copy': 'Kopijuoti',
  'copiedToClipboard': 'Nukopijuota į iškarpinę',
  'openLink': 'Atidaryti Nuorodą',
  'cannotOpenLink': 'Negalima atidaryti nuorodos',
  // 游戏介绍
  'gameIntroduction':
      '1. „Pradedantysis“ prasideda nuo 15 minų ir gali pasiekti iki 99 minų.\n2. „Nauja Fronte“ prasideda nuo 81 minų, kiekvienas lygis minų skaičių padidina be viršaus ribojimo.\n3. Su interneto ryšiu „įveikti“ frontai automatiškai išsaugomi debesyje, kad kiti galėtų juos naudoti.',
};
