// Ukrainian（乌克兰语）
/// Ukrainian language strings for the DMine application
const Map<String, String> stringsUk = {
  'appLabel': 'Найкращий сапер',
  'appTitle': 'DMine - Найкращий сапер',
  'settings': 'Налаштування',
  'gameSettings': 'Налаштування гри',
  'showTimer': 'Показати таймер',
  'showTimerDesc': 'Показувати таймер гри на екрані',
  'showActionCounter': 'Показати лічильник дій',
  'showActionCounterDesc': 'Показувати кількість дій на екрані гри',
  'autoAdjustBoardWidth': 'Автоматично налаштувати ширину поля',
  'autoAdjustBoardWidthDesc':
      'Автоматично підлаштовувати ширину поля під розмір екрана',
  'resetToDefaults': 'Скинути до стандартних налаштувань',
  'resetToDefaultsDesc': 'Повернути всі налаштування до початкових значень',
  'aboutDMine': 'Про DMine',
  'version': 'Версія',
  'close': 'Закрити',
  'manualBoardWidth': 'Вручну встановити ширину поля',
  'currentWidth': 'Поточна',
  'range': 'Діапазон',
  'widthSliderHint':
      'Порада: під час пересування повзунка зміна ширини поля видна одразу',
  'gameRecords': 'Записи гри',
  'selectMapToViewRecords': 'Виберіть мапу для перегляду записів',
  'totalRecords': 'Всього',
  'gameRecordsTitle': 'Список записів гри',
  'pleaseSelectMapFirst': 'Спочатку виберіть мапу',
  'noGameRecords': 'Немає записів гри',
  'miningMethodFlag': 'Позначити прапорцем',
  'miningMethodBlind': 'Сліпе роззначення',
  'statusPlaying': '▶️ У грі...',
  'statusWin': '🎉 Перемога',
  'statusLose': '💥 Поразка',
  'actionsCount': 'Кількість дій',
  'miningMethod': 'Спосіб гри',
  'duration': 'Тривалість',
  'seconds': 'секунд',
  'startTime': 'Час початку',
  'endTime': 'Час закінчення',
  'pauseTime': 'Час паузи',
  'unlock': 'Розблокувати',
  'lock': 'Заблокувати',
  'delete': 'Видалити',
  'languageSetting': 'Налаштування мови',
  'currentLanguage': 'Поточна',
  'systemLanguage': 'Мова системи',
  'chinese': 'Китайська',
  'english': 'Англійська',
  'language': 'Мова',
  // Home page
  'newbie': 'Новачок',
  'newBattle': 'Новий фронт',
  'continueChallenge': 'Продовжити виклик',
  'error': 'Помилка',
  'initializationFailed': 'Не вдалося ініціалізувати',
  // Game page
  'congratulations': 'Вітаємо, ви пройшли рівень!',
  'gameOver': 'Кінець гри',
  'timeUsed': 'Час',
  'actionCount': 'Дії',
  'mineCount': 'Міни',
  'nextLevel': 'Наступний рівень: Рівень {level}',
  'newbieNextLevel': 'Наступний рівень: Новачок {level}',
  'nextLevelMines': 'Міни',
  'mineIncrease': 'Збільшення',
  'newbieFinish': 'Режим новачка завершено',
  'ok': 'ОК',
  'continueNextLevel': 'Перейти до наступного рівня',
  'restart': 'Почати знову',
  'level': 'Рівень {level}',
  'newbieLevel': 'Новачок {level}',
  'operationFailed': 'Операція не вдалася',
  // Game status texts
  'returnHome': 'Повернутися на головну',
  'revealMode': 'Режим відкриття',
  'flagMode': 'Режим прапорців',
  'newMap': 'Нова карта (така ж кількість мін, новий макет)',
  'resetMap': 'Скинути карту (той самий макет, скинути стан)',
  'zoomOut': 'Зменшити',
  'zoomIn': 'Збільшити',
  'resetZoom': 'Скинути масштаб',
  'previousStep': 'Попередній крок',
  'pause': 'Пауза',
  'play': 'Грати',
  'nextStep': 'Наступний крок',
  'clickToStart': 'Натисніть будь-яку клітинку, щоб почати гру',
  'playing': 'У грі...',
  'gameWin': 'Вітаємо, ви пройшли рівень!',
  'gameLose': 'Кінець гри, ви наступили на міну',
  'gamePaused': 'Гра на паузі',
  'ready': 'Готово до початку',
  'clickStartShort': 'Натисніть, щоб почати',
  'playingShort': 'У грі',
  'winShort': 'Пройдено!',
  'loseShort': 'Поразка',
  'pausedShort': 'Пауза',
  // Counter strings
  'currentLevel': 'Поточний рівень',
  'remainingMines': 'Залишилось мін',
  'gameTime': 'Час гри (секунд)',
  'operationCount': 'Кількість операцій',
  'previousLevel': 'Попередній рівень',
  'nextLevelShort': 'Наступний рівень',
  // Battlefront strings
  'completed': 'Завершено',
  'inProgress': 'У процесі',
  'continueGame': 'Продовжити гру',
  'replay': 'Переграти',
  'creater': 'Командир',
  'created': 'Час створення',
  'updated': 'Оновлено',
  // Dialog strings
  'confirm': 'Підтвердити',
  'cancel': 'Скасувати',
  'yes': 'Так',
  'no': 'Ні',
  'save': 'Зберегти',
  'edit': 'Редагувати',
  'levelFormat': 'Рівень {level}',
  'newbieLevelFormat': 'Новачок {level}',
  'totalLevel': '{level}/{totalLevel} рівнів',
  'totalLevelTooltip': 'Поточний: Рівень {level} / Всього {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Немає фронтів',
  'battlefrontCount': '{count} фронтів',
  'levelPrefix': 'РВ{level}',
  'newbieLevelPrefix': 'Новачок РВ{level}',
  'minesCount': '{count} мін',
  'notStarted': 'Не розпочато',
  'victory': 'Перемога',
  'defeat': 'Поразка',
  'gameDurationParam': 'Тривалість: {seconds}с',
  'actionsCountParam': 'Дії: {count} разів',
  'actionsCountParamShort': '{count} разів',
  'miningMethodParam': 'Спосіб: {method}',
  'startTimeParam': 'Початок: {time}',
  'endTimeParam': 'Кінець: {time}',
  'returnButton': 'Назад',
  'battlefrontDetails': 'Деталі фронту',
  'clickToEditName': 'Натисніть, щоб змінити назву',
  'clickToAddDescription': 'Натисніть, щоб додати опис...',
  'noDescription': 'Немає опису',
  // Level record strings
  'levelCount': '{count} рівнів',
  'noLevelRecords': 'Виберіть фронт',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Видалити фронт',
  'deleteBattlefrontContent':
      'Ви впевнені, що хочете видалити фронт \'{name}\'? Цю дію не можна скасувати.',
  'battlefrontLockedCannotDelete': 'Фронт заблоковано, видалення неможливе',
  'unknownNavigationLevel': 'Невідомий рівень',
  'noBattlefrontSelected': 'Фронт не вибрано',
  'noBattlefrontToContinue': 'Немає фронту для продовження',
  'synced': 'Синхронізовано',
  'notSynced': 'Не синхронізовано',
  'newbieBattlefrontName': 'Фронт новачка {number}',
  'battlefrontName': 'Фронт {number}',
  'nickname': 'Нік',
  'nicknameSetting': 'Налаштування ніка',
  'nicknameDesc': 'Встановіть свій нік',
  'enterNickname': 'Введіть нік',
  'nicknameSaved': 'Нік збережено',
  'nicknameUpdated': 'Нік оновлено',
  'nicknameRequired': 'Нік обов’язковий',
  'nicknameTooLong': 'Нік не може перевищувати 30 символів',
  // Level top strings
  'levelTopCount': 'Рейтинг ({count})',
  'levelTopCountShort': 'Рейтинг ({count})',
  'retry': 'Спробувати знову',
  'noLevelTopData': 'Немає даних',
  'remoteBattlefront': 'Віддалений фронт',
  'participated': 'Брав участь',
  'notParticipated': 'Не брав участі',
  'loadMore': 'Завантажити ще',
  'joinBattle': 'Приєднатися до битви',
  'joinBattleTooltip': 'Приєднатися до битви \'{name}\'',
  'joinBattleConfirm':
      'Ви впевнені, що хочете приєднатися до битви \'{name}\'?',
  'joinBattleSuccess': 'Ви успішно приєдналися до битви \'{name}\'',
  'joinBattleErrorSelf': 'Не можна приєднуватися до власного фронту',
  'replayBattlefront': 'Переграти фронт',
  'replayBattlefrontTooltip': 'Переграти фронт \'{name}\'',
  'getReplayBattlefrontConfirm': 'Ви впевнені, що хочете переграти \'{name}\'?',
  'getReplayBattlefrontFailed': 'Не вдалося переграти \'{name}\': {error}',
  'download': 'Завантажити',
  'downloadBattlefront': 'Завантажити фронт',
  'downloadBattlefrontTooltip': 'Завантажити фронт \'{name}\'',
  'getDownloadBattlefrontConfirm':
      'Ви впевнені, що хочете завантажити \'{name}\'?',
  'getDownloadBattlefrontSuccess': '\'{name}\' успішно завантажено',
  'downloadMyOwnBattlefrontError': 'Можна завантажувати лише власні фронти',
  'getDownloadBattlefrontFailed': 'Не вдалося завантажити \'{name}\': {error}',
  'continueGameShort': 'Продовжити битву',
  'replayShort': 'Переграти',
  'highestLevel': 'Рівень {level}',
  'deviceNickname': 'Пристрій',
  'createdTime': 'Час створення',
  'remoteBattlefrontDetail': 'Деталі віддаленого фронту',
  'levelList': 'Список рівнів',
  'fastClearTimeParam': 'Час проходження: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint':
      'Виберіть локальний фронт для перегляду деталей',
  'loadingRemoteDetail': 'Завантаження деталей віддаленого фронту...',
  'noRemoteBattlefrontSelected': 'Віддалений фронт не вибрано',
  'failedToLoadRemoteDetail': 'Не вдалося завантажити деталі',
  'fastestRecord': 'Найшвидше проходження',
  'safestRecord': 'Найбезпечніше проходження',
  'fastestRecordDesc': 'Найшвидше (найменше часу)',
  'safestRecordDesc': 'Найбезпечніше (найменше дій)',
  'creator': 'Творець',
  'player': 'Гравець',
  // Branch maps
  'getBranchMapCount': '{count} копій',
  'collapse': 'Згорнути',
  'expand': 'Розгорнути',
  // Quit battlefront
  'quitBattlefront': 'Залишити фронт',
  'quitBattlefrontTooltip': 'Залишити віддалений фронт',
  'quitBattlefrontTitle': 'Залишити фронт',
  'quitBattlefrontContent':
      'Ви впевнені, що хочете залишити фронт \'{name}\'? Ваш локальний прогрес буде видалено.',
  // Download page
  'downloadClient': 'Завантажити клієнт',
  'browser': 'Браузер',
  'browserDesc': 'Грайте безпосередньо в браузері, без завантаження',
  'windowsDesc': 'Для Windows 10 та новіших',
  'macosDesc': 'Для macOS 10.15 та новіших',
  'android': 'Android',
  'androidDesc': 'Для Android 8.0 та новіших',
  'iosDesc': 'Для iOS 14.0 та новіших',
  'linkAddress': 'Адреса посилання',
  'downloadLink': 'Посилання для завантаження',
  'qrCode': 'QR-код',
  'scanToDownload': 'Скануйте телефоном для завантаження',
  'copy': 'Копіювати',
  'copiedToClipboard': 'Скопійовано в буфер',
  'openLink': 'Відкрити посилання',
  'cannotOpenLink': 'Не вдається відкрити посилання',
  // Game introduction
  'gameIntroduction':
      '1. «Новачок» починається з 15 мін, максимум до 99 мін;\n2. «Новий фронт» починається з 81 мін, кількість зростає кожен рівень, без верхньої межі.\n3. Онлайн завершені фронти автоматично діляться у хмарі для інших гравців.',
};
