/// Armenian language strings for the DMine application
const Map<String, String> stringsHy = {
  'appLabel': 'Տոպ Մինե (Առաջնորդական Մինե Փորձ)',
  'appTitle': 'DMine - Տոպ Մինե (Առաջնորդական Մինե Փորձ)',
  'settings': 'Կարգավորումներ',
  'gameSettings': 'Иգերի Կարգավորումներ',
  'showTimer': 'Ցույց տալ ժամացույցը',
  'showTimerDesc': 'Ցույց տալ խաղի ժամացույցը խաղի ինտերֆեյսում',
  'showActionCounter': 'Ցույց տալ գործողությունների ծրագրավորման սիմվոլը',
  'showActionCounterDesc':
      'Ցույց տալ գործողությունների քանակի չափումը խաղի ինտերֆեյսում',
  'autoAdjustBoardWidth': 'Ավտոմատ ճշգրտում տախտակի լայնությունը',
  'autoAdjustBoardWidthDesc':
      'Ավտոմատ ճշգրտում տախտակի լայնությունը էկրանի չափերի համաձայն',
  'resetToDefaults': 'Վերականգնել սկզբնական կարգավորումները',
  'resetToDefaultsDesc':
      'Վերականգնել բոլոր կարգավորումները սկզբնական արժեքներին',
  'aboutDMine': 'Մասին DMine',
  'version': 'Տարբերակ',
  'close': 'Փակել',
  'manualBoardWidth': 'Մարդկային կարգավորում տախտակի լայնությունը',
  'currentWidth': 'Ընթացիկ',
  'range': 'Հատված',
  'widthSliderHint':
      'Կարևորում. Սլայդերի ձգման ընթացքում կարող եք անմիջապես նախատեսել տախտակի լայնության փոփոխությունները',
  'gameRecords': 'Խաղի Ռեկորդներ',
  'selectMapToViewRecords': 'Ընտրեք քարտեզ ռեկորդներ ընթերցելու համար',
  'totalRecords': 'Ընդհանուր',
  'gameRecordsTitle': 'Խաղի Ռեկորդների Բանկ',
  'pleaseSelectMapFirst': 'Խնդրում ենք նախ ընտրել քարտեզ',
  'noGameRecords': 'Ռեկորդներ չկան',
  'miningMethodFlag': 'Զինծառակ դնել',
  'miningMethodBlind': 'Կույր ջրերի քայլեր',
  'statusPlaying': '▶️ Ներկայումս խաղում...',
  'statusWin': '🎉 Նվաճում',
  'statusLose': '💥 Նախասարսափ',
  'actionsCount': 'Գործողությունների քանակ',
  'miningMethod': 'Միների հանման մեթոդ',
  'duration': 'Ժամանակաշրջան',
  'seconds': 'վայրկյան',
  'startTime': 'Սկիզբի ժամանակ',
  'endTime': 'Վերջի ժամանակ',
  'pauseTime': 'Դադարի ժամանակ',
  'unlock': 'Բացել անվանակարգը',
  'lock': 'Բլոկավորել',
  'delete': 'Ջնջել',
  'languageSetting': 'Լեզվի Կարգավորումներ',
  'currentLanguage': 'Ընթացիկ',
  'systemLanguage': 'Հệտակարի Լեզու',
  'chinese': 'Չիներեն',
  'english': 'Անգլերեն',
  'language': 'Լեզու',
  // Home page
  'newbie': 'Նորեկի Նկարագրություն',
  'gameIntro': 'Խաղի ներկայացում',
  'newBattle': 'Նոր Պատերազմային Ֆրոնտ',
  'continueChallenge': 'Շարունակել Արդարադրություն',
  'error': 'Սխալ',
  'initializationFailed': 'Առաջնարկումն ձախողվեց',
  // Game page
  'congratulations': 'Շնորհավորում ենք Նվաճելով!',
  'gameOver': 'Խաղն ավարտվեց',
  'timeUsed': 'Օգտագործված ժամանակ',
  'actionCount': 'Գործողությունների քանակ',
  'mineCount': 'Միների քանակ',
  'nextLevel': 'Հաջորդ Մակարդակ: {level} Մակարդակ',
  'newbieNextLevel': 'Հաջորդ Մակարդակ: Նորեկի {level} Մակարդակ',
  'nextLevelMines': 'Միների քանակ',
  'mineIncrease': 'Ավելացնել',
  'newbieFinish': 'Նորեկի Նկարագրությունն ավարտվեց',
  'ok': 'Ամենաել',
  'continueNextLevel': 'Շարունակել Արդարադրությունը Հաջորդ Մակարդակում',
  'restart': 'Նորից Սկսել',
  'level': '{level} Մակարդակ',
  'newbieLevel': 'Նորեկի {level} Մակարդակ',
  'operationFailed': 'Գործողությունն ձախողվեց',
  // Game status texts
  'returnHome': 'Վերադառնալ Գլխավոր Էջ',
  'revealMode': 'Առկայականացնել Մոդ',
  'flagMode': 'Զինծառակի Մոդ',
  'newMap': 'Նոր Քարտեզ (միների քանակը անփոփոխ է, ստեղծվում է նոր քարտեզ)',
  'resetMap':
      'Նորից Ներբեռնել Քարտեզ (քարտեզը անփոփոխ է, վերականգնվում է կարգավիճակը)',
  'zoomOut': 'Փոքրացնել',
  'zoomIn': 'Բարձրացնել',
  'resetZoom': 'Վերականգնել Ասılնի',
  'previousStep': 'Նախորդ Քայլ',
  'pause': 'Դադարեցնել',
  'play': 'Խաղալ',
  'nextStep': 'Հաջորդ Քայլ',
  'clickToStart': 'Կտրուկ խմբագրեք որևէ դիրք խաղ սկսելու համար',
  'playing': 'Խաղում...',
  'gameWin': 'Շնորհավորում ենք Նվաճելով!',
  'gameLose': 'Խաղն ավարտվեց, դուք խախտեցիք մին',
  'gamePaused': 'Խաղը Փակ է',
  'ready': 'Պատրաստ Սկսել',
  'clickStartShort': 'Կտրուկ Սկսել',
  'playingShort': 'Խաղում',
  'winShort': 'Նվաճում!',
  'loseShort': 'Մինի խախտումը ձախողվեց',
  'pausedShort': 'Դադար',
  // Counter strings
  'currentLevel': 'Ընթացիկ Մակարդակ',
  'remainingMines': 'Մնացած Միների քանակ',
  'gameTime': 'Խաղի ժամանակ (վայրկյան)',
  'operationCount': 'Գործողությունների քանակ',
  'previousLevel': 'Նախորդ Մակարդակ',
  'nextLevelShort': 'Հաջորդ Մակարդակ',
  // Battlefront strings
  'completed': 'Ավարտված',
  'inProgress': 'Ներկայումս Գործում',
  'continueGame': 'Շարունակել Խաղը',
  'replay': 'Վերանայել',
  'creater': 'Գլխավոր Գեներալ',
  'created': 'Պատերազմի Սկիզբի ժամանակ',
  'updated': 'Թարմացնել',
  // Dialog strings
  'confirm': 'Հաստատել',
  'cancel': 'Չեղարկել',
  'yes': 'Այո',
  'no': 'Ոչ',
  'save': 'Պահպանել',
  'edit': 'Փոփոխել',
  'levelFormat': '{level} Մակարդակ',
  'newbieLevelFormat': 'Նորեկի {level} Մակարդակ',
  'totalLevel': '{level}/{totalLevel} Մակարդակ',
  'totalLevelTooltip':
      'Ընթացիկ: {level} Մակարդակ / Ընդհանուր: {totalLevel} Մակարդակ',
  // Battlefront UI strings
  'noBattlefronts': 'Պատերազմային Ֆրոնտներ չկան',
  'battlefrontCount': '{count} Պատերազմային Ֆրոնտ',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'Նորեկի LV{level}',
  'minesCount': '{count} Մին',
  'notStarted': 'Չսկսված',
  'victory': 'Նվաճում',
  'defeat': 'Նախասարսափ',
  'gameDurationParam': 'Ժամանակաշրջան: {seconds} վայրկյան',
  'actionsCountParam': 'Գործողություններ: {count} անգամ',
  'actionsCountParamShort': '{count} անգամ',
  'miningMethodParam': 'Մեթոդ: {method}',
  'startTimeParam': 'Սկիզբի ժամանակ: {time}',
  'endTimeParam': 'Վերջի ժամանակ: {time}',
  'returnButton': 'Վերադառնալ',
  'battlefrontDetails': 'Պատերազմային Ֆրոնտի Մանրամասներ',
  'clickToEditName': 'Կտրուկ խմբագրեք անունը փոփոխելու համար',
  'clickToAddDescription':
      'Կտրուկ խմբագրեք նկարագրություն ավելացնելու համար...',
  'noDescription': 'Նկարագրություն չկա',
  // Level record strings
  'levelCount': '{count} Մակարդակ',
  'noLevelRecords': 'Խնդրում ենք ընտրել Պատերազմային Ֆրոնտ',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Ջնջել Պատերազմային Ֆրոնտ',
  'deleteBattlefrontContent':
      'Հաստատե՞լ եք "{name}" Պատերազմային Ֆրոնտը ջնջել։ Այս գործողությունը անհետացնելի է։',
  'battlefrontLockedCannotDelete':
      'Պատերազմային Ֆրոնտը լոկավորված է, չհաջողվի ջնջել',
  'unknownNavigationLevel': 'Անհայտ Նավիգացիոն Մակարդակ',
  'noBattlefrontSelected': 'Պատերազմային Ֆրոնտ չի ընտրված',
  'noBattlefrontToContinue': 'Չգտնվեց Շարունակելու համար պատերազմային ֆրոնտ',
  'synced': 'Սինխրոնացված է',
  'notSynced': 'Չհայտնվեց սինխրոնացում',
  'newbieBattlefrontName': 'Նորեկի Պատերազմային Ֆրոնտ{number}',
  'battlefrontName': 'Պատերազմային Ֆրոնտ{number}',
  'nickname': 'Նիկնեյմ',
  'nicknameSetting': 'Նիկնեյմի Կարգավորումներ',
  'nicknameDesc': 'Կարգավորեք ձեր Նիկնեյմը',
  'enterNickname': 'Ներմուծեք Նիկնեյմ',
  'nicknameSaved': 'Նիկնեյմը պահպանվեց',
  'nicknameUpdated': 'Նիկնեյմը թարմացվեց հաջողությամբ',
  'nicknameRequired': 'Նիկնեյմը պարտադիր է',
  'nicknameTooLong': 'Նիկնեյմը չի կարող լինել ավելի երկար 30 սիմվոլից',
  // Level top strings
  'levelTopCount': 'Առաջնորդական Ցանկ ({count})',
  'levelTopCountShort': 'Առաջնորդական ({count})',
  'retry': 'Նորից Փորձել',
  'noLevelTopData': 'Տվյալներ չկան',
  'remoteBattlefront': 'Հեռավոր Պատերազմային Ֆրոնտ',
  'participated': 'Դասավորված է',
  'notParticipated': 'Չդասավորված է',
  'loadMore': 'Բեռնել Ավելին',

  'joinBattle': 'Դասավորվել Պատերազմին',
  'joinBattleTooltip': 'Դասավորվել "{name}" Պատերազմին',
  'joinBattleConfirm': 'Հաստատե՞լ եք "{name}" Պատերազմին դասավորվել։',
  'joinBattleSuccess': 'Հաջողությամբ դասավորվեցիք "{name}" Պատերազմին',
  'joinBattleErrorSelf':
      'Չհաջողվի դասավորվել ձեր սեփական ստեղծած պատերազմային ֆրոնտին',

  'replayBattlefront': 'Վերանայել Պատերազմային Ֆրոնտ',
  'replayBattlefrontTooltip': 'Վերանայել "{name}" Պատերազմային Ֆրոնտ',
  'getReplayBattlefrontConfirm': 'Հաստատե՞լ եք "{name}" Վերանայել։',
  'getReplayBattlefrontFailed': '"{name}" Վերանայումը ձախողվեց: {error}',

  'download': 'Բեռնել',
  'downloadBattlefront': 'Բեռնել Պատերազմային Ֆրոնտ',
  'downloadBattlefrontTooltip': 'Բեռնել "{name}" Պատերազմային Ֆրոնտ',
  'getDownloadBattlefrontConfirm': 'Հաստատե՞լ եք "{name}" Բեռնել։',
  'getDownloadBattlefrontSuccess': 'Հաջողությամբ բեռնվեց "{name}"',
  'downloadMyOwnBattlefrontError':
      'Կարող եք բեռնել միայն ձեր սեփական ստեղծած պատերազմային ֆրոնտները',
  'getDownloadBattlefrontFailed': '"{name}" Բեռնումը ձախողվեց: {error}',

  'continueGameShort': 'Շարունակել Պատերազմը',
  'replayShort': 'Վերանայել',
  'highestLevel': '{level} Մակարդակ',
  'deviceNickname': 'Գործիք',
  'createdTime': 'Ստեղծման ժամանակ',
  'remoteBattlefrontDetail': 'Պատերազմային Ֆրոնտի Մանրամասներ',
  'levelList': 'Մակարդակների Բանկ',
  'fastClearTimeParam': 'Նվաճման ժամանակ: {time}',
  // Հեռավոր Պատերազմային Ֆրոնտի Մանրամասներ
  'selectLocalBattlefrontHint':
      'Խնդրում ենք ընտրել տեղական պատերազմային ֆրոնտ մանրամասներ ընթերցելու համար',
  'loadingRemoteDetail':
      'Բեռնվում է հեռավոր պատերազմային ֆրոնտի մանրամասները...',
  'noRemoteBattlefrontSelected': 'Հեռավոր Պատերազմային Ֆրոնտ չի ընտրված',
  'failedToLoadRemoteDetail':
      'Հեռավոր պատերազմային ֆրոնտի մանրամասները բեռնելը ձախողվեց',
  'fastestRecord': 'Արագ nhấtն Նվաճում',
  'safestRecord': 'Անվտանգ nhấtն Նվաճում',
  'fastestRecordDesc': 'Արագ nhấtն Նվաճում (գերեզման ժամանակ)',
  'safestRecordDesc':
      'Անվտանգ nhấtն Նվաճում (գործողությունների քանակը նվազագույնն է)',
  'creator': 'Ստեղծող',
  'player': 'Խաղացող',
  // Դիրեկցիայի Քարտեզի Տեքստեր
  'getBranchMapCount': '{count} Նախնական Տարբերակ',
  'collapse': 'Կլանել',
  'expand': 'Առաջացնել',
  // Ելք Պատերազմային Ֆրոնտից
  'quitBattlefront': 'Ելք Պատերազմային Ֆրոնտից',
  'quitBattlefrontTooltip': 'Ելք Հեռավոր Պատերազմային Ֆրոնտից',
  'quitBattlefrontTitle': 'Ելք Պատերազմային Ֆրոնտից',
  'quitBattlefrontContent':
      'Հաստատե՞լ եք "{name}" Պատերազմային Ֆրոնտից ելնել։ Ձեր տեղական առաջընթացը ջնջվելու է։',

  // Բեռնման Էջ
  'downloadClient': 'Բեռնել Կլիենտ',
  'browser': 'Բրաուզեր',
  'browserDesc': 'Խաղալ անմիջապես բրաուզերում, բեռնելու անհրաժեշտություն չկա',
  'windowsDesc': 'Տրամադրվում է Windows 10 և բարձրացված տարբերակների համար',
  'macosDesc': 'Տրամադրվում է macOS 10.15 և բարձրացված տարբերակների համար',
  'android': 'Անդրոիդ sistemi',
  'androidDesc': 'Տրամադրվում է Android 8.0 և բարձրացված տարբերակների համար',
  'iosDesc': 'Տրամադրվում է iOS 14.0 և բարձրացված տարբերակների համար',
  'linkAddress': 'Հղման Հասցե',
  'downloadLink': 'Բեռնման Հղում',
  'qrCode': 'QR Կոդ',
  'scanToDownload':
      'Օգտագործեք մոբիլային հեռախոսը QR կոդը սկանավորելու համար և բեռնել',
  'copy': 'Պատճենել',
  'copiedToClipboard': 'Պատճենվեց Ջնջելու Կարթե',
  'openLink': 'Բացել Հղում',
  'cannotOpenLink': 'Չհաջողվեց բացել հղում',
  // Խաղի Նկարագրություն
  'gameIntroduction':
      '1. "Նորեկի Նկարագրություն" սկսվում է 15 միներից, մакսիմում 99 միների մակարդակ է հասնում;\n2. "Նոր Պատերազմային Ֆրոնտ" սկսվում է 81 միներից, յուրաքանչյուր մակարդակում միների քանակը մի քիչ ավելանում է, սահման չկա.\n3. Կենցաղային կապի դեպքում "նվաճված" պատերազմային ֆրոնտները ինքնաբերաբար կիսվում են հիմնական հարթակում, որպեսզի մյուսներն ուսանեն.',
};
