/// Albanian language strings for the DMine application
const Map<String, String> stringsSq = {
  'appLabel': 'Top Miner',
  'appTitle': 'DMine - Top Miner',
  'settings': 'Cilësimet',
  'gameSettings': 'Cilësimet e Lojës',
  'showTimer': 'Shfaq Kronometrin',
  'showTimerDesc': 'Shfaq kronometrin e lojës në ndërfaqen e lojës',
  'showActionCounter': 'Shfaq Numëruesin e Veprimeve',
  'showActionCounterDesc':
      'Shfaq statistikat e numërimit të veprimeve në ndërfaqen e lojës',
  'showUnrevealedCounter': 'Shfaq numëruesin e qelizave të pazbuluara',
  'showUnrevealedCounterDesc': 'Shfaq numrin e qelizave të pazbuluara në ndërfaqen e lojës',
  'showMineCounter': 'Shfaq numëruesin e minave',
  'showMineCounterDesc': 'Shfaq minat e mbetura në ndërfaqen e lojës',
  'autoAdjustBoardWidth': 'Rregullo Automatikisht Gjerësinë e Bordit',
  'autoAdjustBoardWidthDesc':
      'Rregullo automatikisht gjerësinë e bordit bazuar në madhësinë e ekranit',
  'resetToDefaults': 'Rivendos në Cilësimet Parazgjedhje',
  'resetToDefaultsDesc': 'Rikthe të gjitha cilësimet në vlerat parazgjedhje',
  'aboutDMine': 'Rreth DMine',
  'version': 'Versioni',
  'close': 'Mbyll',
  'manualBoardWidth': 'Gjerësia Manuale e Bordit',
  'currentWidth': 'Aktual',
  'range': 'Varg',
  'widthSliderHint':
      'Këshillë: Mund të parashikoni ndryshimet e gjerësisë së bordit ndërsa zvarritni rrëshqitësin',
  'gameRecords': 'Regjistrimet e Lojës',
  'selectMapToViewRecords':
      'Ju lutemi zgjidhni një hartë për të parë regjistrimet',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Lista e Regjistrimeve të Lojës',
  'pleaseSelectMapFirst': 'Ju lutemi zgjidhni së pari një hartë',
  'noGameRecords': 'Nuk ka regjistrime loje',
  'miningMethodFlag': 'Flamur',
  'miningMethodBlind': 'I verbër',
  'statusPlaying': '▶️ Duke luajtur...',
  'statusWin': '🎉 Fitore',
  'statusLose': '💥 Humbje',
  'actionsCount': 'Veprime',
  'miningMethod': 'Metoda',
  'duration': 'Kohëzgjatja',
  'seconds': 's',
  'startTime': 'Koha e Fillimit',
  'endTime': 'Koha e Përfundimit',
  'pauseTime': 'Koha e Pauzës',
  'unlock': 'Zhbyll',
  'lock': 'Blloko',
  'delete': 'Fshi',
  'languageSetting': 'Cilësimi i Gjuhës',
  'currentLanguage': 'Aktual',
  'systemLanguage': 'Gjuha e Sistemit',
  'chinese': 'Kinezisht',
  'english': 'Anglisht',
  'language': 'Gjuha',
  // Home page
  'newbie': 'Fillestar',
  'gameIntro': 'Prezantim i lojës',
  'newBattle': 'Front i Ri',
  'continueChallenge': 'Vazhdo',
  'error': 'Gabim',
  'initializationFailed': 'Inicializimi dështoi',
  // Game page
  'congratulations': 'Urime!',
  'gameOver': 'Lojë e Përfunduar',
  'timeUsed': 'Koha',
  'actionCount': 'Veprime',
  'mineCount': 'Mina',
  'nextLevel': 'Tjetra: Niveli {level}',
  'newbieNextLevel': 'Tjetra: Niveli Fillestar {level}',
  'nextLevelMines': 'Mina',
  'mineIncrease': 'Rritje',
  'newbieFinish': 'Fillestar i përfunduar',
  'ok': 'OK',
  'continueNextLevel': 'Niveli i Ardhshëm',
  'restart': 'Filloj Përsëri',
  'level': 'Niveli {level}',
  'newbieLevel': 'Niveli Fillestar {level}',
  'operationFailed': 'Operacioni dështoi',
  // Game status texts
  'returnHome': 'Kthehu në Shtëpi',
  'revealMode': 'Mënyra e Zbulimit',
  'flagMode': 'Mënyra e Flamurit',
  'newMap': 'Hartë e Re (të njëjtat mina)',
  'resetMap': 'Ringarko Hartën (e njëjta hartë, rivendos gjendjen e lojës)',
  'zoomOut': 'Zvogëlo',
  'zoomIn': 'Zmadh',
  'resetZoom': 'Rivendos Zmadhimin',
  'previousStep': 'Hapi i Mëparshëm',
  'pause': 'Pauzë',
  'play': 'Luaj',
  'nextStep': 'Hapi i Ardhshëm',
  'clickToStart': 'Klikoni çdo qelizë për të filluar lojën',
  'playing': 'Duke luajtur...',
  'gameWin': 'Urime!',
  'gameLose': 'Lojë e Përfunduar, keni shkelur mbi një minë',
  'gamePaused': 'Lojë e Pauzuar',
  'ready': 'Gati për të Filluar',
  'clickStartShort': 'Klikoni Filloni',
  'playingShort': 'Duke luajtur',
  'winShort': 'Fitore!',
  'loseShort': 'Humbje',
  'pausedShort': 'Pauzuar',
  // Counter strings
  'currentLevel': 'Niveli Aktual',
  'remainingMines': 'Minat e Mbetura',
  'unrevealedCells': 'Qelizat e pazbuluara',
  'gameTime': 'Kohëzgjatja e Lojës (sekonda)',
  'operationCount': 'Veprime',
  'previousLevel': 'Niveli i Mëparshëm',
  'nextLevelShort': 'Niveli i Ardhshëm',
  // Battlefront strings
  'completed': 'I përfunduar',
  'inProgress': 'Në Progres',
  'continueGame': 'Vazhdo Lojën',
  'replay': 'Luaj Përsëri',
  'creater': 'Komandant',
  'created': 'Koha e Sulmit',
  'updated': 'Përditësuar',
  // Battlefront UI strings
  'noBattlefronts': 'Nuk ka fronte',
  'battlefrontCount': '{count} front(e)',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'Fillestar LV{level}',
  'minesCount': '{count} mina',
  'notStarted': 'Nuk ka filluar',
  'victory': 'Fitore',
  'defeat': 'Humbje',
  'gameDurationParam': 'Kohëzgjatja: {seconds}s',
  'actionsCountParam': 'Veprime: {count}',
  'actionsCountParamShort': '{count}',
  'miningMethodParam': 'Metoda: {method}',
  'startTimeParam': 'Koha e fillimit: {time}',
  'endTimeParam': 'Koha e përfundimit: {time}',
  'returnButton': 'Kthehu',
  'battlefrontDetails': 'Detajet e Frontit',
  'clickToEditName': 'Klikoni për të redaktuar emrin',
  'clickToAddDescription': 'Klikoni për të shtuar përshkrim...',
  'noDescription': 'Nuk ka përshkrim',
  // Dialog strings
  'confirm': 'Konfirmo',
  'cancel': 'Anulo',
  'yes': 'Po',
  'no': 'Jo',
  'save': 'Ruaj',
  'edit': 'Redakto',
  'levelFormat': 'Niveli {level}',
  'newbieLevelFormat': 'Niveli Fillestar {level}',
  'totalLevel': 'Niveli {level}/{totalLevel}',
  'totalLevelTooltip': 'Niveli Aktual: {level} / Nivelet Totale: {totalLevel}',
  // Level record strings
  'levelCount': '{count} nivele',
  'noLevelRecords': 'Nuk ka regjistrime të niveleve',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Fshi Frontin',
  'deleteBattlefrontContent':
      'Jeni i sigurt që doni të fshini frontin "{name}"? Ky veprim nuk mund të zhbëhet.',
  'battlefrontLockedCannotDelete':
      'Fronti është i bllokuar dhe nuk mund të fshihet',
  'unknownNavigationLevel': 'Niveli i panjohur i navigimit',
  'noBattlefrontSelected': 'Nuk është zgjedhur asnjë front',
  'noBattlefrontToContinue': 'Nuk u gjet front për të vazhduar',
  'synced': 'Sinkronizuar',
  'notSynced': 'Nuk është sinkronizuar',
  'newbieBattlefrontName': 'Front Fillestar {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Pseudonim',
  'nicknameSetting': 'Cilësimi i Pseudonimit',
  'nicknameDesc': 'Vendosni pseudonimin tuaj',
  'enterNickname': 'Vendosni pseudonimin',
  'nicknameSaved': 'Pseudonimi u ruajt',
  'nicknameUpdated': 'Pseudonimi u përditësua me sukses',
  'nicknameRequired': 'Pseudonimi është i detyrueshëm',
  'nicknameTooLong': 'Pseudonimi nuk mund të kalojë 30 karaktere',
  // Level top strings
  'levelTopCount': 'Renditja e Lartë ({count})',
  'levelTopCountShort': 'Lart ({count})',
  'retry': 'Provo Përsëri',
  'noLevelTopData': 'Nuk ka të dhëna',
  'remoteBattlefront': 'Front i Largët',
  'participated': 'Mori pjesë',
  'notParticipated': 'Nuk mori pjesë',
  'loadMore': 'Ngarko më shumë',

  'joinBattle': 'Bashkohu me Betejën',
  'joinBattleTooltip': 'Bashkohu me betejën "{name}"',
  'joinBattleConfirm':
      'Jeni i sigurt që doni të bashkoheni me betejën "{name}"?',
  'joinBattleSuccess': 'U bashkua me sukses me betejën "{name}"',
  'joinBattleErrorSelf':
      'Nuk mund të bashkoheni me betejën "{name}" të krijuar nga vetja',

  'replayBattlefront': 'Luaj Përsëri Frontin',
  'replayBattlefrontTooltip': 'Luaj përsëri frontin "{name}"',
  'getReplayBattlefrontConfirm':
      'Jeni i sigurt që doni të luani përsëri "{name}"?',
  'getReplayBattlefrontFailed': 'Luaj përsëri "{name}" dështoi: {error}',

  'download': 'Shkarko',
  'downloadBattlefront': 'Shkarko Frontin',
  'downloadBattlefrontTooltip': 'Shkarko frontin "{name}"',
  'getDownloadBattlefrontConfirm':
      'Jeni i sigurt që doni të shkarkoni "{name}"?',
  'getDownloadBattlefrontSuccess': 'U shkarkua me sukses "{name}"',
  'downloadMyOwnBattlefrontError': 'Mund të shkarkoni vetëm frontet tuaja',
  'getDownloadBattlefrontFailed': 'Shkarkimi i "{name}" dështoi: {error}',

  'continueGameShort': 'Vazhdo',
  'replayShort': 'Luaj Përsëri',
  'highestLevel': 'Niveli {level}',
  'deviceNickname': 'Pajisja',
  'createdTime': 'Koha e Krijuar',
  'remoteBattlefrontDetail': 'Detajet e Frontit',
  'levelList': 'Lista e Niveleve',
  'fastClearTimeParam': 'Pastrim i shpejtë: {time}',
  // Remote battlefront detail strings
  'selectLocalBattlefrontHint':
      'Ju lutemi zgjidhni një front lokal për të parë detajet',
  'loadingRemoteDetail': 'Po ngarkohen detajet e frontit të largët...',
  'noRemoteBattlefrontSelected': 'Nuk është zgjedhur asnjë front i largët',
  'failedToLoadRemoteDetail':
      'Ngarkimi i detajeve të frontit të largët dështoi',
  'fastestRecord': 'Më i shpejti',
  'safestRecord': 'Më i sigurt',
  'fastestRecordDesc': 'Më i shpejti (koha më e shkurtër)',
  'safestRecordDesc': 'Më i sigurt (më pak veprime)',
  'creator': 'Krijuesi',
  'player': 'Lojtari',
  // Branch map strings
  'getBranchMapCount': '{count} degë',
  'collapse': 'Palos',
  'expand': 'Zgjero',
  // Quit battlefront
  'quitBattlefront': 'Largohu nga Fronti',
  'quitBattlefrontTooltip': 'Largohu nga fronti i largët',
  'quitBattlefrontTitle': 'Largohu nga Fronti',
  'quitBattlefrontContent':
      'Jeni i sigurt që doni të largoheni nga fronti "{name}"? Progresi juaj lokal do të fshihet.',
  // Game introduction
  'gameIntroduction':
      '1. "Fillestar" fillon me 15 mina, mund të shkojë deri në 99 mina.\n2. "Front i Ri" fillon me 81 mina, çdo nivel rrit numrin e minave, pa kufi të sipërm.\n3. Në modalitetin online, frontet e përfunduara ndahen automatikisht në re për të tjerët për të mësuar.',
};
