/// Euskera hizkuntza kateak DMine aplikaziorako
const Map<String, String> stringsEu = {
  'appLabel': 'Mina Bilaketa Gehigarrikoa',
  'appTitle': 'DMine - Mina Bilaketa Gehigarrikoa',
  'settings': 'Ezarpenak',
  'gameSettings': 'Jokoaren ezarpenak',
  'showTimer': 'Erakutsi denbora kontagailua',
  'showTimerDesc': 'Erakutsi jokoaren denbora kontagailua jokoaren interfazean',
  'showActionCounter': 'Erakutsi ekintza kopurua',
  'showActionCounterDesc': 'Erakutsi ekintza kopurua jokoaren interfazean',
  'autoAdjustBoardWidth': 'Automatikoki egokitu taularen zabalera',
  'autoAdjustBoardWidthDesc':
      'Automatikoki egokitu taularen zabalera pantailaren tamainaren arabera',
  'resetToDefaults': 'Berrezarri lehenetsitako balioak',
  'resetToDefaultsDesc': 'Berrezarri ezarpen guztiak lehenetsitako balioetara',
  'aboutDMine': 'DMine-i buruz',
  'version': 'Bertsioa',
  'close': 'Itxi',
  'manualBoardWidth': 'Eskuz ezarri taularen zabalera',
  'currentWidth': 'Orainkoa',
  'range': 'Tartea',
  'widthSliderHint':
      'Aholkua: Laguila arrastatzean taularen zabalera aldaketak berehala ikus daitezke',
  'gameRecords': 'Joko erregistroak',
  'selectMapToViewRecords': 'Hautatu mapa bat erregistroak ikusteko',
  'totalRecords': 'Guztira',
  'gameRecordsTitle': 'Joko erregistroen zerrenda',
  'pleaseSelectMapFirst': 'Hautatu mapa bat lehenik',
  'noGameRecords': 'Ez dago joko erregistrorik',
  'miningMethodFlag': 'Bandera jarri',
  'miningMethodBlind': 'Begiezin mina bilaketa',
  'statusPlaying': '▶️ Martxan...',
  'statusWin': '🎉 Irabaztea',
  'statusLose': '💥 Galera',
  'actionsCount': 'Ekintza kopurua',
  'miningMethod': 'Mina bilaketa metodoa',
  'duration': 'Iraupena',
  'seconds': 'segundo',
  'startTime': 'Hasiera ordua',
  'endTime': 'Amaiera ordua',
  'pauseTime': 'Pausa ordua',
  'unlock': 'Desblokeatu',
  'lock': 'Blokeatu',
  'delete': 'Ezabatu',
  'languageSetting': 'Hizkuntza ezarpena',
  'currentLanguage': 'Orainkoa',
  'systemLanguage': 'Sistemaren hizkuntza',
  'chinese': 'Txinera',
  'english': 'Ingelesa',
  'language': 'Hizkuntza',
  // Home page
  'newbie': 'Hasiberriek',
  'newBattle': 'Borroka frontiera berria',
  'continueChallenge': 'Jarraitu desafioa',
  'error': 'Errorea',
  'initializationFailed': 'Hasieraketa huts egin du',
  // Game page
  'congratulations': 'Zorionak, maila gainditu duzu!',
  'gameOver': 'Jokoa amaitu da',
  'timeUsed': 'Erabilitako denbora',
  'actionCount': 'Ekintza kopurua',
  'mineCount': 'Mina kopurua',
  'nextLevel': 'Hurrengo maila: {level}. maila',
  'newbieNextLevel': 'Hurrengo maila: Hasiberri {level}. maila',
  'nextLevelMines': 'Mina kopurua',
  'mineIncrease': 'Gehiketa',
  'newbieFinish': 'Hasiberrien ametsa amaitu da',
  'ok': 'Ados',
  'continueNextLevel': 'Jarraitu hurrengo mailara',
  'restart': 'Berrabiarazi',
  'level': '{level}. maila',
  'newbieLevel': 'Hasiberri {level}. maila',
  'operationFailed': 'Ekusintza huts egin du',
  // Game status texts
  'returnHome': 'Itzuli hasierara',
  'revealMode': 'Ezkutuko modua',
  'flagMode': 'Bandera modua',
  'newMap': 'Mapa berria (mina kopurua aldatu gabe, mapa berria sortu)',
  'resetMap': 'Berrabiarazi mapa (mapa berdina, egoera berrezarri)',
  'zoomOut': 'Txikitu',
  'zoomIn': 'Handitu',
  'resetZoom': 'Berrezarri tamaina',
  'previousStep': 'Aurreko urratsa',
  'pause': 'Pausarazi',
  'play': 'Jolastu',
  'nextStep': 'Hurrengo urratsa',
  'clickToStart': 'Kliku edozein gelaxkan jokoa hasteko',
  'playing': 'Jolasten...',
  'gameWin': 'Zorionak, maila gainditu duzu!',
  'gameLose': 'Jokoa amaitu da, mina bat jarri duzu',
  'gamePaused': 'Jokoa pausatuta',
  'ready': 'Prest',
  'clickStartShort': 'Kliku hasteko',
  'playingShort': 'Jolasten',
  'winShort': 'Irabazita!',
  'loseShort': 'Mina jarri duzu',
  'pausedShort': 'Pausatuta',
  // Counter strings
  'currentLevel': 'Oraingo maila',
  'remainingMines': 'Gelditako minak',
  'gameTime': 'Joko denbora (segundo)',
  'operationCount': 'Ekintza kopurua',
  'previousLevel': 'Aurreko maila',
  'nextLevelShort': 'Hurrengo maila',
  // Battlefront strings
  'completed': 'Amaituta',
  'inProgress': 'Martxan',
  'continueGame': 'Jarraitu jolasten',
  'replay': 'Berriz erreproduzitu',
  'creater': 'Komandante nagusia',
  'created': 'Borroka hasiera ordua',
  'updated': 'Eguneratuta',
  // Dialog strings
  'confirm': 'Baieztatu',
  'cancel': 'Utzi',
  'yes': 'Bai',
  'no': 'Ez',
  'save': 'Gorde',
  'edit': 'Editatu',
  'levelFormat': '{level}. maila',
  'newbieLevelFormat': 'Hasiberri {level}. maila',
  'totalLevel': '{level}/{totalLevel} maila',
  'totalLevelTooltip': 'Orain: {level}. maila / Guztira {totalLevel} maila',
  // Battlefront UI strings
  'noBattlefronts': 'Ez dago borroka frontierarik',
  'battlefrontCount': '{count} borroka frontiera',
  'levelPrefix': 'ML{level}',
  'newbieLevelPrefix': 'Hasiberri ML{level}',
  'minesCount': '{count} mina',
  'notStarted': 'Ez hasita',
  'victory': 'Irabaztea',
  'defeat': 'Galera',
  'gameDurationParam': 'Iraupena: {seconds} segundo',
  'actionsCountParam': 'Ekintzak: {count} aldiz',
  'actionsCountParamShort': '{count} aldiz',
  'miningMethodParam': 'Metodoa: {method}',
  'startTimeParam': 'Hasiera ordua: {time}',
  'endTimeParam': 'Amaiera ordua: {time}',
  'returnButton': 'Itzuli',
  'battlefrontDetails': 'Borroka frontieraren xehetasunak',
  'clickToEditName': 'Kliku izena aldatzeko',
  'clickToAddDescription': 'Kliku deskribapena gehitzeko...',
  'noDescription': 'Deskribapenik ez',
  // Level record strings
  'levelCount': '{count} maila',
  'noLevelRecords': 'Hautatu borroka frontiera bat',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Ezabatu borroka frontiera',
  'deleteBattlefrontContent':
      'Ziur zaude "{name}" borroka frontiera ezabatu nahi duzula? Ekintza hau ezin da desegin.',
  'battlefrontLockedCannotDelete':
      'Borroka frontiera blokeatuta dago, ezin da ezabatu',
  'unknownNavigationLevel': 'Nabigazio maila ezezaguna',
  'noBattlefrontSelected': 'Ez da borroka frontierarik hautatu',
  'noBattlefrontToContinue': 'Ez da aurkitu jarraitzeko borroka frontierarik',
  'synced': 'Sinkronizatuta',
  'notSynced': 'Sinkronizatu gabe',
  'newbieBattlefrontName': 'Hasiberri borroka frontiera {number}',
  'battlefrontName': 'Borroka frontiera {number}',
  'nickname': 'Ezizena',
  'nicknameSetting': 'Ezizenaren ezarpena',
  'nicknameDesc': 'Ezarri zure ezizena',
  'enterNickname': 'Sartu ezizena',
  'nicknameSaved': 'Ezizena gorde da',
  'nicknameUpdated': 'Ezizena eguneratu da',
  'nicknameRequired': 'Ezizena beharrezkoa da',
  'nicknameTooLong': 'Ezizenak ezin du 30 karaktere baino gehiago izan',
  // Level top strings
  'levelTopCount': 'Gehieneko ranking ({count})',
  'levelTopCountShort': 'Gehienak ({count})',
  'retry': 'Saiatu berriro',
  'noLevelTopData': 'Daturik ez',
  'remoteBattlefront': 'Urruneko borroka frontiera',
  'participated': 'Parte hartuta',
  'notParticipated': 'Parte hartu gabe',
  'loadMore': 'Kargatu gehiago',

  'joinBattle': 'Borrokan parte hartu',
  'joinBattleTooltip': 'Parte hartu "{name}" borrokan',
  'joinBattleConfirm': 'Ziur zaude "{name}" borrokan parte hartu nahi duzula?',
  'joinBattleSuccess': 'Ondo parte hartu duzu "{name}" borrokan',
  'joinBattleErrorSelf': 'Ezin zara zuk sortutako borrokan parte hartu',

  'replayBattlefront': 'Berriz erreproduzitu borroka frontiera',
  'replayBattlefrontTooltip': 'Berriz erreproduzitu "{name}" borroka frontiera',
  'getReplayBattlefrontConfirm':
      'Ziur zaude "{name}" berriz erreproduzitu nahi duzula?',
  'getReplayBattlefrontFailed':
      '"{name}" erreproduzitzeak huts egin du: {error}',

  'download': 'Deskargatu',
  'downloadBattlefront': 'Deskargatu borroka frontiera',
  'downloadBattlefrontTooltip': 'Deskargatu "{name}" borroka frontiera',
  'getDownloadBattlefrontConfirm':
      'Ziur zaude "{name}" deskargatu nahi duzula?',
  'getDownloadBattlefrontSuccess': '"{name}" ondo deskargatu da',
  'downloadMyOwnBattlefrontError':
      'Zuk sortutako borroka frontierak soilik deskargatu ditzakezu',
  'getDownloadBattlefrontFailed':
      '"{name}" deskargatzeak huts egin du: {error}',

  'continueGameShort': 'Jarraitu borrokan',
  'replayShort': 'Berriz erreproduzitu',
  'highestLevel': '{level}. maila',
  'deviceNickname': 'Gailua',
  'createdTime': 'Sortze ordua',
  'remoteBattlefrontDetail': 'Urruneko borroka frontieraren xehetasunak',
  'levelList': 'Mailen zerrenda',
  'fastClearTimeParam': 'Gainditu denbora: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Hautatu tokiko borroka frontiera bat xehetasunak ikusteko',
  'loadingRemoteDetail':
      'Urruneko borroka frontieraren xehetasunak kargatzen...',
  'noRemoteBattlefrontSelected': 'Ez da urruneko borroka frontierarik hautatu',
  'failedToLoadRemoteDetail': 'Urruneko xehetasunak kargatzeak huts egin du',
  'fastestRecord': 'Azkarren gaindiketa',
  'safestRecord': 'Seguruen gaindiketa',
  'fastestRecordDesc': 'Azkarren gaindiketa (gutxien denbora erabilita)',
  'safestRecordDesc': 'Seguruen gaindiketa (gutxien ekintza)',
  'creator': 'Sortzailea',
  'player': 'Jokalaria',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopia',
  'collapse': 'Tolestu',
  'expand': 'Zabaldu',
  // 退出战线
  'quitBattlefront': 'Irten borroka frontieratik',
  'quitBattlefrontTooltip': 'Irten urruneko borroka frontieratik',
  'quitBattlefrontTitle': 'Irten borroka frontieratik',
  'quitBattlefrontContent':
      'Ziur zaude "{name}" borroka frontieratik irten nahi duzula? Zure tokiko aurrerapena ezabatuko da.',

  // 下载页面
  'downloadClient': 'Deskargatu bezeroa',
  'browser': 'Nabigatzailea',
  'browserDesc': 'Jolastu zuzenean nabigatzailean, deskargatu gabe',
  'windowsDesc': 'Windows 10 eta gorakoa',
  'macosDesc': 'macOS 10.15 eta gorakoa',
  'android': 'Android sistema',
  'androidDesc': 'Android 8.0 eta gorakoa',
  'iosDesc': 'iOS 14.0 eta gorakoa',
  'linkAddress': 'Estekaren helbidea',
  'downloadLink': 'Deskargatzeko esteka',
  'qrCode': 'QR kodea',
  'scanToDownload': 'Eskaneatu telefonoarekin deskargatzeko',
  'copy': 'Kopiatu',
  'copiedToClipboard': 'Arbelera kopiatuta',
  'openLink': 'Ireki esteka',
  'cannotOpenLink': 'Ezin da esteka ireki',
  // 游戏介绍
  'gameIntroduction':
      '1. "Hasiberriek" 15 minekin hasten da, gehienez 99 minera iristen da;\n2. "Borroka frontiera berria" 81 minekin hasten da, maila bakoitzean mina kopurua gehitzen da, gehienezik ez.\n3. Internet konexioa dagoenean, "gainditutako" borroka frontierak automatikoki partekatuko dira hodeian besteentzat ikusteko.',
};
