/// Беларускія радкі для прыкладання DMine
const Map<String, String> stringsBe = {
  'appLabel': 'Лепшы мінаапішук',
  'appTitle': 'DMine - Лепшы мінаапішук',
  'settings': 'Налады',
  'gameSettings': 'Налады гульні',
  'showTimer': 'Паказваць таймер часу',
  'showTimerDesc': 'Паказваць таймер гульні на экране гульні',
  'showActionCounter': 'Паказваць лічыльник дзеянняў',
  'showActionCounterDesc': 'Паказваць колькасць дзеянняў на экране гульні',
  'autoAdjustBoardWidth': 'Аўтаматычна выраўноўваць шырыню дошкі',
  'autoAdjustBoardWidthDesc':
      'Аўтаматычна выраўноўваць шырыню дошкі па размеце экрана',
  'resetToDefaults': 'Скінуць на стандартныя налады',
  'resetToDefaultsDesc': 'Аднавіць усе налады па змаўчанні',
  'aboutDMine': 'Пра DMine',
  'version': 'Версія',
  'close': 'Закрыць',
  'manualBoardWidth': 'Ручная ўстанова шырыню дошкі',
  'currentWidth': 'Цяперашняе',
  'range': 'Дыяпазон',
  'widthSliderHint':
      'Падказка: перацягнуўшы паўзунок, вы можаце праглядаць змены шырыню дошкі ў рэжыме нажива',
  'gameRecords': 'Запісы гульні',
  'selectMapToViewRecords': 'Выберце карту, каб праглядаць запісы',
  'totalRecords': 'Усяго',
  'gameRecordsTitle': 'Спіс запісаў гульні',
  'pleaseSelectMapFirst': 'Спачатку выберце карту',
  'noGameRecords': 'Запісаў няма',
  'miningMethodFlag': 'Паставіць сцяжок',
  'miningMethodBlind': 'Слепы пошук',
  'statusPlaying': '▶️ Ідзе гульня...',
  'statusWin': '🎉 Перамога',
  'statusLose': '💥 Параза',
  'actionsCount': 'Колькасць дзеянняў',
  'miningMethod': 'Спосіб мінаапішуку',
  'duration': 'Трайвалісць',
  'seconds': 'секунд',
  'startTime': 'Час пачатку',
  'endTime': 'Час заканчэння',
  'pauseTime': 'Час паўзы',
  'unlock': 'Разблакаваць',
  'lock': 'Заблакаваць',
  'delete': 'Выдаліць',
  'languageSetting': 'Налады мовы',
  'currentLanguage': 'Цяперашняя',
  'systemLanguage': 'Мова сістэмы',
  'chinese': 'Кітайская',
  'english': 'Англійская',
  'language': 'Мова',
  // Home page
  'newbie': 'Навучанне для пачаткоўцаў',
  'gameIntro': 'Апісанне гульні',
  'newBattle': 'Новы фронт',
  'continueChallenge': 'Працягнуць челендж',
  'error': 'Памылка',
  'initializationFailed': 'Памылка ініцыялізацыі',
  // Game page
  'congratulations': 'Віншую! Уровень пройдзен!',
  'gameOver': 'Гульня скончана',
  'timeUsed': 'Часу затрачена',
  'actionCount': 'Колькасць дзеянняў',
  'mineCount': 'Колькасць мін',
  'nextLevel': 'Наступны ўзровень: Узровень {level}',
  'newbieNextLevel': 'Наступны ўзровень: Пачатковы {level} ўзровень',
  'nextLevelMines': 'Колькасць мін',
  'mineIncrease': 'Павелічэнне',
  'newbieFinish': 'Навучанне для пачаткоўцаў завершана',
  'ok': 'ОК',
  'continueNextLevel': 'Працягнуць наступны ўзровень',
  'restart': 'Пачаць зноў',
  'level': 'Узровень {level}',
  'newbieLevel': 'Пачатковы ўзровень {level}',
  'operationFailed': 'Памылка аперацыі',
  // Game status texts
  'returnHome': 'Вярнуцца на галоўную',
  'revealMode': 'Рэжым раскрыцця',
  'flagMode': 'Рэжым сцяжкоў',
  'newMap': 'Новая карта (колькасць мін не мяняецца, стварыць новую карту)',
  'resetMap': 'Перазагрузіць карту (карта тая ж, стан скінуты)',
  'zoomOut': 'Паменшыць',
  'zoomIn': 'Павялічыць',
  'resetZoom': 'Скінуць маштаб',
  'previousStep': 'Папярэдні крок',
  'pause': 'Паўза',
  'play': 'Гуляць',
  'nextStep': 'Наступны крок',
  'clickToStart': 'Націсніце на любую клетку, каб пачаць гульню',
  'playing': 'Гуляе...',
  'gameWin': 'Віншую! Уровень пройдзен!',
  'gameLose': 'Гульня скончана, вы напалі на міну',
  'gamePaused': 'Гульня на паўзе',
  'ready': 'Гатовы',
  'clickStartShort': 'Націсніце, каб пачаць',
  'playingShort': 'Гуляе',
  'winShort': 'Пройдзена!',
  'loseShort': 'Напалі на міну',
  'pausedShort': 'Паўза',
  // Counter strings
  'currentLevel': 'Цяперашні ўзровень',
  'remainingMines': 'Мін засталося',
  'gameTime': 'Час гульні (секунд)',
  'operationCount': 'Колькасць дзеянняў',
  'previousLevel': 'Папярэдні ўзровень',
  'nextLevelShort': 'Наступны ўзровень',
  // Battlefront strings
  'completed': 'Завершана',
  'inProgress': 'У працэсе',
  'continueGame': 'Працягнуць гульню',
  'replay': 'Паўтор',
  'creater': 'Камандзір',
  'created': 'Час пачатку бітвы',
  'updated': 'Абноўлена',
  // Dialog strings
  'confirm': 'Пацвердзіць',
  'cancel': 'Скасаваць',
  'yes': 'Так',
  'no': 'Не',
  'save': 'Захаваць',
  'edit': 'Рэдагаваць',
  'levelFormat': 'Узровень {level}',
  'newbieLevelFormat': 'Пачатковы ўзровень {level}',
  'totalLevel': '{level}/{totalLevel} узроўняў',
  'totalLevelTooltip': 'Цяпер: Узровень {level} / Усяго {totalLevel} узроўняў',
  // Battlefront UI strings
  'noBattlefronts': 'Фронтаў няма',
  'battlefrontCount': '{count} фронтаў',
  'levelPrefix': 'УЗР{level}',
  'newbieLevelPrefix': 'Пачатковы УЗР{level}',
  'minesCount': '{count} мін',
  'notStarted': 'Не пачата',
  'victory': 'Перамога',
  'defeat': 'Параза',
  'gameDurationParam': 'Трайвалісць: {seconds} секунд',
  'actionsCountParam': 'Дзеянні: {count} разоў',
  'actionsCountParamShort': '{count} разоў',
  'miningMethodParam': 'Спосіб: {method}',
  'startTimeParam': 'Час пачатку: {time}',
  'endTimeParam': 'Час заканчэння: {time}',
  'returnButton': 'Вярнуцца',
  'battlefrontDetails': 'Дэталі фронта',
  'clickToEditName': 'Націсніце, каб змяніць назву',
  'clickToAddDescription': 'Націсніце, каб дадаць апісанне...',
  'noDescription': 'Апісання няма',
  // Level record strings
  'levelCount': '{count} узроўняў',
  'noLevelRecords': 'Выберце фронт',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Выдаліць фронт',
  'deleteBattlefrontContent':
      'Вы ўпэўнены, што хочаце выдаліць фронт "{name}"? Гэта дзеянне неўзваротнае.',
  'battlefrontLockedCannotDelete': 'Фронт заблакаваны, нельга выдаліць',
  'unknownNavigationLevel': 'Невядомы ўзровень навігацыі',
  'noBattlefrontSelected': 'Фронт не выбраны',
  'noBattlefrontToContinue': 'Няма фронтаў для працягу',
  'synced': 'Сінхранізавана',
  'notSynced': 'Не сінхранізавана',
  'newbieBattlefrontName': 'Пачатковы фронт {number}',
  'battlefrontName': 'Фронт {number}',
  'nickname': 'Мянушка',
  'nicknameSetting': 'Налады мянушкі',
  'nicknameDesc': 'Усталюйце сваю мянушку',
  'enterNickname': 'Увядзіце мянушку',
  'nicknameSaved': 'Мянушка захавана',
  'nicknameUpdated': 'Мянушка абноўлена',
  'nicknameRequired': 'Мянушка абавязковая',
  'nicknameTooLong': 'Мянушка не можа быць больш за 30 знакаў',
  // Level top strings
  'levelTopCount': 'Рэйтынг ({count})',
  'levelTopCountShort': 'Рэйтынг ({count})',
  'retry': 'Паспрабаваць зноў',
  'noLevelTopData': 'Данных няма',
  'remoteBattlefront': 'Аддалены фронт',
  'participated': 'Удзельнічалі',
  'notParticipated': 'Не удзельнічалі',
  'loadMore': 'Загрузіць яшчэ',

  'joinBattle': 'Далучыцца да бітвы',
  'joinBattleTooltip': 'Далучыцца да бітвы "{name}"',
  'joinBattleConfirm': 'Вы ўпэўнены, што хочаце далучыцца да бітвы "{name}"?',
  'joinBattleSuccess': 'Вы паспяхова далучыліся да бітвы "{name}"',
  'joinBattleErrorSelf': 'Нельга далучыцца да бітвы, створанай вамі',

  'replayBattlefront': 'Паўториць фронт',
  'replayBattlefrontTooltip': 'Паўториць фронт "{name}"',
  'getReplayBattlefrontConfirm': 'Вы ўпэўнены, што хочаце паўтарыць "{name}"?',
  'getReplayBattlefrontFailed': 'Памылка паўтору "{name}": {error}',

  'download': 'Скачаць',
  'downloadBattlefront': 'Скачаць фронт',
  'downloadBattlefrontTooltip': 'Скачаць фронт "{name}"',
  'getDownloadBattlefrontConfirm': 'Вы ўпэўнены, што хочаце скачаць "{name}"?',
  'getDownloadBattlefrontSuccess': 'Фронт "{name}" паспяхова спампаваны',
  'downloadMyOwnBattlefrontError':
      'Можна скачаць толькі фронты, створаныя вамі',
  'getDownloadBattlefrontFailed': 'Памылка спампавання "{name}": {error}',

  'continueGameShort': 'Працягнуць бітву',
  'replayShort': 'Паўтор',
  'highestLevel': 'Узровень {level}',
  'deviceNickname': 'Прылада',
  'createdTime': 'Час стварэння',
  'remoteBattlefrontDetail': 'Дэталі аддаленага фронта',
  'levelList': 'Спіс узроўняў',
  'fastClearTimeParam': 'Час праходжання: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Выберце лакальны фронт, каб праглядаць дэталі',
  'loadingRemoteDetail': 'Загрузка дэталяў аддаленага фронта...',
  'noRemoteBattlefrontSelected': 'Аддалены фронт не выбраны',
  'failedToLoadRemoteDetail': 'Памылка загрузкі дэталяў аддаленага фронта',
  'fastestRecord': 'Самы хуткі праход',
  'safestRecord': 'Самы бяспечны праход',
  'fastestRecordDesc': 'Самы хуткі праход (менш за ўсё часу)',
  'safestRecordDesc': 'Самы бяспечны праход (менш за ўсё дзеянняў)',
  'creator': 'Стваральнік',
  'player': 'Гульца',
  // 分支地图字符串
  'getBranchMapCount': '{count} копій',
  'collapse': 'Згарнуць',
  'expand': 'Разгарнуць',
  // 退出战线
  'quitBattlefront': 'Выйсці з фронта',
  'quitBattlefrontTooltip': 'Выйсці з аддаленага фронта',
  'quitBattlefrontTitle': 'Выйсці з фронта',
  'quitBattlefrontContent':
      'Вы ўпэўнены, што хочаце выйсці з фронта "{name}"? Ваш лакальны прогрэс будзе выдалены.',

  // 下载页面
  'downloadClient': 'Скачаць кліент',
  'browser': 'Браўзер',
  'browserDesc': 'Гуляйце прама ў браўзеры, без спампавання',
  'windowsDesc': 'Для Windows 10 і вышэй',
  'macosDesc': 'Для macOS 10.15 і вышэй',
  'android': 'Android',
  'androidDesc': 'Для Android 8.0 і вышэй',
  'iosDesc': 'Для iOS 14.0 і вышэй',
  'linkAddress': 'Спасылка',
  'downloadLink': 'Спасылка на спампаванне',
  'qrCode': 'QR-код',
  'scanToDownload': 'Скануйце QR-код на тэлефоне, каб скачаць',
  'copy': 'Скапіяваць',
  'copiedToClipboard': 'Скапіявана ў буфер абмену',
  'openLink': 'Адкрыць спасылку',
  'cannotOpenLink': 'Нельга адкрыць спасылку',
  // 游戏介绍
  'gameIntroduction':
      '1. «Навучанне» пачынаецца з 15 мін, дасягае максімуму 99 мін;\n2. «Новы фронт» пачынаецца з 81 мін, на кожным узроўні міны павелічваюцца, без верхняга ліміту.\n3. Пры падключэнні да інтэрнэту «пройдзеныя» фронты аўтаматычна размяшчаюцца ў хмару для навучання іншых.',
};
