/// Chinese language strings for the DMine application
const Map<String, String> stringsZh = {
  'appLabel': '顶级扫雷',
  'appTitle': 'DMine - 顶级扫雷',
  'settings': '设置',
  'gameSettings': '游戏设置',
  'showTimer': '显示用时计时器',
  'showTimerDesc': '在游戏界面显示游戏计时器',
  'showActionCounter': '显示动作数计数器',
  'showActionCounterDesc': '在游戏界面显示动作次数统计',
  'autoAdjustBoardWidth': '自动调整棋盘宽度',
  'autoAdjustBoardWidthDesc': '自动根据屏幕大小调整棋盘宽度',
  'resetToDefaults': '重置为默认设置',
  'resetToDefaultsDesc': '恢复所有设置为默认值',
  'aboutDMine': '关于顶雷',
  'version': '版本',
  'close': '关闭',
  'manualBoardWidth': '手动设置棋盘宽度',
  'currentWidth': '当前',
  'range': '范围',
  'widthSliderHint': '提示：滑块拖动过程中可以即时预览棋盘宽度变化',
  'gameRecords': '游戏记录',
  'selectMapToViewRecords': '请选择一个地图查看记录',
  'totalRecords': '共',
  'gameRecordsTitle': '游戏记录列表',
  'pleaseSelectMapFirst': '请先选择一个地图',
  'noGameRecords': '暂无游戏记录',
  'miningMethodFlag': '插旗',
  'miningMethodBlind': '盲扫',
  'statusPlaying': '▶️ 进行中...',
  'statusWin': '🎉 胜利',
  'statusLose': '💥 失败',
  'actionsCount': '操作数',
  'miningMethod': '扫雷方式',
  'duration': '时长',
  'seconds': '秒',
  'startTime': '开始时间',
  'endTime': '结束时间',
  'pauseTime': '暂停时间',
  'unlock': '解锁',
  'lock': '锁定',
  'delete': '删除',
  'languageSetting': '语言设置',
  'currentLanguage': '当前',
  'systemLanguage': '系统语言',
  'chinese': '中文',
  'english': 'English',
  'language': '语言',
  // Home page
  'newbie': '新手入门',
  'gameIntro': '游戏介绍',
  'newBattle': '新战线',
  'continueChallenge': '继续挑战',
  'error': '错误',
  'initializationFailed': '初始化失败',
  // Game page
  'congratulations': '恭喜通关！',
  'gameOver': '游戏结束',
  'timeUsed': '用时',
  'actionCount': '动作数',
  'mineCount': '地雷数',
  'nextLevel': '下一关: 第 {level} 关',
  'newbieNextLevel': '下一关: 新手第 {level} 关',
  'nextLevelMines': '地雷数',
  'mineIncrease': '增加',
  'newbieFinish': '新手入门已完成',
  'ok': '确定',
  'continueNextLevel': '继续挑战下一关',
  'restart': '重新开始',
  'level': '第 {level} 关',
  'newbieLevel': '新手第 {level} 关',
  'operationFailed': '操作失败',
  // Game status texts
  'returnHome': '返回主页',
  'revealMode': '揭开模式',
  'flagMode': '插旗模式',
  'newMap': '新地图(地雷数不变,生成新地图)',
  'resetMap': '重新载入地图(地图不变,重置状态)',
  'zoomOut': '缩小',
  'zoomIn': '放大',
  'resetZoom': '恢复原样',
  'previousStep': '上一步',
  'pause': '暂停',
  'play': '播放',
  'nextStep': '下一步',
  'clickToStart': '点击任意格子开始游戏',
  'playing': '游戏中...',
  'gameWin': '恭喜通关！',
  'gameLose': '游戏结束，踩到地雷了',
  'gamePaused': '游戏暂停',
  'ready': '准备开始',
  'clickStartShort': '点击开始',
  'playingShort': '游戏中',
  'winShort': '通关！',
  'loseShort': '踩雷失败',
  'pausedShort': '暂停',
  // Counter strings
  'currentLevel': '当前关次',
  'remainingMines': '剩余地雷数',
  'gameTime': '游戏用时（秒）',
  'operationCount': '操作次数',
  'previousLevel': '上一关',
  'nextLevelShort': '下一关',
  // Battlefront strings
  'completed': '已完成',
  'inProgress': '进行中',
  'continueGame': '继续游戏',
  'replay': '回放',
  'creater': '总司令',
  'created': '开战时间',
  'updated': '更新',
  // Dialog strings
  'confirm': '确认',
  'cancel': '取消',
  'yes': '是',
  'no': '否',
  'save': '保存',
  'edit': '编辑',
  'levelFormat': '第 {level} 关',
  'newbieLevelFormat': '新手第 {level} 关',
  'totalLevel': '{level}/{totalLevel} 关',
  'totalLevelTooltip': '当前: 第 {level} 关 / 共 {totalLevel} 关',
  // Battlefront UI strings
  'noBattlefronts': '暂无战线',
  'battlefrontCount': '{count}个战线',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': '新手LV{level}',
  'minesCount': '{count}雷',
  'notStarted': '未开始',
  'victory': '胜利',
  'defeat': '失败',
  'gameDurationParam': '时长: {seconds}秒',
  'actionsCountParam': '动作: {count}次',
  'actionsCountParamShort': '{count}次',
  'miningMethodParam': '方式: {method}',
  'startTimeParam': '开始时间: {time}',
  'endTimeParam': '结束时间: {time}',
  'returnButton': '返回',
  'battlefrontDetails': '战线详情',
  'clickToEditName': '点击修改名称',
  'clickToAddDescription': '点击添加描述...',
  'noDescription': '暂无描述',
  // Level record strings
  'levelCount': '{count}个关次',
  'noLevelRecords': '请选择战线',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': '删除战线',
  'deleteBattlefrontContent': '确定要删除战线 "{name}" 吗？此操作不可撤销。',
  'battlefrontLockedCannotDelete': '战线已锁定，无法删除',
  'unknownNavigationLevel': '未知层级',
  'noBattlefrontSelected': '未选择战线',
  'noBattlefrontToContinue': '没有找到可继续的战线',
  'synced': '已同步',
  'notSynced': '未同步',
  'newbieBattlefrontName': '新手战线{number}',
  'battlefrontName': '战线{number}',
  'nickname': '昵称',
  'nicknameSetting': '昵称设置',
  'nicknameDesc': '设置您的昵称',
  'enterNickname': '输入昵称',
  'nicknameSaved': '昵称已保存',
  'nicknameUpdated': '昵称更新成功',
  'nicknameRequired': '昵称为必填项',
  'nicknameTooLong': '昵称不能超过30个字符',
  // Level top strings
  'levelTopCount': '顶级榜 ({count})',
  'levelTopCountShort': '顶级 ({count})',
  'retry': '重试',
  'noLevelTopData': '暂无数据',
  'remoteBattlefront': '远程战线',
  'participated': '已参战',
  'notParticipated': '未参战',
  'loadMore': '加载更多',

  'joinBattle': '参战',
  'joinBattleTooltip': '参战"{name}"',
  'joinBattleConfirm': '确认要参战"{name}"吗？',
  'joinBattleSuccess': '成功参战"{name}"',
  'joinBattleErrorSelf': '不能参战自己创建的战线',

  'replayBattlefront': '回放战线',
  'replayBattlefrontTooltip': '回放战线"{name}"',
  'getReplayBattlefrontConfirm': '确认要回放"{name}"吗？',
  'getReplayBattlefrontFailed': '回放"{name}"失败: {error}',

  'download': '下载',
  'downloadBattlefront': '下载战线',
  'downloadBattlefrontTooltip': '下载战线"{name}"',
  'getDownloadBattlefrontConfirm': '确认要下载"{name}"吗？',
  'getDownloadBattlefrontSuccess': '成功下载"{name}"',
  'downloadMyOwnBattlefrontError': '只能下载自己创建的战线',
  'getDownloadBattlefrontFailed': '下载"{name}"失败: {error}',

  'continueGameShort': '继续战斗',
  'replayShort': '回放',
  'highestLevel': '第 {level} 关',
  'deviceNickname': '设备',
  'createdTime': '创建时间',
  'remoteBattlefrontDetail': '战线详情',
  'levelList': '关次列表',
  'fastClearTimeParam': '通关时间: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': '请选择一个本地战线查看详情',
  'loadingRemoteDetail': '加载远程战线详情中...',
  'noRemoteBattlefrontSelected': '未选择远程战线',
  'failedToLoadRemoteDetail': '加载远程战线详情失败',
  'fastestRecord': '最快通关',
  'safestRecord': '最稳通关',
  'fastestRecordDesc': '最快通关(用时最少)',
  'safestRecordDesc': '最稳通关(动作数最少)',
  'creator': '开创者',
  'player': '玩家',
  // 分支地图字符串
  'getBranchMapCount': '{count}个副本',
  'collapse': '折叠',
  'expand': '展开',
  // 退出战线
  'quitBattlefront': '退出战线',
  'quitBattlefrontTooltip': '退出远程战线',
  'quitBattlefrontTitle': '退出战线',
  'quitBattlefrontContent': '确定要退出战线 "{name}" 吗？您的本地进度将被删除。',

  // 下载页面
  'downloadClient': '下载客户端',
  'browser': '浏览器',
  'browserDesc': '直接在浏览器中游玩，无需下载',
  'windowsDesc': '适用于Windows 10及以上系统',
  'linuxDesc': '适用于Linux系统',
  'macosDesc': '适用于macOS 10.15及以上系统',
  'android': '安卓系统',
  'androidDesc': '适用于Android 8.0及以上系统',
  'iosDesc': '适用于iOS 14.0及以上系统',
  'ohos': '鸿蒙系统',
  'ohosDesc': '适用于HarmonyOS操作系统',
  'linkAddress': '链接地址',
  'downloadLink': '下载链接',
  'qrCode': '二维码',
  'scanToDownload': '使用手机扫码下载',
  'copy': '复制',
  'copiedToClipboard': '已复制到剪贴板',
  'openLink': '打开链接',
  'cannotOpenLink': '无法打开链接',
  // 自动更新
  'updateAvailableTitle': '发现新版本',
  'forceUpdateTitle': '需要强制更新',
  'currentVersion': '当前版本',
  'latestVersionText': '最新版本',
  'updateLog': '更新日志',
  'remindLater': '稍后提醒',
  'skipThisVersion': '跳过此版本',
  'exitApp': '退出应用',
  'updateNow': '立即更新',
  // 游戏介绍
  'gameIntroduction':
      '1. "新手入门"将从15雷开始,最高可以到99雷;\n2. "新战线"从81雷开始,每关次会增加一定数量的地雷,上不封顶.\n3. 联网情况下"已通关"的战线会自动分享到云端,供其他人学习.',
};
