// Spanish（西班牙语）
/// Spanish language strings for the DMine application
const Map<String, String> stringsEs = {
  'appLabel': 'Buscaminas Top',
  'appTitle': 'DMine - Buscaminas Top',
  'settings': 'Configuración',
  'gameSettings': 'Configuración del juego',
  'showTimer': 'Mostrar temporizador',
  'showTimerDesc': 'Muestra el temporizador de la partida en la pantalla',
  'showActionCounter': 'Mostrar contador de acciones',
  'showActionCounterDesc':
      'Muestra el número de acciones en la pantalla del juego',
  'autoAdjustBoardWidth': 'Ajustar ancho del tablero automáticamente',
  'autoAdjustBoardWidthDesc':
      'Ajusta automáticamente el ancho del tablero al tamaño de la pantalla',
  'resetToDefaults': 'Restaurar ajustes por defecto',
  'resetToDefaultsDesc':
      'Restablece todos los ajustes a los valores predeterminados',
  'aboutDMine': 'Acerca de DMine',
  'version': 'Versión',
  'close': 'Cerrar',
  'manualBoardWidth': 'Establecer ancho del tablero manualmente',
  'currentWidth': 'Actual',
  'range': 'Rango',
  'widthSliderHint':
      'Consejo: al deslizar el control, verás el cambio de ancho al instante',
  'gameRecords': 'Registros de partida',
  'selectMapToViewRecords': 'Selecciona un mapa para ver los registros',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Lista de registros de partida',
  'pleaseSelectMapFirst': 'Selecciona un mapa primero',
  'noGameRecords': 'Sin registros de partida',
  'miningMethodFlag': 'Marcar con bandera',
  'miningMethodBlind': 'Destapar a ciegas',
  'statusPlaying': '▶️ En juego...',
  'statusWin': '🎉 Victoria',
  'statusLose': '💥 Derrota',
  'actionsCount': 'Número de acciones',
  'miningMethod': 'Modo de juego',
  'duration': 'Duración',
  'seconds': 'segundos',
  'startTime': 'Hora de inicio',
  'endTime': 'Hora de fin',
  'pauseTime': 'Tiempo de pausa',
  'unlock': 'Desbloquear',
  'lock': 'Bloquear',
  'delete': 'Eliminar',
  'languageSetting': 'Configuración de idioma',
  'currentLanguage': 'Actual',
  'systemLanguage': 'Idioma del sistema',
  'chinese': 'Chino',
  'english': 'Inglés',
  'language': 'Idioma',
  // Home page
  'newbie': 'Principiante',
  'gameIntro': 'Introducción al juego',
  'newBattle': 'Nuevo frente',
  'continueChallenge': 'Continuar desafío',
  'error': 'Error',
  'initializationFailed': 'Fallo en la inicialización',
  // Game page
  'congratulations': '¡Felicidades, has superado el nivel!',
  'gameOver': 'Fin del juego',
  'timeUsed': 'Tiempo',
  'actionCount': 'Acciones',
  'mineCount': 'Minas',
  'nextLevel': 'Siguiente nivel: Nivel {level}',
  'newbieNextLevel': 'Siguiente nivel: Principiante {level}',
  'nextLevelMines': 'Minas',
  'mineIncrease': 'Aumento',
  'newbieFinish': 'Modo principiante completado',
  'ok': 'Aceptar',
  'continueNextLevel': 'Continuar al siguiente nivel',
  'restart': 'Reiniciar',
  'level': 'Nivel {level}',
  'newbieLevel': 'Principiante {level}',
  'operationFailed': 'Operación fallida',
  // Game status texts
  'returnHome': 'Volver al inicio',
  'revealMode': 'Modo destapar',
  'flagMode': 'Modo bandera',
  'newMap': 'Nuevo mapa (mismas minas, nuevo diseño)',
  'resetMap': 'Restablecer mapa (mismo diseño, reiniciar estado)',
  'zoomOut': 'Alejar',
  'zoomIn': 'Acercar',
  'resetZoom': 'Restablecer zoom',
  'previousStep': 'Paso anterior',
  'pause': 'Pausar',
  'play': 'Jugar',
  'nextStep': 'Siguiente paso',
  'clickToStart': 'Haz clic en cualquier casilla para empezar',
  'playing': 'En juego...',
  'gameWin': '¡Felicidades, has superado el nivel!',
  'gameLose': 'Fin del juego, has pisado una mina',
  'gamePaused': 'Juego pausado',
  'ready': 'Listo para empezar',
  'clickStartShort': 'Clic para iniciar',
  'playingShort': 'En juego',
  'winShort': '¡Completado!',
  'loseShort': 'Derrota',
  'pausedShort': 'Pausado',
  // Counter strings
  'currentLevel': 'Nivel actual',
  'remainingMines': 'Minas restantes',
  'gameTime': 'Tiempo de juego (segundos)',
  'operationCount': 'Número de operaciones',
  'previousLevel': 'Nivel anterior',
  'nextLevelShort': 'Siguiente nivel',
  // Battlefront strings
  'completed': 'Completado',
  'inProgress': 'En progreso',
  'continueGame': 'Continuar juego',
  'replay': 'Repetir',
  'creater': 'Comandante',
  'created': 'Hora de creación',
  'updated': 'Actualizado',
  // Dialog strings
  'confirm': 'Confirmar',
  'cancel': 'Cancelar',
  'yes': 'Sí',
  'no': 'No',
  'save': 'Guardar',
  'edit': 'Editar',
  'levelFormat': 'Nivel {level}',
  'newbieLevelFormat': 'Principiante {level}',
  'totalLevel': '{level}/{totalLevel} niveles',
  'totalLevelTooltip': 'Actual: Nivel {level} / Total {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Sin frentes',
  'battlefrontCount': '{count} frentes',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'Principiante NV{level}',
  'minesCount': '{count} minas',
  'notStarted': 'Sin iniciar',
  'victory': 'Victoria',
  'defeat': 'Derrota',
  'gameDurationParam': 'Duración: {seconds}s',
  'actionsCountParam': 'Acciones: {count} veces',
  'actionsCountParamShort': '{count} veces',
  'miningMethodParam': 'Modo: {method}',
  'startTimeParam': 'Inicio: {time}',
  'endTimeParam': 'Fin: {time}',
  'returnButton': 'Volver',
  'battlefrontDetails': 'Detalles del frente',
  'clickToEditName': 'Haz clic para editar el nombre',
  'clickToAddDescription': 'Haz clic para añadir descripción...',
  'noDescription': 'Sin descripción',
  // Level record strings
  'levelCount': '{count} niveles',
  'noLevelRecords': 'Selecciona un frente',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Eliminar frente',
  'deleteBattlefrontContent':
      '¿Seguro que quieres eliminar el frente \'{name}\'? Esta acción no se puede deshacer.',
  'battlefrontLockedCannotDelete': 'Frente bloqueado, no se puede eliminar',
  'unknownNavigationLevel': 'Nivel desconocido',
  'noBattlefrontSelected': 'Ningún frente seleccionado',
  'noBattlefrontToContinue': 'No hay frente para continuar',
  'synced': 'Sincronizado',
  'notSynced': 'No sincronizado',
  'newbieBattlefrontName': 'Frente de principiante {number}',
  'battlefrontName': 'Frente {number}',
  'nickname': 'Apodo',
  'nicknameSetting': 'Configuración de apodo',
  'nicknameDesc': 'Establece tu apodo',
  'enterNickname': 'Ingresa tu apodo',
  'nicknameSaved': 'Apodo guardado',
  'nicknameUpdated': 'Apodo actualizado',
  'nicknameRequired': 'El apodo es obligatorio',
  'nicknameTooLong': 'El apodo no puede superar los 30 caracteres',
  // Level top strings
  'levelTopCount': 'Ranking ({count})',
  'levelTopCountShort': 'Ranking ({count})',
  'retry': 'Reintentar',
  'noLevelTopData': 'Sin datos',
  'remoteBattlefront': 'Frente remoto',
  'participated': 'Participó',
  'notParticipated': 'No participó',
  'loadMore': 'Cargar más',
  'joinBattle': 'Unirse a la batalla',
  'joinBattleTooltip': 'Unirse a la batalla \'{name}\'',
  'joinBattleConfirm': '¿Seguro que quieres unirte a la batalla \'{name}\'?',
  'joinBattleSuccess': 'Te has unido a la batalla \'{name}\' con éxito',
  'joinBattleErrorSelf': 'No puedes unirte a tu propio frente',
  'replayBattlefront': 'Repetir frente',
  'replayBattlefrontTooltip': 'Repetir el frente \'{name}\'',
  'getReplayBattlefrontConfirm': '¿Seguro que quieres repetir \'{name}\'?',
  'getReplayBattlefrontFailed': 'No se pudo repetir \'{name}\': {error}',
  'download': 'Descargar',
  'downloadBattlefront': 'Descargar frente',
  'downloadBattlefrontTooltip': 'Descargar el frente \'{name}\'',
  'getDownloadBattlefrontConfirm': '¿Seguro que quieres descargar \'{name}\'?',
  'getDownloadBattlefrontSuccess': '\'{name}\' descargado con éxito',
  'downloadMyOwnBattlefrontError': 'Solo puedes descargar tus propios frentes',
  'getDownloadBattlefrontFailed': 'No se pudo descargar \'{name}\': {error}',
  'continueGameShort': 'Continuar batalla',
  'replayShort': 'Repetir',
  'highestLevel': 'Nivel {level}',
  'deviceNickname': 'Dispositivo',
  'createdTime': 'Hora de creación',
  'remoteBattlefrontDetail': 'Detalles del frente remoto',
  'levelList': 'Lista de niveles',
  'fastClearTimeParam': 'Tiempo completado: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint': 'Selecciona un frente local para ver detalles',
  'loadingRemoteDetail': 'Cargando detalles del frente remoto...',
  'noRemoteBattlefrontSelected': 'Ningún frente remoto seleccionado',
  'failedToLoadRemoteDetail': 'No se pudo cargar los detalles',
  'fastestRecord': 'Completado más rápido',
  'safestRecord': 'Completado más seguro',
  'fastestRecordDesc': 'Más rápido (menos tiempo)',
  'safestRecordDesc': 'Más seguro (menos acciones)',
  'creator': 'Creador',
  'player': 'Jugador',
  // Branch maps
  'getBranchMapCount': '{count} copias',
  'collapse': 'Contraer',
  'expand': 'Expandir',
  // Quit battlefront
  'quitBattlefront': 'Abandonar frente',
  'quitBattlefrontTooltip': 'Abandonar el frente remoto',
  'quitBattlefrontTitle': 'Abandonar frente',
  'quitBattlefrontContent':
      '¿Seguro que quieres abandonar el frente \'{name}\'? Tu progreso local se eliminará.',
  // Game introduction
  'gameIntroduction':
      '1. «Principiante» empieza con 15 minas, hasta un máximo de 99;\n2. «Nuevo frente» empieza con 81 minas, aumenta cada nivel, sin límite superior.\n3. Con conexión, los frentes completados se comparten automáticamente en la nube para otros jugadores.',
};
