// Estonian（爱沙尼亚语）
/// Eesti keele stringid DMine rakenduse jaoks
const Map<String, String> stringsEt = {
  'appLabel': 'Parim miinidekaitse',
  'appTitle': 'DMine - Parim miinidekaitse',
  'settings': 'Seaded',
  'gameSettings': 'Mänguseaded',
  'showTimer': 'Kuva taimer',
  'showTimerDesc': 'Kuva mängu taimer mängu liideses',
  'showActionCounter': 'Kuva tegevuste loendur',
  'showActionCounterDesc': 'Kuva tegevuste arv mängu liideses',
  'autoAdjustBoardWidth': 'Automaatselt kohandada laua laiust',
  'autoAdjustBoardWidthDesc':
      'Automaatselt kohandada laua laiust ekraani suuruse järgi',
  'resetToDefaults': 'Taastada vaikeväärtused',
  'resetToDefaultsDesc': 'Taastada kõik seaded vaikeväärtustele',
  'aboutDMine': 'DMine kohta',
  'version': 'Versioon',
  'close': 'Sulge',
  'manualBoardWidth': 'Käsitsi määrata laua laius',
  'currentWidth': 'Praegune',
  'range': 'Vahemik',
  'widthSliderHint':
      'Vihje: Saab vaadata laua laiuse muutusi reaalajas libistamisega',
  'gameRecords': 'Mängurekordid',
  'selectMapToViewRecords': 'Vali kaart, et näha rekorde',
  'totalRecords': 'Kokku',
  'gameRecordsTitle': 'Mängurekordide loend',
  'pleaseSelectMapFirst': 'Vali esmalt kaart',
  'noGameRecords': 'Mängurekordeid pole',
  'miningMethodFlag': 'Pane lipp',
  'miningMethodBlind': 'Pime otsing',
  'statusPlaying': '▶️ Mängimas...',
  'statusWin': '🎉 Võit',
  'statusLose': '💥 Kaotus',
  'actionsCount': 'Tegevuste arv',
  'miningMethod': 'Miinide otsimise meetod',
  'duration': 'Kestus',
  'seconds': 'sekundit',
  'startTime': 'Algusaeg',
  'endTime': 'Lõpuaeg',
  'pauseTime': 'Pausaeg',
  'unlock': 'Võta lukust',
  'lock': 'Lukusta',
  'delete': 'Kustuta',
  'languageSetting': 'Keele seade',
  'currentLanguage': 'Praegune',
  'systemLanguage': 'Süsteemikeel',
  'chinese': 'Hiina keel',
  'english': 'Inglise keel',
  'language': 'Keel',
  // Home page
  'newbie': 'Algaja',
  'gameIntro': 'Mängu tutvustus',
  'newBattle': 'Uus rida',
  'continueChallenge': 'Jätka väljakutset',
  'error': 'Viga',
  'initializationFailed': 'Initsialiseerimine ebaõnnestus',
  // Game page
  'congratulations': 'Palju õnne, olete taseme läbinud!',
  'gameOver': 'Mäng läbi',
  'timeUsed': 'Kulunud aeg',
  'actionCount': 'Tegevuste arv',
  'mineCount': 'Miinide arv',
  'nextLevel': 'Järgmine tase: Tase {level}',
  'newbieNextLevel': 'Järgmine tase: Algaja {level}',
  'nextLevelMines': 'Miinide arv',
  'mineIncrease': 'Suurendus',
  'newbieFinish': 'Algajaõpetus lõpetatud',
  'ok': 'OK',
  'continueNextLevel': 'Jätka järgmisesse taseme',
  'restart': 'Taaskäivita',
  'level': 'Tase {level}',
  'newbieLevel': 'Algaja tase {level}',
  'operationFailed': 'Tegevus ebaõnnestus',
  // Game status texts
  'returnHome': 'Tagasi avalehele',
  'revealMode': 'Avastamise režiim',
  'flagMode': 'Lippude režiim',
  'newMap': 'Uus kaart (miinide arv ei muutu, loo uus kaart)',
  'resetMap': 'Lae kaart uuesti (sama kaart, taasta olek)',
  'zoomOut': 'Vähenda suurt',
  'zoomIn': 'Suurenda suurt',
  'resetZoom': 'Taasta originaalsuurus',
  'previousStep': 'Eelmine samm',
  'pause': 'Paus',
  'play': 'Mängi',
  'nextStep': 'Järgmine samm',
  'clickToStart': 'Klõpsa suvalisele laualele, et alustada mängu',
  'playing': 'Mängimas...',
  'gameWin': 'Palju õnne, olete taseme läbinud!',
  'gameLose': 'Mäng läbi, astusite miini',
  'gamePaused': 'Mäng pausil',
  'ready': 'Valmis',
  'clickStartShort': 'Klõpsa alustamiseks',
  'playingShort': 'Mängimas',
  'winShort': 'Läbitud!',
  'loseShort': 'Asti miini',
  'pausedShort': 'Pausil',
  // Counter strings
  'currentLevel': 'Praegune tase',
  'remainingMines': 'Jäänud miinid',
  'gameTime': 'Mänguaeg (sekundit)',
  'operationCount': 'Tegevuste arv',
  'previousLevel': 'Eelmine tase',
  'nextLevelShort': 'Järgmine tase',
  // Battlefront strings
  'completed': 'Lõpetatud',
  'inProgress': 'Toimub',
  'continueGame': 'Jätka mängu',
  'replay': 'Mängi uuesti',
  'creater': 'Ülempealik',
  'created': 'Võitluse algusaeg',
  'updated': 'Uuendatud',
  // Dialog strings
  'confirm': 'Kinnita',
  'cancel': 'Tühista',
  'yes': 'Jah',
  'no': 'Ei',
  'save': 'Salvesta',
  'edit': 'Muuda',
  'levelFormat': 'Tase {level}',
  'newbieLevelFormat': 'Algaja tase {level}',
  'totalLevel': '{level}/{totalLevel} taset',
  'totalLevelTooltip': 'Praegune: Tase {level} / Kokku {totalLevel} taset',
  // Battlefront UI strings
  'noBattlefronts': 'Ridu pole',
  'battlefrontCount': '{count} rida',
  'levelPrefix': 'TS{level}',
  'newbieLevelPrefix': 'ALG{level}',
  'minesCount': '{count} miini',
  'notStarted': 'Pole alustatud',
  'victory': 'Võit',
  'defeat': 'Kaotus',
  'gameDurationParam': 'Kestus: {seconds} sekundit',
  'actionsCountParam': 'Tegevused: {count} korda',
  'actionsCountShort': '{count} korda',
  'miningMethodParam': 'Meetod: {method}',
  'startTimeParam': 'Algusaeg: {time}',
  'endTimeParam': 'Lõpuaeg: {time}',
  'returnButton': 'Tagasi',
  'battlefrontDetails': 'Rida detailid',
  'clickToEditName': 'Klõpsa nime muutmiseks',
  'clickToAddDescription': 'Klõpsa kirjelduse lisamiseks...',
  'noDescription': 'Kirjeldus puudub',
  // Level record strings
  'levelCount': '{count} taset',
  'noLevelRecords': 'Vali rida',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Kustuta rida',
  'deleteBattlefrontContent':
      'Kas olete kindel, et soovite kustutada rea "{name}"? See tegevus on tagasivõimatu.',
  'battlefrontLockedCannotDelete': 'Rida on lukustatud, ei saa kustutada',
  'unknownNavigationLevel': 'Tundmatu navigeerimise tase',
  'noBattlefrontSelected': 'Rida pole valitud',
  'noBattlefrontToContinue': 'Ei leitud jätkamiseks rida',
  'synced': 'Sünkroniseeritud',
  'notSynced': 'Pole sünkroniseeritud',
  'newbieBattlefrontName': 'Algaja rida {number}',
  'battlefrontName': 'Rida {number}',
  'nickname': 'Hüüdnimi',
  'nicknameSetting': 'Hüüdnime seade',
  'nicknameDesc': 'Määra oma hüüdnimi',
  'enterNickname': 'Sisesta hüüdnimi',
  'nicknameSaved': 'Hüüdnimi salvestatud',
  'nicknameUpdated': 'Hüüdnimi uuendatud',
  'nicknameRequired': 'Hüüdnimi on kohustuslik',
  'nicknameTooLong': 'Hüüdnimi ei tohi olla rohkem kui 30 tähemärki',
  // Level top strings
  'levelTopCount': 'Edetabel ({count})',
  'levelTopCountShort': 'Edetabel ({count})',
  'retry': 'Proovi uuesti',
  'noLevelTopData': 'Andmed puuduvad',
  'remoteBattlefront': 'Kaugrida',
  'participated': 'Osalenud',
  'notParticipated': 'Pole osalenud',
  'loadMore': 'Laadi rohkem',

  'joinBattle': 'Liitu võitlusega',
  'joinBattleTooltip': 'Liitu võitlusega "{name}"',
  'joinBattleConfirm':
      'Kas olete kindel, et soovite liituda võitlusega "{name}"?',
  'joinBattleSuccess': 'Olete edukalt liitunud võitlusega "{name}"',
  'joinBattleErrorSelf': 'Ei saa liituda enda loodud reaga',

  'replayBattlefront': 'Mängi rida uuesti',
  'replayBattlefrontTooltip': 'Mängi rida "{name}" uuesti',
  'getReplayBattlefrontConfirm':
      'Kas olete kindel, et soovite mängida "{name}" uuesti?',
  'getReplayBattlefrontFailed':
      'Rea "{name}" uuesti mängimine ebaõnnestus: {error}',

  'download': 'Laadi alla',
  'downloadBattlefront': 'Laadi rida alla',
  'downloadBattlefrontTooltip': 'Laadi rida "{name}" alla',
  'getDownloadBattlefrontConfirm':
      'Kas olete kindel, et soovite alla laadida "{name}"?',
  'getDownloadBattlefrontSuccess': 'Rida "{name}" edukalt alla laaditud',
  'downloadMyOwnBattlefrontError': 'Saate alla laadida ainult enda loodud ridu',
  'getDownloadBattlefrontFailed':
      'Rea "{name}" allalaadimine ebaõnnestus: {error}',

  'continueGameShort': 'Jätka võitlust',
  'replayShort': 'Uuesti mängi',
  'highestLevel': 'Tase {level}',
  'deviceNickname': 'Seade',
  'createdTime': 'Loomise aeg',
  'remoteBattlefrontDetail': 'Kaugrea detailid',
  'levelList': 'Tasemete loend',
  'fastClearTimeParam': 'Läbimise aeg: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Vali kohalik rida, et näha detaile',
  'loadingRemoteDetail': 'Laen kaugrea detaile...',
  'noRemoteBattlefrontSelected': 'Kaugrida pole valitud',
  'failedToLoadRemoteDetail': 'Kaugrea detailide laadimine ebaõnnestus',
  'fastestRecord': 'Kiireim läbimine',
  'safestRecord': 'Kindlaim läbimine',
  'fastestRecordDesc': 'Kiireim läbimine (vähem aega)',
  'safestRecordDesc': 'Kindlaim läbimine (vähem tegevusi)',
  'creator': 'Looja',
  'player': 'Mängija',
  // 分支地图字符串
  'getBranchMapCount': '{count} koopiat',
  'collapse': 'Ahenda',
  'expand': 'Laienda',
  // 退出战线
  'quitBattlefront': 'Lahku reast',
  'quitBattlefrontTooltip': 'Lahku kaugreast',
  'quitBattlefrontTitle': 'Lahku reast',
  'quitBattlefrontContent':
      'Kas olete kindel, et soovite lahkuda reast "{name}"? Teie kohalik edasiminek kustutatakse.',
  // 游戏介绍
  'gameIntroduction':
      '1. "Algaja" algab 15 miiniga, võib ulatuda kuni 99 miinini;\n2. "Uus rida" algab 81 miiniga, iga tase lisab miine, ülemise piirita.\n3. Internetiühenduse korral jagatakse "läbitud" ridud automaatselt pilves teiste õppimiseks.',
};
