// Welsh（威尔士语）
/// Welsh (Cymraeg) language strings for the DMine application
const Map<String, String> stringsCy = {
  'appLabel': 'Y Mwynwr Uchel',
  'appTitle': 'DMine - Y Mwynwr Uchel',
  'settings': 'Gosodiadau',
  'gameSettings': 'Gosodiadau\'r Gêm',
  'showTimer': 'Dangos yr amserydd',
  'showTimerDesc': 'Dangos amserydd y gêm ar y sgrin',
  'showActionCounter': 'Dangos cyfrif y gweithredoedd',
  'showActionCounterDesc': 'Dangos nifer y gweithredoedd ar sgrin y gêm',
  'autoAdjustBoardWidth': 'Addasu lled y bwrdd yn awtomatig',
  'autoAdjustBoardWidthDesc':
      'Addasu lled y bwrdd yn awtomatagol yn ôl maint y sgrin',
  'resetToDefaults': 'Ailosod i\'r gosodiadau diofyn',
  'resetToDefaultsDesc': 'Ailosod pob gosodiad i\'r gwerthoedd diofyn',
  'aboutDMine': 'Ynghylch DMine',
  'version': 'Fersiwn',
  'close': 'Cau',
  'manualBoardWidth': 'Gosod lled y bwrdd â llaw',
  'currentWidth': 'Cyfredol',
  'range': 'Ystod',
  'widthSliderHint':
      'Awgrym: wrth llyncu\'r llithwr, gwelwch newid lled y bwrdd ar unwaith',
  'gameRecords': 'Cofnodion y gêm',
  'selectMapToViewRecords': 'Dewiswch fap i weld y cofnodion',
  'totalRecords': 'Cyfanswm',
  'gameRecordsTitle': 'Rhestr cofnodion y gêm',
  'pleaseSelectMapFirst': 'Dewiswch fap yn gyntaf',
  'noGameRecords': 'Dim cofnodion gêm',
  'miningMethodFlag': 'Marcio â baner',
  'miningMethodBlind': 'Chwilio\'n ddall',
  'statusPlaying': '▶️ Yn chwarae...',
  'statusWin': '🎉 Ennill',
  'statusLose': '💥 Colli',
  'actionsCount': 'Nifer y gweithredoedd',
  'miningMethod': 'Ffordd chwarae',
  'duration': 'Hyd',
  'seconds': 'eiliadau',
  'startTime': 'Amser dechreu',
  'endTime': 'Amser gorffen',
  'pauseTime': 'Amser oedi',
  'unlock': 'Datgloi',
  'lock': 'Cloi',
  'delete': 'Dileu',
  'languageSetting': 'Gosod iaith',
  'currentLanguage': 'Cyfredol',
  'systemLanguage': 'Iaith y system',
  'chinese': 'Tsieineg',
  'english': 'Saesneg',
  'language': 'Iaith',
  // Home page
  'newbie': 'Dechreuwr',
  'gameIntro': 'Disgrifiad gêm',
  'newBattle': 'Rymfil newydd',
  'continueChallenge': 'Parhau â\'r her',
  'error': 'Gwall',
  'initializationFailed': 'Methodd y gychwyn',
  // Game page
  'congratulations': 'Llongyfarchiadau, rydych wedi gorffen y lefel!',
  'gameOver': 'Gêm drosedd',
  'timeUsed': 'Amser a ddefnyddiwyd',
  'actionCount': 'Gweithredoedd',
  'mineCount': 'Mwynau',
  'nextLevel': 'Y lefel nesaf: Lefel {level}',
  'newbieNextLevel': 'Y lefel nesaf: Dechreuwr {level}',
  'nextLevelMines': 'Mwynau',
  'mineIncrease': 'Cynyddu',
  'newbieFinish': 'Modd dechreuwr wedi gorffen',
  'ok': 'Iawn',
  'continueNextLevel': 'Parhau i\'r lefel nesaf',
  'restart': 'Dechrau eto',
  'level': 'Lefel {level}',
  'newbieLevel': 'Dechreuwr {level}',
  'operationFailed': 'Methodd y weithred',
  // Game status texts
  'returnHome': 'Nôl i\'r cartref',
  'revealMode': 'Modd datgelu',
  'flagMode': 'Modd baner',
  'newMap': 'Map newydd (yr un nifer o fwynau, llun newydd)',
  'resetMap': 'Ailosod y map (yr un llun, ailosod y statws)',
  'zoomOut': 'Lleihau',
  'zoomIn': 'Chwyddo',
  'resetZoom': 'Ailosod y chwyddiad',
  'previousStep': 'Y cam blaenorol',
  'pause': 'Oedi',
  'play': 'Chwarae',
  'nextStep': 'Y cam nesaf',
  'clickToStart': 'Cliciwch ar unrhyw sgwâr i gychwyn y gêm',
  'playing': 'Yn chwarae...',
  'gameWin': 'Llongyfarchiadau, rydych wedi gorffen y lefel!',
  'gameLose': 'Gêm drosedd, rydych wedi taro ar fwyn',
  'gamePaused': 'Gêm wedi oedi',
  'ready': 'Barod i gychwyn',
  'clickStartShort': 'Cliciwch i gychwyn',
  'playingShort': 'Yn chwarae',
  'winShort': 'Wedi gorffen!',
  'loseShort': 'Colli',
  'pausedShort': 'Wedi oedi',
  // Counter strings
  'currentLevel': 'Y lefel cyfredol',
  'remainingMines': 'Mwynau sy\'n weddill',
  'gameTime': 'Amser y gêm (eiliadau)',
  'operationCount': 'Nifer y gweithredoedd',
  'previousLevel': 'Y lefel blaenorol',
  'nextLevelShort': 'Y lefel nesaf',
  // Battlefront strings
  'completed': 'Wedi gorffen',
  'inProgress': 'Yn mynd rhagddo',
  'continueGame': 'Parhau â\'r gêm',
  'replay': 'Chwarae eto',
  'creater': 'Llywydd',
  'created': 'Amser creu',
  'updated': 'Diweddarwyd',
  // Dialog strings
  'confirm': 'Cadarnhau',
  'cancel': 'Diddymu',
  'yes': 'Iawn',
  'no': 'Na',
  'save': 'Cadw',
  'edit': 'Golygu',
  'levelFormat': 'Lefel {level}',
  'newbieLevelFormat': 'Dechreuwr {level}',
  'totalLevel': '{level}/{totalLevel} lefel',
  'totalLevelTooltip': 'Cyfredol: Lefel {level} / Cyfanswm {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Dim rymfil',
  'battlefrontCount': '{count} o rymfil',
  'levelPrefix': 'LL{level}',
  'newbieLevelPrefix': 'Dechreuwr LL{level}',
  'minesCount': '{count} o fwyn',
  'notStarted': 'Heb gychwyn',
  'victory': 'Ennill',
  'defeat': 'Colli',
  'gameDurationParam': 'Hyd: {seconds}e',
  'actionsCountParam': 'Gweithredoedd: {count} gwaith',
  'actionsCountParamShort': '{count} gwaith',
  'miningMethodParam': 'Ffordd: {method}',
  'startTimeParam': 'Dechreu: {time}',
  'endTimeParam': 'Gorffen: {time}',
  'returnButton': 'Nôl',
  'battlefrontDetails': 'Manylion y rymfil',
  'clickToEditName': 'Cliciwch i olygu\'r enw',
  'clickToAddDescription': 'Cliciwch i ychwanegu disgrifiad...',
  'noDescription': 'Dim disgrifiad',
  // Level record strings
  'levelCount': '{count} lefel',
  'noLevelRecords': 'Dewiswch rymfil',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Dileu\'r rymfil',
  'deleteBattlefrontContent':
      'Ydych chi\'n siŵr eisiau dileu\'r rymfil \'{name}\'? Ni ellir dadwneud y weithred hon.',
  'battlefrontLockedCannotDelete':
      'Mae\'r rymfil wedi clo’i, ni ellir ei ddileu',
  'unknownNavigationLevel': 'Lefel anhysbys',
  'noBattlefrontSelected': 'Dim rymfil wedi ei ddewis',
  'noBattlefrontToContinue': 'Dim rymfil i barhau ag ef',
  'synced': 'Wedi ei gysoni',
  'notSynced': 'Heb ei gysoni',
  'newbieBattlefrontName': 'Rymfil dechreuwr {number}',
  'battlefrontName': 'Rymfil {number}',
  'nickname': 'Llysenw',
  'nicknameSetting': 'Gosod llysenw',
  'nicknameDesc': 'Gosodwch eich llysenw',
  'enterNickname': 'Rhowch eich llysenw',
  'nicknameSaved': 'Llysenw wedi ei gadw',
  'nicknameUpdated': 'Llysenw wedi ei ddiweddaru',
  'nicknameRequired': 'Mae llysenw yn ofynnol',
  'nicknameTooLong': 'Ni all y llysenw fod yn hirach na 30 nod',
  // Level top strings
  'levelTopCount': 'Rhestr Uchel ({count})',
  'levelTopCountShort': 'Uchel ({count})',
  'retry': 'Trechu eto',
  'noLevelTopData': 'Dim data',
  'remoteBattlefront': 'Rymfil pell',
  'participated': 'Wes gynnal',
  'notParticipated': 'Heb gynnal',
  'loadMore': 'Llwytho mwy',
  'joinBattle': 'Ymunu â\'r rymfil',
  'joinBattleTooltip': 'Ymunu â\'r rymfil \'{name}\'',
  'joinBattleConfirm': 'Ydych chi\'n siŵr eisiau ymunu â\'r rymfil \'{name}\'?',
  'joinBattleSuccess': 'Wedi ymunu â\'r rymfil \'{name}\' yn llwyddiannus',
  'joinBattleErrorSelf': 'Ni allwch ymunu â\'ch rymfil eich hun',
  'replayBattlefront': 'Chwarae\'r rymfil eto',
  'replayBattlefrontTooltip': 'Chwarae\'r rymfil \'{name}\' eto',
  'getReplayBattlefrontConfirm':
      'Ydych chi\'n siŵr eisiau chwarae \'{name}\' eto?',
  'getReplayBattlefrontFailed': 'Methodd ailchwarae \'{name}\': {error}',
  'download': 'Llwytho i lawr',
  'downloadBattlefront': 'Llwytho\'r rymfil i lawr',
  'downloadBattlefrontTooltip': 'Llwytho\'r rymfil \'{name}\' i lawr',
  'getDownloadBattlefrontConfirm':
      'Ydych chi\'n siŵr eisiau llwytho \'{name}\' i lawr?',
  'getDownloadBattlefrontSuccess':
      '\'{name}\' wedi ei lwytho i lawr yn llwyddiannus',
  'downloadMyOwnBattlefrontError':
      'Dim ond eich rymfiliau eich hun y gallwch eu llwytho i lawr',
  'getDownloadBattlefrontFailed': 'Methodd llwytho \'{name}\' i lawr: {error}',
  'continueGameShort': 'Parhau â\'r rymfil',
  'replayShort': 'Ailchwarae',
  'highestLevel': 'Lefel {level}',
  'deviceNickname': 'Dyfais',
  'createdTime': 'Amser creu',
  'remoteBattlefrontDetail': 'Manylion y rymfil pell',
  'levelList': 'Rhestr lefelau',
  'fastClearTimeParam': 'Amser gorffen: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint': 'Dewiswch rymfil lleol i weld y manylion',
  'loadingRemoteDetail': 'Llwytho manylion y rymfil pell...',
  'noRemoteBattlefrontSelected': 'Dim rymfil pell wedi ei ddewis',
  'failedToLoadRemoteDetail': 'Methodd llwytho\'r manylion',
  'fastestRecord': 'Gorffen cyflymaf',
  'safestRecord': 'Gorffen ddiogelaf',
  'fastestRecordDesc': 'Cyflymaf (lleiaf o amser)',
  'safestRecordDesc': 'Ddiogelaf (lleiaf o weithredoedd)',
  'creator': 'Creuwr',
  'player': 'Chwaraewr',
  // Branch maps
  'getBranchMapCount': '{count} o gopïau',
  'collapse': 'Crynhoi',
  'expand': 'Ehangu',
  // Quit battlefront
  'quitBattlefront': 'Gadael y rymfil',
  'quitBattlefrontTooltip': 'Gadael y rymfil pell',
  'quitBattlefrontTitle': 'Gadael y rymfil',
  'quitBattlefrontContent':
      'Ydych chi\'n siŵr eisiau gadael y rymfil \'{name}\'? Bydd eich cynnydd lleol yn cael ei ddileu.',
  // Game introduction
  'gameIntroduction':
      '1. Mae "Dechreuwr" yn dechreu gyda 15 o fwynau, hyd at 99 o fwynau;\n2. Mae "Rymfil Newydd" yn dechreu gyda 81 o fwynau, mae\'r nifer yn cynyddu pob lefel, dim terfyn uwch.\n3. Ar-lein, mae rymfiliau a glenwyd yn cael eu rhannu yn y cwmni ar eu cefn i eraill i ddysgu.',
};
