/// English language strings for the DMine application
const Map<String, String> stringsEn = {
  'appLabel': 'DMine',
  'appTitle': 'DMine',
  'settings': 'Settings',
  'gameSettings': 'Settings',
  'showTimer': 'Show Timer',
  'showTimerDesc': 'Display game timer on game interface',
  'showActionCounter': 'Show Action Counter',
  'showActionCounterDesc': 'Display action count statistics on game interface',
  'autoAdjustBoardWidth': 'Auto Adjust Board Width',
  'autoAdjustBoardWidthDesc':
      'Automatically adjust board width based on screen size',
  'resetToDefaults': 'Reset to Default Settings',
  'resetToDefaultsDesc': 'Restore all settings to default values',
  'aboutDMine': 'About DMine',
  'version': 'Version',
  'close': 'Close',
  'manualBoardWidth': 'Manual Board Width',
  'currentWidth': 'Current',
  'range': 'Range',
  'widthSliderHint':
      'Tip: You can preview board width changes while dragging the slider',
  'gameRecords': 'Game Records',
  'selectMapToViewRecords': 'Please select a map to view records',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Game Records List',
  'pleaseSelectMapFirst': 'Please select a map first',
  'noGameRecords': 'No game records',
  'miningMethodFlag': 'Flag',
  'miningMethodBlind': 'Blind',
  'statusPlaying': '▶️ Playing...',
  'statusWin': '🎉 Victory',
  'statusLose': '💥 Failure',
  'actionsCount': 'Actions',
  'miningMethod': 'Method',
  'duration': 'Duration',
  'seconds': 's',
  'startTime': 'Start Time',
  'endTime': 'End Time',
  'pauseTime': 'Pause Time',
  'unlock': 'Unlock',
  'lock': 'Lock',
  'delete': 'Delete',
  'languageSetting': 'Language Setting',
  'currentLanguage': 'Current',
  'systemLanguage': 'System Language',
  'chinese': 'Chinese',
  'english': 'English',
  'language': 'Language',
  // Home page
  'newbie': 'Newbie',
  'newBattle': 'New Battle',
  'continueChallenge': 'Continue',
  'error': 'Error',
  'initializationFailed': 'Initialization failed',
  // Game page
  'congratulations': 'Congratulations!',
  'gameOver': 'Game Over',
  'timeUsed': 'Time',
  'actionCount': 'Actions',
  'mineCount': 'Mines',
  'nextLevel': 'Next: Level {level}',
  'newbieNextLevel': 'Next: Newbie Level {level}',
  'nextLevelMines': 'Mines',
  'mineIncrease': 'Increase',
  'newbieFinish': 'Newbie completed',
  'ok': 'OK',
  'continueNextLevel': 'Next Level',
  'restart': 'Restart',
  'level': 'Level {level}',
  'newbieLevel': 'Newbie Level {level}',
  'operationFailed': 'Operation failed',
  // Game status texts
  'returnHome': 'Return Home',
  'revealMode': 'Reveal Mode',
  'flagMode': 'Flag Mode',
  'newMap': 'New Map (same mines)',
  'resetMap': 'Reload Map (same map, reset game state)',
  'zoomOut': 'Zoom Out',
  'zoomIn': 'Zoom In',
  'resetZoom': 'Reset Zoom',
  'previousStep': 'Previous Step',
  'pause': 'Pause',
  'play': 'Play',
  'nextStep': 'Next Step',
  'clickToStart': 'Click any cell to start game',
  'playing': 'Playing...',
  'gameWin': 'Congratulations!',
  'gameLose': 'Game Over, stepped on a mine',
  'gamePaused': 'Game Paused',
  'ready': 'Ready to Start',
  'clickStartShort': 'Click Start',
  'playingShort': 'Playing',
  'winShort': 'Win!',
  'loseShort': 'Failure',
  'pausedShort': 'Paused',
  // Counter strings
  'currentLevel': 'Current Level',
  'remainingMines': 'Remaining Mines',
  'gameTime': 'Duration (seconds)',
  'operationCount': 'Actions',
  'previousLevel': 'Previous Level',
  'nextLevelShort': 'Next Level',
  // Battlefront strings
  'completed': 'Completed',
  'inProgress': 'In Progress',
  'continueGame': 'Continue Game',
  'replay': 'Replay',
  'creater': 'Commander',
  'created': 'Attack Time',
  'updated': 'Updated',
  // Battlefront UI strings
  'noBattlefronts': 'No battlefronts',
  'battlefrontCount': '{count} battlefront(s)',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'Newbie LV{level}',
  'minesCount': '{count} mines',
  'notStarted': 'Not started',
  'victory': 'Victory',
  'defeat': 'Defeat',
  'gameDurationParam': 'Duration: {seconds}s',
  'actionsCountParam': 'Actions: {count}',
  'actionsCountParamShort': '{count}',
  'miningMethodParam': 'Method: {method}',
  'startTimeParam': 'Start time: {time}',
  'endTimeParam': 'End time: {time}',
  'returnButton': 'Return',
  'battlefrontDetails': 'Battlefront Details',
  'clickToEditName': 'Click to edit name',
  'clickToAddDescription': 'Click to add description...',
  'noDescription': 'No description',
  // Dialog strings
  'confirm': 'Confirm',
  'cancel': 'Cancel',
  'yes': 'Yes',
  'no': 'No',
  'save': 'Save',
  'edit': 'Edit',
  'levelFormat': 'Level {level}',
  'newbieLevelFormat': 'Newbie Level {level}',
  'totalLevel': 'Level {level}/{totalLevel}',
  'totalLevelTooltip': 'Current Level: {level} / Total Levels: {totalLevel}',
  // Level record strings
  'levelCount': '{count} levels',
  'noLevelRecords': 'No level records',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Delete Battlefront',
  'deleteBattlefrontContent':
      'Are you sure you want to delete battlefront "{name}"? This action cannot be undone.',
  'battlefrontLockedCannotDelete':
      'Battlefront is locked and cannot be deleted',
  'unknownNavigationLevel': 'Unknown navigation level',
  'noBattlefrontSelected': 'No battlefront selected',
  'noBattlefrontToContinue': 'No battlefront found to continue',
  'synced': 'Synced',
  'notSynced': 'Not synced',
  'newbieBattlefrontName': 'Newbie Battlefront {number}',
  'battlefrontName': 'Battlefront {number}',
  'nickname': 'Nickname',
  'nicknameSetting': 'Nickname Setting',
  'nicknameDesc': 'Set your nickname',
  'enterNickname': 'Enter nickname',
  'nicknameSaved': 'Nickname saved',
  'nicknameUpdated': 'Nickname updated successfully',
  'nicknameRequired': 'Nickname is required',
  'nicknameTooLong': 'Nickname cannot exceed 30 characters',
  // Top ranking
  'levelTopCount': 'Top Ranking ({count})',
  'levelTopCountShort': 'Top ({count})',
  'retry': 'Retry',
  'noLevelTopData': 'No data',
  'remoteBattlefront': 'Remote Battlefront',
  'participated': 'Participated',
  'notParticipated': 'Not Participated',
  'loadMore': 'Load More',

  'joinBattle': 'Join Battle',
  'joinBattleTooltip': 'Join battle "{name}"',
  'joinBattleConfirm': 'Are you sure you want to join battle "{name}"?',
  'joinBattleSuccess': 'Successfully joined battle "{name}"',
  'joinBattleErrorSelf': 'Cannot join battle "{name}" created by yourself',

  'replayBattlefront': 'Replay Battlefront',
  'replayBattlefrontTooltip': 'Replay battlefront "{name}"',
  'getReplayBattlefrontConfirm': 'Are you sure you want to replay "{name}"?',
  'getReplayBattlefrontFailed': 'Failed to replay "{name}": {error}',

  'downloadBattlefront': 'Download',
  'downloadBattlefrontTooltip': 'Download "{name}"',
  'getDownloadBattlefrontConfirm':
      'Are you sure you want to download "{name}"?',
  'download': 'Download',
  'getDownloadBattlefrontSuccess': 'Successfully downloaded "{name}"',
  'downloadMyOwnBattlefrontError': 'Can only download your own battlefront',
  'getDownloadBattlefrontFailed': 'Failed to download "{name}": {error}',

  'continueGameShort': 'Continue',
  'replayShort': 'Replay',
  'highestLevel': 'Level {level}',
  'deviceNickname': 'Device Nickname',
  'createdTime': 'Created Time',
  'remoteBattlefrontDetail': 'Battlefront Detail',
  'levelList': 'Level List',
  'fastClearTimeParam': 'Fast clear: {time}',
  // Remote battlefront detail strings
  'selectLocalBattlefrontHint': 'Please select a battlefront to view details',
  'loadingRemoteDetail': 'Loading battlefront details...',
  'noRemoteBattlefrontSelected': 'No battlefront selected',
  'failedToLoadRemoteDetail': 'Failed to load battlefront details',
  'fastestRecord': 'Fastest',
  'safestRecord': 'Safest',
  'fastestRecordDesc': 'Fastest (shortest time)',
  'safestRecordDesc': 'Safest (fewest actions)',
  'creator': 'Creator',
  'player': 'Player',
  // Branch map strings
  'getBranchMapCount': '{count} branch',
  'collapse': 'Collapse',
  'expand': 'Expand',
  // Quit battlefront
  'quitBattlefront': 'Quit Battlefront',
  'quitBattlefrontTooltip': 'Quit remote battlefront',
  'quitBattlefrontTitle': 'Quit Battlefront',
  'quitBattlefrontContent':
      'Are you sure you want to quit battlefront "{name}"? Your local progress will be deleted.',

  // Download page
  'downloadClient': 'Download Client',
  'browser': 'Browser',
  'browserDesc': 'Play directly in browser, no download needed',
  'windowsDesc': 'For Windows 10 and above',
  'linuxDesc': 'For Linux operating system',
  'macosDesc': 'For macOS 10.15 and above',
  'android': 'Android',
  'androidDesc': 'For Android 8.0 and above',
  'iosDesc': 'For iOS 14.0 and above',
  'ohos': 'OHOS',
  'ohosDesc': 'For HarmonyOS operating system',
  'linkAddress': 'Link Address',
  'downloadLink': 'Download Link',
  'qrCode': 'QR Code',
  'scanToDownload': 'Scan with phone to download',
  'copy': 'Copy',
  'copiedToClipboard': 'Copied to clipboard',
  'openLink': 'Open link',
  'cannotOpenLink': 'Cannot open link',
  // Auto-update
  'updateAvailableTitle': 'Update Available',
  'forceUpdateTitle': 'Update Required',
  'currentVersion': 'Current Version',
  'latestVersionText': 'Latest Version',
  'updateLog': 'Changelog',
  'remindLater': 'Remind Me Later',
  'skipThisVersion': 'Skip This Version',
  'exitApp': 'Exit App',
  'updateNow': 'Update Now',
  // Game introduction
  'gameIntroduction':
      '1. "Newbie" starts with 15 mines, up to 99 mines.\n2. "New Battlefront" starts with 81 mines, each level increases mine count, no upper limit.\n3. In online mode, completed battlefronts are automatically shared to the cloud for others to learn.',
};
