// Hebrew（希伯来语）
/// מחרוזות בעברית עבור אפליקציית DMine
const Map<String, String> stringsIw = {
  'appLabel': 'מוצא מוקשים מעולה',
  'appTitle': 'DMine - מוצא מוקשים מעולה',
  'settings': 'הגדרות',
  'gameSettings': 'הגדרות משחק',
  'showTimer': 'הצג טיימר',
  'showTimerDesc': 'הצג את טיימר המשחק בממשק המשתמש',
  'showActionCounter': 'הצג מונה פעולות',
  'showActionCounterDesc': 'הצג את מספר הפעולות בממשק המשחק',
  'autoAdjustBoardWidth': 'התאם אוטומטית את רוחב הלוח',
  'autoAdjustBoardWidthDesc': 'התאם אוטומטית רוחב הלוח לפי גודל המסך',
  'resetToDefaults': 'אפס להגדרות ברירת מחדל',
  'resetToDefaultsDesc': 'אפס את כל ההגדרות לערכים המקוריים',
  'aboutDMine': 'אודות DMine',
  'version': 'גרסה',
  'close': 'סגור',
  'manualBoardWidth': 'קבע ידנית רוחב הלוח',
  'currentWidth': 'נוכחי',
  'range': 'טווח',
  'widthSliderHint':
      'טיפ: תוכל לראות שינויים ברוחב הלוח בזמן אמת בזמן שגורר את המחוון',
  'gameRecords': 'שיאי משחק',
  'selectMapToViewRecords': 'בחר מפה כדי להציג שיאים',
  'totalRecords': 'סך הכל',
  'gameRecordsTitle': 'רשימת שיאי משחק',
  'pleaseSelectMapFirst': 'ראשית בחר מפה',
  'noGameRecords': 'אין שיאי משחק',
  'miningMethodFlag': 'הצב דגל',
  'miningMethodBlind': 'חיפוש עיוור',
  'statusPlaying': '▶️ במשחק...',
  'statusWin': '🎉 ניצחון',
  'statusLose': '💥 הפסד',
  'actionsCount': 'מספר פעולות',
  'miningMethod': 'שיטת חיפוש מוקשים',
  'duration': 'משך זמן',
  'seconds': 'שניות',
  'startTime': 'שעת התחלה',
  'endTime': 'שעת סיום',
  'pauseTime': 'זמן השהייה',
  'unlock': 'בטל נעילה',
  'lock': 'נעל',
  'delete': 'מחק',
  'languageSetting': 'הגדרת שפה',
  'currentLanguage': 'נוכחי',
  'systemLanguage': 'שפת מערכת',
  'chinese': 'סינית',
  'english': 'אנגלית',
  'language': 'שפה',
  // Home page
  'newbie': 'מתחיל',
  'newBattle': 'חזית חדשה',
  'continueChallenge': 'המשך אתגר',
  'error': 'שגיאה',
  'initializationFailed': 'אתחול נכשל',
  // Game page
  'congratulations': 'מזל טוב, עברת את השלב!',
  'gameOver': 'סוף המשחק',
  'timeUsed': 'זמן שנוצל',
  'actionCount': 'מספר פעולות',
  'mineCount': 'מספר מוקשים',
  'nextLevel': 'שלב הבא: שלב {level}',
  'newbieNextLevel': 'שלב הבא: מתחיל {level}',
  'nextLevelMines': 'מספר מוקשים',
  'mineIncrease': 'הגדלה',
  'newbieFinish': 'הדרכת מתחילים הסתיימה',
  'ok': 'אישור',
  'continueNextLevel': 'המשך לשלב הבא',
  'restart': 'הפעל מחדש',
  'level': 'שלב {level}',
  'newbieLevel': 'שלב מתחיל {level}',
  'operationFailed': 'פעולה נכשלה',
  // Game status texts
  'returnHome': 'חזרה לדף הבית',
  'revealMode': 'מצב חשיפה',
  'flagMode': 'מצב דגלים',
  'newMap': 'מפה חדשה (אותו מספר מוקשים, יצירת מפה חדשה)',
  'resetMap': 'טען מחדש את המפה (אותה מפה, אפס מצב)',
  'zoomOut': 'הקטן',
  'zoomIn': 'הגדל',
  'resetZoom': 'אפס זום',
  'previousStep': 'צעד קודם',
  'pause': 'השהה',
  'play': 'שחק',
  'nextStep': 'צעד הבא',
  'clickToStart': 'לחץ על כל משבצת כדי להתחיל את המשחק',
  'playing': 'במשחק...',
  'gameWin': 'מזל טוב, עברת את השלב!',
  'gameLose': 'סוף המשחק, פגעת במוקש',
  'gamePaused': 'המשחק מושהה',
  'ready': 'מוכן',
  'clickStartShort': 'לחץ כדי להתחיל',
  'playingShort': 'במשחק',
  'winShort': 'הסתיים!',
  'loseShort': 'פגיעה במוקש',
  'pausedShort': 'מושהה',
  // Counter strings
  'currentLevel': 'שלב נוכחי',
  'remainingMines': 'מוקשים שנותרו',
  'gameTime': 'זמן משחק (שניות)',
  'operationCount': 'מספר פעולות',
  'previousLevel': 'שלב קודם',
  'nextLevelShort': 'שלב הבא',
  // Battlefront strings
  'completed': 'הושלם',
  'inProgress': 'בתהליך',
  'continueGame': 'המשך משחק',
  'replay': 'שחק שוב',
  'creater': 'מפקד',
  'created': 'שעת תחילת הקרב',
  'updated': 'עודכן',
  // Dialog strings
  'confirm': 'אישור',
  'cancel': 'ביטול',
  'yes': 'כן',
  'no': 'לא',
  'save': 'שמור',
  'edit': 'ערוך',
  'levelFormat': 'שלב {level}',
  'newbieLevelFormat': 'שלב מתחיל {level}',
  'totalLevel': '{level}/{totalLevel} שלבים',
  'totalLevelTooltip': 'נוכחי: שלב {level} / סך הכל {totalLevel} שלבים',
  // Battlefront UI strings
  'noBattlefronts': 'אין חזיתות',
  'battlefrontCount': '{count} חזיתות',
  'levelPrefix': 'שׁ{level}',
  'newbiePrefix': 'מ״ת{level}',
  'minesCount': '{count} מוקשים',
  'notStarted': 'לא התחיל',
  'victory': 'ניצחון',
  'defeat': 'הפסד',
  'gameDurationParam': 'משך זמן: {seconds} שניות',
  'actionsCountParam': 'פעולות: {count} פעמים',
  'actionsCountParamShort': '{count} פעמים',
  'miningMethodParam': 'שיטה: {method}',
  'startTimeParam': 'שעת התחלה: {time}',
  'endTimeParam': 'שעת סיום: {time}',
  'returnButton': 'חזור',
  'battlefrontDetails': 'פרטי חזית',
  'clickToEditName': 'לחץ כדי לשנות שם',
  'clickToAddDescription': 'לחץ כדי להוסיף תיאור...',
  'noDescription': 'אין תיאור',
  // Level record strings
  'levelCount': '{count} שלבים',
  'noLevelRecords': 'בחר חזית',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'מחק חזית',
  'deleteBattlefrontContent':
      'האם אתה בטוח שברצונך למחוק את החזית "{name}"? פעולה זו בלתי הפיכה.',
  'battlefrontLockedCannotDelete': 'החזית נעולה, לא ניתן למחוק',
  'unknownNavigationLevel': 'שלב ניווט לא ידוע',
  'noBattlefrontSelected': 'לא נבחרה חזית',
  'noBattlefrontToContinue': 'אין חזית להמשך',
  'synced': 'סונכרן',
  'notSynced': 'לא סונכרן',
  'newbieBattlefrontName': 'חזית מתחילים {number}',
  'battlefrontName': 'חזית {number}',
  'nickname': 'כינוי',
  'nicknameSetting': 'הגדרת כינוי',
  'nicknameDesc': 'קבע את הכינוי שלך',
  'enterNickname': 'הזן כינוי',
  'nicknameSaved': 'הכינוי נשמר',
  'nicknameUpdated': 'הכינוי עודכן',
  'nicknameRequired': 'נדרש כינוי',
  'nicknameTooLong': 'הכינוי לא יכול לעבור 30 תווים',
  // Level top strings
  'levelTopCount': 'דירוג ({count})',
  'levelTopCountShort': 'דירוג ({count})',
  'retry': 'נסה שוב',
  'noLevelTopData': 'אין נתונים',
  'remoteBattlefront': 'חזית מרוחקת',
  'participated': 'השתתף',
  'notParticipated': 'לא השתתף',
  'loadMore': 'טען עוד',

  'joinBattle': 'הצטרף לקרב',
  'joinBattleTooltip': 'הצטרף לקרב "{name}"',
  'joinBattleConfirm': 'האם אתה בטוח שברצונך להצטרף לקרב "{name}"?',
  'joinBattleSuccess': 'הצטרפת בהצלחה לקרב "{name}"',
  'joinBattleErrorSelf': 'אינך יכול להצטרף לחזית שלך',

  'replayBattlefront': 'שחק חזית שוב',
  'replayBattlefrontTooltip': 'שחק את החזית "{name}" שוב',
  'getReplayBattlefrontConfirm': 'האם אתה בטוח שברצונך לשחק את "{name}" שוב?',
  'getReplayBattlefrontFailed': 'ניסיון לשחק שוב את "{name}" נכשל: {error}',

  'download': 'הורד',
  'downloadBattlefront': 'הורד חזית',
  'downloadBattlefrontTooltip': 'הורד את החזית "{name}"',
  'getDownloadBattlefrontConfirm': 'האם אתה בטוח שברצונך להוריד את "{name}"?',
  'getDownloadBattlefrontSuccess': 'החזית "{name}" הורדה בהצלחה',
  'downloadMyOwnBattlefrontError': 'ניתן להוריד רק חזיתות משלך',
  'getDownloadBattlefrontFailed': 'הורדת "{name}" נכשלה: {error}',

  'continueGameShort': 'המשך הקרב',
  'replayShort': 'שחק שוב',
  'highestLevel': 'שלב {level}',
  'deviceNickname': 'מכשיר',
  'createdTime': 'שעת יצירה',
  'remoteBattlefrontDetail': 'פרטי חזית מרוחקת',
  'levelList': 'רשימת שלבים',
  'fastClearTimeParam': 'זמן סיום מהיר: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'בחר חזית מקומית כדי להציג פרטים',
  'loadingRemoteDetail': 'טוען פרטי חזית מרוחקת...',
  'noRemoteBattlefrontSelected': 'לא נבחרה חזית מרוחקת',
  'failedToLoadRemoteDetail': 'טעינת פרטים מרוחקים נכשלה',
  'fastestRecord': 'סיום המהיר ביותר',
  'safestRecord': 'סיום הבטוח ביותר',
  'fastestRecordDesc': 'סיום המהיר ביותר (פחות זמן)',
  'safestRecordDesc': 'סיום הבטוח ביותר (פחות פעולות)',
  'creator': 'יוצר',
  'player': 'שחקן',
  // 分支地图字符串
  'getBranchMapCount': '{count} עותקים',
  'collapse': 'כווץ',
  'expand': 'הרחב',
  // 退出战线
  'quitBattlefront': 'עזוב חזית',
  'quitBattlefrontTooltip': 'עזוב חזית מרוחקת',
  'quitBattlefrontTitle': 'עזוב חזית',
  'quitBattlefrontContent':
      'האם אתה בטוח שברצונך לעזוב את החזית "{name}"? ההתקדמות המקומית שלך תימחק.',

  // 下载页面
  'downloadClient': 'הורד לקוח',
  'browser': 'דפדפן',
  'browserDesc': 'שחק ישירות בדפדפן, ללא הורדה',
  'windowsDesc': 'עבור Windows 10 וגירסאות חדשות יותר',
  'macosDesc': 'עבור macOS 10.15 וגירסאות חדשות יותר',
  'android': 'אנדרואיד',
  'androidDesc': 'עבור אנדרואיד 8.0 וגירסאות חדשות יותר',
  'iosDesc': 'עבור iOS 14.0 וגירסאות חדשות יותר',
  'linkAddress': 'כתובת קישור',
  'downloadLink': 'קישור להורדה',
  'qrCode': 'קוד QR',
  'scanToDownload': 'סרוק בטלפון כדי להוריד',
  'copy': 'העתק',
  'copiedToClipboard': 'הועתק ללוח העריכה',
  'openLink': 'פתח קישור',
  'cannotOpenLink': 'לא ניתן לפתוח את הקישור',
  // 游戏介绍
  'gameIntroduction':
      '1. "מתחיל" מתחיל עם 15 מוקשים, יכול להגיע עד 99 מוקשים;\n2. "חזית חדשה" מתחילה עם 81 מוקשים, כל שלב מוסיף מוקשים ללא גבול עליון.\n3. עם חיבור לאינטרנט, חזיתות "מושלמות" משותפות אוטומטית בענן לאחרים ללמוד מהן.',
};
