// Hungarian（匈牙利语）
/// Magyar szövegek a DMine alkalmazáshoz
const Map<String, String> stringsHu = {
  'appLabel': 'Prémium aknavetés',
  'appTitle': 'DMine - Prémium aknavetés',
  'settings': 'Beállítások',
  'gameSettings': 'Játékbeállítások',
  'showTimer': 'Időző megjelenítése',
  'showTimerDesc': 'A játék időzőjének megjelenítése az interfészen',
  'showActionCounter': 'Művelet számláló megjelenítése',
  'showActionCounterDesc':
      'A műveletek számának megjelenítése a játékfelületen',
  'autoAdjustBoardWidth': 'A tábla szélességének automatikus igazítása',
  'autoAdjustBoardWidthDesc':
      'A tábla szélességének automatikus igazítása a képernyő méretéhez',
  'resetToDefaults': 'Alapértelmezettek visszaállítása',
  'resetToDefaultsDesc':
      'Minden beállítás visszaállítása az alapértelmezett értékekre',
  'aboutDMine': 'A DMine-ról',
  'version': 'Verzió',
  'close': 'Bezárás',
  'manualBoardWidth': 'Tábla szélességének manuális beállítása',
  'currentWidth': 'Aktuális',
  'range': 'Tartomány',
  'widthSliderHint':
      'Tipp: Értesítheted a tábla szélességének változásait valós időben a csúszka húzásával',
  'gameRecords': 'Játék eredmények',
  'selectMapToViewRecords':
      'Válassz egy térképet az eredmények megtekintéséhez',
  'totalRecords': 'Összesen',
  'gameRecordsTitle': 'Játék eredmények listája',
  'pleaseSelectMapFirst': 'Először válassz egy térképet',
  'noGameRecords': 'Nincs játék eredmény',
  'miningMethodFlag': 'Zászló elhelyezése',
  'miningMethodBlind': 'Vak keresés',
  'statusPlaying': '▶️ Játék folyamatban...',
  'statusWin': '🎉 Győzelem',
  'statusLose': '💥 Vereség',
  'actionsCount': 'Műveletek száma',
  'miningMethod': 'Aknakeresési módszer',
  'duration': 'Időtartam',
  'seconds': 'másodperc',
  'startTime': 'Kezdés időpontja',
  'endTime': 'Befejezés időpontja',
  'pauseTime': 'Szünet idő',
  'unlock': 'Feloldás',
  'lock': 'Zárolás',
  'delete': 'Törlés',
  'languageSetting': 'Nyelv beállítása',
  'currentLanguage': 'Aktuális',
  'systemLanguage': 'Rendszer nyelv',
  'chinese': 'Kínai',
  'english': 'Angol',
  'language': 'Nyelv',
  // Home page
  'newbie': 'Kezdő',
  'gameIntro': 'Játék bemutatása',
  'newBattle': 'Új front',
  'continueChallenge': 'Kihívás folytatása',
  'error': 'Hiba',
  'initializationFailed': 'Az inicializáció sikertelen',
  // Game page
  'congratulations': 'Gratulálok, teljesítetted a szintet!',
  'gameOver': 'Játék vége',
  'timeUsed': 'Felhasznált idő',
  'actionCount': 'Műveletek száma',
  'mineCount': 'Aknák száma',
  'nextLevel': 'Következő szint: {level}. szint',
  'newbieNextLevel': 'Következő szint: Kezdő {level}',
  'nextLevelMines': 'Aknák száma',
  'mineIncrease': 'Növelés',
  'newbieFinish': 'Kezdő bemutató teljesítve',
  'ok': 'OK',
  'continueNextLevel': 'Tovább a következő szintre',
  'restart': 'Újraindítás',
  'level': '{level}. szint',
  'newbieLevel': 'Kezdő szint {level}',
  'operationFailed': 'A művelet sikertelen',
  // Game status texts
  'returnHome': 'Vissza a főoldalra',
  'revealMode': 'Felfedési mód',
  'flagMode': 'Zászló mód',
  'newMap': 'Új térkép (ugyanannyi akna, új térkép generálása)',
  'resetMap': 'Térkép újratöltése (ugyanaz a térkép, állapot visszaállítása)',
  'zoomOut': 'Kicsinyítés',
  'zoomIn': 'Nagyítás',
  'resetZoom': 'Zoom visszaállítása',
  'previousStep': 'Előző lépés',
  'pause': 'Szünet',
  'play': 'Játék',
  'nextStep': 'Következő lépés',
  'clickToStart': 'Kattints bármely mezőre a játék indításához',
  'playing': 'Játék folyamatban...',
  'gameWin': 'Gratulálok, teljesítetted a szintet!',
  'gameLose': 'Játék vége, aknázt ütköztél',
  'gamePaused': 'Játék szünetel',
  'ready': 'Kész',
  'clickStartShort': 'Kattints az indításhoz',
  'playingShort': 'Folyamatban',
  'winShort': 'Teljesítve!',
  'loseShort': 'Aknát találtál',
  'pausedShort': 'Szünetel',
  // Counter strings
  'currentLevel': 'Aktuális szint',
  'remainingMines': 'Hátralévő aknák',
  'gameTime': 'Játékidő (másodperc)',
  'operationCount': 'Műveletek száma',
  'previousLevel': 'Előző szint',
  'nextLevelShort': 'Következő szint',
  // Battlefront strings
  'completed': 'Teljesítve',
  'inProgress': 'Folyamatban',
  'continueGame': 'Játék folytatása',
  'replay': 'Újrajáték',
  'creater': 'Parancsnok',
  'created': 'Csata kezdete',
  'updated': 'Frissítve',
  // Dialog strings
  'confirm': 'Megerősítés',
  'cancel': 'Mégse',
  'yes': 'Igen',
  'no': 'Nem',
  'save': 'Mentés',
  'edit': 'Szerkesztés',
  'levelFormat': '{level}. szint',
  'newbieLevelFormat': 'Kezdő szint {level}',
  'totalLevel': '{level}/{totalLevel} szint',
  'totalLevelTooltip': 'Aktuális: {level}. szint / Összesen {totalLevel} szint',
  // Battlefront UI strings
  'noBattlefronts': 'Nincs front',
  'battlefrontCount': '{count} front',
  'levelPrefix': 'SZ{level}',
  'newbieLevelPrefix': 'KE{level}',
  'minesCount': '{count} akna',
  'notStarted': 'Nem indult',
  'victory': 'Győzelem',
  'defeat': 'Vereség',
  'gameDurationParam': 'Időtartam: {seconds} másodperc',
  'actionsCountParam': 'Műveletek: {count} alkalommal',
  'actionsCountParamShort': '{count} alkalommal',
  'miningMethodParam': 'Módszer: {method}',
  'startTimeParam': 'Kezdés: {time}',
  'endTimeParam': 'Befejezés: {time}',
  'returnButton': 'Vissza',
  'battlefrontDetails': 'Front részletei',
  'clickToEditName': 'Kattints a név módosításához',
  'clickToAddDescription': 'Kattints a leírás hozzáadásához...',
  'noDescription': 'Nincs leírás',
  // Level record strings
  'levelCount': '{count} szint',
  'noLevelRecords': 'Válassz egy frontot',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Front törlése',
  'deleteBattlefrontContent':
      'Biztosan törölni szeretnéd a(z) "{name}" frontot? Ez a művelet nem visszavonható.',
  'battlefrontLockedCannotDelete': 'A front zárolva van, nem törölhető',
  'unknownNavigationLevel': 'Ismeretlen navigációs szint',
  'noBattlefrontSelected': 'Nincs front kiválasztva',
  'noBattlefrontToContinue': 'Nincs folytatható front',
  'synced': 'Szinkronizálva',
  'notSynced': 'Nincs szinkronizálva',
  'newbieBattlefrontName': 'Kezdő front {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Becenév',
  'nicknameSetting': 'Becenév beállítása',
  'nicknameDesc': 'Állítsd be a beceneved',
  'enterNickname': 'Írd be a becenevet',
  'nicknameSaved': 'Becenév elmentve',
  'nicknameUpdated': 'Becenév frissítve',
  'nicknameRequired': 'Becenév kötelező',
  'nicknameTooLong': 'A becenév nem lehet hosszabb 30 karakternél',
  // Level top strings
  'levelTopCount': 'Rangsor ({count})',
  'levelTopCountShort': 'Rangsor ({count})',
  'retry': 'Újra próbálkozás',
  'noLevelTopData': 'Nincs adat',
  'remoteBattlefront': 'Távoli front',
  'participated': 'Rész vett',
  'notParticipated': 'Nem vett részt',
  'loadMore': 'Több betöltése',

  'joinBattle': 'Csatlakozás a csatához',
  'joinBattleTooltip': 'Csatlakozás a(z) "{name}" csatához',
  'joinBattleConfirm': 'Biztosan csatlakozni szeretnél a(z) "{name}" csatához?',
  'joinBattleSuccess': 'Sikeresen csatlakozottál a(z) "{name}" csatához',
  'joinBattleErrorSelf': 'Nem csatlakozhatsz a saját frontodhoz',

  'replayBattlefront': 'Front újrajátéka',
  'replayBattlefrontTooltip': 'A(z) "{name}" front újrajátéka',
  'getReplayBattlefrontConfirm':
      'Biztosan újra szeretnéd játszani a(z) "{name}" frontot?',
  'getReplayBattlefrontFailed':
      'A(z) "{name}" front újrajátéka sikertelen: {error}',

  'download': 'Letöltés',
  'downloadBattlefront': 'Front letöltése',
  'downloadBattlefrontTooltip': 'A(z) "{name}" front letöltése',
  'getDownloadBattlefrontConfirm':
      'Biztosan letölteni szeretnéd a(z) "{name}" frontot?',
  'getDownloadBattlefrontSuccess': 'A(z) "{name}" front sikeresen letöltve',
  'downloadMyOwnBattlefrontError': 'Csak a saját frontjaidat töltheted le',
  'getDownloadBattlefrontFailed':
      'A(z) "{name}" front letöltése sikertelen: {error}',

  'continueGameShort': 'Csata folytatása',
  'replayShort': 'Újrajáték',
  'highestLevel': '{level}. szint',
  'deviceNickname': 'Eszköz',
  'createdTime': 'Létrehozás ideje',
  'remoteBattlefrontDetail': 'Távoli front részletei',
  'levelList': 'Szint lista',
  'fastClearTimeParam': 'Teljesítési idő: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Válassz egy helyi frontot a részletek megtekintéséhez',
  'loadingRemoteDetail': 'Távoli front részleteinek betöltése...',
  'noRemoteBattlefrontSelected': 'Nincs távoli front kiválasztva',
  'failedToLoadRemoteDetail': 'A távoli részletek betöltése sikertelen',
  'fastestRecord': 'Leggyorsabb teljesítés',
  'safestRecord': 'Legbiztonságosabb teljesítés',
  'fastestRecordDesc': 'Leggyorsabb teljesítés (kevesebb idő)',
  'safestRecordDesc': 'Legbiztonságosabb teljesítés (kevesebb művelet)',
  'creator': 'Készítő',
  'player': 'Játékos',
  // 分支地图字符串
  'getBranchMapCount': '{count} másolat',
  'collapse': 'Összecsukás',
  'expand': 'Kibontás',
  // 退出战线
  'quitBattlefront': 'Front elhagyása',
  'quitBattlefrontTooltip': 'Távoli front elhagyása',
  'quitBattlefrontTitle': 'Front elhagyása',
  'quitBattlefrontContent':
      'Biztosan elhagyod a(z) "{name}" frontot? A helyi előrehaladásod törlésre kerül.',

  // 下载页面
  'downloadClient': 'Kliens letöltése',
  'browser': 'Böngésző',
  'browserDesc': 'Játék közvetlenül a böngészőben, letöltés nélkül',
  'windowsDesc': 'Windows 10 és újabb verziókhoz',
  'macosDesc': 'macOS 10.15 és újabb verziókhoz',
  'android': 'Android',
  'androidDesc': 'Android 8.0 és újabb verziókhoz',
  'iosDesc': 'iOS 14.0 és újabb verziókhoz',
  'linkAddress': 'Hivatkozás címe',
  'downloadLink': 'Letöltési hivatkozás',
  'qrCode': 'QR kód',
  'scanToDownload': 'Olvasd be a telefontól a letöltéshez',
  'copy': 'Másolás',
  'copiedToClipboard': 'Vágólapra másolva',
  'openLink': 'Hivatkozás megnyitása',
  'cannotOpenLink': 'A hivatkozás nem nyitható meg',
  // 游戏介绍
  'gameIntroduction':
      '1. A „Kezdő” 15 aknával kezdődik, és akár 99 aknáig nyúlhat.\n2. Az „Új front” 81 aknával kezdődik, minden szint további aknákat ad, felső korlát nélkül.\n3. Internetkapcsolat esetén a „teljesített” frontok automatikusan megosztódnak a felhőben mások számára.',
};
