/// Bulgarian（保加利亚语）
/// Български езикови низове за приложението DMine
const Map<String, String> stringsBg = {
  'appTitle': 'DMine - Елитен миноловач',
  'settings': 'Настройки',
  'gameSettings': 'Игрови настройки',
  'showTimer': 'Показвай таймер',
  'showTimerDesc': 'Показвай таймера на играта в интерфейса',
  'showActionCounter': 'Показвай брояч на действия',
  'showActionCounterDesc': 'Показвай броя на действията в интерфейса',
  'autoAdjustBoardWidth': 'Автоматично подстрой ширина на дъската',
  'autoAdjustBoardWidthDesc':
      'Автоматично подстрой ширината на дъската според размера на екрана',
  'resetToDefaults': 'Възстанови стандартни настройки',
  'resetToDefaultsDesc': 'Възстанови всички настройки по подразбиране',
  'aboutDMine': 'За DMine',
  'version': 'Версия',
  'close': 'Затвори',
  'manualBoardWidth': 'Ръчно задаване на ширина на дъската',
  'currentWidth': 'Текущо',
  'range': 'Диапазон',
  'widthSliderHint':
      'Съвет: Можете да прегледате промените в реално време чрез плъзгача',
  'gameRecords': 'Игрови записи',
  'selectMapToViewRecords': 'Изберете карта за преглед на записите',
  'totalRecords': 'Общо',
  'gameRecordsTitle': 'Списък на игровите записи',
  'pleaseSelectMapFirst': 'Първо изберете карта',
  'noGameRecords': 'Няма игрови записи',
  'miningMethodFlag': 'Постави знаме',
  'miningMethodBlind': 'Слепa търсене',
  'statusPlaying': '▶️ В ход...',
  'statusWin': '🎉 Победа',
  'statusLose': '💥 Загуба',
  'actionsCount': 'Брой действия',
  'miningMethod': 'Метод на миноловане',
  'duration': 'Времетраене',
  'seconds': 'секунди',
  'startTime': 'Начално време',
  'endTime': 'Крайно време',
  'pauseTime': 'Време на пауза',
  'unlock': 'Отключи',
  'lock': 'Заключи',
  'delete': 'Изтрий',
  'languageSetting': 'Настройка на езика',
  'currentLanguage': 'Текущ',
  'systemLanguage': 'Системен език',
  'chinese': 'Китайски',
  'english': 'Английски',
  'language': 'Език',
  // Home page
  'newbie': 'Начинаещи',
  'newBattle': 'Нов фронт',
  'continueChallenge': 'Продължи предизвикателството',
  'error': 'Грешка',
  'initializationFailed': 'Инициализацията не успя',
  // Game page
  'congratulations': 'Поздравления, преминахте ниво!',
  'gameOver': 'Край на играта',
  'timeUsed': 'Използвано време',
  'actionCount': 'Брой действия',
  'mineCount': 'Брой мини',
  'nextLevel': 'Следващо ниво: Ниво {level}',
  'newbieNextLevel': 'Следващо ниво: Ниво за начинаещи {level}',
  'nextLevelMines': 'Брой мини',
  'mineIncrease': 'Увеличение',
  'newbieFinish': 'Обучението за начинаещи завършено',
  'ok': 'ОК',
  'continueNextLevel': 'Продължи към следващото ниво',
  'restart': 'Рестартирай',
  'level': 'Ниво {level}',
  'newbieLevel': 'Ниво за начинаещи {level}',
  'operationFailed': 'Операцията не успя',
  // Game status texts
  'returnHome': 'Върни се в началото',
  'revealMode': 'Режим на разкриване',
  'flagMode': 'Режим на знамена',
  'newMap': 'Нова карта (брой мини не се променя, генерирай нова карта)',
  'resetMap': 'Презареди карта (карта не се променя, нулирай състояние)',
  'zoomOut': 'Намали',
  'zoomIn': 'Увеличи',
  'resetZoom': 'Възстанови оригиналния мащаб',
  'previousStep': 'Предишна стъпка',
  'pause': 'Пауза',
  'play': 'Пусни',
  'nextStep': 'Следваща стъпка',
  'clickToStart': 'Кликнете върху всяко поле за начало на играта',
  'playing': 'Игра в ход...',
  'gameWin': 'Поздравления, преминахте ниво!',
  'gameLose': 'Край на играта, натъкнахте на мина',
  'gamePaused': 'Играта е на пауза',
  'ready': 'Готово',
  'clickStartShort': 'Кликни за старт',
  'playingShort': 'В ход',
  'winShort': 'Преминахте!',
  'loseShort': 'Натъкнахте на мина',
  'pausedShort': 'Пауза',
  // Counter strings
  'currentLevel': 'Текущо ниво',
  'remainingMines': 'Оставащи мини',
  'gameTime': 'Игрово време (секунди)',
  'operationCount': 'Брой действия',
  'previousLevel': 'Предишно ниво',
  'nextLevelShort': 'Следващо ниво',
  // Battlefront strings
  'completed': 'Завършено',
  'inProgress': 'В процес',
  'continueGame': 'Продължи играта',
  'replay': 'Повтори',
  'creater': 'Главен командир',
  'created': 'Време на началото на битката',
  'updated': 'Актуализирано',
  // Dialog strings
  'confirm': 'Потвърди',
  'cancel': 'Откажи',
  'yes': 'Да',
  'no': 'Не',
  'save': 'Запази',
  'edit': 'Редактирай',
  'levelFormat': 'Ниво {level}',
  'newbieLevelFormat': 'Ниво за начинаещи {level}',
  'totalLevel': '{level}/{totalLevel} нива',
  'totalLevelTooltip': 'Текущо: Ниво {level} / Общо {totalLevel} нива',
  // Battlefront UI strings
  'noBattlefronts': 'Няма фронтове',
  'battlefrontCount': '{count} фронта',
  'levelPrefix': 'НВ{level}',
  'newbieLevelPrefix': 'НВ за начинаещи {level}',
  'minesCount': '{count} мини',
  'notStarted': 'Не започнато',
  'victory': 'Победа',
  'defeat': 'Загуба',
  'gameDurationParam': 'Времетраене: {seconds} секунди',
  'actionsCountParam': 'Действия: {count} пъти',
  'actionsCountParamShort': '{count} пъти',
  'miningMethodParam': 'Метод: {method}',
  'startTimeParam': 'Начално време: {time}',
  'endTimeParam': 'Крайно време: {time}',
  'returnButton': 'Назад',
  'battlefrontDetails': 'Детайли за фронта',
  'clickToEditName': 'Кликни за промяна на името',
  'clickToAddDescription': 'Кликни за добавяне на описание...',
  'noDescription': 'Няма описание',
  // Level record strings
  'levelCount': '{count} нива',
  'noLevelRecords': 'Изберете фронт',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Изтрий фронт',
  'deleteBattlefrontContent':
      'Сигурни ли сте, че искате да изтриете фронта "{name}"? Тази операция е необратима.',
  'battlefrontLockedCannotDelete': 'Фронтът е заключен, не може да бъде изтрит',
  'unknownNavigationLevel': 'Неизвестно ниво за навигация',
  'noBattlefrontSelected': 'Няма избран фронт',
  'noBattlefrontToContinue': 'Няма намерен фронт за продължаване',
  'synced': 'Синхронизирано',
  'notSynced': 'Не синхронизирано',
  'newbieBattlefrontName': 'Фронт за начинаещи {number}',
  'battlefrontName': 'Фронт {number}',
  'nickname': 'Псевдоним',
  'nicknameSetting': 'Настройка на псевдонима',
  'nicknameDesc': 'Задайте своя псевдоним',
  'enterNickname': 'Въведете псевдоним',
  'nicknameSaved': 'Псевдонимът е запазен',
  'nicknameUpdated': 'Псевдонимът е актуализиран',
  'nicknameRequired': 'Псевдонимът е задължителен',
  'nicknameTooLong': 'Псевдонимът не може да надвишава 30 символа',
  // Level top strings
  'levelTopCount': 'Класация ({count})',
  'levelTopCountShort': 'Класация ({count})',
  'retry': 'Опитай отново',
  'noLevelTopData': 'Няма данни',
  'remoteBattlefront': 'Отдалечен фронт',
  'participated': 'Участвано',
  'notParticipated': 'Не участвано',
  'loadMore': 'Зареди още',

  'joinBattle': 'Присъедини се към битката',
  'joinBattleTooltip': 'Присъедини се към битката "{name}"',
  'joinBattleConfirm':
      'Сигурни ли сте, че искате да се присъедините към битката "{name}"?',
  'joinBattleSuccess': 'Успешно се присъединихте към битката "{name}"',
  'joinBattleErrorSelf': 'Не можете да се присъедините към собствен си фронт',

  'replayBattlefront': 'Повтори фронта',
  'replayBattlefrontTooltip': 'Повтори фронта "{name}"',
  'getReplayBattlefrontConfirm':
      'Сигурни ли сте, че искате да повторите "{name}"?',
  'getReplayBattlefrontFailed': 'Повторението на "{name}" не успя: {error}',

  'download': 'Свали',
  'downloadBattlefront': 'Свали фронт',
  'downloadBattlefrontTooltip': 'Свали фронта "{name}"',
  'getDownloadBattlefrontConfirm':
      'Сигурни ли сте, че искате да свалите "{name}"?',
  'getDownloadBattlefrontSuccess': 'Фронтът "{name}" е успешно свален',
  'downloadMyOwnBattlefrontError': 'Можете да сваляте само собствени фронтове',
  'getDownloadBattlefrontFailed': 'Свалянето на "{name}" не успя: {error}',

  'continueGameShort': 'Продължи битката',
  'replayShort': 'Повтори',
  'highestLevel': 'Ниво {level}',
  'deviceNickname': 'Устройство',
  'createdTime': 'Време на създаване',
  'remoteBattlefrontDetail': 'Детайли за отдалечения фронт',
  'levelList': 'Списък на нивата',
  'fastClearTimeParam': 'Време за преминаване: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Изберете локален фронт за преглед на детайлите',
  'loadingRemoteDetail': 'Зареждане на детайли за отдалечения фронт...',
  'noRemoteBattlefrontSelected': 'Няма избран отдалечен фронт',
  'failedToLoadRemoteDetail': 'Неуспешно зареждане на детайли',
  'fastestRecord': 'Най-бързо преминаване',
  'safestRecord': 'Най-сигурно преминаване',
  'fastestRecordDesc': 'Най-бързо преминаване (най-малко време)',
  'safestRecordDesc': 'Най-сигурно преминаване (най-малко действия)',
  'creator': 'Създател',
  'player': 'Играч',
  // 分支地图字符串
  'getBranchMapCount': '{count} копия',
  'collapse': 'Свиши',
  'expand': 'Разшири',
  // 退出战线
  'quitBattlefront': 'Напусни фронта',
  'quitBattlefrontTooltip': 'Напусни отдалечения фронт',
  'quitBattlefrontTitle': 'Напусни фронта',
  'quitBattlefrontContent':
      'Сигурни ли сте, че искате да напуснете фронта "{name}"? Вашият локален прогрес ще бъде изтрит.',

  // 下载页面
  'downloadClient': 'Свали клиент',
  'browser': 'Браузър',
  'browserDesc': 'Играйте директно в браузъра, без сваляне',
  'windowsDesc': 'За Windows 10 и по-нови',
  'macosDesc': 'За macOS 10.15 и по-нови',
  'android': 'Android',
  'androidDesc': 'За Android 8.0 и по-нови',
  'iosDesc': 'За iOS 14.0 и по-нови',
  'linkAddress': 'Адрес на връзката',
  'downloadLink': 'Връзка за сваляне',
  'qrCode': 'QR код',
  'scanToDownload': 'Сканирайте с телефона за сваляне',
  'copy': 'Копирай',
  'copiedToClipboard': 'Копирано в клипборда',
  'openLink': 'Отвори връзка',
  'cannotOpenLink': 'Не може да отвори връзката',
  // 游戏介绍
  'gameIntroduction':
      '1. „Начинаещи“ започва с 15 мини, може да достигне до 99 мини;\n2. „Нов фронт“ започва с 81 мини, на всяко ниво се добавят мини, без горна граница.\n3. При интернет връзка „преминатите“ фронтове се споделят автоматично в облака за учене на други.',
};
