// Tatar（鞑靼语）
/// Tatar language strings for the DMine application
const Map<String, String> stringsTt = {
  'appLabel': 'Югалары Минер',
  'appTitle': 'DMine - Югалары Минер',
  'settings': 'Көйләмләр',
  'gameSettings': 'Уйын көйләмләре',
  'showTimer': 'Вакыт кальсарын күрсәтү',
  'showTimerDesc': 'Уйын экранында уйын вакыты кальсарын күрсәтергә',
  'showActionCounter': 'Хәрәкәт санын күрсәтү',
  'showActionCounterDesc': 'Уйын экранында хәрәкәтләр санын күрсәтергә',
  'autoAdjustBoardWidth': 'Таваның киңлеген автоматик түзәтү',
  'autoAdjustBoardWidthDesc':
      'Экран көлеме буйынса таваның киңлеген автоматик түзәтү',
  'resetToDefaults': 'Киләчлек көйләмләргә кайту',
  'resetToDefaultsDesc': 'Барлык көйләмнәрне киләчлек дәрәҗәләргә кайтарга',
  'aboutDMine': 'DMine турында',
  'version': 'Версия',
  'close': 'Ябырга',
  'manualBoardWidth': 'Таваның киңлеген куллы түзәтү',
  'currentWidth': 'Хәзерге',
  'range': 'Чигәрләре',
  'widthSliderHint':
      'Килеш: Аңлаткычты йөзгәндә, таваның киңлеге үзгәреше үзгәртеп корылга',
  'gameRecords': 'Уйын язмалары',
  'selectMapToViewRecords': 'Язмаларны карау өчен картаны сайлагыз',
  'totalRecords': 'Һәммәсе',
  'gameRecordsTitle': 'Уйын язмалары исемлеге',
  'pleaseSelectMapFirst': 'Моннан артык картаны сайлагыз',
  'noGameRecords': 'Уйын язмасы юк',
  'miningMethodFlag': 'Байрак билгеләү',
  'miningMethodBlind': 'Күзсез чаралау',
  'statusPlaying': '▶️ Һәммен...',
  'statusWin': '🎉 Җиңү',
  'statusLose': '💥 Йөкләү',
  'actionsCount': 'Хәрәкәтләр саны',
  'miningMethod': 'Уйын уену ысулы',
  'duration': 'Вакыт узунлыгы',
  'seconds': 'сәгендә',
  'startTime': 'Башлау вакыты',
  'endTime': 'Аяклау вакыты',
  'pauseTime': 'Вакытны токтату',
  'unlock': 'Ачырга',
  'lock': 'Болгаруга',
  'delete': 'Бетергә',
  'languageSetting': 'Тел көйләме',
  'currentLanguage': 'Хәзерге',
  'systemLanguage': 'Система теле',
  'chinese': 'Чыну',
  'english': 'Англис',
  'language': 'Тел',
  // Home page
  'newbie': 'Яңа уенчы',
  'newBattle': 'Яңа фронт',
  'continueChallenge': 'Чәленешне дәвам итәргә',
  'error': 'Хата',
  'initializationFailed': 'Башлау сәтсиз булды',
  // Game page
  'congratulations': 'Котлыйыз, дәрәҗәне үттегез!',
  'gameOver': 'Уйын тәмам',
  'timeUsed': 'Вакыт',
  'actionCount': 'Хәрәкәтләр',
  'mineCount': 'Миналар',
  'nextLevel': 'Киләч дәрәҗә: {level} дәрәҗә',
  'newbieNextLevel': 'Киләч дәрәҗә: Яңа уенчы {level}',
  'nextLevelMines': 'Миналар',
  'mineIncrease': 'Арту',
  'newbieFinish': 'Яңа уенчы режимы тәмам',
  'ok': 'Туганай',
  'continueNextLevel': 'Киләч дәрәҗәгә дәвам итәргә',
  'restart': 'Яңадан башлатагыз',
  'level': '{level} дәрәҗә',
  'newbieLevel': 'Яңа уенчы {level}',
  'operationFailed': 'Эшләү сәтсиз булды',
  // Game status texts
  'returnHome': 'Башкачка кайту',
  'revealMode': 'Ачыру режиме',
  'flagMode': 'Байрак режиме',
  'newMap': 'Яңа карта (миналар саны үзгәрми, яңа план)',
  'resetMap': 'Картаны кайтарга (план үзгәрми, хәлди кайтарга)',
  'zoomOut': 'Кечкертү',
  'zoomIn': 'Улчертү',
  'resetZoom': 'Аслы булышу',
  'previousStep': 'Алдагы кадәм',
  'pause': 'Токтату',
  'play': 'Уенагыз',
  'nextStep': 'Киләч кадәм',
  'clickToStart': 'Уйынны башларга өчен хаҗәр кырты басыгыз',
  'playing': 'Уйында...',
  'gameWin': 'Котлыйыз, дәрәҗәне үттегез!',
  'gameLose': 'Уйын тәмам, минанга тапшыргыз',
  'gamePaused': 'Уйын токтатылды',
  'ready': 'Башларга әзер',
  'clickStartShort': 'Башларга басыгыз',
  'playingShort': 'Уйында',
  'winShort': 'Үттелде!',
  'loseShort': 'Йөкләү',
  'pausedShort': 'Токтатулды',
  // Counter strings
  'currentLevel': 'Хәзерге дәрәҗә',
  'remainingMines': 'Калган миналар',
  'gameTime': 'Уйын вакыты (сәгендә)',
  'operationCount': 'Эшләр саны',
  'previousLevel': 'Алдагы дәрәҗә',
  'nextLevelShort': 'Киләч дәрәҗә',
  // Battlefront strings
  'completed': 'Тәмамланды',
  'inProgress': 'Һәммен',
  'continueGame': 'Уйынны дәвам итәргә',
  'replay': 'Яңадан уенагыз',
  'creater': 'Командан',
  'created': 'Башлау вакыты',
  'updated': 'Яңартылды',
  // Dialog strings
  'confirm': 'Тасдиклагыз',
  'cancel': 'Бетергә',
  'yes': 'Әйе',
  'no': 'Юк',
  'save': 'Саклагыз',
  'edit': 'Түзәтү',
  'levelFormat': '{level} дәрәҗә',
  'newbieLevelFormat': 'Яңа уенчы {level}',
  'totalLevel': '{level}/{totalLevel} дәрәҗә',
  'totalLevelTooltip': 'Хәзер: {level} дәрәҗә / Һәммәсе {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Фронтлар юк',
  'battlefrontCount': '{count} фронт',
  'levelPrefix': 'ДР{level}',
  'newbieLevelPrefix': 'Яңа уенчы ДР{level}',
  'minesCount': '{count} мина',
  'notStarted': 'Башланмады',
  'victory': 'Җиңү',
  'defeat': 'Йөкләү',
  'gameDurationParam': 'Вакыт: {seconds}с',
  'actionsCountParam': 'Хәрәкәтләр: {count} тапкыр',
  'actionsCountParamShort': '{count} тапкыр',
  'miningMethodParam': 'Ысулы: {method}',
  'startTimeParam': 'Башлау: {time}',
  'endTimeParam': 'Аяклау: {time}',
  'returnButton': 'Кайту',
  'battlefrontDetails': 'Фронт тафсиләтләре',
  'clickToEditName': 'Исемне түзәтү өчен басыгыз',
  'clickToAddDescription': 'Тасвир өстәү өчен басыгыз...',
  'noDescription': 'Тасвир юк',
  // Level record strings
  'levelCount': '{count} дәрәҗә',
  'noLevelRecords': 'Фронтны сайлагыз',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Фронтны бетергә',
  'deleteBattlefrontContent':
      'Сез \'{name}\' фронтын бетергәңне сезмез? Бу эш кайтырга мөмкин түгел.',
  'battlefrontLockedCannotDelete': 'Фронт болган, бетергәргә мөмкин түгел',
  'unknownNavigationLevel': 'Билгесез дәрәҗә',
  'noBattlefrontSelected': 'Фронт сайланмады',
  'noBattlefrontToContinue': 'Дәвам итәргә фронт юк',
  'synced': 'Синхронлаштырылды',
  'notSynced': 'Синхронлаштырылмады',
  'newbieBattlefrontName': 'Яңа уенчы фронты {number}',
  'battlefrontName': 'Фронт {number}',
  'nickname': 'Ләкәп исем',
  'nicknameSetting': 'Ләкәп исем көйләме',
  'nicknameDesc': 'Сезнең ләкәп исемегезне көйләгез',
  'enterNickname': 'Ләкәп исемегезне кире гыз',
  'nicknameSaved': 'Ләкәп исем сакланды',
  'nicknameUpdated': 'Ләкәп исем яңартылды',
  'nicknameRequired': 'Ләкәп исем кирәк',
  'nicknameTooLong': 'Ләкәп исем 30 символдан артык була алмаш',
  // Level top strings
  'levelTopCount': 'Югары исемлек ({count})',
  'levelTopCountShort': 'Югары ({count})',
  'retry': 'Яңадан хәер',
  'noLevelTopData': 'Мәғлүмәт юк',
  'remoteBattlefront': 'Көрәсә фронт',
  'participated': 'Катнашты',
  'notParticipated': 'Катнашмады',
  'loadMore': 'Күбрәк йөкләргә',
  'joinBattle': 'Җәтигәгә катнашу',
  'joinBattleTooltip': '\'{name}\' Җәтигәгә катнашу',
  'joinBattleConfirm': 'Сез \'{name}\' Җәтигәгә катнашуны сезмез?',
  'joinBattleSuccess': '\'{name}\' Җәтигәгә сәтле катнашты',
  'joinBattleErrorSelf': 'Үзегезнең фронтынга катнаша аласыз',
  'replayBattlefront': 'Фронтны яңадан уенагыз',
  'replayBattlefrontTooltip': '\'{name}\' фронтын яңадан уенагыз',
  'getReplayBattlefrontConfirm': 'Сез \'{name}\' яңадан уенугызны сезмез?',
  'getReplayBattlefrontFailed': '\'{name}\' яңадан уенмады: {error}',
  'download': 'Йөкләргә',
  'downloadBattlefront': 'Фронтны йөкләргә',
  'downloadBattlefrontTooltip': '\'{name}\' фронтын йөкләргә',
  'getDownloadBattlefrontConfirm': 'Сез \'{name}\' йөкләргәне сезмез?',
  'getDownloadBattlefrontSuccess': '\'{name}\' сәтле йөкләнде',
  'downloadMyOwnBattlefrontError':
      'Сезнең үзегезнең фронтларын гына йөклә аласыз',
  'getDownloadBattlefrontFailed': '\'{name}\' йөкләү сәтсиз: {error}',
  'continueGameShort': 'Җәтигәгә дәвам итәргә',
  'replayShort': 'Яңадан уенагыз',
  'highestLevel': '{level} дәрәҗә',
  'deviceNickname': 'Чегәш',
  'createdTime': 'Ясалган вакыты',
  'remoteBattlefrontDetail': 'Көрәсә фронт тафсиләтләре',
  'levelList': 'Дәрәҗәләр исемлеге',
  'fastClearTimeParam': 'Тәмамлау вакыты: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint':
      'Мәзмәндерне карау өчен уртача фронтны сайлагыз',
  'loadingRemoteDetail': 'Көрәсә фронт мәзмәндәре йөкләнә...',
  'noRemoteBattlefrontSelected': 'Көрәсә фронт сайланмады',
  'failedToLoadRemoteDetail': 'Мәзмәндәрне йөкләү сәтсиз булды',
  'fastestRecord': 'Иң тиз тәмамлау',
  'safestRecord': 'Иң бекетле тәмамлау',
  'fastestRecordDesc': 'Иң тиз (иң кечкенә вакыт)',
  'safestRecordDesc': 'Иң бекетле (иң кечкенә хәрәкәт)',
  'creator': 'Ясаучы',
  'player': 'Уенчы',
  // Branch maps
  'getBranchMapCount': '{count} көйләм',
  'collapse': 'Йыгырту',
  'expand': 'Улчертү',
  // Quit battlefront
  'quitBattlefront': 'Фронттан чыгу',
  'quitBattlefrontTooltip': 'Көрәсә фронттан чыгу',
  'quitBattlefrontTitle': 'Фронттан чыгу',
  'quitBattlefrontContent':
      'Сез \'{name}\' фронттан чыгуны сезмез? Сезнең уртача прогрессеңиз бетереләчәк.',
  // Download page
  'downloadClient': 'Клиентны йөкләргә',
  'browser': 'Күзәтелмә',
  'browserDesc': 'Йөкләүсиз, күзәтелмәдә һәзен уенагыз',
  'windowsDesc': 'Windows 10 һәм аннан югары өчен',
  'macosDesc': 'macOS 10.15 һәм аннан югары өчен',
  'android': 'Android',
  'androidDesc': 'Android 8.0 һәм аннан югары өчен',
  'iosDesc': 'iOS 14.0 һәм аннан югары өчен',
  'linkAddress': 'Сылтама адресы',
  'downloadLink': 'Йөкләү сылтамасы',
  'qrCode': 'QR-коды',
  'scanToDownload': 'Йөкләү өчен телефон белән сканерләгез',
  'copy': 'Көйләргә',
  'copiedToClipboard': 'Буферга көйләнгән',
  'openLink': 'Сылтаманы ачу',
  'cannotOpenLink': 'Сылтаманы ачу мөмкин түгел',
  // Game introduction
  'gameIntroduction':
      '1. "Яңа уенчы" 15 минә башлый, 99 минәгә кадәр;\n2. "Яңа фронт" 81 минә башлый, һәр дәрәҗәдә арта, югары чиге юк.\n3. Интернетта тәмамланган фронтлар автоматик булып облакта берләшә.',
};
