/// Czech（捷克语）
/// České texty pro aplikaci DMine
const Map<String, String> stringsCs = {
  'appLabel': 'Nejlepší miny',
  'appTitle': 'DMine - Nejlepší miny',
  'settings': 'Nastavení',
  'gameSettings': 'Nastavení hry',
  'showTimer': 'Zobrazit časovač',
  'showTimerDesc': 'Zobrazit časovač hry v rozhraní',
  'showActionCounter': 'Zobrazit čítač akcí',
  'showActionCounterDesc': 'Zobrazit počet akcí v rozhraní hry',
  'autoAdjustBoardWidth': 'Automaticky upravit šířku hrací plochy',
  'showUnrevealedCounter': 'Zobrazit počítadlo neodhalených polí',
  'showUnrevealedCounterDesc': 'Zobrazit počet neodhalených polí v herním rozhraní',
  'showMineCounter': 'Zobrazit počítadlo min',
  'showMineCounterDesc': 'Zobrazit zbývající počet min v herním rozhraní',
  'autoAdjustBoardWidthDesc':
      'Automaticky upravit šířku plochy podle velikosti obrazovky',
  'resetToDefaults': 'Obnovit výchozí nastavení',
  'resetToDefaultsDesc': 'Obnovit všechna nastavení na výchozí hodnoty',
  'aboutDMine': 'O DMine',
  'version': 'Verze',
  'close': 'Zavřít',
  'manualBoardWidth': 'Ruční nastavení šířky plochy',
  'currentWidth': 'Aktuální',
  'range': 'Rozsah',
  'widthSliderHint':
      'Tip: Změny šířky plochy uvidíte v reálném čase při tažení posuvníku',
  'gameRecords': 'Herní záznamy',
  'selectMapToViewRecords': 'Vyberte mapu pro zobrazení záznamů',
  'totalRecords': 'Celkem',
  'gameRecordsTitle': 'Seznam herních záznamů',
  'pleaseSelectMapFirst': 'Nejprve vyberte mapu',
  'noGameRecords': 'Žádné herní záznamy',
  'miningMethodFlag': 'Označit vlajkou',
  'miningMethodBlind': 'Slepé hledání',
  'statusPlaying': '▶️ Hra probíhá...',
  'statusWin': '🎉 Vítězství',
  'statusLose': '💥 Prohra',
  'actionsCount': 'Počet akcí',
  'miningMethod': 'Zpět hledání min',
  'duration': 'Trvání',
  'seconds': 'sekund',
  'startTime': 'Čas začátku',
  'endTime': 'Čas konce',
  'pauseTime': 'Čas pauzy',
  'unlock': 'Odemknout',
  'lock': 'Zamknout',
  'delete': 'Smazat',
  'languageSetting': 'Nastavení jazyka',
  'currentLanguage': 'Aktuální',
  'systemLanguage': 'Systémový jazyk',
  'chinese': 'Čínština',
  'english': 'Angličtina',
  'language': 'Jazyk',
  // Home page
  'newbie': 'Začátečníci',
  'gameIntro': 'Popis hry',
  'newBattle': 'Nová fronta',
  'continueChallenge': 'Pokračovat ve výzvě',
  'error': 'Chyba',
  'initializationFailed': 'Inicializace selhala',
  // Game page
  'congratulations': 'Gratulujeme, jste prošli úroveň!',
  'gameOver': 'Konec hry',
  'timeUsed': 'Uplynulý čas',
  'actionCount': 'Počet akcí',
  'mineCount': 'Počet min',
  'nextLevel': 'Další úroveň: Úroveň {level}',
  'newbieNextLevel': 'Další úroveň: Začátečnická {level}',
  'nextLevelMines': 'Počet min',
  'mineIncrease': 'Zvýšení',
  'newbieFinish': 'Začátečnický kurz dokončen',
  'ok': 'OK',
  'continueNextLevel': 'Pokračovat na další úroveň',
  'restart': 'Restartovat',
  'level': 'Úroveň {level}',
  'newbieLevel': 'Začátečnická úroveň {level}',
  'operationFailed': 'Operace selhala',
  // Game status texts
  'returnHome': 'Zpět na hlavní stránku',
  'revealMode': 'Režim odhalování',
  'flagMode': 'Režim vlajek',
  'newMap': 'Nová mapa (počet min beze změny, vygenerovat novou mapu)',
  'resetMap': 'Znovu načíst mapu (stejná mapa, reset stavu)',
  'zoomOut': 'Zmenšit',
  'zoomIn': 'Zvětšit',
  'resetZoom': 'Obnovit původní přiblížení',
  'previousStep': 'Předchozí krok',
  'pause': 'Pauza',
  'play': 'Spustit',
  'nextStep': 'Další krok',
  'clickToStart': 'Klikněte na libovolné políčko pro spuštění hry',
  'playing': 'Hra probíhá...',
  'gameWin': 'Gratulujeme, jste prošli úroveň!',
  'gameLose': 'Konec hry, narazili jste na minu',
  'gamePaused': 'Hra pozastavena',
  'ready': 'Připraveno',
  'clickStartShort': 'Klikněte pro start',
  'playingShort': 'Probíhá',
  'winShort': 'Dokončeno!',
  'loseShort': 'Narazili na minu',
  'pausedShort': 'Pozastaveno',
  // Counter strings
  'currentLevel': 'Aktuální úroveň',
  'remainingMines': 'Zbývající miny',
  'unrevealedCells': 'Neodhalená pole',
  'gameTime': 'Čas hry (sekund)',
  'operationCount': 'Počet akcí',
  'previousLevel': 'Předchozí úroveň',
  'nextLevelShort': 'Další úroveň',
  // Battlefront strings
  'completed': 'Dokončeno',
  'inProgress': 'Probíhá',
  'continueGame': 'Pokračovat ve hře',
  'replay': 'Přehrát',
  'creater': 'Velitel',
  'created': 'Čas začátku bitvy',
  'updated': 'Aktualizováno',
  // Dialog strings
  'confirm': 'Potvrdit',
  'cancel': 'Zrušit',
  'yes': 'Ano',
  'no': 'Ne',
  'save': 'Uložit',
  'edit': 'Upravit',
  'levelFormat': 'Úroveň {level}',
  'newbieLevelFormat': 'Začátečnická úroveň {level}',
  'totalLevel': '{level}/{totalLevel} úrovní',
  'totalLevelTooltip': 'Aktuálně: Úroveň {level} / Celkem {totalLevel} úrovní',
  // Battlefront UI strings
  'noBattlefronts': 'Žádné fronty',
  'battlefrontCount': '{count} front',
  'levelPrefix': 'ÚR{level}',
  'newbieLevelPrefix': 'ZAČ{level}',
  'minesCount': '{count} min',
  'notStarted': 'Nezahájeno',
  'victory': 'Vítězství',
  'defeat': 'Prohra',
  'gameDurationParam': 'Trvání: {seconds} sekund',
  'actionsCountParam': 'Akce: {count} krát',
  'actionsCountParamShort': '{count} krát',
  'miningMethodParam': 'Způsob: {method}',
  'startTimeParam': 'Čas začátku: {time}',
  'endTimeParam': 'Čas konce: {time}',
  'returnButton': 'Zpět',
  'battlefrontDetails': 'Detaily fronty',
  'clickToEditName': 'Klikněte pro změnu názvu',
  'clickToAddDescription': 'Klikněte pro přidání popisu...',
  'noDescription': 'Bez popisu',
  // Level record strings
  'levelCount': '{count} úrovní',
  'noLevelRecords': 'Vyberte frontu',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Smazat frontu',
  'deleteBattlefrontContent':
      'Opravdu chcete smazat frontu "{name}"? Tato akce je nevratná.',
  'battlefrontLockedCannotDelete': 'Fronta je zamčena, nelze smazat',
  'unknownNavigationLevel': 'Neznámá úroveň navigace',
  'noBattlefrontSelected': 'Žádná fronta nebyla vybrána',
  'noBattlefrontToContinue': 'Žádná fronta k pokračování',
  'synced': 'Synchronizováno',
  'notSynced': 'Nesynchronizováno',
  'newbieBattlefrontName': 'Začátečnická fronta {number}',
  'battlefrontName': 'Fronta {number}',
  'nickname': 'Přezdívka',
  'nicknameSetting': 'Nastavení přezdívky',
  'nicknameDesc': 'Nastavte svou přezdívku',
  'enterNickname': 'Zadejte přezdívku',
  'nicknameSaved': 'Přezdívka uložena',
  'nicknameUpdated': 'Přezdívka aktualizována',
  'nicknameRequired': 'Přezdívka je povinná',
  'nicknameTooLong': 'Přezdívka nesmí být delší než 30 znaků',
  // Level top strings
  'levelTopCount': 'Žebříček ({count})',
  'levelTopCountShort': 'Žebříček ({count})',
  'retry': 'Zkusit znovu',
  'noLevelTopData': 'Žádná data',
  'remoteBattlefront': 'Vzdálená fronta',
  'participated': 'Zúčastněno',
  'notParticipated': 'Nezúčastněno',
  'loadMore': 'Načíst více',

  'joinBattle': 'Připojit se k bitvě',
  'joinBattleTooltip': 'Připojit se k bitvě "{name}"',
  'joinBattleConfirm': 'Opravdu se chcete připojit k bitvě "{name}"?',
  'joinBattleSuccess': 'Úspěšně jste se připojili k bitvě "{name}"',
  'joinBattleErrorSelf': 'Nelze se připojit k vlastní frontě',

  'replayBattlefront': 'Přehrát frontu',
  'replayBattlefrontTooltip': 'Přehrát frontu "{name}"',
  'getReplayBattlefrontConfirm': 'Opravdu chcete přehrát "{name}"?',
  'getReplayBattlefrontFailed': 'Přehrání "{name}" selhalo: {error}',

  'download': 'Stáhnout',
  'downloadBattlefront': 'Stáhnout frontu',
  'downloadBattlefrontTooltip': 'Stáhnout frontu "{name}"',
  'getDownloadBattlefrontConfirm': 'Opravdu chcete stáhnout "{name}"?',
  'getDownloadBattlefrontSuccess': 'Fronta "{name}" byla úspěšně stažena',
  'downloadMyOwnBattlefrontError': 'Můžete stahovat pouze vlastní fronty',
  'getDownloadBattlefrontFailed': 'Stažení "{name}" selhalo: {error}',

  'continueGameShort': 'Pokračovat v bitvě',
  'replayShort': 'Přehrát',
  'highestLevel': 'Úroveň {level}',
  'deviceNickname': 'Zařízení',
  'createdTime': 'Čas vytvoření',
  'remoteBattlefrontDetail': 'Detaily vzdálené fronty',
  'levelList': 'Seznam úrovní',
  'fastClearTimeParam': 'Čas dokončení: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint': 'Vyberte místní frontu pro zobrazení detailů',
  'loadingRemoteDetail': 'Načítání detailů vzdálené fronty...',
  'noRemoteBattlefrontSelected': 'Žádná vzdálená fronta nebyla vybrána',
  'failedToLoadRemoteDetail': 'Načítání detailů selhalo',
  'fastestRecord': 'Nejrychlejší průchod',
  'safestRecord': 'Nejbezpečnější průchod',
  'fastestRecordDesc': 'Nejrychlejší průchod (nejméně času)',
  'safestRecordDesc': 'Nejbezpečnější průchod (nejméně akcí)',
  'creator': 'Vytvořitel',
  'player': 'Hráč',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopií',
  'collapse': 'Sbalit',
  'expand': 'Rozbalit',
  // 退出战线
  'quitBattlefront': 'Opustit frontu',
  'quitBattlefrontTooltip': 'Opustit vzdálenou frontu',
  'quitBattlefrontTitle': 'Opustit frontu',
  'quitBattlefrontContent':
      'Opravdu chcete opustit frontu "{name}"? Váš místní postup bude smazán.',
  // 游戏介绍
  'gameIntroduction':
      '1. "Začátečníci" začíná s 15 minami, maximálně až 99 min;\n2. "Nová fronta" začíná s 81 minami, na každé úrovni se přidají miny, bez horního limitu.\n3. Při připojení k internetu se "dokončené" fronty automaticky sdílejí v cloudu pro učení ostatních.',
};
