// Latvian（拉脱维亚语）
/// Latvijas valodas tekstiem lietotnei DMine
const Map<String, String> stringsLv = {
  'appLabel': 'Premium Mineris',
  'appTitle': 'DMine - Premium Mineris',
  'settings': 'Iestatījumi',
  'gameSettings': 'Spēles iestatījumi',
  'showTimer': 'Rādīt taimeri',
  'showTimerDesc': 'Rādīt spēles taimeri saskarnē',
  'showActionCounter': 'Rādīt darbību skaitītāju',
  'showActionCounterDesc': 'Rādīt darbību skaitu spēles laukumā',
  'autoAdjustBoardWidth': 'Automātiski pielāgot laukuma platumu',
  'showUnrevealedCounter': 'Rādīt neatklāto šūnu skaitītāju',
  'showUnrevealedCounterDesc': 'Rādīt neatklāto šūnu skaitu spēles saskarnē',
  'showMineCounter': 'Rādīt mīnu skaitītāju',
  'showMineCounterDesc': 'Rādīt atlikušo mīnu skaitu spēles saskarnē',
  'autoAdjustBoardWidthDesc':
      'Pielāgot laukuma platumu atbilstoši ekrāna izmēram',
  'resetToDefaults': 'Atstatīt uz noklusējumu',
  'resetToDefaultsDesc': 'Atstatīt visus iestatījumus uz sākotnējām vērtībām',
  'aboutDMine': 'Par DMine',
  'version': 'Versija',
  'close': 'Aizvērt',
  'manualBoardWidth': 'Manuāli iestatīt laukuma platumu',
  'currentWidth': 'Pašreizējais',
  'range': 'Diapazons',
  'widthSliderHint':
      'Padoms: vilkot slīdni, var redzēt laukuma platuma izmaiņas reālajā laikā',
  'gameRecords': 'Spēles ieraksti',
  'selectMapToViewRecords': 'Izvēlieties karti, lai skatītos ierakstus',
  'totalRecords': 'Kopā',
  'gameRecordsTitle': 'Spēles ierakstu saraksts',
  'pleaseSelectMapFirst': 'Vispirms izvēlieties karti',
  'noGameRecords': 'Nav spēles ierakstu',
  'miningMethodFlag': 'Iestatīt karogu',
  'miningMethodBlind': 'Aklā meklēšana',
  'statusPlaying': '▶️ Spēlē...',
  'statusWin': '🎉 Uzvarēts',
  'statusLose': '💥 Zaudēts',
  'actionsCount': 'Darbību skaits',
  'miningMethod': 'Mīnu meklēšanas metode',
  'duration': 'Ilgums',
  'seconds': 'sekundes',
  'startTime': 'Sākuma laiks',
  'endTime': 'Beigu laiks',
  'pauseTime': 'Pauzes laiks',
  'unlock': 'Atbloķēt',
  'lock': 'Bloķēt',
  'delete': 'Dzēst',
  'languageSetting': 'Valodas iestatījums',
  'currentLanguage': 'Pašreizējā',
  'systemLanguage': 'Sistēmas valoda',
  'chinese': 'Ķīniešu',
  'english': 'Angļu',
  'language': 'Valoda',
  // Home page
  'newbie': 'Iesācējs',
  'gameIntro': 'Spēles apraksts',
  'newBattle': 'Jauna līnija',
  'continueChallenge': 'Turpināt izaicinājumu',
  'error': 'Kļūda',
  'initializationFailed': 'Inicializācija neizdevās',
  // Game page
  'congratulations': 'Apsveicam! Jūs pabeidzāt līmeni!',
  'gameOver': 'Spēle beigusies',
  'timeUsed': 'Izlietotais laiks',
  'actionCount': 'Darbību skaits',
  'mineCount': 'Mīnu skaits',
  'nextLevel': 'Nākamais līmenis: Līmenis {level}',
  'newbieNextLevel': 'Nākamais līmenis: Iesācējs {level}',
  'nextLevelMines': 'Mīnu skaits',
  'mineIncrease': 'Palielinājums',
  'newbieFinish': 'Iesācēja pamācība pabeigta',
  'ok': 'OK',
  'continueNextLevel': 'Doties uz nākamo līmeni',
  'restart': 'Uzsākt no jauna',
  'level': 'Līmenis {level}',
  'newbieLevel': 'Iesācēja līmenis {level}',
  'operationFailed': 'Darbība neizdevās',
  // Game status texts
  'returnHome': 'Atgriezties uz sākumu',
  'revealMode': 'Atklāšanas režīms',
  'flagMode': 'Karogu režīms',
  'newMap': 'Jauna karte (tāds pats mīnu skaits, izveidot jaunu karti)',
  'resetMap': 'Pārlādēt karti (pati karte, atstatīt stāvokli)',
  'zoomOut': 'Samazināt',
  'zoomIn': 'Palielināt',
  'resetZoom': 'Atstatāt tālummaiņu',
  'previousStep': 'Iepriekšējais solis',
  'pause': 'Pauze',
  'play': 'Spēlēt',
  'nextStep': 'Nākamais solis',
  'clickToStart': 'Noklikšķiniet uz jebkuras šūnas, lai sāktu spēli',
  'playing': 'Spēlē...',
  'gameWin': 'Apsveicam! Jūs pabeidzāt līmeni!',
  'gameLose': 'Spēle beigusies, jūs ieskātāt mīnu',
  'gamePaused': 'Spēle pauzē',
  'ready': 'Gatavs',
  'clickStartShort': 'Noklikšķiniet, lai sāktu',
  'playingShort': 'Notiek',
  'winShort': 'Pabeigts!',
  'loseShort': 'Ieskāta mīna',
  'pausedShort': 'Pauzē',
  // Counter strings
  'currentLevel': 'Pašreizējais līmenis',
  'remainingMines': 'Atlikušās mīnas',
  'unrevealedCells': 'Neatklātās šūnas',
  'gameTime': 'Spēles laiks (sekundes)',
  'operationCount': 'Darbību skaits',
  'previousLevel': 'Iepriekšējais līmenis',
  'nextLevelShort': 'Nākamais līmenis',
  // Battlefront strings
  'completed': 'Pabeigts',
  'inProgress': 'Notiek',
  'continueGame': 'Turpināt spēli',
  'replay': 'Atkārtoti spēlēt',
  'creater': 'Komandieris',
  'created': 'Karošanas sākuma laiks',
  'updated': 'Atjaunināts',
  // Dialog strings
  'confirm': 'Apstiprināt',
  'cancel': 'Atcelt',
  'yes': 'Jā',
  'no': 'Nē',
  'save': 'Saglabāt',
  'edit': 'Rediģēt',
  'levelFormat': 'Līmenis {level}',
  'newbieLevelFormat': 'Iesācēja līmenis {level}',
  'totalLevel': '{level}/{totalLevel} līmeņi',
  'totalLevelTooltip':
      'Pašreizējais: Līmenis {level} / Kopā {totalLevel} līmeņi',
  // Battlefront UI strings
  'noBattlefronts': 'Nav līniju',
  'battlefrontCount': '{count} līnijas',
  'levelPrefix': 'LV{level}',
  'newbiePrefix': 'IE{level}',
  'minesCount': '{count} mīnas',
  'notStarted': 'Neuzsākts',
  'victory': 'Uzvara',
  'defeat': 'Zaudējums',
  'gameDurationParam': 'Ilgums: {seconds} sekundes',
  'actionsCountParam': 'Darbības: {count} reizes',
  'actionsCountParamShort': '{count} reizes',
  'miningMethodParam': 'Metode: {method}',
  'startTimeParam': 'Sākums: {time}',
  'endTimeParam': 'Beigas: {time}',
  'returnButton': 'Atpakaļ',
  'battlefrontDetails': 'Līnijas detaļas',
  'clickToEditName': 'Noklikšķiniet, lai mainītu nosaukumu',
  'clickToAddDescription': 'Noklikšķiniet, lai pievienotu aprakstu...',
  'noDescription': 'Nav apraksta',
  // Level record strings
  'levelCount': '{count} līmeņi',
  'noLevelRecords': 'Izvēlieties līniju',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Dzēst līniju',
  'deleteBattlefrontContent':
      'Vai tiešām vēlaties dzēst līniju "{name}"? Šī darbība nav atgriezeniska.',
  'battlefrontLockedCannotDelete': 'Līnija bloķēta, nevar dzēst',
  'unknownNavigationLevel': 'Nezināms navigācijas līmenis',
  'noBattlefrontSelected': 'Nav izvēlēta līnija',
  'noBattlefrontToContinue': 'Nav līnijas, kuru turpināt',
  'synced': 'Sinhronizēts',
  'notSynced': 'Nav sinhronizēts',
  'newbieBattlefrontName': 'Iesācēja līnija {number}',
  'battlefrontName': 'Līnija {number}',
  'nickname': 'Segvārds',
  'nicknameSetting': 'Segvārda iestatījums',
  'nicknameDesc': 'Iestatiet savu segvārdu',
  'enterNickname': 'Ievadiet segvārdu',
  'nicknameSaved': 'Segvārds saglabāts',
  'nicknameUpdated': 'Segvārds atjaunināts',
  'nicknameRequired': 'Segvārds ir obligāts',
  'nicknameTooLong': 'Segvārds nedrīkst būt garāks par 30 rakstzīmēm',
  // Level top strings
  'levelTopCount': 'Vērtēšana ({count})',
  'levelTopCountShort': 'Vērtēšana ({count})',
  'retry': 'Mēģināt vēlreiz',
  'noLevelTopData': 'Nav datu',
  'remoteBattlefront': 'Attālināta līnija',
  'participated': 'Piedalījies',
  'notParticipated': 'Nav piedalījies',
  'loadMore': 'Ielādēt vairāk',

  'joinBattle': 'Pievienoties kaujai',
  'joinBattleTooltip': 'Pievienoties kaujai "{name}"',
  'joinBattleConfirm': 'Vai tiešām vēlaties pievienoties kaujai "{name}"?',
  'joinBattleSuccess': 'Jūs veiksmīgi pievienojāties kaujai "{name}"',
  'joinBattleErrorSelf': 'Nevar pievienoties savai līnijai',

  'replayBattlefront': 'Atkārtoti spēlēt līniju',
  'replayBattlefrontTooltip': 'Atkārtoti spēlēt līniju "{name}"',
  'getReplayBattlefrontConfirm':
      'Vai tiešām vēlaties atkārtoti spēlēt "{name}"?',
  'getReplayBattlefrontFailed': 'Neizdevās atkārtoti spēlēt "{name}": {error}',

  'download': 'Lejupielādēt',
  'downloadBattlefront': 'Lejupielādēt līniju',
  'downloadBattlefrontTooltip': 'Lejupielādēt līniju "{name}"',
  'getDownloadBattlefrontConfirm': 'Vai tiešām vēlaties lejupielādēt "{name}"?',
  'getDownloadBattlefrontSuccess': 'Līnija "{name}" veiksmīgi lejupielādēta',
  'downloadMyOwnBattlefrontError': 'Var lejupielādēt tikai savas līnijas',
  'getDownloadBattlefrontFailed': 'Neizdevās lejupielādēt "{name}": {error}',

  'continueGameShort': 'Turpināt kauju',
  'replayShort': 'Atkārtoti',
  'highestLevel': 'Līmenis {level}',
  'deviceNickname': 'Ierīce',
  'createdTime': 'Izveidošanas laiks',
  'remoteBattlefrontDetail': 'Attālinātas līnijas detaļas',
  'levelList': 'Līmeņu saraksts',
  'fastClearTimeParam': 'Pabeigšanas laiks: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Izvēlieties vietējo līniju, lai skatītos detaļas',
  'loadingRemoteDetail': 'Ielādē attālinātas līnijas detaļas...',
  'noRemoteBattlefrontSelected': 'Nav izvēlēta attālināta līnija',
  'failedToLoadRemoteDetail': 'Neizdevās ielādēt attālinātos datus',
  'fastestRecord': 'Ātākā pabeigšana',
  'safestRecord': 'Drošākā pabeigšana',
  'fastestRecordDesc': 'Ātākā pabeigšana (mazāks laiks)',
  'safestRecordDesc': 'Drošākā pabeigšana (mazāk darbību)',
  'creator': 'Izveidotājs',
  'player': 'Spēlētājs',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopijas',
  'collapse': 'Sakļaut',
  'expand': 'Izvērst',
  // 退出战线
  'quitBattlefront': 'Pamest līniju',
  'quitBattlefrontTooltip': 'Pamest attālināto līniju',
  'quitBattlefrontTitle': 'Pamest līniju',
  'quitBattlefrontContent':
      'Vai tiešām vēlaties pamest līniju "{name}"? Jūsu vietējais progress tiks dzēsts.',
  // 游戏介绍
  'gameIntroduction':
      '1. „Iesācējs” sākas ar 15 mīnām un var sasniegt līdz 99 mīnām.\n2. „Jauna līnija” sākas ar 81 mīnu, katrs līmenis palielina mīnu skaitu bez augšēja ierobežojuma.\n3. Ar interneta pieslēgumu „pabeigtās” līnijas automātiski tiek kopīgotas mākonī, lai citi varētu to izmantot.',
};
