// Macedonian（马其顿语）
/// Македонски текстови за апликацијата DMine
const Map<String, String> stringsMk = {
  'appLabel': 'Премиум Минер',
  'appTitle': 'DMine - Премиум Минер',
  'settings': 'Подесувања',
  'gameSettings': 'Подесувања на играта',
  'showTimer': 'Прикажи тајмер',
  'showTimerDesc': 'Го прикажува тајмерот на играта во интерфејсот',
  'showActionCounter': 'Прикажи број на акции',
  'showActionCounterDesc': 'Го прикажува бројот на акции на таблото',
  'autoAdjustBoardWidth': 'Автоматско прилагодување на ширина',
  'autoAdjustBoardWidthDesc':
      'Автоматски го прилагодува ширината на таблото според големината на екранот',
  'resetToDefaults': 'Врати ги стандардните подесувања',
  'resetToDefaultsDesc':
      'Ги враќа сите подесувања на нивните оригинални вредности',
  'aboutDMine': 'За DMine',
  'version': 'Верзија',
  'close': 'Затвори',
  'manualBoardWidth': 'Ручно постави ширина',
  'currentWidth': 'Моментално',
  'range': 'Опсег',
  'widthSliderHint':
      'Совет: Повлечете лизгачот за да ги видите промените во реално време',
  'gameRecords': 'Рекорди на играта',
  'selectMapToViewRecords': 'Изберете карта за да ги видите рекордите',
  'totalRecords': 'Вкупно',
  'gameRecordsTitle': 'Листа на рекорди',
  'pleaseSelectMapFirst': 'Прво изберете карта',
  'noGameRecords': 'Нема рекорди на играта',
  'miningMethodFlag': 'Постави знаме',
  'miningMethodBlind': 'Слепо пронаоѓање',
  'statusPlaying': '▶️ Се игра...',
  'statusWin': '🎉 Победа',
  'statusLose': '💥 Загуба',
  'actionsCount': 'Број на акции',
  'miningMethod': 'Метод за пронаоѓање мини',
  'duration': 'Времетраење',
  'seconds': 'секунди',
  'startTime': 'Време на почеток',
  'endTime': 'Време на крај',
  'pauseTime': 'Време на пауза',
  'unlock': 'Отклучи',
  'lock': 'Заклучи',
  'delete': 'Избриши',
  'languageSetting': 'Подесување на јазик',
  'currentLanguage': 'Моментален',
  'systemLanguage': 'Системски јазик',
  'chinese': 'Кинески',
  'english': 'Англиски',
  'language': 'Јазик',
  // Home page
  'newbie': 'Почетник',
  'newBattle': 'Нова фронт',
  'continueChallenge': 'Продолжи со предизвикот',
  'error': 'Грешка',
  'initializationFailed': 'Иницијализацијата не успеа',
  // Game page
  'congratulations': 'Честитки! ја завршивте нивото!',
  'gameOver': 'Играта заврши',
  'timeUsed': 'Потрошено време',
  'actionCount': 'Број на акции',
  'mineCount': 'Број на мини',
  'nextLevel': 'Следно ниво: Ниво {level}',
  'newbieNextLevel': 'Следно ниво: Почетник {level}',
  'nextLevelMines': 'Број на мини',
  'mineIncrease': 'Зголемување',
  'newbieFinish': 'Утрена за почетници завршена',
  'ok': 'ОК',
  'continueNextLevel': 'Оди на следно ниво',
  'restart': 'Рестартирај',
  'level': 'Ниво {level}',
  'newbieLevel': 'Ниво за почетници {level}',
  'operationFailed': 'Операцијата не успеа',
  // Game status texts
  'returnHome': 'Врати се дома',
  'revealMode': 'Режим на откривање',
  'flagMode': 'Режим на знаме',
  'newMap': 'Нова карта (ист број мини, креирај нова)',
  'resetMap': 'Врати ја картата (иста карта, врати состојба)',
  'zoomOut': 'Намали',
  'zoomIn': 'Зголеми',
  'resetZoom': 'Ресетирај зум',
  'previousStep': 'Претходен чекор',
  'pause': 'Пауза',
  'play': 'Играј',
  'nextStep': 'Следен чекор',
  'clickToStart': 'Кликнете на било која ќелија за да започнете',
  'playing': 'Се игра...',
  'gameWin': 'Честитки! ја завршивте нивото!',
  'gameLose': 'Играта заврши, нацеливте на мина',
  'gamePaused': 'Играта е паузирана',
  'ready': 'Подготвен',
  'clickStartShort': 'Кликни за почеток',
  'playingShort': 'Во тек',
  'winShort': 'Завршено!',
  'loseShort': 'Нацелана мина',
  'pausedShort': 'Паузирано',
  // Counter strings
  'currentLevel': 'Моментално ниво',
  'remainingMines': 'Останати мини',
  'gameTime': 'Време на игра (секунди)',
  'operationCount': 'Број на акции',
  'previousLevel': 'Претходно ниво',
  'nextLevelShort': 'Следно ниво',
  // Battlefront strings
  'completed': 'Завршено',
  'inProgress': 'Во тек',
  'continueGame': 'Продолжи со играта',
  'replay': 'Повтори играта',
  'creater': 'Креатор',
  'created': 'Создадено на',
  'updated': 'Ажурирано на',
  // Dialog strings
  'confirm': 'Потврди',
  'cancel': 'Откажи',
  'yes': 'Да',
  'no': 'Не',
  'save': 'Зачувај',
  'edit': 'Уреди',
  'levelFormat': 'Ниво {level}',
  'newbieLevelFormat': 'Ниво за почетници {level}',
  'totalLevel': '{level}/{totalLevel} нивоа',
  'totalLevelTooltip': 'Моментално: Ниво {level} / Вкупно {totalLevel} нивоа',
  // Battlefront UI strings
  'noBattlefronts': 'Нема фронтови',
  'battlefrontCount': '{count} фронтови',
  'levelPrefix': 'НВ{level}',
  'newbiePrefix': 'ПЧ{level}',
  'minesCount': '{count} мини',
  'notStarted': 'Не започнато',
  'victory': 'Победа',
  'defeat': 'Загуба',
  'gameDurationParam': 'Времетраење: {seconds} секунди',
  'actionsCountParam': 'Акции: {count} пати',
  'actionsCountParamShort': '{count} пати',
  'miningMethodParam': 'Метод: {method}',
  'startTimeParam': 'Почеток: {time}',
  'endTimeParam': 'Крај: {time}',
  'returnButton': 'Назад',
  'battlefrontDetails': 'Детали за фронтот',
  'clickToEditName': 'Кликнете за да го измените името',
  'clickToAddDescription': 'Кликнете за да додадете опис...',
  'noDescription': 'Нема опис',
  // Level record strings
  'levelCount': '{count} нивоа',
  'noLevelRecords': 'Изберете фронт',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Избриши фронт',
  'deleteBattlefrontContent':
      'Дали сигурно сакате да го избришете фронтот "{name}"? Оваа акција не може да се врати.',
  'battlefrontLockedCannotDelete': 'Фронтот е заклучен, не може да се избрише',
  'unknownNavigationLevel': 'Непознато ниво за навигација',
  'noBattlefrontSelected': 'Нема избран фронт',
  'noBattlefrontToContinue': 'Нема фронт за продолжување',
  'synced': 'Синхронизирано',
  'notSynced': 'Не синхронизирано',
  'newbieBattlefrontName': 'Фронт за почетници {number}',
  'battlefrontName': 'Фронт {number}',
  'nickname': 'Прекар',
  'nicknameSetting': 'Подесување на прекар',
  'nicknameDesc': 'Поставете го вашиот прекар',
  'enterNickname': 'Внесете прекар',
  'nicknameSaved': 'Прекарот е зачуван',
  'nicknameUpdated': 'Прекарот е ажуриран',
  'nicknameRequired': 'Прекарот е задолжителен',
  'nicknameTooLong': 'Прекарот не може да подолг од 30 карактери',
  // Level top strings
  'levelTopCount': 'Рангирање ({count})',
  'levelTopCountShort': 'Рангирање ({count})',
  'retry': 'Обидете се повторно',
  'noLevelTopData': 'Нема податоци',
  'remoteBattlefront': 'Далечински фронт',
  'participated': 'Учествував',
  'notParticipated': 'Не учествував',
  'loadMore': 'Вчитај повеќе',

  'joinBattle': 'Придружи се на битката',
  'joinBattleTooltip': 'Придружи се на битката "{name}"',
  'joinBattleConfirm':
      'Дали сигурно сакате да се придружите на битката "{name}"?',
  'joinBattleSuccess': 'Успешно се придруживте на битката "{name}"',
  'joinBattleErrorSelf': 'Не можете да се придружите на вашиот сопствен фронт',

  'replayBattlefront': 'Повтори го фронтот',
  'replayBattlefrontTooltip': 'Повтори го фронтот "{name}"',
  'getReplayBattlefrontConfirm':
      'Дали сигурно сакате да го повторите "{name}"?',
  'getReplayBattlefrontFailed': 'Не успеа повторување на "{name}": {error}',

  'download': 'Преземи',
  'downloadBattlefront': 'Преземи фронт',
  'downloadBattlefrontTooltip': 'Преземи го фронтот "{name}"',
  'getDownloadBattlefrontConfirm':
      'Дали сигурно сакате да го преземете "{name}"?',
  'getDownloadBattlefrontSuccess': 'Фронтот "{name}" е успешно преземен',
  'downloadMyOwnBattlefrontError':
      'Можете да преземете само ваши сопствени фронтови',
  'getDownloadBattlefrontFailed': 'Не успеа преземање на "{name}": {error}',

  'continueGameShort': 'Продолжи ја битката',
  'replayShort': 'Повтори',
  'highestLevel': 'Ниво {level}',
  'deviceNickname': 'Уред',
  'createdTime': 'Време на создавање',
  'remoteBattlefrontDetail': 'Детали за далечинскиот фронт',
  'levelList': 'Листа на нивоа',
  'fastClearTimeParam': 'Време за завршување: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Изберете локален фронт за да ги видите деталите',
  'loadingRemoteDetail': 'Вчитаат се деталите за далечинскиот фронт...',
  'noRemoteBattlefrontSelected': 'Нема избран далечински фронт',
  'failedToLoadRemoteDetail': 'Не успеа вчитање на далечински податоци',
  'fastestRecord': 'Најбрзо завршено',
  'safestRecord': 'Најбезбедно завршено',
  'fastestRecordDesc': 'Најбрзо завршено (најмалку време)',
  'safestRecordDesc': 'Најбезбедно завршено (најмалку акции)',
  'creator': 'Креатор',
  'player': 'Играч',
  // 分支地图字符串
  'getBranchMapCount': '{count} копии',
  'collapse': 'Собери',
  'expand': 'Рашири',
  // 退出战线
  'quitBattlefront': 'Напушти го фронтот',
  'quitBattlefrontTooltip': 'Напушти го далечинскиот фронт',
  'quitBattlefrontTitle': 'Напушти фронт',
  'quitBattlefrontContent':
      'Дали сигурно сакате да го напуштите фронтот "{name}"? Вашиот локален прогрес ќе биде избришан.',

  // 下载页面
  'downloadClient': 'Преземи клиент',
  'browser': 'Браузер',
  'browserDesc': 'Играјте директно во браузерот, без преземање',
  'windowsDesc': 'За Windows 10 и понови',
  'macosDesc': 'За macOS 10.15 и понови',
  'android': 'Android',
  'androidDesc': 'За Android 8.0 и понови',
  'iosDesc': 'За iOS 14.0 и понови',
  'linkAddress': 'Линк адреса',
  'downloadLink': 'Линк за преземање',
  'qrCode': 'QR код',
  'scanToDownload': 'Сканирајте со телефон за да преземете',
  'copy': 'Копирај',
  'copiedToClipboard': 'Копирано во клипборд',
  'openLink': 'Отвори го линкот',
  'cannotOpenLink': 'Не може да се отвори линкот',
  // 游戏介绍
  'gameIntroduction':
      '1. „Почетник“ започнува со 15 мини и може да стигне до 99 мини.\n2. „Нова фронт“ започнува со 81 мини, секое ниво го зголемува бројот без горна граница.\n3. Со интернет врска, „завршени“ фронтови автоматски се зачувуваат во облакот за други да ги користат.',
};
