// Turkish（土耳其语）
/// Turkish language strings for the DMine application
const Map<String, String> stringsTr = {
  'appTitle': 'DMine - En İyi Mayın Tarlası',
  'settings': 'Ayarlar',
  'gameSettings': 'Oyun Ayarları',
  'showTimer': 'Zamanlayıcıyı Göster',
  'showTimerDesc': 'Oyun ekranında zamanlayıcıyı gösterir',
  'showActionCounter': 'Hamle Sayacını Göster',
  'showActionCounterDesc': 'Oyun ekranında hamle sayısını gösterir',
  'autoAdjustBoardWidth': 'Tahta Genişliğini Otomatik Ayarla',
  'autoAdjustBoardWidthDesc':
      'Ekran boyutuna göre tahta genişliğini otomatik ayarlar',
  'resetToDefaults': 'Varsayılanlara Sıfırla',
  'resetToDefaultsDesc': 'Tüm ayarları varsayılan değerlere geri döndürür',
  'aboutDMine': 'DMine Hakkında',
  'version': 'Sürüm',
  'close': 'Kapat',
  'manualBoardWidth': 'Tahta Genişliğini Elle Ayarla',
  'currentWidth': 'Mevcut',
  'range': 'Aralık',
  'widthSliderHint':
      'İpucu: Kaydırıcıyı sürüklerken tahta genişliği anlık olarak değişir',
  'gameRecords': 'Oyun Kayıtları',
  'selectMapToViewRecords': 'Kayıtları görmek için bir harita seçin',
  'totalRecords': 'Toplam',
  'gameRecordsTitle': 'Oyun Kayıtları Listesi',
  'pleaseSelectMapFirst': 'Lütfen önce bir harita seçin',
  'noGameRecords': 'Henüz oyun kaydı yok',
  'miningMethodFlag': 'Bayrak Yerleştir',
  'miningMethodBlind': 'Kör Keşif',
  'statusPlaying': '▶️ Oynanıyor...',
  'statusWin': '🎉 Zafer',
  'statusLose': '💥 Kaybedildi',
  'actionsCount': 'Hamle Sayısı',
  'miningMethod': 'Oyun Metodu',
  'duration': 'Süre',
  'seconds': 'saniye',
  'startTime': 'Başlangıç Saati',
  'endTime': 'Bitiş Saati',
  'pauseTime': 'Duraklatma Süresi',
  'unlock': 'Kilidi Aç',
  'lock': 'Kilitle',
  'delete': 'Sil',
  'languageSetting': 'Dil Ayarı',
  'currentLanguage': 'Mevcut',
  'systemLanguage': 'Sistem Dili',
  'chinese': 'Çince',
  'english': 'İngilizce',
  'language': 'Dil',
  // Home page
  'newbie': 'Yeni Başlayan',
  'newBattle': 'Yeni Cephe',
  'continueChallenge': 'Mücadeleye Devam Et',
  'error': 'Hata',
  'initializationFailed': 'Başlatma Başarısız',
  // Game page
  'congratulations': 'Tebrikler, Bölümü Geçtin!',
  'gameOver': 'Oyun Bitti',
  'timeUsed': 'Süre',
  'actionCount': 'Hamle',
  'mineCount': 'Mayın',
  'nextLevel': 'Sonraki Bölüm: {level}. Bölüm',
  'newbieNextLevel': 'Sonraki Bölüm: Yeni Başlayan {level}',
  'nextLevelMines': 'Mayın Sayısı',
  'mineIncrease': 'Artış',
  'newbieFinish': 'Yeni Başlayan Modu Tamamlandı',
  'ok': 'Tamam',
  'continueNextLevel': 'Sonraki Bölüme Geç',
  'restart': 'Yeniden Başlat',
  'level': '{level}. Bölüm',
  'newbieLevel': 'Yeni Başlayan {level}',
  'operationFailed': 'İşlem Başarısız',
  // Game status texts
  'returnHome': 'Ana Sayfaya Dön',
  'revealMode': 'Açma Modu',
  'flagMode': 'Bayrak Modu',
  'newMap': 'Yeni Harita (Mayın sayısı aynı, yeni düzen)',
  'resetMap': 'Haritayı Sıfırla (Düzen aynı, durumu sıfırla)',
  'zoomOut': 'Uzaklaştır',
  'zoomIn': 'Yakınlaştır',
  'resetZoom': 'Orijinale Dön',
  'previousStep': 'Önceki Adım',
  'pause': 'Duraklat',
  'play': 'Oyna',
  'nextStep': 'Sonraki Adım',
  'clickToStart': 'Oyunu başlatmak için herhangi bir kareye tıkla',
  'playing': 'Oynanıyor...',
  'gameWin': 'Tebrikler, Bölümü Geçtin!',
  'gameLose': 'Oyun Bitti, Mayına Bastın',
  'gamePaused': 'Oyun Duraklatıldı',
  'ready': 'Başlamaya Hazır',
  'clickStartShort': 'Başlamak için tıkla',
  'playingShort': 'Oynanıyor',
  'winShort': 'Başarılı!',
  'loseShort': 'Kaybedildi',
  'pausedShort': 'Duraklatıldı',
  // Counter strings
  'currentLevel': 'Mevcut Bölüm',
  'remainingMines': 'Kalan Mayınlar',
  'gameTime': 'Oyun Süresi (saniye)',
  'operationCount': 'İşlem Sayısı',
  'previousLevel': 'Önceki Bölüm',
  'nextLevelShort': 'Sonraki Bölüm',
  // Battlefront strings
  'completed': 'Tamamlandı',
  'inProgress': 'Devam Ediyor',
  'continueGame': 'Oyuna Devam Et',
  'replay': 'Tekrar Oyna',
  'creater': 'Komutan',
  'created': 'Başlama Zamanı',
  'updated': 'Güncellendi',
  // Dialog strings
  'confirm': 'Onayla',
  'cancel': 'İptal',
  'yes': 'Evet',
  'no': 'Hayır',
  'save': 'Kaydet',
  'edit': 'Düzenle',
  'levelFormat': '{level}. Bölüm',
  'newbieLevelFormat': 'Yeni Başlayan {level}',
  'totalLevel': '{level}/{totalLevel} Bölüm',
  'totalLevelTooltip': 'Mevcut: {level}. Bölüm / Toplam {totalLevel}',
  // Battlefront UI strings
  'noBattlefronts': 'Cephe Yok',
  'battlefrontCount': '{count} Cephe',
  'levelPrefix': 'BL{level}',
  'newbieLevelPrefix': 'Başlangıç BL{level}',
  'minesCount': '{count} Mayın',
  'notStarted': 'Başlatılmadı',
  'victory': 'Zafer',
  'defeat': 'Mağlubiyet',
  'gameDurationParam': 'Süre: {seconds}sn',
  'actionsCountParam': 'Hamle: {count} kere',
  'actionsCountParamShort': '{count} kere',
  'miningMethodParam': 'Metod: {method}',
  'startTimeParam': 'Başlangıç: {time}',
  'endTimeParam': 'Bitiş: {time}',
  'returnButton': 'Geri',
  'battlefrontDetails': 'Cephe Detayları',
  'clickToEditName': 'İsmi düzenlemek için tıkla',
  'clickToAddDescription': 'Açıklama eklemek için tıkla...',
  'noDescription': 'Açıklama Yok',
  // Level record strings
  'levelCount': '{count} Bölüm',
  'noLevelRecords': 'Lütfen bir cephe seçin',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Cepheyi Sil',
  'deleteBattlefrontContent':
      '\'{name}\' cephesini silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
  'battlefrontLockedCannotDelete': 'Cephe kilitli, silinemez',
  'unknownNavigationLevel': 'Bilinmeyen Seviye',
  'noBattlefrontSelected': 'Cephe Seçilmedi',
  'noBattlefrontToContinue': 'Devam edilecek cephe bulunamadı',
  'synced': 'Senkronize Edildi',
  'notSynced': 'Senkronize Edilmedi',
  'newbieBattlefrontName': 'Başlangıç Cephesi {number}',
  'battlefrontName': 'Cephe {number}',
  'nickname': 'Takma Ad',
  'nicknameSetting': 'Takma Ad Ayarı',
  'nicknameDesc': 'Takma adınızı ayarlayın',
  'enterNickname': 'Takma ad girin',
  'nicknameSaved': 'Takma ad kaydedildi',
  'nicknameUpdated': 'Takma ad güncellendi',
  'nicknameRequired': 'Takma ad zorunludur',
  'nicknameTooLong': 'Takma ad 30 karakteri geçemez',
  // Level top strings
  'levelTopCount': 'Liderlik Tablosu ({count})',
  'levelTopCountShort': 'Liderler ({count})',
  'retry': 'Tekrar Dene',
  'noLevelTopData': 'Veri Yok',
  'remoteBattlefront': 'Uzak Cephe',
  'participated': 'Katıldı',
  'notParticipated': 'Katılmadı',
  'loadMore': 'Daha Fazla Yükle',
  'joinBattle': 'Savaşa Katıl',
  'joinBattleTooltip': '\'{name}\' savaşına katıl',
  'joinBattleConfirm':
      '\'{name}\' savaşına katılmak istediğinize emin misiniz?',
  'joinBattleSuccess': '\'{name}\' savaşına başarıyla katıldınız',
  'joinBattleErrorSelf': 'Kendi cephenize katılamazsınız',
  'replayBattlefront': 'Cepheyi Tekrar Oyna',
  'replayBattlefrontTooltip': '\'{name}\' cephesini tekrar oyna',
  'getReplayBattlefrontConfirm':
      '\'{name}\' tekrar oynamak istediğinize emin misiniz?',
  'getReplayBattlefrontFailed': '\'{name}\' tekrar oynatma başarısız: {error}',
  'download': 'İndir',
  'downloadBattlefront': 'Cepheyi İndir',
  'downloadBattlefrontTooltip': '\'{name}\' cephesini indir',
  'getDownloadBattlefrontConfirm':
      '\'{name}\' indirmek istediğinize emin misiniz?',
  'getDownloadBattlefrontSuccess': '\'{name}\' başarıyla indirildi',
  'downloadMyOwnBattlefrontError':
      'Sadece kendi cephelerinizi indirebilirsiniz',
  'getDownloadBattlefrontFailed': '\'{name}\' indirme başarısız: {error}',
  'continueGameShort': 'Savaşa Devam Et',
  'replayShort': 'Tekrar Oyna',
  'highestLevel': '{level}. Bölüm',
  'deviceNickname': 'Cihaz',
  'createdTime': 'Oluşturulma Zamanı',
  'remoteBattlefrontDetail': 'Uzak Cephe Detayları',
  'levelList': 'Bölüm Listesi',
  'fastClearTimeParam': 'Geçme Süresi: {time}',
  // Remote battlefront details
  'selectLocalBattlefrontHint': 'Detayları görmek için yerel bir cephe seçin',
  'loadingRemoteDetail': 'Uzak cephe detayları yükleniyor...',
  'noRemoteBattlefrontSelected': 'Uzak cephe seçilmedi',
  'failedToLoadRemoteDetail': 'Detaylar yüklenemedi',
  'fastestRecord': 'En Hızlı Geçme',
  'safestRecord': 'En Güvenli Geçme',
  'fastestRecordDesc': 'En hızlı (en az süre)',
  'safestRecordDesc': 'En güvenli (en az hamle)',
  'creator': 'Oluşturan',
  'player': 'Oyuncu',
  // Branch maps
  'getBranchMapCount': '{count} Kopya',
  'collapse': 'Daralt',
  'expand': 'Genişlet',
  // Quit battlefront
  'quitBattlefront': 'Cepheden Ayrıl',
  'quitBattlefrontTooltip': 'Uzak cepheden ayrıl',
  'quitBattlefrontTitle': 'Cepheden Ayrıl',
  'quitBattlefrontContent':
      '\'{name}\' cephesinden ayrılmak istediğinize emin misiniz? Yerel ilerlemeniz silinecektir.',
  // Download page
  'downloadClient': 'İstemciyi İndir',
  'browser': 'Tarayıcı',
  'browserDesc': 'İndirmeden tarayıcıda doğrudan oynayın',
  'windowsDesc': 'Windows 10 ve üstü için',
  'macosDesc': 'macOS 10.15 ve üstü için',
  'android': 'Android',
  'androidDesc': 'Android 8.0 ve üstü için',
  'iosDesc': 'iOS 14.0 ve üstü için',
  'linkAddress': 'Link Adresi',
  'downloadLink': 'İndirme Linki',
  'qrCode': 'QR Kod',
  'scanToDownload': 'İndirmek için telefonla tarayın',
  'copy': 'Kopyala',
  'copiedToClipboard': 'Panoya kopyalandı',
  'openLink': 'Linki Aç',
  'cannotOpenLink': 'Link açılamıyor',
  // Game introduction
  'gameIntroduction':
      '1. "Yeni Başlayan" 15 mayınla başlar, maksimum 99 mayına kadar;\n2. "Yeni Cephe" 81 mayınla başlar, her bölümde artar, üst sınırı yoktur.\n3. Çevrimiçi olduğunuzda tamamlanan cepheler otomatik olarak bulutta paylaşılır.',
};
