// Corsican（科西嘉语）
/// Stringhe in corsu per l'applicazione DMine
const Map<String, String> stringsCo = {
  'appLabel': 'Cacciamine di primu ordine',
  'appTitle': 'DMine - Cacciamine di primu ordine',
  'settings': 'Impostazioni',
  'gameSettings': 'Impostazioni di u ghjocu',
  'showTimer': 'Affissà u cronometru',
  'showTimerDesc': 'Affissà u cronometru di u ghjocu nant\'interfaccia',
  'showActionCounter': 'Affissà u contatore d\'azzioni',
  'showActionCounterDesc':
      'Affissà u numeru d\'azzioni nant\'interfaccia di u ghjocu',
  'autoAdjustBoardWidth': 'Aghjustà automàticamente a larghezza di u tavulinu',
  'autoAdjustBoardWidthDesc':
      'Aghjustà automàticamente a larghezza di u tavulinu secondu a dimensione di u schermu',
  'resetToDefaults': 'Ripristinà i paràmetri predefiniti',
  'resetToDefaultsDesc':
      'Ripristinà tutte l\'impostazioni à i valori predefiniti',
  'aboutDMine': 'À propositu di DMine',
  'version': 'Versione',
  'close': 'Chiudi',
  'manualBoardWidth': 'Impostà manualmente a larghezza di u tavulinu',
  'currentWidth': 'Attuale',
  'range': 'Intervallu',
  'widthSliderHint':
      'Cunsigliu: Pudete vede i cambiamenti di larghezza in tempu reale trascinendu u cursore',
  'gameRecords': 'Registri di ghjocu',
  'selectMapToViewRecords': 'Sceglite una carta per vede i registri',
  'totalRecords': 'Totale',
  'gameRecordsTitle': 'Lista di registri di ghjocu',
  'pleaseSelectMapFirst': 'Sceglite prima una carta',
  'noGameRecords': 'Nisunu registru di ghjocu',
  'miningMethodFlag': 'Mettì una bandiera',
  'miningMethodBlind': 'Caccia à cecu',
  'statusPlaying': '▶️ In corsu...',
  'statusWin': '🎉 Vittoria',
  'statusLose': '💥 Scunfitta',
  'actionsCount': 'Numeru d\'azzioni',
  'miningMethod': 'Metudu di caccia mine',
  'duration': 'Durata',
  'seconds': 'sicondi',
  'startTime': 'Ora di iniziu',
  'endTime': 'Ora di fine',
  'pauseTime': 'Ora di pausa',
  'unlock': 'Sbloccà',
  'lock': 'Bloccà',
  'delete': 'Cancellà',
  'languageSetting': 'Impostazione di lingua',
  'currentLanguage': 'Attuale',
  'systemLanguage': 'Lingua di u sistema',
  'chinese': 'Cinese',
  'english': 'Inglese',
  'language': 'Lingua',
  // Home page
  'newbie': 'Iniziu per principianti',
  'newBattle': 'Nova battaglia',
  'continueChallenge': 'Cuntinuà a sfida',
  'error': 'Errore',
  'initializationFailed': 'Inizializazione fallita',
  // Game page
  'congratulations': 'Felicitazioni, avete passatu u livellu!',
  'gameOver': 'Ghjocu finitu',
  'timeUsed': 'Tempu impiegatu',
  'actionCount': 'Numeru d\'azzioni',
  'mineCount': 'Numeru di mine',
  'nextLevel': 'Livellu prossimu: Livellu {level}',
  'newbieNextLevel': 'Livellu prossimu: Iniziu {level}',
  'nextLevelMines': 'Numeru di mine',
  'mineIncrease': 'Aumentu',
  'newbieFinish': 'Iniziu per principianti finitu',
  'ok': 'Va bè',
  'continueNextLevel': 'Cuntinuà à u livellu prossimu',
  'restart': 'Ricomincà',
  'level': 'Livellu {level}',
  'newbieLevel': 'Iniziu {level}',
  'operationFailed': 'Operazione fallita',
  // Game status texts
  'returnHome': 'Ritornà à a pagina iniziale',
  'revealMode': 'Modu di rivelazione',
  'flagMode': 'Modu di bandiere',
  'newMap': 'Carta nova (stessu numeru di mine, genera carta nova)',
  'resetMap': 'Ricaricà a carta (stessa carta, ripristina u statu)',
  'zoomOut': 'Riduce',
  'zoomIn': 'Aumentà',
  'resetZoom': 'Ripristinà u zoom',
  'previousStep': 'Passu precedente',
  'pause': 'Pausa',
  'play': 'Ripruducà',
  'nextStep': 'Passu prossimu',
  'clickToStart': 'Cliccate nantu à qualsiasi casella per cumincià u ghjocu',
  'playing': 'In ghjocu...',
  'gameWin': 'Felicitazioni, avete passatu u livellu!',
  'gameLose': 'Ghjocu finitu, avete calatu nantu à una mina',
  'gamePaused': 'Ghjocu in pausa',
  'ready': 'Prontu',
  'clickStartShort': 'Clicca per cumincià',
  'playingShort': 'In ghjocu',
  'winShort': 'Passatu!',
  'loseShort': 'Calatu nantu à una mina',
  'pausedShort': 'In pausa',
  // Counter strings
  'currentLevel': 'Livellu attuale',
  'remainingMines': 'Mine rimaste',
  'gameTime': 'Tempu di ghjocu (sicondi)',
  'operationCount': 'Numeru d\'azzioni',
  'previousLevel': 'Livellu precedente',
  'nextLevelShort': 'Livellu prossimu',
  // Battlefront strings
  'completed': 'Finitu',
  'inProgress': 'In corsu',
  'continueGame': 'Cuntinuà u ghjocu',
  'replay': 'Riprodurre',
  'creater': 'Cumandante capu',
  'created': 'Ora di iniziu di battaglia',
  'updated': 'Aggiurnatu',
  // Dialog strings
  'confirm': 'Cunfirmà',
  'cancel': 'Annullà',
  'yes': 'Iè',
  'no': 'Innò',
  'save': 'Salvà',
  'edit': 'Mudificà',
  'levelFormat': 'Livellu {level}',
  'newbieLevelFormat': 'Iniziu {level}',
  'totalLevel': '{level}/{totalLevel} livelli',
  'totalLevelTooltip': 'Attuale: Livellu {level} / Totale {totalLevel} livelli',
  // Battlefront UI strings
  'noBattlefronts': 'Nisuna battaglia',
  'battlefrontCount': '{count} battaglie',
  'levelPrefix': 'LV{level}',
  'newbieLevelPrefix': 'IN{level}',
  'minesCount': '{count} mine',
  'notStarted': 'Micca iniziatu',
  'victory': 'Vittoria',
  'defeat': 'Scunfitta',
  'gameDurationParam': 'Durata: {seconds} sicondi',
  'actionsCountParam': 'Azioni: {count} volte',
  'actionsCountParamShort': '{count} volte',
  'miningMethodParam': 'Metudu: {method}',
  'startTimeParam': 'Ora iniziu: {time}',
  'endTimeParam': 'Ora fine: {time}',
  'returnButton': 'Ritornà',
  'battlefrontDetails': 'Dettagli di a battaglia',
  'clickToEditName': 'Clicca per cambià u nome',
  'clickToAddDescription': 'Clicca per aghjunghje una descrizzione...',
  'noDescription': 'Nisuna descrizzione',
  // Level record strings
  'levelCount': '{count} livelli',
  'noLevelRecords': 'Sceglite una battaglia',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Cancellà a battaglia',
  'deleteBattlefrontContent':
      'Site sicuru di vulete cancellà a battaglia "{name}"? Sta azzione ùn pò esse annullata.',
  'battlefrontLockedCannotDelete': 'Battaglia bloccata, ùn si pò cancellà',
  'unknownNavigationLevel': 'Livellu scunnisciutu',
  'noBattlefrontSelected': 'Nisuna battaglia scelta',
  'noBattlefrontToContinue': 'Nisuna battaglia da cuntinuà',
  'synced': 'Sincronizatu',
  'notSynced': 'Micca sincronizatu',
  'newbieBattlefrontName': 'Battaglia d\'iniziu {number}',
  'battlefrontName': 'Battaglia {number}',
  'nickname': 'Sopranome',
  'nicknameSetting': 'Impostazione di sopranome',
  'nicknameDesc': 'Impostà u vostru sopranome',
  'enterNickname': 'Inserite u sopranome',
  'nicknameSaved': 'Sopranome salvatu',
  'nicknameUpdated': 'Sopranome aghjurnatu',
  'nicknameRequired': 'U sopranome hè obligatoriu',
  'nicknameTooLong': 'U sopranome ùn pò supere 30 caratteri',
  // Level top strings
  'levelTopCount': 'Classifica ({count})',
  'levelTopCountShort': 'Classifica ({count})',
  'retry': 'Riprovà',
  'noLevelTopData': 'Nisunu dati',
  'remoteBattlefront': 'Battaglia remota',
  'participated': 'Partecipatu',
  'notParticipated': 'Micca participatu',
  'loadMore': 'Caricà di più',

  'joinBattle': 'Unìsi à a battaglia',
  'joinBattleTooltip': 'Unìsi à a battaglia "{name}"',
  'joinBattleConfirm': 'Site sicuru di vulete unìsi à a battaglia "{name}"?',
  'joinBattleSuccess': 'Vi site unitu bè à a battaglia "{name}"',
  'joinBattleErrorSelf': 'Ùn pudete micca unìsi à a vostra battaglia propria',

  'replayBattlefront': 'Riprodurre a battaglia',
  'replayBattlefrontTooltip': 'Riprodurre a battaglia "{name}"',
  'getReplayBattlefrontConfirm': 'Site sicuru di vulete riprodurre "{name}"?',
  'getReplayBattlefrontFailed': 'Impussibile riprodurre "{name}": {error}',

  'download': 'Scaricà',
  'downloadBattlefront': 'Scaricà a battaglia',
  'downloadBattlefrontTooltip': 'Scaricà a battaglia "{name}"',
  'getDownloadBattlefrontConfirm': 'Site sicuru di vulete scaricà "{name}"?',
  'getDownloadBattlefrontSuccess': 'Battaglia "{name}" scaricata bè',
  'downloadMyOwnBattlefrontError':
      'Pudete scaricà solu e vostre battaglie proprie',
  'getDownloadBattlefrontFailed': 'Impussibile scaricà "{name}": {error}',

  'continueGameShort': 'Cuntinuà a battaglia',
  'replayShort': 'Riprodurre',
  'highestLevel': 'Livellu {level}',
  'deviceNickname': 'Dispositivu',
  'createdTime': 'Ora di creazione',
  'remoteBattlefrontDetail': 'Dettagli di battaglia remota',
  'levelList': 'Lista di livelli',
  'fastClearTimeParam': 'Tempu di passaghju: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Sceglite una battaglia lucale per vede i dettagli',
  'loadingRemoteDetail': 'Caricamentu di dettagli di battaglia remota...',
  'noRemoteBattlefrontSelected': 'Nisuna battaglia remota scelta',
  'failedToLoadRemoteDetail': 'Impussibile caricà i dettagli remoti',
  'fastestRecord': 'Passaghju u più veloce',
  'safestRecord': 'Passaghju u più sicuru',
  'fastestRecordDesc': 'Passaghju u più veloce (menu tempu)',
  'safestRecordDesc': 'Passaghju u più sicuru (menu azzioni)',
  'creator': 'Creatore',
  'player': 'Ghjucatore',
  // 分支地图字符串
  'getBranchMapCount': '{count} copie',
  'collapse': 'Riduce',
  'expand': 'Espande',
  // 退出战线
  'quitBattlefront': 'Abbandonà a battaglia',
  'quitBattlefrontTooltip': 'Abbandonà a battaglia remota',
  'quitBattlefrontTitle': 'Abbandonà a battaglia',
  'quitBattlefrontContent':
      'Site sicuru di vulete abbandunà a battaglia "{name}"? U vostru prugressu lucale serà cancellatu.',

  // 下载页面
  'downloadClient': 'Scaricà u cliente',
  'browser': 'Navigatore',
  'browserDesc': 'Ghjucate direttamente in u navigatore, senza scaricà',
  'windowsDesc': 'Per Windows 10 è superiore',
  'macosDesc': 'Per macOS 10.15 è superiore',
  'android': 'Android',
  'androidDesc': 'Per Android 8.0 è superiore',
  'iosDesc': 'Per iOS 14.0 è superiore',
  'linkAddress': 'Indirizzu di u ligame',
  'downloadLink': 'Ligame di scaricamentu',
  'qrCode': 'Codice QR',
  'scanToDownload': 'Scannate cù u telefunu per scaricà',
  'copy': 'Copià',
  'copiedToClipboard': 'Copiatu in u appunti',
  'openLink': 'Aprì u ligame',
  'cannotOpenLink': 'Impussibile aprì u ligame',
  // 游戏介绍
  'gameIntroduction':
      '1. "Iniziu" principia cù 15 mine, pò ghjunghje finu à 99 mine;\n2. "Nova battaglia" principia cù 81 mine, ogni livellu aghjusta mine, senza limitu superiore.\n3. Cù cunnessione internet, e battaglie "passate" sò spartute automàticamente in nuvola per chì altri pò amparà.',
};
