/// Cadenas en asturianu pa l'aplicación DMine
const Map<String, String> stringsAst = {
  'appLabel': 'Buscamines de alto nivel',
  'appTitle': 'DMine - Buscamines de l\'alto nivel',
  'settings': 'Axustes',
  'gameSettings': 'Axustes del xocu',
  'showTimer': 'Amosar cronómetru de tempu emplegáu',
  'showTimerDesc': 'Amosar el cronómetru del xocu na interfaz del xocu',
  'showActionCounter': 'Amosar contador de accionez',
  'showActionCounterDesc':
      'Amosar l\'estadística del númberu d\'accionez na interfaz del xocu',
  'showUnrevealedCounter': 'Amosar contador de caselles sin revelar',
  'showUnrevealedCounterDesc': 'Amosar el númberu de caselles sin revelar na interfaz del xuegu',
  'showMineCounter': 'Amosar contador de mines',
  'showMineCounterDesc': 'Amosar les mines que queden na interfaz del xuegu',
  'autoAdjustBoardWidth': 'Axustar automáticamente l\'anchu del tableru',
  'autoAdjustBoardWidthDesc':
      'Axustar automáticamente l\'anchu del tableru según el tamañu de la pantalla',
  'resetToDefaults': 'Restablir axustes por defectu',
  'resetToDefaultsDesc': 'Restablir tolos axustes a los valores por defectu',
  'aboutDMine': 'Sobre DMine',
  'version': 'Versión',
  'close': 'Zarrar',
  'manualBoardWidth': 'Establecer manualmente l\'anchu del tableru',
  'currentWidth': 'Actualmente',
  'range': 'Rangu',
  'widthSliderHint':
      'Consellu: Puedes previsualizar los cambeos d\'anchu del tableru en tiempu real mientres arrastres el control deslizante',
  'gameRecords': 'Rexistros del xocu',
  'selectMapToViewRecords': 'Selecciona un mapa pa ver los rexistros',
  'totalRecords': 'Total',
  'gameRecordsTitle': 'Llista de rexistros del xocu',
  'pleaseSelectMapFirst': 'Selecciona primero un mapa',
  'noGameRecords': 'Sense rexistros de xocu',
  'miningMethodFlag': 'Marcar con bandera',
  'miningMethodBlind': 'Buscamines a ciegas',
  'statusPlaying': '▶️ En curs...',
  'statusWin': '🎉 Victoria',
  'statusLose': '💥 Derrota',
  'actionsCount': 'Númberu d\'operaciones',
  'miningMethod': 'Metódu de buscamines',
  'duration': 'Duración',
  'seconds': 'segundos',
  'startTime': 'Hora d\'iniciu',
  'endTime': 'Hora de finalización',
  'pauseTime': 'Hora de pausa',
  'unlock': 'Desbloquear',
  'lock': 'Bloquear',
  'delete': 'Eliminar',
  'languageSetting': 'Axuste d\'idioma',
  'currentLanguage': 'Actualmente',
  'systemLanguage': 'Idioma del sistema',
  'chinese': 'Chinu',
  'english': 'Inglés',
  'language': 'Idioma',
  // Home page
  'newbie': 'Iniciación pa principiantes',
  'gameIntro': 'Descripción del xuegu',
  'newBattle': 'Nova frente de batalla',
  'continueChallenge': 'Continuar el reto',
  'error': 'Error',
  'initializationFailed': 'Falló la inicialización',
  // Game page
  'congratulations': '¡Enhorabuena, completachistes el nivel!',
  'gameOver': 'Xocu finalizáu',
  'timeUsed': 'Tempu emplegáu',
  'actionCount': 'Númberu d\'accionez',
  'mineCount': 'Númberu de minas',
  'nextLevel': 'Siguiente nivel: Nivel {level}',
  'newbieNextLevel': 'Siguiente nivel: Nivel de principiante {level}',
  'nextLevelMines': 'Númberu de minas',
  'mineIncrease': 'Aumentu',
  'newbieFinish': 'Iniciación pa principiantes completada',
  'ok': 'Aceptar',
  'continueNextLevel': 'Continuar el reto con el siguiente nivel',
  'restart': 'Reiniciar',
  'level': 'Nivel {level}',
  'newbieLevel': 'Nivel de principiante {level}',
  'operationFailed': 'Falló l\'operación',
  // Game status texts
  'returnHome': 'Volver a la pantalla principal',
  'revealMode': 'Modu de descubrimientu',
  'flagMode': 'Modu de bandera',
  'newMap': 'Nuevu mapa (númberu de minas constante, xenerar nuevu mapa)',
  'resetMap': 'Recargar mapa (mapa constante, restablir estado)',
  'zoomOut': 'Reducir zoom',
  'zoomIn': 'Aumentar zoom',
  'resetZoom': 'Restablir zoom original',
  'previousStep': 'Pasu anterior',
  'pause': 'Pausa',
  'play': 'Reproducir',
  'nextStep': 'Siguiente pasu',
  'clickToStart': 'Fai clic en calquier casilla pa empezar el xocu',
  'playing': 'Xocu en curs...',
  'gameWin': '¡Enhorabuena, completachistes el nivel!',
  'gameLose': 'Xocu finalizáu, pisachistes una mina',
  'gamePaused': 'Xocu pausáu',
  'ready': 'Listu pa empezar',
  'clickStartShort': 'Fai clic pa empezar',
  'playingShort': 'Xocu en curs',
  'winShort': '¡Completáu!',
  'loseShort': 'Derrota por pisar mina',
  'pausedShort': 'Pausáu',
  // Counter strings
  'currentLevel': 'Nivel actual',
  'remainingMines': 'Númberu de minas restantes',
  'unrevealedCells': 'Caselles sin revelar',
  'gameTime': 'Tempu de xocu (segundos)',
  'operationCount': 'Númberu d\'operaciones',
  'previousLevel': 'Nivel anterior',
  'nextLevelShort': 'Siguiente nivel',
  // Battlefront strings
  'completed': 'Completáu',
  'inProgress': 'En curs',
  'continueGame': 'Continuar xocu',
  'replay': 'Reproducir de nuevo',
  'creater': 'Comandante en xefe',
  'created': 'Hora d\'iniciu de la batalla',
  'updated': 'Actualizáu',
  // Dialog strings
  'confirm': 'Confirmar',
  'cancel': 'Anullar',
  'yes': 'Sí',
  'no': 'Non',
  'save': 'Guardar',
  'edit': 'Editar',
  'levelFormat': 'Nivel {level}',
  'newbieLevelFormat': 'Nivel de principiante {level}',
  'totalLevel': 'Nivel {level}/{totalLevel}',
  'totalLevelTooltip':
      'Actualmente: Nivel {level} / Total {totalLevel} niveles',
  // Battlefront UI strings
  'noBattlefronts': 'Sense frentes de batalla',
  'battlefrontCount': '{count} frentes de batalla',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'NV de principiante {level}',
  'minesCount': '{count} minas',
  'notStarted': 'Non empezáu',
  'victory': 'Victoria',
  'defeat': 'Derrota',
  'gameDurationParam': 'Duración: {seconds} segundos',
  'actionsCountParam': 'Accionez: {count} veces',
  'actionsCountParamShort': '{count} veces',
  'miningMethodParam': 'Metódu: {method}',
  'startTimeParam': 'Hora d\'iniciu: {time}',
  'endTimeParam': 'Hora de finalización: {time}',
  'returnButton': 'Volver',
  'battlefrontDetails': 'Detalles de la frente de batalla',
  'clickToEditName': 'Fai clic pa modificar el nome',
  'clickToAddDescription': 'Fai clic pa añadir descripción...',
  'noDescription': 'Sense descripción',
  // Level record strings
  'levelCount': '{count} niveles',
  'noLevelRecords': 'Selecciona una frente de batalla',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Eliminar frente de batalla',
  'deleteBattlefrontContent':
      '¿Seguru que quier eliminar la frente de batalla "{name}"? Esta operación nun se puede desfacerse.',
  'battlefrontLockedCannotDelete':
      'La frente de batalla ta bloqueda, nun se puede eliminar',
  'unknownNavigationLevel': 'Nivel de navegación desconecutu',
  'noBattlefrontSelected': 'Ninguna frente de batalla seleccionada',
  'noBattlefrontToContinue':
      'Nun s\'atopó nenguna frente de batalla pa continuar',
  'synced': 'Sincronizáu',
  'notSynced': 'Non sincronizáu',
  'newbieBattlefrontName': 'Frente de batalla de principiante {number}',
  'battlefrontName': 'Frente de batalla {number}',
  'nickname': 'Apelativu',
  'nicknameSetting': 'Axuste de apelativu',
  'nicknameDesc': 'Establece to apelativu',
  'enterNickname': 'Introducir apelativu',
  'nicknameSaved': 'Apelativu guardáu',
  'nicknameUpdated': 'Apelativu actualizáu con éxitu',
  'nicknameRequired': 'El apelativu ye obligatoriu',
  'nicknameTooLong': 'El apelativu nun puede superar los 30 carácteres',
  // Level top strings
  'levelTopCount': 'Ránking de l\'alto nivel ({count})',
  'levelTopCountShort': 'Alto nivel ({count})',
  'retry': 'Reintentar',
  'noLevelTopData': 'Sense datos',
  'remoteBattlefront': 'Frente de batalla remotu',
  'participated': 'Participáu',
  'notParticipated': 'Non participáu',
  'loadMore': 'Cargar más',

  'joinBattle': 'Participar na batalla',
  'joinBattleTooltip': 'Participar na batalla "{name}"',
  'joinBattleConfirm': '¿Seguru que quier participar na batalla "{name}"?',
  'joinBattleSuccess': 'Participación exitosa na batalla "{name}"',
  'joinBattleErrorSelf':
      'Nun se puede participar en batalles creades por ti mesmu',

  'replayBattlefront': 'Reproducir de nuevo la frente de batalla',
  'replayBattlefrontTooltip':
      'Reproducir de nuevo la frente de batalla "{name}"',
  'getReplayBattlefrontConfirm':
      '¿Seguru que quier reproducir de nuevo "{name}"?',
  'getReplayBattlefrontFailed': 'Falló la reproducción de "{name}": {error}',

  'download': 'Descargar',
  'downloadBattlefront': 'Descargar frente de batalla',
  'downloadBattlefrontTooltip': 'Descargar la frente de batalla "{name}"',
  'getDownloadBattlefrontConfirm': '¿Seguru que quier descargar "{name}"?',
  'getDownloadBattlefrontSuccess': 'Descarga exitosa de "{name}"',
  'downloadMyOwnBattlefrontError':
      'Sólo se pueden descargar frentes de batalla creados por ti mesmu',
  'getDownloadBattlefrontFailed': 'Falló la descarga de "{name}": {error}',

  'continueGameShort': 'Continuar la batalla',
  'replayShort': 'Reproducir de nuevo',
  'highestLevel': 'Nivel {level}',
  'deviceNickname': 'Dispositivu',
  'createdTime': 'Hora de creación',
  'remoteBattlefrontDetail': 'Detalles de la frente de batalla remota',
  'levelList': 'Llista de niveles',
  'fastClearTimeParam': 'Tempu de completación: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Selecciona una frente de batalla local pa ver los detalles',
  'loadingRemoteDetail': 'Cargando detalles de la frente de batalla remota...',
  'noRemoteBattlefrontSelected':
      'Ninguna frente de batalla remota seleccionada',
  'failedToLoadRemoteDetail':
      'Falló la carga de detalles de la frente de batalla remota',
  'fastestRecord': 'Completación más rápida',
  'safestRecord': 'Completación más segura',
  'fastestRecordDesc': 'Completación más rápida (menos tempu emplegáu)',
  'safestRecordDesc': 'Completación más segura (menos número d\'accionez)',
  'creator': 'Creador',
  'player': 'Xogador',
  // 分支地图字符串
  'getBranchMapCount': '{count} copias',
  'collapse': 'Plegar',
  'expand': 'Expandir',
  // 退出战线
  'quitBattlefront': 'Abandonar frente de batalla',
  'quitBattlefrontTooltip': 'Abandonar la frente de batalla remota',
  'quitBattlefrontTitle': 'Abandonar frente de batalla',
  'quitBattlefrontContent':
      '¿Seguru que quier abandonar la frente de batalla "{name}"? El to progresu local se eliminará.',
  // 游戏介绍
  'gameIntroduction':
      '1. La "Iniciación pa principiantes" empezará con 15 minas, y puede llegar hasta 99 minas;\n2. La "Nova frente de batalla" empezará con 81 minas, y cada nivel aumentará un certu númberu de minas, sen límite superior.\n3. En casu de conexión a internet, les frentes de batalla "completadas" se compartirán automáticamente na nube pa que otros puedan aprender.',
};
