// Dutch（荷兰语）
/// Nederlandse teksten voor de DMine applicatie
const Map<String, String> stringsNl = {
  'appTitle': 'DMine - Top Mijnenveger',
  'settings': 'Instellingen',
  'gameSettings': 'Spelinstellingen',
  'showTimer': 'Tijdweergave weergeven',
  'showTimerDesc': 'Toon de spelklok op de spelinterface',
  'showActionCounter': 'Actieteller weergeven',
  'showActionCounterDesc': 'Toon het aantal acties op de spelinterface',
  'autoAdjustBoardWidth': 'Automatisch bordbreedte aanpassen',
  'autoAdjustBoardWidthDesc':
      'Pas de bordbreedte automatisch aan op schermgrootte',
  'resetToDefaults': 'Herstel naar standaardinstellingen',
  'resetToDefaultsDesc': 'Alle instellingen terugzetten naar standaardwaarden',
  'aboutDMine': 'Over DMine',
  'version': 'Versie',
  'close': 'Sluiten',
  'manualBoardWidth': 'Handmatig bordbreedte instellen',
  'currentWidth': 'Huidig',
  'range': 'Bereik',
  'widthSliderHint':
      'Tip: Wijzigingen aan bordbreedte live bekijken tijdens schuiven van de slider',
  'gameRecords': 'Spelrecords',
  'selectMapToViewRecords': 'Selecteer een map om records te bekijken',
  'totalRecords': 'Totaal',
  'gameRecordsTitle': 'Lijst met spelrecords',
  'pleaseSelectMapFirst': 'Selecteer eerst een map',
  'noGameRecords': 'Geen spelrecords beschikbaar',
  'miningMethodFlag': 'Vlag plaatsen',
  'miningMethodBlind': 'Blind zoeken',
  'statusPlaying': '▶️ Bezig...',
  'statusWin': '🎉 Gewonnen',
  'statusLose': '💥 Verloren',
  'actionsCount': 'Aantal acties',
  'miningMethod': 'Mijnzoekmethode',
  'duration': 'Duur',
  'seconds': 'seconden',
  'startTime': 'Starttijd',
  'endTime': 'Eindtijd',
  'pauseTime': 'Pauzetijd',
  'unlock': 'Ontgrendelen',
  'lock': 'Vergrendelen',
  'delete': 'Verwijderen',
  'languageSetting': 'Taalinstelling',
  'currentLanguage': 'Huidig',
  'systemLanguage': 'Systeemtaal',
  'chinese': 'Chinees',
  'english': 'Engels',
  'language': 'Taal',
  // Home page
  'newbie': 'Nieuweling',
  'newBattle': 'Nieuwe front',
  'continueChallenge': 'Uitdaging voortzetten',
  'error': 'Fout',
  'initializationFailed': 'Initialisatie mislukt',
  // Game page
  'congratulations': 'Gefeliciteerd, niveau voltooid!',
  'gameOver': 'Spel voorbij',
  'timeUsed': 'Tijd gebruikt',
  'actionCount': 'Aantal acties',
  'mineCount': 'Aantal mijnen',
  'nextLevel': 'Volgend niveau: Niveau {level}',
  'newbieNextLevel': 'Volgend niveau: Nieuweling {level}',
  'nextLevelMines': 'Aantal mijnen',
  'mineIncrease': 'Verhoging',
  'newbieFinish': 'Nieuwelingstraining voltooid',
  'ok': 'OK',
  'continueNextLevel': 'Ga naar volgend niveau',
  'restart': 'Opnieuw starten',
  'level': 'Niveau {level}',
  'newbieLevel': 'Nieuweling {level}',
  'operationFailed': 'Bewerking mislukt',
  // Game status texts
  'returnHome': 'Terug naar start',
  'revealMode': 'Onthulmodus',
  'flagMode': 'Vlagmodus',
  'newMap': 'Nieuwe map (aantal mijnen blijft gelijk, nieuwe map genereren)',
  'resetMap': 'Map herladen (zelfde map, status resetten)',
  'zoomOut': 'Uitzoomen',
  'zoomIn': 'Inzoomen',
  'resetZoom': 'Zoom resetten',
  'previousStep': 'Vorige stap',
  'pause': 'Pauzeren',
  'play': 'Spelen',
  'nextStep': 'Volgende stap',
  'clickToStart': 'Klik een vakje om het spel te starten',
  'playing': 'Spel bezig...',
  'gameWin': 'Gefeliciteerd, niveau voltooid!',
  'gameLose': 'Spel voorbij, mijn geraakt',
  'gamePaused': 'Spel gepauzeerd',
  'ready': 'Klaar',
  'clickStartShort': 'Klik om te starten',
  'playingShort': 'Bezig',
  'winShort': 'Voltooid!',
  'loseShort': 'Mijn geraakt',
  'pausedShort': 'Gepauzeerd',
  // Counter strings
  'currentLevel': 'Huidig niveau',
  'remainingMines': 'Resterende mijnen',
  'gameTime': 'Speltijd (seconden)',
  'operationCount': 'Aantal bewerkingen',
  'previousLevel': 'Vorige niveau',
  'nextLevelShort': 'Volgend niveau',
  // Battlefront strings
  'completed': 'Voltooid',
  'inProgress': 'Bezig',
  'continueGame': 'Spel voortzetten',
  'replay': 'Opnieuw afspelen',
  'creater': 'Commandant',
  'created': 'Strijd begintijd',
  'updated': 'Bijgewerkt',
  // Dialog strings
  'confirm': 'Bevestigen',
  'cancel': 'Annuleren',
  'yes': 'Ja',
  'no': 'Nee',
  'save': 'Opslaan',
  'edit': 'Bewerken',
  'levelFormat': 'Niveau {level}',
  'newbieLevelFormat': 'Nieuweling {level}',
  'totalLevel': '{level}/{totalLevel} niveaus',
  'totalLevelTooltip': 'Huidig: Niveau {level} / Totaal {totalLevel} niveaus',
  // Battlefront UI strings
  'noBattlefronts': 'Geen fronten',
  'battlefrontCount': '{count} fronten',
  'levelPrefix': 'NV{level}',
  'newbieLevelPrefix': 'NIEUW{level}',
  'minesCount': '{count} mijnen',
  'notStarted': 'Niet gestart',
  'victory': 'Overwinning',
  'defeat': 'Nederlaag',
  'gameDurationParam': 'Duur: {seconds} seconden',
  'actionsCountParam': 'Acties: {count} keer',
  'actionsCountParamShort': '{count} keer',
  'miningMethodParam': 'Methode: {method}',
  'startTimeParam': 'Starttijd: {time}',
  'endTimeParam': 'Eindtijd: {time}',
  'returnButton': 'Terug',
  'battlefrontDetails': 'Frontdetails',
  'clickToEditName': 'Klik om naam te wijzigen',
  'clickToAddDescription': 'Klik om beschrijving toe te voegen...',
  'noDescription': 'Geen beschrijving',
  // Level record strings
  'levelCount': '{count} niveaus',
  'noLevelRecords': 'Selecteer een front',
  // Battlefront operations and messages
  'deleteBattlefrontTitle': 'Front verwijderen',
  'deleteBattlefrontContent':
      'Weet je zeker dat je het front "{name}" wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
  'battlefrontLockedCannotDelete': 'Front is vergrendeld, kan niet verwijderen',
  'unknownNavigationLevel': 'Onbekend navigatieniveau',
  'noBattlefrontSelected': 'Geen front geselecteerd',
  'noBattlefrontToContinue': 'Geen front om voort te zetten',
  'synced': 'Gesynchroniseerd',
  'notSynced': 'Niet gesynchroniseerd',
  'newbieBattlefrontName': 'Nieuwelingfront {number}',
  'battlefrontName': 'Front {number}',
  'nickname': 'Bijnaam',
  'nicknameSetting': 'Bijnaaminstelling',
  'nicknameDesc': 'Stel je bijnaam in',
  'enterNickname': 'Voer bijnaam in',
  'nicknameSaved': 'Bijnaam opgeslagen',
  'nicknameUpdated': 'Bijnaam bijgewerkt',
  'nicknameRequired': 'Bijnaam is verplicht',
  'nicknameTooLong': 'Bijnaam mag niet langer zijn dan 30 tekens',
  // Level top strings
  'levelTopCount': 'Ranglijst ({count})',
  'levelTopCountShort': 'Top ({count})',
  'retry': 'Opnieuw proberen',
  'noLevelTopData': 'Geen gegevens',
  'remoteBattlefront': 'Extern front',
  'participated': 'Deelgenomen',
  'notParticipated': 'Niet deelgenomen',
  'loadMore': 'Meer laden',

  'joinBattle': 'Deelnemen aan strijd',
  'joinBattleTooltip': 'Deelnemen aan strijd "{name}"',
  'joinBattleConfirm': 'Weet je zeker dat je wilt deelnemen aan "{name}"?',
  'joinBattleSuccess': 'Succesvol deelgenomen aan "{name}"',
  'joinBattleErrorSelf': 'Kan niet deelnemen aan je eigen front',

  'replayBattlefront': 'Front opnieuw afspelen',
  'replayBattlefrontTooltip': 'Front "{name}" opnieuw afspelen',
  'getReplayBattlefrontConfirm':
      'Weet je zeker dat je "{name}" opnieuw wilt afspelen?',
  'getReplayBattlefrontFailed': 'Opnieuw afspelen "{name}" mislukt: {error}',

  'download': 'Downloaden',
  'downloadBattlefront': 'Front downloaden',
  'downloadBattlefrontTooltip': 'Front "{name}" downloaden',
  'getDownloadBattlefrontConfirm':
      'Weet je zeker dat je "{name}" wilt downloaden?',
  'getDownloadBattlefrontSuccess': 'Front "{name}" succesvol gedownload',
  'downloadMyOwnBattlefrontError': 'Alleen je eigen fronten downloaden',
  'getDownloadBattlefrontFailed': 'Downloaden "{name}" mislukt: {error}',

  'continueGameShort': 'Strijd voortzetten',
  'replayShort': 'Opnieuw',
  'highestLevel': 'Niveau {level}',
  'deviceNickname': 'Apparaat',
  'createdTime': 'Aanmaaktijd',
  'remoteBattlefrontDetail': 'Extern frontdetails',
  'levelList': 'Niveaulijst',
  'fastClearTimeParam': 'Voltooidtijd: {time}',
  // 远程战线详情字符串
  'selectLocalBattlefrontHint':
      'Selecteer een lokaal front om details te bekijken',
  'loadingRemoteDetail': 'Externe frontdetails laden...',
  'noRemoteBattlefrontSelected': 'Geen extern front geselecteerd',
  'failedToLoadRemoteDetail': 'Laden externe details mislukt',
  'fastestRecord': 'Snelste voltooiing',
  'safestRecord': 'Veiligste voltooiing',
  'fastestRecordDesc': 'Snelste voltooiing (minste tijd)',
  'safestRecordDesc': 'Veiligste voltooiing (minste acties)',
  'creator': 'Maker',
  'player': 'Speler',
  // 分支地图字符串
  'getBranchMapCount': '{count} kopieën',
  'collapse': 'Samenvouwen',
  'expand': 'Uitvouwen',
  // 退出战线
  'quitBattlefront': 'Front verlaten',
  'quitBattlefrontTooltip': 'Extern front verlaten',
  'quitBattlefrontTitle': 'Front verlaten',
  'quitBattlefrontContent':
      'Weet je zeker dat je het front "{name}" wilt verlaten? Je lokale voortgang wordt verwijderd.',

  // 下载页面
  'downloadClient': 'Client downloaden',
  'browser': 'Browser',
  'browserDesc': 'Speel direct in de browser, zonder download',
  'windowsDesc': 'Voor Windows 10 en hoger',
  'macosDesc': 'Voor macOS 10.15 en hoger',
  'android': 'Android',
  'androidDesc': 'Voor Android 8.0 en hoger',
  'iosDesc': 'Voor iOS 14.0 en hoger',
  'linkAddress': 'Linkadres',
  'downloadLink': 'Downloadlink',
  'qrCode': 'QR-code',
  'scanToDownload': 'Scan met telefoon om te downloaden',
  'copy': 'Kopiëren',
  'copiedToClipboard': 'Gekopieerd naar klembord',
  'openLink': 'Link openen',
  'cannotOpenLink': 'Kan link niet openen',
  // 游戏介绍
  'gameIntroduction':
      '1. "Nieuweling" begint met 15 mijnen, maximaal 99 mijnen;\n2. "Nieuwe front" begint met 81 mijnen, elk niveau voegt mijnen toe zonder bovengrens.\n3. Met internet worden "voltooide" fronten automatisch gedeeld in de cloud voor anderen.',
};
